//! Payload codec against upstream (ex-110).
//!
//! Upstream: `packages/excalidraw/data/encode.ts` at the pinned commit
//! 438d89861f53d8a90ad566113ecac1b83761098f — byte-string helpers
//! (`encode.ts:14-39`), `encode` (`:99-121`) and `decode` (`:123-144`) — on
//! top of pako 2.0.3 (`packages/excalidraw/package.json:105`, locked in
//! `yarn.lock`).
//!
//! `fixtures/payload/goldens.json` is generated by
//! `scripts/fixtures/payload-goldens.sh`, which runs upstream's encode.ts
//! verbatim on the locked pako release; CI regenerates it and fails if it
//! drifts. Every expectation below is upstream output:
//!
//! - `encode`: for each text, `pako.deflate(text)`, `JSON.stringify(encode({text}))`
//!   and `JSON.stringify(encode({text, compress: false}))`;
//! - `deflate`: `pako.deflate(bytes)` for binary inputs and for every library
//!   in the `fixtures/libraries` corpus;
//! - `decode`: what `decode(data)` returns (as UTF-16 code units), throws, or
//!   `undefined` when pako gives up on incomplete input.
//!
//! Large values are pinned by length and SHA-256; values up to 4 KiB are also
//! stored inline so a failure shows the difference.

use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use base64::Engine as _;
use excali_core::encode::{
    byte_string_to_bytes, byte_string_to_string, decode, deflate, encode, inflate,
    inflate_to_string, to_byte_string, DecodeError, EncodedData, InflateError,
};
use serde_json::Value;
use sha2::{Digest, Sha256};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn goldens() -> &'static Value {
    static G: OnceLock<Value> = OnceLock::new();
    G.get_or_init(|| {
        let text = include_str!("fixtures/payload/goldens.json");
        serde_json::from_str(text).expect("goldens.json parses")
    })
}

fn cases(kind: &str) -> &'static [Value] {
    goldens()[kind].as_array().expect("case list")
}

fn read_repo(rel: &str) -> Vec<u8> {
    let data = std::fs::read(repo_root().join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}"));
    if rel.ends_with(".gz") {
        let mut out = Vec::new();
        flate2::read::GzDecoder::new(&data[..])
            .read_to_end(&mut out)
            .unwrap_or_else(|e| panic!("{rel}: {e}"));
        out
    } else {
        data
    }
}

/// The generator in `scripts/fixtures/payload_goldens.mjs`.
fn xorshift32(seed: u32) -> impl FnMut() -> u32 {
    let mut x = seed;
    move || {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        x
    }
}

/// `textOf` in the generator.
fn text_of(spec: &Value) -> String {
    if let Some(t) = spec.get("text") {
        return t.as_str().unwrap().to_owned();
    }
    if let Some(f) = spec.get("file") {
        return String::from_utf8(read_repo(f.as_str().unwrap())).expect("fixture is UTF-8");
    }
    if let Some(r) = spec.get("repeat") {
        return r.as_str().unwrap().repeat(spec["count"].as_u64().unwrap() as usize);
    }
    if let Some(x) = spec.get("xorshift_text") {
        let alphabet: Vec<&str> = x["alphabet"]
            .as_array()
            .unwrap()
            .iter()
            .map(|a| a.as_str().unwrap())
            .collect();
        let mut next = xorshift32(x["seed"].as_u64().unwrap() as u32);
        let count = x["count"].as_u64().unwrap();
        return (0..count)
            .map(|_| alphabet[next() as usize % alphabet.len()])
            .collect();
    }
    panic!("not a text spec: {spec}");
}

/// `bytesOf` in the generator.
fn bytes_of(spec: &Value) -> Vec<u8> {
    if let Some(f) = spec.get("file_bytes") {
        return read_repo(f.as_str().unwrap());
    }
    if let Some(x) = spec.get("xorshift_bytes") {
        let mut next = xorshift32(x["seed"].as_u64().unwrap() as u32);
        let mask = x["mask"].as_u64().unwrap() as u32;
        return (0..x["count"].as_u64().unwrap())
            .map(|_| (next() & mask) as u8)
            .collect();
    }
    panic!("not a bytes spec: {spec}");
}

fn sha256_hex(data: &[u8]) -> String {
    Sha256::digest(data)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

fn check_bytes(label: &str, got: &[u8], golden: &Value) {
    if let Some(b64) = golden.get("base64") {
        let want = base64::engine::general_purpose::STANDARD
            .decode(b64.as_str().unwrap())
            .unwrap();
        assert_eq!(got, &want[..], "{label}");
    }
    assert_eq!(got.len() as u64, golden["len"].as_u64().unwrap(), "{label}: length");
    assert_eq!(sha256_hex(got), golden["sha256"].as_str().unwrap(), "{label}: sha256");
}

fn check_text(label: &str, got: &str, golden: &Value) {
    if let Some(want) = golden.get("text") {
        assert_eq!(got, want.as_str().unwrap(), "{label}");
    }
    check_bytes(label, got.as_bytes(), &{
        let mut g = golden.clone();
        g.as_object_mut().unwrap().remove("text");
        g
    });
}

#[test]
fn deflate_is_byte_identical_to_pako_for_text() {
    for case in cases("encode") {
        let name = case["name"].as_str().unwrap();
        let text = text_of(&case["input"]);
        check_bytes(&format!("{name}: deflate"), &deflate(text.as_bytes()), &case["deflate"]);
    }
}

#[test]
fn encode_output_is_identical_to_upstream() {
    for case in cases("encode") {
        let name = case["name"].as_str().unwrap();
        let text = text_of(&case["input"]);

        let compressed = encode(&text, true);
        assert!(compressed.compressed, "{name}");
        assert_eq!(compressed.version.as_deref(), Some("1"), "{name}");
        assert_eq!(compressed.encoding, "bstring", "{name}");
        check_text(&format!("{name}: encode"), &compressed.to_json(), &case["encoded_json"]);

        let raw = encode(&text, false);
        assert!(!raw.compressed, "{name}");
        check_text(&format!("{name}: encode (no compression)"), &raw.to_json(), &case["raw_json"]);
    }
}

#[test]
fn encode_decode_round_trip() {
    for case in cases("encode") {
        let name = case["name"].as_str().unwrap();
        let text = text_of(&case["input"]);
        for compress in [true, false] {
            let data = encode(&text, compress);
            assert_eq!(decode(&data).unwrap(), text, "{name} (compress: {compress})");
            // Through JSON, as the PNG and SVG embeddings carry it.
            let parsed: EncodedData = serde_json::from_str(&data.to_json()).unwrap();
            assert_eq!(parsed, data, "{name} (compress: {compress})");
            assert_eq!(decode(&parsed).unwrap(), text, "{name} (compress: {compress})");
        }
    }
}

#[test]
fn upstream_encoded_json_decodes_to_the_text() {
    for case in cases("encode") {
        let name = case["name"].as_str().unwrap();
        for key in ["encoded_json", "raw_json"] {
            let Some(json) = case[key].get("text") else {
                continue;
            };
            let data: EncodedData = serde_json::from_str(json.as_str().unwrap()).unwrap();
            assert_eq!(decode(&data).unwrap(), text_of(&case["input"]), "{name}: {key}");
        }
    }
}

#[test]
fn deflate_is_byte_identical_to_pako_for_binary_and_the_library_corpus() {
    let all = cases("deflate");
    assert!(
        all.iter()
            .filter(|c| c["name"].as_str().unwrap().starts_with("library:"))
            .count()
            >= 232,
        "every catalogue library is covered"
    );
    for case in all {
        let name = case["name"].as_str().unwrap();
        let bytes = bytes_of(&case["input"]);
        let z = deflate(&bytes);
        check_bytes(&format!("{name}: deflate"), &z, &case["deflate"]);
        assert_eq!(inflate(&z).unwrap(), bytes, "{name}: inflate(deflate(x))");
    }
}

fn utf16_le(s: &str) -> Vec<u8> {
    s.encode_utf16().flat_map(u16::to_le_bytes).collect()
}

#[test]
fn decode_matches_upstream_on_every_wrapper() {
    for case in cases("decode") {
        let name = case["name"].as_str().unwrap();
        let data: EncodedData = serde_json::from_value(case["data"].clone())
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        let result = &case["result"];
        let got = decode(&data);
        if let Some(want) = result.get("utf16") {
            let got = got.unwrap_or_else(|e| panic!("{name}: {e}"));
            if let Some(units) = want.get("units") {
                let units: Vec<u16> = units
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|u| u.as_u64().unwrap() as u16)
                    .collect();
                // Rust strings cannot hold a lone surrogate; it comes back as
                // U+FFFD, exactly as String::from_utf16_lossy maps it.
                assert_eq!(got, String::from_utf16_lossy(&units), "{name}");
            }
            let le = utf16_le(&got);
            assert_eq!(le.len() as u64 / 2, want["len"].as_u64().unwrap(), "{name}: length");
            assert_eq!(sha256_hex(&le), want["sha256"].as_str().unwrap(), "{name}: sha256");
        } else if let Some(msg) = result.get("error") {
            let err = got.expect_err(name);
            assert_eq!(err.to_string(), msg.as_str().unwrap(), "{name}");
        } else {
            assert_eq!(result["undefined"], Value::Bool(true), "{name}");
            let err = got.expect_err(name);
            assert!(
                matches!(err, DecodeError::Inflate(InflateError::Incomplete)),
                "{name}: {err:?}"
            );
        }
    }
}

#[test]
fn unknown_encoding_message_is_upstreams() {
    let data = EncodedData {
        version: None,
        encoding: "utf8".into(),
        compressed: false,
        encoded: "x".into(),
    };
    let err = decode(&data).unwrap_err();
    assert_eq!(err, DecodeError::UnknownEncoding("utf8".into()));
    assert_eq!(err.to_string(), r#"decode: unknown encoding "utf8""#);
}

/// The scene embedded in upstream's own `smiley_embedded_v2.svg` fixture
/// (written by upstream's `encodeSvgBase64Payload`): decoding and encoding
/// again reproduces the embedded wrapper exactly.
#[test]
fn upstream_svg_fixture_payload_re_encodes_byte_for_byte() {
    let svg = String::from_utf8(read_repo(
        "fixtures/upstream/packages/excalidraw/tests/fixtures/smiley_embedded_v2.svg",
    ))
    .unwrap();
    let start = svg.find("<!-- payload-start -->").unwrap() + "<!-- payload-start -->".len();
    let end = svg.find("<!-- payload-end -->").unwrap();
    let json = base64::engine::general_purpose::STANDARD
        .decode(svg[start..end].trim())
        .unwrap();
    // payload-version 2: the base64 holds a byte string, one char per byte.
    let json = to_byte_string(&json);
    let data: EncodedData = serde_json::from_str(&json).unwrap();
    assert!(data.compressed);
    let scene = decode(&data).unwrap();
    assert!(scene.starts_with("{\n  \"type\": \"excalidraw\""));
    let again = encode(&scene, true);
    assert_eq!(again, data);
    assert_eq!(again.to_json(), json);
}

#[test]
fn byte_string_helpers_follow_encode_ts() {
    // toByteString: one char per byte.
    let all: Vec<u8> = (0..=255).collect();
    let bs = to_byte_string(&all);
    assert_eq!(bs.chars().count(), 256);
    assert!(bs.chars().zip(0u32..).all(|(c, i)| c as u32 == i));
    assert_eq!(byte_string_to_bytes(&bs), all);
    // byteStringToArrayBuffer: each UTF-16 code unit is stored in a Uint8Array.
    assert_eq!(byte_string_to_bytes("\u{141}\u{2603}x\u{1F600}"), [0x41, 0x03, 0x78, 0x3d, 0x00]);
    // byteStringToString: TextDecoder("utf-8"), BOM stripped, U+FFFD on errors.
    assert_eq!(byte_string_to_string(&to_byte_string("é中😀".as_bytes())), "é中😀");
    assert_eq!(byte_string_to_string("\u{ef}\u{bb}\u{bf}a"), "a");
    assert_eq!(byte_string_to_string("\u{ff}"), "\u{fffd}");
    assert_eq!(byte_string_to_string(""), "");
}

#[test]
fn inflate_to_string_uses_pakos_utf8_decoder() {
    // pako's buf2string does not validate continuation bytes and keeps a BOM.
    let z = deflate(&[0xef, 0xbb, 0xbf, b'h', b'i']);
    assert_eq!(inflate_to_string(&z).unwrap(), "\u{feff}hi");
    let z = deflate(&[b'a', 0xff, b'b', 0xc3, b'(', b'c', 0xe2, 0x82, b'd', 0xfe, b'A']);
    assert_eq!(inflate_to_string(&z).unwrap(), "a\u{fffd}\u{2}d\u{6}A");
    assert_eq!(inflate(&[]), Err(InflateError::Incomplete));
}

/// Round trips over generated inputs whose sizes sit on deflate's internal
/// boundaries: the 32 KiB window, the 64 KiB sliding buffer and stored-block
/// limit, and the 16 Ki-symbol block buffer.
#[test]
fn round_trip_on_buffer_boundaries() {
    let mut next = xorshift32(0x5eed);
    for len in [
        0usize, 1, 2, 3, 4, 257, 258, 259, 262, 16383, 16384, 16385, 32506, 32768, 32769, 65535,
        65536, 65537, 98304, 131072,
    ] {
        for mask in [0xffu32, 0x0f, 0x01] {
            let bytes: Vec<u8> = (0..len).map(|_| (next() & mask) as u8).collect();
            let z = deflate(&bytes);
            assert_eq!(inflate(&z).unwrap(), bytes, "len {len} mask {mask:#x}");
        }
        let text: String = (0..len)
            .map(|_| ['a', 'b', ' ', 'é', '中', '😀', '\n'][next() as usize % 7])
            .collect();
        for compress in [true, false] {
            assert_eq!(decode(&encode(&text, compress)).unwrap(), text, "len {len}");
        }
    }
}
