//! PNG scene payload against upstream (ex-111).
//!
//! Upstream: `packages/excalidraw/data/image.ts` at the pinned commit
//! (`getTEXtChunk`, `encodePngMetadata`, `decodePngMetadata`), on
//! png-chunks-extract 1.0.0, png-chunks-encode 1.0.0, png-chunk-text 1.0.0
//! (with crc-32 0.3.0 and sliced 1.0.1) and the payload codec of ex-110
//! (`site/content/research/data-model.md`, section 5).
//!
//! `fixtures/png/goldens.json` is generated by `scripts/fixtures/png-goldens.sh`,
//! which runs upstream's image.ts verbatim on the locked npm releases; CI
//! regenerates it and fails if it drifts, then has upstream decode the PNGs
//! the `png_embed` example writes. Every expectation below is upstream output:
//!
//! - `decode`: `getTEXtChunk` and `decodePngMetadata` on upstream's fixture
//!   PNGs, hand-built PNGs (every error png-chunks-extract and png-chunk-text
//!   raise, every branch of `decodePngMetadata`, the payload wrapper as any
//!   JSON) and random corruptions of the embedded fixtures;
//! - `prefixes`: `decodePngMetadata` on every prefix of the embedded fixtures;
//! - `encode`: the bytes `encodePngMetadata` writes for PNGs and scene texts,
//!   and what upstream decodes from them;
//! - `text_chunks`: the tEXt text upstream writes for a scene text.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use base64::Engine as _;
use excali_core::constants::MIME_TYPE_EXCALIDRAW;
use excali_core::document::Document;
use excali_core::element::{Element, ElementBase, ElementKind, FontFamily, TextFields};
use excali_core::encode::encode;
use excali_core::png::{
    decode_png_metadata, decode_text_chunk, encode_chunks, encode_png_metadata, encode_text_chunk,
    extract_chunks, get_text_chunk, Chunk, DecodePngMetadataError, PngError,
};
use serde_json::Value;
use sha2::{Digest, Sha256};

const FIXTURES: &str = "fixtures/upstream/packages/excalidraw/tests/fixtures";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn read_repo(rel: &str) -> Vec<u8> {
    std::fs::read(repo_root().join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}"))
}

fn fixture(name: &str) -> Vec<u8> {
    read_repo(&format!("{FIXTURES}/{name}"))
}

fn goldens() -> &'static Value {
    static G: OnceLock<Value> = OnceLock::new();
    G.get_or_init(|| {
        let text = include_str!("fixtures/png/goldens.json");
        serde_json::from_str(text).expect("goldens.json parses")
    })
}

fn cases(kind: &str) -> &'static [Value] {
    goldens()[kind].as_array().expect("case list")
}

/// The generator in `scripts/fixtures/png_goldens.mjs`.
fn xorshift32(seed: u32) -> impl FnMut() -> u32 {
    let mut x = seed;
    move || {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        x
    }
}

/// `materialize` in the generator.
fn materialize(spec: &Value) -> Vec<u8> {
    if let Some(f) = spec.get("file") {
        return read_repo(f.as_str().unwrap());
    }
    if let Some(b) = spec.get("base64") {
        return base64::engine::general_purpose::STANDARD
            .decode(b.as_str().unwrap())
            .unwrap();
    }
    if let Some(p) = spec.get("prefix") {
        let mut bytes = read_repo(p["file"].as_str().unwrap());
        bytes.truncate(p["len"].as_u64().unwrap() as usize);
        return bytes;
    }
    if let Some(f) = spec.get("flip") {
        let mut bytes = read_repo(f["file"].as_str().unwrap());
        let mut next = xorshift32(f["seed"].as_u64().unwrap() as u32);
        for _ in 0..f["count"].as_u64().unwrap() {
            let pos = next() as usize % bytes.len();
            bytes[pos] ^= ((next() & 0xff) | 1) as u8;
        }
        return bytes;
    }
    panic!("not a bytes spec: {spec}");
}

/// `textOf` in the generator.
fn text_of(spec: &Value) -> String {
    if let Some(t) = spec.get("text") {
        return t.as_str().unwrap().to_owned();
    }
    if let Some(r) = spec.get("repeat") {
        return r
            .as_str()
            .unwrap()
            .repeat(spec["count"].as_u64().unwrap() as usize);
    }
    if let Some(f) = spec.get("file") {
        return String::from_utf8(read_repo(f.as_str().unwrap())).expect("fixture is UTF-8");
    }
    panic!("not a text spec: {spec}");
}

fn sha256_hex(data: &[u8]) -> String {
    Sha256::digest(data)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// A string against `stringGolden`: UTF-16 length, SHA-256 of the UTF-16LE
/// code units, and the text when inlined.
fn check_string(label: &str, got: &str, golden: &Value) {
    if let Some(want) = golden.get("text") {
        assert_eq!(got, want.as_str().unwrap(), "{label}");
    }
    let units: Vec<u16> = got.encode_utf16().collect();
    let le: Vec<u8> = units.iter().flat_map(|u| u.to_le_bytes()).collect();
    assert_eq!(
        units.len() as u64,
        golden["len"].as_u64().unwrap(),
        "{label}: UTF-16 length"
    );
    assert_eq!(
        sha256_hex(&le),
        golden["sha256"].as_str().unwrap(),
        "{label}: sha256"
    );
}

fn check_bytes(label: &str, got: &[u8], golden: &Value) {
    if let Some(b64) = golden.get("base64") {
        let want = base64::engine::general_purpose::STANDARD
            .decode(b64.as_str().unwrap())
            .unwrap();
        assert_eq!(got, &want[..], "{label}");
    }
    assert_eq!(
        got.len() as u64,
        golden["len"].as_u64().unwrap(),
        "{label}: length"
    );
    assert_eq!(
        sha256_hex(got),
        golden["sha256"].as_str().unwrap(),
        "{label}: sha256"
    );
}

/// `decodePngMetadata`'s outcome against `{ok}`, `{undefined}` or `{error}`.
fn check_decoded(
    label: &str,
    got: &Result<Option<String>, DecodePngMetadataError>,
    golden: &Value,
) {
    match (got, golden) {
        (Ok(Some(text)), g) if g.get("ok").is_some() => check_string(label, text, &g["ok"]),
        (Ok(None), g) if g.get("undefined").is_some() => {}
        (Err(e), g) if g.get("error").is_some() => {
            assert_eq!(e.to_string(), g["error"].as_str().unwrap(), "{label}")
        }
        _ => panic!("{label}: got {got:?}, upstream {golden}"),
    }
}

/// `(type, text)` of each element of a decoded scene, read as upstream's
/// `expect.objectContaining({ type, text })` does. The fixtures predate
/// fields the typed model requires (`updated`, `index`), which upstream's
/// restore fills in on load; restore (ex-103, ex-104) is not part of this
/// task, so the scene is read as JSON.
fn scene_elements(text: &str) -> Vec<(String, String)> {
    let scene: Value = serde_json::from_str(text).expect("the payload is JSON");
    assert_eq!(scene["type"], "excalidraw");
    scene["elements"]
        .as_array()
        .expect("elements")
        .iter()
        .map(|e| {
            let field = |k: &str| e[k].as_str().unwrap_or_default().to_owned();
            (field("type"), field("text"))
        })
        .collect()
}

/// `(type, text)` of each element of a scene read by the typed model.
fn document_elements(text: &str) -> Vec<(String, String)> {
    let doc = Document::from_json(text).expect("the payload is a scene");
    doc.elements
        .expect("elements")
        .iter()
        .map(|e| match &e.kind {
            ElementKind::Text(t) => ("text".to_owned(), t.text.clone()),
            other => (format!("{:?}", other.element_type()), String::new()),
        })
        .collect()
}

// --- acceptance: upstream's export.test.tsx fixtures ---------------------------

/// `export.test.tsx` "import embedded png (legacy v1)": one text element "test".
#[test]
fn test_embedded_v1_png_decodes_to_its_text_element() {
    let text = decode_png_metadata(&fixture("test_embedded_v1.png"))
        .expect("decodes")
        .expect("has a scene");
    assert_eq!(
        scene_elements(&text),
        [("text".to_owned(), "test".to_owned())]
    );
}

/// `export.test.tsx` "import embedded png (v2)": one text element "\u{1F600}" (a grinning face).
#[test]
fn smiley_embedded_v2_png_decodes_to_its_text_element() {
    let text = decode_png_metadata(&fixture("smiley_embedded_v2.png"))
        .expect("decodes")
        .expect("has a scene");
    assert_eq!(
        scene_elements(&text),
        [("text".to_owned(), "\u{1F600}".to_owned())]
    );
}

/// `export.test.tsx` "export embedded png and reimport": a 16x16 text
/// element "\u{1F600}" serialized as a scene, embedded in smiley.png, read
/// back by the typed model.
#[test]
fn export_embedded_png_and_reimport() {
    let mut base = ElementBase::new("A", 0.0, 0.0, 1.0, 1.0);
    base.width = 16.0;
    base.height = 16.0;
    let text = TextFields::new("\u{1F600}", FontFamily::default(), 1.25);
    let doc = Document::new(
        "https://excalidraw.com",
        vec![Element::new(base, ElementKind::Text(text))],
        serde_json::Map::new(),
        Some(serde_json::Map::new()),
    );
    let written = encode_png_metadata(&fixture("smiley.png"), &doc.to_json()).unwrap();
    let back = decode_png_metadata(&written).unwrap().unwrap();
    assert_eq!(back, doc.to_json());
    assert_eq!(Document::from_json(&back).unwrap(), doc);
    assert_eq!(
        document_elements(&back),
        [("text".to_owned(), "\u{1F600}".to_owned())]
    );
}

/// The embedded fixtures decode to upstream's text exactly.
#[test]
fn embedded_fixture_scenes_decode_to_upstream_text() {
    for name in ["test_embedded_v1.png", "smiley_embedded_v2.png"] {
        let golden = format!("fixture_{name}");
        let case = cases("decode")
            .iter()
            .find(|c| c["name"] == golden.as_str())
            .expect("fixture case");
        check_decoded(name, &decode_png_metadata(&fixture(name)), &case["decoded"]);
    }
}

#[test]
fn a_png_without_a_scene_is_invalid() {
    let err = decode_png_metadata(&fixture("smiley.png")).unwrap_err();
    assert_eq!(err, DecodePngMetadataError::Invalid);
    assert_eq!(err.to_string(), "INVALID");
}

// --- goldens ----------------------------------------------------------------

#[test]
fn goldens_come_from_the_pinned_upstream_and_locked_packages() {
    let g = goldens();
    let pin = std::fs::read_to_string(repo_root().join("site/config.toml")).unwrap();
    let commit = g["upstream_commit"].as_str().unwrap();
    assert!(pin.contains(commit), "goldens from {commit}, not the pin");
    assert_eq!(g["keyword"], MIME_TYPE_EXCALIDRAW);
    for (name, version) in [
        ("png-chunk-text", "1.0.0"),
        ("png-chunks-encode", "1.0.0"),
        ("png-chunks-extract", "1.0.0"),
        ("crc-32", "0.3.0"),
        ("sliced", "1.0.1"),
        ("pako", "2.0.3"),
    ] {
        assert_eq!(g["packages"][name], version, "{name}");
    }
}

#[test]
fn decode_matches_upstream() {
    let cases = cases("decode");
    assert!(cases.len() > 400);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let png = materialize(&case["input"]);

        let chunk = get_text_chunk(&png);
        let want = &case["text_chunk"];
        match (&chunk, want) {
            (Ok(None), w) if w.get("null").is_some() => {}
            (Ok(Some(c)), w) if w.get("keyword").is_some() => {
                assert_eq!(c.keyword, w["keyword"].as_str().unwrap(), "{name}: keyword");
                check_string(&format!("{name}: tEXt text"), &c.text, &w["text"]);
            }
            (Err(e), w) if w.get("error").is_some() => {
                assert_eq!(e.to_string(), w["error"].as_str().unwrap(), "{name}: tEXt")
            }
            _ => panic!("{name}: getTEXtChunk got {chunk:?}, upstream {want}"),
        }

        check_decoded(name, &decode_png_metadata(&png), &case["decoded"]);
    }
}

#[test]
fn every_prefix_of_the_embedded_fixtures_matches_upstream() {
    for p in cases("prefixes") {
        let file = p["file"].as_str().unwrap();
        let bytes = read_repo(file);
        assert_eq!(bytes.len() as u64, p["len"].as_u64().unwrap());
        let mut next = 0;
        for run in p["runs"].as_array().unwrap() {
            let (from, to) = (run["from"].as_u64().unwrap(), run["to"].as_u64().unwrap());
            assert_eq!(from, next, "{file}: runs are contiguous");
            for len in from..=to {
                let got = decode_png_metadata(&bytes[..len as usize]);
                check_decoded(&format!("{file}[..{len}]"), &got, &run["result"]);
            }
            next = to + 1;
        }
        assert_eq!(next, bytes.len() as u64 + 1, "{file}: every prefix");
    }
}

#[test]
fn encode_png_metadata_writes_upstream_bytes() {
    let cases = cases("encode");
    assert!(cases.len() >= 20);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let png = materialize(&case["png"]);
        let metadata = text_of(&case["metadata"]);
        let written = encode_png_metadata(&png, &metadata);
        match (&written, &case["written"]) {
            (Ok(bytes), w) if w.get("ok").is_some() => {
                check_bytes(name, bytes, &w["ok"]);
                check_decoded(
                    &format!("{name}: decode"),
                    &decode_png_metadata(bytes),
                    &case["decoded"],
                );
            }
            (Err(e), w) if w.get("error").is_some() => {
                assert_eq!(e.to_string(), w["error"].as_str().unwrap(), "{name}")
            }
            _ => panic!("{name}: got {written:?}, upstream {}", case["written"]),
        }
    }
}

#[test]
fn text_chunk_text_is_upstreams_json() {
    for case in cases("text_chunks") {
        let name = case["name"].as_str().unwrap();
        let text = text_of(&case["metadata"]);
        check_string(name, &encode(&text, true).to_json(), &case["json"]);
    }
}

// --- png-chunks-extract / png-chunks-encode / png-chunk-text ------------------

#[test]
fn chunks_round_trip_through_encode() {
    for name in [
        "smiley.png",
        "deer.png",
        "test_embedded_v1.png",
        "smiley_embedded_v2.png",
    ] {
        let bytes = fixture(name);
        let chunks = extract_chunks(&bytes).unwrap();
        assert_eq!(chunks.first().unwrap().name, *b"IHDR", "{name}");
        assert_eq!(chunks.last().unwrap().name, *b"IEND", "{name}");
        assert_eq!(encode_chunks(&chunks), bytes, "{name}");
    }
}

#[test]
fn metadata_chunk_goes_just_before_iend() {
    let written = encode_png_metadata(&fixture("smiley.png"), "{}").unwrap();
    let names: Vec<[u8; 4]> = extract_chunks(&written)
        .unwrap()
        .iter()
        .map(|c| c.name)
        .collect();
    assert_eq!(names, [*b"IHDR", *b"PLTE", *b"IDAT", *b"tEXt", *b"IEND"]);
    let chunk = get_text_chunk(&written).unwrap().unwrap();
    assert_eq!(chunk.keyword, MIME_TYPE_EXCALIDRAW);
    assert_eq!(chunk.text, encode("{}", true).to_json());
}

/// A chunk claiming 4 GiB is checked without allocating it: the CRC runs
/// over the zeros png-chunks-extract reads past the end in O(log n).
/// Upstream really does allocate 0xFFFFFFFF + 4 bytes and read zeros into
/// them; the generator runs it (goldens case `huge_chunk_length`, about a
/// minute and 4.4 GB per call in Node) so the error is upstream's own.
#[test]
fn a_huge_chunk_length_is_checked_without_allocating() {
    let mut png = fixture("smiley.png");
    png.truncate(8 + 25);
    png.extend_from_slice(&[0xff, 0xff, 0xff, 0xff]);
    png.extend_from_slice(b"IDAT");
    png.extend_from_slice(b"some data");
    let case = cases("decode")
        .iter()
        .find(|c| c["name"] == "huge_chunk_length")
        .expect("upstream golden for the 4 GiB chunk");
    assert_eq!(materialize(&case["input"]), png, "same bytes as the golden");
    let err = extract_chunks(&png).unwrap_err();
    assert_eq!(err, PngError::CrcMismatch { name: *b"IDAT" });
    assert_eq!(
        err.to_string(),
        case["text_chunk"]["error"].as_str().unwrap(),
        "getTEXtChunk"
    );
    check_decoded(
        "huge_chunk_length",
        &decode_png_metadata(&png),
        &case["decoded"],
    );
}

#[test]
fn png_chunk_text_encode_errors() {
    assert_eq!(
        encode_text_chunk("k\u{100}", "text").unwrap_err().to_string(),
        "Only Latin-1 characters are permitted in PNG tEXt chunks. You might want to consider base64 encoding and/or zEXt compression"
    );
    assert_eq!(
        encode_text_chunk("", "text").unwrap_err(),
        PngError::NotLatin1,
        "the Latin-1 test needs at least one character"
    );
    assert_eq!(encode_text_chunk("k", "").unwrap_err(), PngError::NotLatin1);
    let long = "k".repeat(80);
    assert_eq!(
        encode_text_chunk(&long, "text").unwrap_err().to_string(),
        format!("Keyword \"{long}\" is longer than the 79-character limit imposed by the PNG specification")
    );
    assert!(encode_text_chunk(&"k".repeat(79), "text").is_ok());
    assert_eq!(
        encode_text_chunk("a\0b", "text").unwrap_err().to_string(),
        "0x00 character is not permitted in tEXt keywords"
    );
    assert_eq!(
        encode_text_chunk("k", "a\0b").unwrap_err().to_string(),
        "0x00 character is not permitted in tEXt content"
    );
    assert_eq!(
        encode_text_chunk("k\u{e9}", "caf\u{e9}").unwrap(),
        Chunk {
            name: *b"tEXt",
            data: b"k\xe9\0caf\xe9".to_vec(),
        }
    );
}

#[test]
fn png_chunk_text_decode() {
    let c = decode_text_chunk(b"key\0val\xff").unwrap();
    assert_eq!((c.keyword.as_str(), c.text.as_str()), ("key", "val\u{ff}"));
    let c = decode_text_chunk(b"only keyword").unwrap();
    assert_eq!((c.keyword.as_str(), c.text.as_str()), ("only keyword", ""));
    assert_eq!(
        decode_text_chunk(b"k\0a\0b").unwrap_err().to_string(),
        "Invalid NULL character found. 0x00 character is not permitted in tEXt content"
    );
}

#[test]
fn embedded_scene_round_trips_for_every_fixture_scene() {
    for rel in [
        "crates/excali-core/tests/fixtures/every-type.excalidraw",
        "crates/excali-core/tests/fixtures/unknown-keys.excalidraw",
        "crates/excali-core/tests/fixtures/empty-scene.excalidraw",
    ] {
        let text = String::from_utf8(read_repo(rel)).unwrap();
        for png in ["smiley.png", "deer.png"] {
            let written = encode_png_metadata(&fixture(png), &text).unwrap();
            assert_eq!(
                decode_png_metadata(&written).unwrap().as_deref(),
                Some(&text[..]),
                "{rel} in {png}"
            );
        }
    }
}
