//! Scene-level restore: `restoreElements` and `bumpElementVersions`
//! (`packages/excalidraw/data/restore.ts:946-1173` at the pinned commit
//! 438d89861f53d8a90ad566113ecac1b83761098f; research page
//! `site/content/research/data-model.md`, section 3.4 "Scene-level passes",
//! and section 7).
//!
//! The first part ports the scene-level cases of upstream's
//! `packages/excalidraw/tests/data/restore.test.ts` ("restoreElements" and
//! "repairing bindings"), snapshot included. The second part states each
//! pass as a readable rule. The exhaustive check against upstream's own
//! output is `restore::scene_tests::upstream_fixture` inside the crate
//! (`fixtures/restore-elements.json`, generated by
//! `tools/goldens/restore-elements-fixtures.mjs`).

use excali_core::restore::{
    bump_element_versions, restore_elements, ElbowArrowRequest, RestoreElementsOptions,
    RestoreEnv, StickyNoteLayout, StickyNoteLayoutRequest, TestEnv, TextDimensionsRequest,
};
use serde_json::{json, Map, Value};

fn obj(v: Value) -> Map<String, Value> {
    match v {
        Value::Object(m) => m,
        _ => panic!("not an object"),
    }
}

fn opts(repair: bool, delete_invisible: bool) -> RestoreElementsOptions {
    RestoreElementsOptions {
        repair_bindings: repair,
        delete_invisible_elements: delete_invisible,
        refresh_dimensions: false,
    }
}

fn restore_with(
    elements: Vec<Value>,
    existing: Option<Vec<Value>>,
    options: RestoreElementsOptions,
    env: &mut dyn RestoreEnv,
) -> Vec<Map<String, Value>> {
    let existing: Option<Vec<Map<String, Value>>> =
        existing.map(|e| e.into_iter().map(obj).collect());
    restore_elements(&elements, existing.as_deref(), options, env).expect("restores")
}

/// `restoreElements(elements, null, opts)` in upstream's test mode.
fn restore(elements: Vec<Value>, options: RestoreElementsOptions) -> Vec<Map<String, Value>> {
    restore_with(elements, None, options, &mut TestEnv::default())
}

fn plain() -> RestoreElementsOptions {
    RestoreElementsOptions::default()
}

fn repair() -> RestoreElementsOptions {
    opts(true, false)
}

fn ids(elements: &[Map<String, Value>]) -> Vec<Value> {
    elements.iter().map(|e| e["id"].clone()).collect()
}

fn by_id<'a>(elements: &'a [Map<String, Value>], id: &str) -> &'a Map<String, Value> {
    elements
        .iter()
        .find(|e| e["id"] == id)
        .unwrap_or_else(|| panic!("no element {id}"))
}

/// What `API.createElement` (`tests/helpers/api.ts:166-436`) builds in
/// upstream's test mode, for the fields every type shares.
fn api(ty: &str, id: &str, fields: Value) -> Value {
    let mut element = obj(json!({
        "id": id,
        "type": ty,
        "x": 0,
        "y": 0,
        "width": 100,
        "height": 100,
        "angle": 0,
        "strokeColor": "#1e1e1e",
        "backgroundColor": "transparent",
        "fillStyle": "solid",
        "strokeWidth": 2,
        "strokeStyle": "solid",
        "roughness": 1,
        "opacity": 100,
        "groupIds": [],
        "frameId": null,
        "index": null,
        "roundness": null,
        "seed": 1,
        "version": 1,
        "versionNonce": 0,
        "isDeleted": false,
        "boundElements": null,
        "updated": 1,
        "created": 1,
        "link": null,
        "locked": false
    }));
    match ty {
        "text" => element.extend(obj(json!({
            "text": "test",
            "fontSize": 20,
            "baseFontSize": null,
            "fontFamily": 5,
            "textAlign": "left",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "test",
            "autoResize": true,
            "lineHeight": 1.25,
            "labelPosition": null
        }))),
        "arrow" | "line" => {
            element.extend(obj(json!({
                "points": [[0, 0], [100, 100]],
                "startBinding": null,
                "endBinding": null,
                "startArrowhead": null,
                "endArrowhead": null
            })));
            if ty == "arrow" {
                element.insert("elbowed".into(), json!(false));
            } else {
                element.insert("polygon".into(), json!(false));
            }
        }
        "freedraw" => element.extend(obj(json!({
            "strokeWidth": 1,
            "points": [[0, 0], [10, 10]],
            "pressures": [],
            "simulatePressure": true,
            "strokeOptions": { "variability": "variable", "streamline": 0.5 }
        }))),
        "stickynote" => element.extend(obj(json!({
            "width": 250,
            "height": 250,
            "baseHeight": 250,
            "backgroundColor": "#ffdf6b",
            "roundness": { "type": 3 }
        }))),
        _ => {}
    }
    element.extend(obj(fields));
    Value::Object(element)
}

// -- restore.test.ts: "restoreElements" -------------------------------------------

/// "basic restoreElements" (restore.test.ts:52-59).
#[test]
fn basic_restore() {
    let restored = restore(
        vec![api("text", "t", json!({})), api("rectangle", "r", json!({}))],
        plain(),
    );
    assert_eq!(restored.len(), 2);
}

/// "preserves creation metadata when repairing duplicate element IDs"
/// (restore.test.ts:94-103).
#[test]
fn duplicate_ids_keep_creation_metadata() {
    let element = api("rectangle", "r", json!({ "created": 123 }));
    let mut copy = obj(element.clone());
    copy.insert("created".into(), Value::Null);
    let restored = restore(vec![element, Value::Object(copy)], plain());
    let created: Vec<&Value> = restored.iter().map(|e| &e["created"]).collect();
    assert_eq!(created, [&json!(123), &Value::Null]);
    assert_ne!(restored[0]["id"], restored[1]["id"]);
    // the second one gets randomId(): id0 in test mode
    assert_eq!(restored[1]["id"], "id0");
}

/// "should restore transparent sticky note stroke as black"
/// (restore.test.ts:105-114).
#[test]
fn transparent_sticky_note_stroke_is_black() {
    let restored = restore(
        vec![api("stickynote", "s", json!({ "strokeColor": "transparent" }))],
        plain(),
    );
    assert_eq!(restored[0]["strokeColor"], "#1e1e1e");
}

/// "when imported data state is null it should return an empty array of
/// elements", "should return empty array when element is null"
/// (restore.test.ts:116-123).
#[test]
fn no_elements() {
    assert!(restore(vec![], plain()).is_empty());
}

/// "should not call isInvisiblySmallElement when element is a selection
/// element" (restore.test.ts:125-130): the selection is dropped before the
/// check, which would throw on its missing points... were it linear.
#[test]
fn selection_is_dropped() {
    assert!(restore(vec![json!({ "type": "selection" })], opts(false, true)).is_empty());
}

/// "should return empty array when input type is not supported"
/// (restore.test.ts:132-141).
#[test]
fn unsupported_type_is_dropped() {
    let restored = restore(
        vec![api("text", "t", json!({ "type": "not supported" }))],
        plain(),
    );
    assert!(restored.is_empty());
}

/// "should return empty array when isInvisiblySmallElement is true"
/// (restore.test.ts:143-152) mocks the helper; a zero-size rectangle is
/// invisibly small.
#[test]
fn invisibly_small_element_is_deleted() {
    let restored = restore(
        vec![api("rectangle", "r", json!({ "width": 0, "height": 0 }))],
        opts(false, true),
    );
    assert_eq!(restored.len(), 1);
    assert_eq!(restored[0]["isDeleted"], true);
    // bumpVersion, then syncInvalidIndices bumps again
    assert_eq!(restored[0]["version"], 3);
}

/// "should clamp restored font ceilings to the sticky note maximum"
/// (restore.test.ts:232-245).
#[test]
fn font_ceiling_is_clamped() {
    let restored = restore(
        vec![api("text", "t", json!({ "baseFontSize": 1e20 }))],
        plain(),
    );
    assert_eq!(restored[0]["baseFontSize"], 512);
}

/// "should clear a font ceiling on text that is not bound to a sticky note"
/// (restore.test.ts:247-262).
#[test]
fn font_ceiling_is_cleared_off_a_note() {
    let restored = restore(
        vec![api("text", "t", json!({ "baseFontSize": 28 }))],
        repair(),
    );
    assert_eq!(restored[0]["baseFontSize"], Value::Null);
}

/// "should seed the font ceiling and a visible stroke on a sticky note
/// label" (restore.test.ts:264-291).
#[test]
fn sticky_label_is_seeded() {
    let note = api(
        "stickynote",
        "sticky",
        json!({ "boundElements": [{ "type": "text", "id": "label" }] }),
    );
    let mut label = obj(api(
        "text",
        "label",
        json!({ "containerId": "sticky", "strokeColor": "transparent" }),
    ));
    label.remove("baseFontSize");
    let restored = restore(vec![note, Value::Object(label)], repair());
    let label = by_id(&restored, "label");
    assert_eq!(label["baseFontSize"], 20);
    assert_eq!(label["strokeColor"], "#1e1e1e");
}

/// "should give a note its label's color when the two drifted apart"
/// (restore.test.ts:293-319).
#[test]
fn note_takes_its_label_color() {
    let restored = restore(
        vec![
            api(
                "stickynote",
                "sticky",
                json!({ "boundElements": [{ "type": "text", "id": "label" }] }),
            ),
            api(
                "text",
                "label",
                json!({ "containerId": "sticky", "strokeColor": "#e03131" }),
            ),
        ],
        repair(),
    );
    assert_eq!(by_id(&restored, "sticky")["strokeColor"], "#e03131");
    assert_eq!(by_id(&restored, "label")["strokeColor"], "#e03131");
}

/// Answers `getStickyNoteLayout` with a fixed layout and records the calls.
#[derive(Default)]
struct LayoutEnv {
    test: TestEnv,
    calls: Vec<(Value, Value)>,
}

impl RestoreEnv for LayoutEnv {
    fn now(&mut self) -> f64 {
        self.test.now()
    }
    fn random_id(&mut self) -> String {
        self.test.random_id()
    }
    fn random_integer(&mut self) -> f64 {
        self.test.random_integer()
    }
    fn sticky_note_layout(
        &mut self,
        request: StickyNoteLayoutRequest<'_>,
    ) -> Option<StickyNoteLayout> {
        let text = request.text.map_or(Value::Null, |t| t["id"].clone());
        self.calls.push((request.note["id"].clone(), text));
        Some(StickyNoteLayout {
            container: obj(json!({ "height": 480, "baseHeight": 250 })),
            text: Some(obj(json!({ "fontSize": 16, "baseFontSize": 28 }))),
        })
    }
}

/// "should refit a sticky note together with its label when refreshing
/// dimensions" (restore.test.ts:342-379): the note and its label are
/// refitted together by `getStickyNoteLayout`, whose measuring the
/// environment supplies; the label is not refreshed on its own.
#[test]
fn sticky_note_refit_with_its_label() {
    let mut env = LayoutEnv::default();
    let restored = restore_with(
        vec![
            api(
                "stickynote",
                "sticky",
                json!({ "boundElements": [{ "type": "text", "id": "label" }] }),
            ),
            api(
                "text",
                "label",
                json!({ "containerId": "sticky", "fontSize": 28 }),
            ),
        ],
        None,
        RestoreElementsOptions {
            repair_bindings: true,
            refresh_dimensions: true,
            delete_invisible_elements: false,
        },
        &mut env,
    );
    assert_eq!(env.calls, [(json!("sticky"), json!("label"))]);
    let note = by_id(&restored, "sticky");
    let text = by_id(&restored, "label");
    assert_eq!(note["baseHeight"], 250);
    assert_eq!(note["height"], 480);
    assert_eq!(text["fontSize"], 16);
    assert_eq!(text["baseFontSize"], 28);
}

/// "should strip element if restore fails" (restore.test.ts:539-567): a
/// throwing getter cannot be in a file; a non-string link throws the same
/// way.
#[test]
fn element_whose_restore_fails_is_dropped() {
    let restored = restore(
        vec![
            api("rectangle", "r1", json!({ "boundElements": [] })),
            api("rectangle", "r2", json!({ "boundElements": [], "link": 7 })),
        ],
        plain(),
    );
    assert_eq!(ids(&restored), [json!("r1")]);
}

/// "should remove imperceptibly small elements" (restore.test.ts:569-590).
#[test]
fn imperceptibly_small_arrow_is_deleted() {
    let restored = restore(
        vec![api(
            "arrow",
            "a",
            json!({ "points": [[0, 0], [0.02, 0.05]] }),
        )],
        opts(false, true),
    );
    assert_eq!(restored[0]["isDeleted"], true);
}

/// "should keep 'imperceptibly' small freedraw/line elements"
/// (restore.test.ts:592-621).
#[test]
fn small_freedraw_and_line_are_kept() {
    let points = json!({ "points": [[0, 0], [0.0001, 0.0001]] });
    let restored = restore(
        vec![api("freedraw", "f", points.clone()), api("line", "l", points)],
        plain(),
    );
    assert_eq!(ids(&restored), [json!("f"), json!("l")]);
    assert!(restored.iter().all(|e| e["isDeleted"] == false));
}

/// "bump versions of local duplicate elements when supplied"
/// (restore.test.ts:909-933).
#[test]
fn bump_versions_of_local_duplicates() {
    let mut env = TestEnv::default();
    let restored = restore_with(
        vec![api("rectangle", "rect", json!({})), api("ellipse", "ellipse", json!({}))],
        None,
        plain(),
        &mut env,
    );
    let modified = obj(api(
        "rectangle",
        "rect",
        json!({ "isDeleted": true, "version": 2, "versionNonce": 5 }),
    ));
    let before = restored[0]["versionNonce"].clone();
    let bumped = bump_element_versions(restored, Some(&[modified]), &mut env).expect("bumps");
    assert_eq!(bumped[0]["id"], "rect");
    assert_ne!(bumped[0]["versionNonce"], before);
    assert_eq!(bumped[0]["version"], 3);
    // the ellipse was re-indexed on restore: 1 + 1
    assert_eq!(bumped[1]["version"], 2);
}

/// "bump versions of local duplicate elements when supplied even if both
/// have same version" (restore.test.ts:935-970).
#[test]
fn bump_versions_on_same_version_other_nonce() {
    let once = restore(vec![api("rectangle", "rect", json!({}))], plain());
    // restored once: +1 for the index
    assert_eq!(once[0]["version"], 2);
    let twice = restore(vec![Value::Object(once[0].clone())], plain());
    // restoring it again does not re-index
    assert_eq!(twice[0]["version"], 2);
    assert_eq!(twice[0]["versionNonce"], once[0]["versionNonce"]);

    let mut modified_1 = once[0].clone();
    modified_1.insert("width".into(), json!(500));
    modified_1.insert("versionNonce".into(), json!(11));
    let mut modified_2 = twice[0].clone();
    modified_2.insert("width".into(), json!(600));
    modified_2.insert("versionNonce".into(), json!(22));
    let mut env = TestEnv::default();
    let restored = restore_with(vec![Value::Object(modified_1)], None, plain(), &mut env);
    let bumped = bump_element_versions(restored, Some(&[modified_2]), &mut env).expect("bumps");
    assert_eq!(bumped[0]["id"], "rect");
    assert_ne!(bumped[0]["versionNonce"], 11);
    assert_eq!(bumped[0]["version"], 3);
}

// -- restore.test.ts: "repairing bindings" -------------------------------------------

/// "should repair bound %s label order and fractional index"
/// (restore.test.ts:1224-1257).
#[test]
fn repair_bound_label_order_and_index() {
    for container_type in ["arrow", "rectangle"] {
        let restored = restore(
            vec![
                api(
                    "text",
                    "label",
                    json!({ "index": "b2a", "containerId": "container" }),
                ),
                api(
                    container_type,
                    "container",
                    json!({
                        "index": "b2f",
                        "boundElements": [{ "type": "text", "id": "label" }]
                    }),
                ),
            ],
            repair(),
        );
        assert_eq!(ids(&restored), [json!("container"), json!("label")]);
        assert_eq!(restored[0]["index"], "b2f");
        let (label, container) = (
            restored[1]["index"].as_str().unwrap(),
            restored[0]["index"].as_str().unwrap(),
        );
        assert!(label > container, "{label} > {container}");
    }
}

/// "should strip arrow binding if repair throws" (restore.test.ts:1259-1309),
/// with its snapshot (`__snapshots__/restore.test.ts.snap:3-49`).
#[test]
fn strip_arrow_binding_if_repair_throws() {
    let restored = restore(
        vec![
            api(
                "arrow",
                "id-arrow01",
                json!({ "endBinding": { "elementId": 42 } }),
            ),
            api(
                "rectangle",
                "rect",
                json!({ "boundElements": [{ "type": "arrow", "id": "id-arrow01" }] }),
            ),
        ],
        plain(),
    );
    assert_eq!(restored[0]["endBinding"], Value::Null);
    assert_eq!(restored[1]["id"], "rect");
    let mut arrow = restored[0].clone();
    assert!(arrow.remove("seed").is_some_and(|s| s.is_number()));
    assert!(arrow.remove("versionNonce").is_some_and(|s| s.is_number()));
    assert_eq!(
        Value::Object(arrow),
        json!({
            "angle": 0,
            "backgroundColor": "transparent",
            "boundElements": [],
            "created": 1,
            "elbowed": false,
            "endArrowhead": null,
            "endBinding": null,
            "fillStyle": "solid",
            "frameId": null,
            "groupIds": [],
            "height": 100,
            "id": "id-arrow01",
            "index": "a0",
            "isDeleted": false,
            "link": null,
            "locked": false,
            "opacity": 100,
            "points": [[0, 0], [100, 100]],
            "roughness": 1,
            "roundness": null,
            "startArrowhead": null,
            "startBinding": null,
            "strokeColor": "#1e1e1e",
            "strokeStyle": "solid",
            "strokeWidth": 2,
            "type": "arrow",
            "updated": 1,
            "version": 2,
            "width": 100,
            "x": 0,
            "y": 0
        })
    );
}

/// "should repair container boundElements when repair is true"
/// (restore.test.ts:1311-1355).
#[test]
fn repair_container_bound_elements() {
    let elements = || {
        vec![
            api("rectangle", "c", json!({ "boundElements": [] })),
            api("text", "t", json!({ "containerId": "c" })),
        ]
    };
    let restored = restore(elements(), plain());
    assert_eq!(restored[0]["boundElements"], json!([]));
    assert_eq!(restored[1]["containerId"], "c");

    let restored = restore(elements(), repair());
    assert_eq!(
        restored[0]["boundElements"],
        json!([{ "type": "text", "id": "t" }])
    );
    assert_eq!(restored[1]["containerId"], "c");
}

/// "should repair containerId of boundElements when repair is true"
/// (restore.test.ts:1357-1399).
#[test]
fn repair_container_id_of_bound_elements() {
    let elements = || {
        vec![
            api(
                "rectangle",
                "c",
                json!({ "boundElements": [{ "type": "text", "id": "t" }] }),
            ),
            api("text", "t", json!({ "containerId": null })),
        ]
    };
    let restored = restore(elements(), plain());
    assert_eq!(restored[1]["containerId"], Value::Null);

    let restored = restore(elements(), repair());
    assert_eq!(
        restored[0]["boundElements"],
        json!([{ "type": "text", "id": "t" }])
    );
    assert_eq!(restored[1]["containerId"], "c");
}

/// "should ignore bound element if deleted" (restore.test.ts:1401-1429).
#[test]
fn deleted_bound_element_is_ignored() {
    let restored = restore(
        vec![
            api("rectangle", "c", json!({ "boundElements": [] })),
            api("text", "t", json!({ "containerId": "c", "isDeleted": true })),
        ],
        plain(),
    );
    assert_eq!(restored[0]["boundElements"], json!([]));
    assert_eq!(restored[1]["containerId"], "c");
}

/// "should remove bindings of deleted elements from boundElements when
/// repair is true" (restore.test.ts:1431-1506).
#[test]
fn bindings_of_deleted_elements_are_removed() {
    let bindings = json!([
        { "type": "text", "id": "deleted" },
        { "type": "text", "id": "invisible" },
        { "type": "text", "id": "non-existent" }
    ]);
    let elements = || {
        vec![
            api("rectangle", "c", json!({ "boundElements": bindings })),
            api(
                "text",
                "invisible",
                json!({ "containerId": "c", "width": 0, "height": 0 }),
            ),
            api(
                "text",
                "deleted",
                json!({ "containerId": "c", "isDeleted": true }),
            ),
        ]
    };
    let restored = restore(elements(), opts(false, true));
    assert_eq!(restored[0]["boundElements"], bindings);
    assert_eq!(restored[1]["isDeleted"], true);

    let restored = restore(elements(), opts(true, true));
    assert_eq!(restored[0]["boundElements"], json!([]));
    assert_eq!(ids(&restored), [json!("c"), json!("invisible"), json!("deleted")]);
    assert_eq!(restored[1]["containerId"], "c");
    assert_eq!(restored[1]["isDeleted"], true);
    assert_eq!(restored[2]["containerId"], "c");
}

/// "should remove containerId if container not exists when repair is true"
/// (restore.test.ts:1508-1552).
#[test]
fn container_id_of_missing_container_is_removed() {
    let elements = || {
        vec![
            api("text", "t1", json!({ "containerId": "non-existent" })),
            api(
                "text",
                "t2",
                json!({ "containerId": "non-existent", "isDeleted": true }),
            ),
        ]
    };
    let restored = restore(elements(), plain());
    assert!(restored.iter().all(|e| e["containerId"] == "non-existent"));
    let restored = restore(elements(), repair());
    assert!(restored.iter().all(|e| e["containerId"] == Value::Null));
}

// -- the passes as rules -------------------------------------------------------------

/// Duplicate ids: the first keeps its id, each later one gets `randomId()`;
/// ids are compared as JS `Set` keys, so `7` and `"7"` differ.
#[test]
fn duplicate_ids_get_fresh_ids() {
    let restored = restore(
        vec![
            api("rectangle", "r", json!({})),
            api("rectangle", "r", json!({})),
            api("rectangle", "r", json!({})),
            api("rectangle", "x", json!({ "id": 7 })),
            api("rectangle", "x", json!({ "id": "7" })),
        ],
        plain(),
    );
    assert_eq!(
        ids(&restored),
        [json!("r"), json!("id0"), json!("id1"), json!(7), json!("7")]
    );
}

/// `syncInvalidIndices`: valid indices are kept, the rest filled between
/// their valid neighbours, each change bumping the version.
#[test]
fn invalid_indices_are_repaired() {
    let restored = restore(
        vec![
            api("rectangle", "a", json!({ "index": "a0" })),
            api("rectangle", "b", json!({ "index": null })),
            api("rectangle", "c", json!({ "index": "zzz" })),
            api("rectangle", "d", json!({ "index": "a1" })),
        ],
        plain(),
    );
    let indices: Vec<&Value> = restored.iter().map(|e| &e["index"]).collect();
    assert_eq!(indices, [&json!("a0"), &json!("a0G"), &json!("a0V"), &json!("a1")]);
    let versions: Vec<&Value> = restored.iter().map(|e| &e["version"]).collect();
    assert_eq!(versions, [&json!(1), &json!(2), &json!(2), &json!(1)]);
}

/// Without `repairBindings` only the per-element restore, duplicate ids,
/// invisibly small elements and indices apply.
#[test]
fn no_repair_without_the_option() {
    let restored = restore(
        vec![
            api("text", "t", json!({ "containerId": "gone", "angle": 1 })),
            api("rectangle", "r", json!({ "frameId": "gone" })),
        ],
        plain(),
    );
    assert_eq!(restored[0]["containerId"], "gone");
    assert_eq!(restored[0]["angle"], 1);
    assert_eq!(restored[1]["frameId"], "gone");
}

/// `repairFrameMembership`: a `frameId` naming no element is cleared; any
/// existing element keeps it (the type is not checked).
#[test]
fn frame_membership() {
    let restored = restore(
        vec![
            api("frame", "f", json!({ "name": null })),
            api("rectangle", "in", json!({ "frameId": "f" })),
            api("rectangle", "missing", json!({ "frameId": "gone" })),
            api("rectangle", "odd", json!({ "frameId": "in" })),
        ],
        repair(),
    );
    assert_eq!(by_id(&restored, "in")["frameId"], "f");
    assert_eq!(by_id(&restored, "missing")["frameId"], Value::Null);
    assert_eq!(by_id(&restored, "odd")["frameId"], "in");
}

/// `repairBoundElement`: a bound text takes its container's angle, 0 for
/// an arrow container or a missing one.
#[test]
fn bound_text_takes_container_angle() {
    let restored = restore(
        vec![
            api(
                "rectangle",
                "r",
                json!({ "angle": 1.5, "boundElements": [{ "type": "text", "id": "t" }] }),
            ),
            api("text", "t", json!({ "containerId": "r", "angle": 0.3 })),
            api(
                "arrow",
                "a",
                json!({ "angle": 1.5, "boundElements": [{ "type": "text", "id": "u" }] }),
            ),
            api("text", "u", json!({ "containerId": "a", "angle": 0.3 })),
            api("text", "v", json!({ "containerId": "gone", "angle": 0.3 })),
        ],
        repair(),
    );
    assert_eq!(by_id(&restored, "t")["angle"], 1.5);
    assert_eq!(by_id(&restored, "u")["angle"], 0);
    assert_eq!(by_id(&restored, "v")["angle"], 0);
}

/// `repairContainerElement`: bindings deduplicated by id, those naming no
/// element or a deleted one dropped, in order.
#[test]
fn container_bound_elements_deduplicated() {
    let restored = restore(
        vec![
            api(
                "rectangle",
                "r",
                json!({ "boundElements": [
                    { "type": "text", "id": "t" },
                    { "type": "arrow", "id": "a" },
                    { "type": "text", "id": "t" },
                    { "type": "arrow", "id": "gone" },
                    { "type": "arrow", "id": "d" }
                ] }),
            ),
            api("text", "t", json!({ "containerId": "r" })),
            api("arrow", "a", json!({})),
            api("arrow", "d", json!({ "isDeleted": true })),
        ],
        repair(),
    );
    assert_eq!(
        restored[0]["boundElements"],
        json!([{ "type": "text", "id": "t" }, { "type": "arrow", "id": "a" }])
    );
}

/// Linear bindings: an arrow's binding to an element not in the restored
/// scene is dropped (even if it is in the existing elements).
#[test]
fn arrow_binding_to_missing_target_is_dropped() {
    let binding = json!({ "elementId": "r", "fixedPoint": [0.25, 0.75], "mode": "orbit" });
    let arrow = api("arrow", "a", json!({ "endBinding": binding }));
    let existing = vec![api("rectangle", "r", json!({}))];

    let restored = restore_with(
        vec![arrow.clone()],
        Some(existing.clone()),
        plain(),
        &mut TestEnv::default(),
    );
    assert_eq!(restored[0]["endBinding"], binding);

    let restored = restore_with(vec![arrow], Some(existing), repair(), &mut TestEnv::default());
    assert_eq!(restored[0]["endBinding"], Value::Null);
}

/// Bound text is moved right after its container, which keeps its index;
/// the moved text gets one between its new neighbours.
#[test]
fn bound_text_moves_after_its_container() {
    let restored = restore(
        vec![
            api("rectangle", "r", json!({
                "index": "a0",
                "boundElements": [{ "type": "text", "id": "t" }]
            })),
            api("rectangle", "s", json!({ "index": "a1" })),
            api("text", "t", json!({ "index": "a2", "containerId": "r" })),
        ],
        repair(),
    );
    assert_eq!(ids(&restored), [json!("r"), json!("t"), json!("s")]);
    assert_eq!(restored[0]["index"], "a0");
    assert_eq!(restored[1]["index"], "a0V");
    assert_eq!(restored[2]["index"], "a1");
}

/// Records elbow re-route requests.
#[derive(Default)]
struct ElbowEnv {
    test: TestEnv,
    requests: Vec<(Value, Vec<Value>)>,
    answer: Option<Map<String, Value>>,
}

impl RestoreEnv for ElbowEnv {
    fn now(&mut self) -> f64 {
        self.test.now()
    }
    fn random_id(&mut self) -> String {
        self.test.random_id()
    }
    fn random_integer(&mut self) -> f64 {
        self.test.random_integer()
    }
    fn update_elbow_arrow_points(
        &mut self,
        request: ElbowArrowRequest<'_>,
    ) -> Option<Map<String, Value>> {
        self.requests
            .push((request.arrow["id"].clone(), request.points.to_vec()));
        self.answer.clone()
    }
}

fn elbow(id: &str, points: Value) -> Value {
    api(
        "arrow",
        id,
        json!({
            "elbowed": true,
            "points": points,
            "fixedSegments": null,
            "startIsSpecial": null,
            "endIsSpecial": null,
            "endArrowhead": "arrow"
        }),
    )
}

/// An unbound elbow arrow with a segment that is not axis-aligned is
/// re-routed from `[0, 0]` to its last point by the environment
/// (`updateElbowArrowPoints`), keeping its index; a valid one is not.
#[test]
fn invalid_unbound_elbow_arrow_is_rerouted() {
    let mut env = ElbowEnv {
        answer: Some(obj(json!({
            "points": [[0, 0], [50, 0], [50, 50], [100, 50]],
            "index": "zz"
        }))),
        ..ElbowEnv::default()
    };
    let restored = restore_with(
        vec![
            elbow("bad", json!([[0, 0], [60, 40], [100, 50]])),
            elbow("good", json!([[0, 0], [50, 0], [50, 50], [100, 50]])),
        ],
        None,
        repair(),
        &mut env,
    );
    assert_eq!(env.requests, [(json!("bad"), vec![json!([0, 0]), json!([100, 50])])]);
    assert_eq!(
        restored[0]["points"],
        json!([[0, 0], [50, 0], [50, 50], [100, 50]])
    );
    assert_eq!(restored[0]["index"], "a0");
}

/// Without routing (the default environment) the elbow arrow is kept as
/// restored.
#[test]
fn elbow_arrow_kept_without_routing() {
    let restored = restore(
        vec![elbow("bad", json!([[0, 0], [60, 40], [100, 50]]))],
        repair(),
    );
    assert_eq!(restored[0]["points"], json!([[0, 0], [60, 40], [100, 50]]));
}

/// `refreshTextDimensions` is asked for every text but a sticky label, with
/// its container.
#[test]
fn refresh_text_dimensions_with_container() {
    #[derive(Default)]
    struct TextEnv {
        test: TestEnv,
        calls: Vec<(Value, Value)>,
    }
    impl RestoreEnv for TextEnv {
        fn now(&mut self) -> f64 {
            self.test.now()
        }
        fn random_id(&mut self) -> String {
            self.test.random_id()
        }
        fn random_integer(&mut self) -> f64 {
            self.test.random_integer()
        }
        fn refresh_text_dimensions(
            &mut self,
            request: TextDimensionsRequest<'_>,
        ) -> Option<Map<String, Value>> {
            let container = request.container.map_or(Value::Null, |c| c["id"].clone());
            self.calls.push((request.text["id"].clone(), container));
            Some(obj(json!({ "width": 42, "height": 7 })))
        }
    }
    let mut env = TextEnv::default();
    let restored = restore_with(
        vec![
            api(
                "rectangle",
                "r",
                json!({ "boundElements": [{ "type": "text", "id": "t" }] }),
            ),
            api("text", "t", json!({ "containerId": "r" })),
            api("text", "free", json!({})),
            api(
                "stickynote",
                "n",
                json!({ "boundElements": [{ "type": "text", "id": "label" }] }),
            ),
            api("text", "label", json!({ "containerId": "n" })),
        ],
        None,
        RestoreElementsOptions {
            repair_bindings: true,
            refresh_dimensions: true,
            delete_invisible_elements: false,
        },
        &mut env,
    );
    assert_eq!(
        env.calls,
        [(json!("t"), json!("r")), (json!("free"), Value::Null)]
    );
    assert_eq!(by_id(&restored, "t")["width"], 42);
    assert_eq!(by_id(&restored, "label")["width"], 100);
}

/// Inputs upstream throws on fail the whole restore with V8's message.
#[test]
fn errors() {
    let err = |elements: Vec<Value>, options| {
        restore_elements(&elements, None, options, &mut TestEnv::default())
            .expect_err("throws")
            .to_string()
    };
    assert_eq!(
        err(vec![api("rectangle", "r", json!({})), Value::Null], plain()),
        "Cannot read properties of null (reading 'id')"
    );
    assert_eq!(
        err(
            vec![api("rectangle", "r", json!({ "boundElements": 5 }))],
            repair()
        ),
        "container.boundElements.slice is not a function"
    );
    let mut line = obj(api("line", "l", json!({})));
    line.remove("points");
    assert_eq!(
        err(vec![Value::Object(line)], opts(false, true)),
        "Cannot read properties of undefined (reading 'length')"
    );
}
