//! Per-type restore: `restoreElement` (`packages/excalidraw/data/restore.ts:517-752`
//! at the pinned commit 438d89861f53d8a90ad566113ecac1b83761098f; research
//! page `site/content/research/data-model.md`, section 3.4).
//!
//! The first part ports the per-element cases of upstream's
//! `packages/excalidraw/tests/data/restore.test.ts` (copied under
//! `fixtures/upstream/`), snapshots included: upstream runs them through
//! `restoreElements`, whose only per-element effect on these inputs is
//! `syncInvalidIndices` (index `a0`, `a1`, ... and the version bump that
//! comes with it), so the snapshot tests apply the crate's
//! `sync_invalid_indices` to the restored elements the same way. Scene-level
//! passes (duplicate ids, invisibly small elements, binding repair) are
//! `restoreElements`' and not ported here.
//!
//! The second part is the rules as readable tables. The exhaustive check
//! against upstream's own output is `restore::element_tests::upstream_fixture`
//! inside the crate (`fixtures/restore-element.json`, generated by
//! `tools/goldens/restore-fixtures.mjs`).

use excali_core::element::Element;
use excali_core::fractional_index::{sync_invalid_indices, ChangeStamp};
use excali_core::restore::{
    restore_element, BindingEnd, ElementsMap, LegacyBinding, LegacyBindingRequest, RestoreEnv,
    RestoreError, RestoreOptions, TestEnv, MAX_LINEAR_PX,
};
use serde_json::{json, Map, Value};

fn obj(v: Value) -> Map<String, Value> {
    match v {
        Value::Object(m) => m,
        _ => panic!("not an object"),
    }
}

/// `restoreElement(element, arrayToMap([element]), null, opts)`.
fn restore_opts(
    element: Value,
    opts: RestoreOptions,
) -> Result<Option<Map<String, Value>>, RestoreError> {
    let element = obj(element);
    let targets = ElementsMap::new(std::slice::from_ref(&element));
    restore_element(&element, &targets, None, opts, &mut TestEnv::default())
}

fn restore(element: Value) -> Map<String, Value> {
    restore_opts(element, RestoreOptions::default())
        .expect("restores")
        .expect("a restorable type")
}

fn delete_invisible() -> RestoreOptions {
    RestoreOptions {
        delete_invisible_elements: true,
    }
}

/// What `API.createElement` (`tests/helpers/api.ts:166-436`) builds in
/// upstream's test mode, for the fields every type shares: seed 1,
/// `created` and `updated` 1, `boundElements` null, sharp corners.
fn api_base(ty: &str, id: &str) -> Map<String, Value> {
    obj(json!({
        "id": id,
        "type": ty,
        "x": 0,
        "y": 0,
        "width": 100,
        "height": 100,
        "angle": 0,
        "strokeColor": "#1e1e1e",
        "backgroundColor": "transparent",
        "fillStyle": "solid",
        "strokeWidth": 2,
        "strokeStyle": "solid",
        "roughness": 1,
        "opacity": 100,
        "groupIds": [],
        "frameId": null,
        "index": null,
        "roundness": null,
        "seed": 1,
        "version": 1,
        "versionNonce": 0,
        "isDeleted": false,
        "boundElements": null,
        "updated": 1,
        "created": 1,
        "link": null,
        "locked": false
    }))
}

fn api(ty: &str, id: &str, fields: Value) -> Value {
    let mut element = api_base(ty, id);
    element.extend(obj(fields));
    Value::Object(element)
}

fn api_text(id: &str, fields: Value) -> Value {
    let mut element = obj(api(
        "text",
        id,
        json!({
            "text": "test",
            "fontSize": 20,
            "baseFontSize": null,
            "fontFamily": 5,
            "textAlign": "left",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "test",
            "autoResize": true,
            "lineHeight": 1.25,
            "labelPosition": null
        }),
    ));
    element.extend(obj(fields));
    Value::Object(element)
}

fn api_linear(ty: &str, id: &str, fields: Value) -> Value {
    let mut element = obj(api(
        ty,
        id,
        json!({
            "points": [[0, 0], [100, 100]],
            "startBinding": null,
            "endBinding": null,
            "startArrowhead": null,
            "endArrowhead": null
        }),
    ));
    if ty == "arrow" {
        element.insert("elbowed".into(), json!(false));
    } else {
        element.insert("polygon".into(), json!(false));
    }
    element.extend(obj(fields));
    Value::Object(element)
}

fn api_freedraw(id: &str, fields: Value) -> Value {
    let mut element = obj(api(
        "freedraw",
        id,
        json!({
            "strokeWidth": 1,
            "points": [[0, 0], [10, 10]],
            "pressures": [],
            "simulatePressure": true,
            "strokeOptions": { "variability": "variable", "streamline": 0.5 }
        }),
    ));
    element.extend(obj(fields));
    Value::Object(element)
}

// -- restoreElements' index pass, for the snapshots ------------------------------

struct Stamp;

impl ChangeStamp for Stamp {
    fn version_nonce(&mut self) -> f64 {
        0.0
    }
    fn updated(&mut self) -> f64 {
        1.0
    }
}

/// `restoreElements(elements, null)` for inputs whose only scene-level
/// change is `syncInvalidIndices`: each element restored, then indexed.
fn restore_scene(elements: Vec<Value>, opts: RestoreOptions) -> Vec<Map<String, Value>> {
    let maps: Vec<Map<String, Value>> = elements.into_iter().map(obj).collect();
    let targets = ElementsMap::new(&maps);
    let mut env = TestEnv::default();
    let mut typed: Vec<Element> = maps
        .iter()
        .filter_map(|e| restore_element(e, &targets, None, opts, &mut env).expect("restores"))
        .map(|m| Element::from_map(m).expect("the typed model reads the restored element"))
        .collect();
    sync_invalid_indices(&mut typed, &mut Stamp).expect("indices sync");
    typed.iter().map(Element::to_map).collect()
}

/// A vitest snapshot: keys in any order, `Any<Number>` fields (`seed`,
/// `versionNonce`) and `customData: undefined` left out.
fn assert_snapshot(got: &Map<String, Value>, snapshot: Value) {
    let mut got = got.clone();
    assert!(got.remove("seed").is_some_and(|s| s.is_number()));
    assert!(got.remove("versionNonce").is_some_and(|s| s.is_number()));
    assert!(!got.contains_key("customData"));
    assert_eq!(as_floats(Value::Object(got)), as_floats(snapshot));
}

/// Every number as an f64, so `2` and `2.0` (the typed model's) compare
/// equal, as they do in JS.
fn as_floats(value: Value) -> Value {
    match value {
        Value::Number(n) => n
            .as_f64()
            .and_then(serde_json::Number::from_f64)
            .map_or(Value::Null, Value::Number),
        Value::Array(items) => Value::Array(items.into_iter().map(as_floats).collect()),
        Value::Object(map) => {
            Value::Object(map.into_iter().map(|(k, v)| (k, as_floats(v))).collect())
        }
        other => other,
    }
}

fn snapshot_base(ty: &str, id: &str, index: &str, version: u32) -> Map<String, Value> {
    obj(json!({
        "angle": 0,
        "backgroundColor": "transparent",
        "boundElements": [],
        "created": 1,
        "fillStyle": "solid",
        "frameId": null,
        "groupIds": [],
        "height": 100,
        "id": id,
        "index": index,
        "isDeleted": false,
        "link": null,
        "locked": false,
        "opacity": 100,
        "roughness": 1,
        "roundness": null,
        "strokeColor": "#1e1e1e",
        "strokeStyle": "solid",
        "strokeWidth": 2,
        "type": ty,
        "updated": 1,
        "version": version,
        "width": 100,
        "x": 0,
        "y": 0
    }))
}

fn snapshot(ty: &str, id: &str, index: &str, version: u32, fields: Value) -> Value {
    let mut s = snapshot_base(ty, id, index, version);
    s.extend(obj(fields));
    Value::Object(s)
}

// -- restore.test.ts: "restoreElements" -------------------------------------------

/// "basic restoreElements" (restore.test.ts:52-59).
#[test]
fn basic_restore() {
    let restored = restore_scene(
        vec![api_text("t", json!({})), api("rectangle", "r", json!({}))],
        RestoreOptions::default(),
    );
    assert_eq!(restored.len(), 2);
}

/// "restores created=%s without substituting load or last-update time"
/// (restore.test.ts:61-92); undefined is a missing key in a file.
#[test]
fn created_is_kept() {
    for created in [json!(123), json!(0), Value::Null, json!("absent")] {
        let mut element = obj(api(
            "rectangle",
            "r",
            json!({ "index": "a0", "updated": 456 }),
        ));
        if created == "absent" {
            element.remove("created");
        } else {
            element.insert("created".into(), created.clone());
        }
        let r = restore(Value::Object(element));
        let want = if created == "absent" {
            Value::Null
        } else {
            created
        };
        assert_eq!(r["created"], want);
        assert_eq!(r["updated"], json!(456));
        assert_eq!(r["id"], json!("r"));
        // A restored element restores to itself.
        assert_eq!(restore(Value::Object(r.clone())), r);
    }
}

/// "should restore transparent sticky note stroke as black" (restore.test.ts:105-114).
#[test]
fn sticky_note_transparent_stroke_becomes_black() {
    let sticky = api(
        "stickynote",
        "s",
        json!({
            "strokeColor": "transparent",
            "backgroundColor": "#ffdf6b",
            "baseHeight": 100
        }),
    );
    assert_eq!(restore(sticky)["strokeColor"], json!("#1e1e1e"));
}

/// "should return empty array when input type is not supported"
/// (restore.test.ts:132-141) and selection (125-130): no element.
#[test]
fn unsupported_types_are_dropped() {
    for ty in ["not supported", "selection", "Rectangle", "hexagon"] {
        let element = api_text("t", json!({ "type": ty }));
        assert_eq!(
            restore_opts(element, RestoreOptions::default()),
            Ok(None),
            "{ty}"
        );
    }
    assert_eq!(restore_opts(json!({}), RestoreOptions::default()), Ok(None));
    assert_eq!(
        restore_opts(json!({ "type": 5 }), RestoreOptions::default()),
        Ok(None)
    );
}

/// "should restore text element correctly passing value for each attribute"
/// (restore.test.ts:154-174), snapshot `restore.test.ts.snap`.
#[test]
fn text_snapshot() {
    let text = api_text(
        "id-text01",
        json!({
            "x": -20,
            "y": -8.75,
            "fontSize": 14,
            "fontFamily": 1,
            "text": "text",
            "originalText": "text",
            "textAlign": "center",
            "verticalAlign": "middle"
        }),
    );
    let restored = restore_scene(vec![text], RestoreOptions::default());
    assert_snapshot(
        &restored[0],
        snapshot(
            "text",
            "id-text01",
            "a0",
            2,
            json!({
                "autoResize": true,
                "baseFontSize": null,
                "containerId": null,
                "fontFamily": 1,
                "fontSize": 14,
                "labelPosition": null,
                "lineHeight": 1.25,
                "originalText": "text",
                "text": "text",
                "textAlign": "center",
                "verticalAlign": "middle",
                "x": -20,
                "y": -8.75
            }),
        ),
    );
}

/// "should not delete empty text element when opts.deleteInvisibleElements
/// is not defined" (restore.test.ts:176-191).
#[test]
fn empty_text_kept_without_delete_invisible() {
    let r = restore(api_text("t", json!({ "text": "", "originalText": "" })));
    assert_eq!(r["isDeleted"], json!(false));
    assert_eq!(r["id"], json!("t"));
}

/// "should restore text element correctly with unknown font family, null
/// text and undefined alignment" (restore.test.ts:193-213): the legacy
/// `font` string wins, an unknown family is Excalifont, and empty text is
/// deleted with a version bump.
#[test]
fn text_unknown_font_null_text_snapshot() {
    let mut text = obj(api_text(
        "id-text01",
        json!({ "text": null, "font": "10 unknown" }),
    ));
    text.remove("textAlign");
    text.remove("verticalAlign");
    let restored = restore_scene(vec![Value::Object(text)], delete_invisible());
    assert_eq!(restored[0]["isDeleted"], json!(true));
    assert_snapshot(
        &restored[0],
        snapshot(
            "text",
            "id-text01",
            "a0",
            3,
            json!({
                "autoResize": true,
                "baseFontSize": null,
                "containerId": null,
                "font": "10 unknown",
                "fontFamily": 5,
                "fontSize": 10,
                "isDeleted": true,
                "labelPosition": null,
                "lineHeight": 1.25,
                "originalText": "",
                "text": "",
                "textAlign": "left",
                "verticalAlign": "top"
            }),
        ),
    );
}

/// "should sanitize non-finite font sizes on text elements"
/// (restore.test.ts:215-230); NaN is `null` in a file.
#[test]
fn non_finite_font_size() {
    let r = restore(api_text(
        "t",
        json!({ "fontSize": null, "baseFontSize": "abc" }),
    ));
    assert_eq!(r["fontSize"], json!(20));
    assert_eq!(r["baseFontSize"], Value::Null);
}

/// "should clamp restored font ceilings to the sticky note maximum"
/// (restore.test.ts:232-245).
#[test]
fn base_font_size_clamped() {
    let r = restore(api_text("t", json!({ "baseFontSize": 1e20 })));
    assert_eq!(r["baseFontSize"], json!(512));
}

/// "should restore freedraw element correctly" (restore.test.ts:381-397).
#[test]
fn freedraw_snapshot() {
    let restored = restore_scene(
        vec![api_freedraw("id-freedraw01", json!({}))],
        RestoreOptions::default(),
    );
    assert_snapshot(
        &restored[0],
        snapshot(
            "freedraw",
            "id-freedraw01",
            "a0",
            2,
            json!({
                "points": [[0, 0], [10, 10]],
                "pressures": [],
                "simulatePressure": true,
                "strokeOptions": { "streamline": 0.5, "variability": "variable" },
                "strokeWidth": 1
            }),
        ),
    );
}

/// "should restore only valid freedraw points and keep pressures aligned"
/// (restore.test.ts:399-430); Infinity and NaN are `null` in a file.
#[test]
fn freedraw_invalid_points() {
    let r = restore(api_freedraw(
        "f",
        json!({
            "simulatePressure": false,
            "points": [[0, 0], [null, 10], null, [20, 20], [null, 30], [40, null]],
            "pressures": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
        }),
    ));
    assert_eq!(r["points"], json!([[0, 0], [20, 20]]));
    assert_eq!(r["pressures"], json!([0.1, 0.4]));
}

/// "should restore freedraw stroke variability" (restore.test.ts:432-477).
#[test]
fn freedraw_stroke_variability() {
    let table = [
        (Value::Null, "variable", 0.5),
        (json!({ "variability": "scribble" }), "variable", 0.5),
        (json!({ "variability": 42 }), "variable", 0.5),
        (
            json!({ "variability": "constant", "streamline": 0.8 }),
            "constant",
            0.8,
        ),
        (
            json!({ "variability": "variable", "streamline": 0.8 }),
            "variable",
            0.8,
        ),
    ];
    for (options, variability, streamline) in table {
        let mut element = obj(api_freedraw("f", json!({})));
        if options.is_null() {
            element.remove("strokeOptions");
        } else {
            element.insert("strokeOptions".into(), options);
        }
        let r = restore(Value::Object(element));
        assert_eq!(
            r["strokeOptions"],
            json!({ "variability": variability, "streamline": streamline })
        );
    }
}

/// "should restore line and draw elements correctly" (restore.test.ts:479-504).
#[test]
fn line_and_draw_snapshots() {
    let line = api_linear("line", "id-line01", json!({}));
    let draw = api_linear("line", "id-draw01", json!({ "type": "draw" }));
    let restored = restore_scene(vec![line, draw], RestoreOptions::default());
    for (element, id, index) in [
        (&restored[0], "id-line01", "a0"),
        (&restored[1], "id-draw01", "a1"),
    ] {
        assert_snapshot(
            element,
            snapshot(
                "line",
                id,
                index,
                2,
                json!({
                    "endArrowhead": null,
                    "endBinding": null,
                    "points": [[0, 0], [100, 100]],
                    "polygon": false,
                    "startArrowhead": null,
                    "startBinding": null
                }),
            ),
        );
    }
}

fn arrow_snapshot(id: &str) -> Value {
    snapshot(
        "arrow",
        id,
        "a0",
        2,
        json!({
            "elbowed": false,
            "endArrowhead": null,
            "endBinding": null,
            "points": [[0, 0], [100, 100]],
            "startArrowhead": null,
            "startBinding": null
        }),
    )
}

/// "should restore arrow element correctly" (restore.test.ts:506-517).
#[test]
fn arrow_snapshot_test() {
    let restored = restore_scene(
        vec![api_linear("arrow", "id-arrow01", json!({}))],
        RestoreOptions::default(),
    );
    assert_snapshot(&restored[0], arrow_snapshot("id-arrow01"));
}

/// "should normalize legacy crowfoot arrowheads on restore" (restore.test.ts:519-537).
#[test]
fn crowfoot_arrowheads() {
    let r = restore(api_linear(
        "arrow",
        "a",
        json!({ "startArrowhead": "crowfoot_one", "endArrowhead": "crowfoot_one_or_many" }),
    ));
    assert_eq!(r["startArrowhead"], json!("cardinality_one"));
    assert_eq!(r["endArrowhead"], json!("cardinality_one_or_many"));
}

/// "should strip element if restore fails" (restore.test.ts:539-567): the
/// port has no throwing getters; an element upstream throws on is an error,
/// which `restoreElements` drops.
#[test]
fn failing_element_is_an_error() {
    let rect = api("rectangle", "r", json!({ "boundElementIds": "a1" }));
    assert_eq!(
        restore_opts(rect, RestoreOptions::default()),
        Err(RestoreError::BoundElementIdsNotArray)
    );
}

/// "should remove imperceptibly small elements" (restore.test.ts:569-590)
/// and "should keep 'imperceptibly' small freedraw/line elements"
/// (592-621): marking an invisibly small element deleted is
/// `restoreElements`' (`restore.ts:989-998`); restoreElement keeps all three.
#[test]
fn tiny_elements_restore() {
    let arrow = api_linear("arrow", "a", json!({ "points": [[0, 0], [0.02, 0.05]] }));
    let r = restore_opts(arrow, delete_invisible())
        .expect("restores")
        .expect("an arrow");
    assert_eq!(r["isDeleted"], json!(false));
    assert_eq!(r["points"], json!([[0, 0], [0.02, 0.05]]));
    let freedraw = api_freedraw("f", json!({ "points": [[0, 0], [0.0001, 0.0001]] }));
    assert_eq!(restore(freedraw)["id"], json!("f"));
    let line = api_linear("line", "l", json!({ "points": [[0, 0], [0.0001, 0.0001]] }));
    assert_eq!(restore(line)["id"], json!("l"));
}

/// "should restore loop linears correctly" (restore.test.ts:623-673).
#[test]
fn loop_linears() {
    let points = json!([[0, 0], [100, 100], [100, 200], [0, 0]]);
    let line = restore(api_linear("line", "l", json!({ "points": points })));
    let arrow = restore(api_linear(
        "arrow",
        "a",
        json!({ "points": points, "x": 500, "y": 500 }),
    ));
    assert_eq!(line["type"], json!("line"));
    assert_eq!(line["points"], points);
    assert_eq!(arrow["type"], json!("arrow"));
    assert_eq!(arrow["points"], points);
}

/// `endArrowhead` null stays null (restore.test.ts:675-682); missing
/// becomes "arrow" (684-695).
#[test]
fn arrow_end_arrowhead_default() {
    let arrow = api_linear("arrow", "a", json!({}));
    assert_eq!(restore(arrow.clone())["endArrowhead"], Value::Null);
    let mut missing = obj(arrow);
    missing.remove("endArrowhead");
    assert_eq!(
        restore(Value::Object(missing))["endArrowhead"],
        json!("arrow")
    );
}

/// "when element.points of a line element is not an array" (restore.test.ts:697-717).
#[test]
fn line_points_not_array() {
    let line = api_linear(
        "line",
        "l",
        json!({ "width": 100, "height": 200, "points": "not an array" }),
    );
    assert_eq!(restore(line)["points"], json!([[0, 0], [100, 200]]));
}

/// "should restore only valid linear points" (restore.test.ts:719-763);
/// Infinity and NaN are `null` in a file.
#[test]
fn only_valid_linear_points() {
    let line = restore(api_linear(
        "line",
        "l",
        json!({
            "x": 10, "y": 20, "width": 100, "height": 200,
            "points": [[2, 3], null, [null, 4], [5, 7], [null, 8], [9, null]]
        }),
    ));
    assert_eq!(line["points"], json!([[0, 0], [3, 4]]));
    assert_eq!((&line["x"], &line["y"]), (&json!(12), &json!(23)));
    assert_eq!((&line["width"], &line["height"]), (&json!(3), &json!(4)));
    let arrow = restore(api_linear(
        "arrow",
        "a",
        json!({ "width": 100, "height": 200, "points": [[null, 0], [null, 4]] }),
    ));
    assert_eq!(arrow["points"], json!([[0, 0], [100, 200]]));
}

/// "should mark extremely large linear elements as deleted to avoid
/// freezing" (restore.test.ts:765-810): over 75,000 px the element is
/// replaced by a deleted 100 x 100 one at the origin.
#[test]
fn oversized_linear_elements() {
    let huge_line = restore(api_linear(
        "line",
        "l",
        json!({
            "x": 419048829414166_i64, "y": 8484,
            "points": [[0, 0], [-302985021938436_i64, 0], [-838097658820234_i64, 30]]
        }),
    ));
    let huge_arrow = restore(api_linear(
        "arrow",
        "a",
        json!({ "points": [[0, 0], [900000, 0]] }),
    ));
    let normal = restore(api_linear(
        "line",
        "n",
        json!({ "points": [[0, 0], [100, 200]] }),
    ));
    for r in [&huge_line, &huge_arrow] {
        assert_eq!(r["isDeleted"], json!(true));
        assert_eq!((&r["width"], &r["height"]), (&json!(100), &json!(100)));
        assert_eq!((&r["x"], &r["y"]), (&json!(0), &json!(0)));
        assert_eq!(r["points"], json!([[0, 0], [100, 100]]));
    }
    assert_eq!(normal["isDeleted"], json!(false));
    assert_eq!(
        (&normal["width"], &normal["height"]),
        (&json!(100), &json!(200))
    );
}

/// "when the number of points of a line is greater or equal 2"
/// (restore.test.ts:812-863): points are re-based so the first is [0, 0].
#[test]
fn points_rebased() {
    let at_origin = restore(api_linear(
        "line",
        "l0",
        json!({ "width": 100, "height": 200, "x": 10, "y": 20, "points": [[0, 0], [1, 1]] }),
    ));
    assert_eq!(at_origin["points"], json!([[0, 0], [1, 1]]));
    let moved = restore(api_linear(
        "line",
        "l1",
        json!({ "width": 200, "height": 400, "x": 30, "y": 40, "points": [[3, 4], [5, 6]] }),
    ));
    assert_eq!(moved["points"], json!([[0, 0], [2, 2]]));
    assert_eq!((&moved["x"], &moved["y"]), (&json!(33), &json!(44)));
}

/// "should restore correctly with rectangle, ellipse and diamond elements"
/// (restore.test.ts:865-907).
#[test]
fn generic_snapshots() {
    let fields = |ty: &str| {
        json!({
            "fillStyle": "cross-hatch",
            "strokeStyle": "dashed",
            "roughness": 2,
            "opacity": 10,
            "x": 10,
            "y": 20,
            "strokeColor": "red",
            "backgroundColor": "blue",
            "width": 100,
            "height": 200,
            "groupIds": ["1", "2", "3"],
            "roundness": { "type": if ty == "rectangle" { 3 } else { 2 } }
        })
    };
    let elements = ["rectangle", "ellipse", "diamond"]
        .iter()
        .enumerate()
        .map(|(i, ty)| api(ty, &(i + 1).to_string(), fields(ty)))
        .collect();
    let restored = restore_scene(elements, RestoreOptions::default());
    for (i, ty) in ["rectangle", "ellipse", "diamond"].iter().enumerate() {
        let id = (i + 1).to_string();
        let index = ["a0", "a1", "a2"][i];
        assert_snapshot(&restored[i], snapshot(ty, &id, index, 2, fields(ty)));
    }
}

// -- restore.test.ts: "repairing bindings" --------------------------------------

/// "should strip arrow binding if repair throws" (restore.test.ts:1259-1309):
/// a legacy binding to an id no element has is dropped.
#[test]
fn arrow_binding_to_missing_element_is_dropped() {
    let container = obj(api(
        "rectangle",
        "container",
        json!({ "boundElements": [{ "type": "arrow", "id": "id-arrow01" }] }),
    ));
    let arrow = obj(api_linear(
        "arrow",
        "id-arrow01",
        json!({ "endBinding": { "elementId": 42 } }),
    ));
    let all = [arrow.clone(), container];
    let targets = ElementsMap::new(&all);
    let r = restore_element(
        &arrow,
        &targets,
        None,
        RestoreOptions::default(),
        &mut TestEnv::default(),
    )
    .expect("restores")
    .expect("an arrow");
    assert_eq!(r["endBinding"], Value::Null);
    let mut typed = vec![Element::from_map(r).expect("typed")];
    sync_invalid_indices(&mut typed, &mut Stamp).expect("indices sync");
    assert_snapshot(&typed[0].to_map(), arrow_snapshot("id-arrow01"));
}

// -- the rules ---------------------------------------------------------------------

/// The legacy `font: "<size>px <Family>"` (`restore.ts:538-544`): size by
/// `parseFloat` of the first word, family by exact name of the second (so
/// two-word names never match), unknown names Excalifont; a non-finite
/// size is 20.
#[test]
fn legacy_font_string() {
    let table: &[(&str, Value, Value)] = &[
        ("20px Virgil", json!(20), json!(1)),
        ("16px Helvetica", json!(16), json!(2)),
        ("36px Cascadia", json!(36), json!(3)),
        ("12.5px Nunito", json!(12.5), json!(6)),
        ("1e2px Assistant", json!(100), json!(10)),
        ("20px Lilita One", json!(20), json!(5)),
        ("20px virgil", json!(20), json!(5)),
        ("20px", json!(20), json!(5)),
        ("abc Virgil", json!(20), json!(1)),
        ("Infinity Virgil", json!(20), json!(1)),
        ("20px  Virgil", json!(20), json!(5)),
        ("", json!(20), json!(5)),
    ];
    for (font, size, family) in table {
        let mut element = obj(api_text("t", json!({ "font": font })));
        element.remove("fontSize");
        element.remove("fontFamily");
        let r = restore(Value::Object(element));
        assert_eq!(
            (&r["fontSize"], &r["fontFamily"]),
            (size, family),
            "{font:?}"
        );
        // The legacy key stays (upstream spreads the element back).
        assert_eq!(r["font"], json!(font));
    }
    let null_font = api_text("t", json!({ "font": null }));
    assert_eq!(
        restore_opts(null_font, RestoreOptions::default()).map(|_| ()),
        Err(RestoreError::FontNull)
    );
    let number_font = api_text("t", json!({ "font": 20 }));
    assert_eq!(
        restore_opts(number_font, RestoreOptions::default()).map(|_| ()),
        Err(RestoreError::FontNotString)
    );
}

/// `lineHeight || (height ? height / lines / fontSize : lineHeight of
/// element.fontFamily)` (`restore.ts:555-562`, `textMeasurements.ts:80-85`,
/// `font-metadata.ts:175-181`).
#[test]
fn text_line_height() {
    let detected = restore(api_text(
        "t",
        json!({ "lineHeight": 0, "height": 72, "fontSize": 16, "text": "a\r\nb\rc" }),
    ));
    assert_eq!(detected["lineHeight"], json!(1.5));
    for (family, want) in [
        (1, 1.25),
        (2, 1.15),
        (3, 1.2),
        (4, 1.25),
        (7, 1.15),
        (9, 1.15),
    ] {
        let r = restore(api_text(
            "t",
            json!({ "lineHeight": null, "height": 0, "fontFamily": family }),
        ));
        assert_eq!(r["lineHeight"], json!(want), "family {family}");
    }
    let no_text = api_text("t", json!({ "lineHeight": null, "text": null }));
    assert_eq!(
        restore_opts(no_text, RestoreOptions::default()).map(|_| ()),
        Err(RestoreError::TextNull)
    );
}

/// `normalizeArrowhead` (`packages/element/src/arrowheads.ts:3-21`) on
/// lines and arrows: legacy names renamed, anything else kept as it is.
#[test]
fn arrowhead_renames() {
    let table: &[(Value, Value)] = &[
        (json!("dot"), json!("circle")),
        (json!("crowfoot_one"), json!("cardinality_one")),
        (json!("crowfoot_many"), json!("cardinality_many")),
        (
            json!("crowfoot_one_or_many"),
            json!("cardinality_one_or_many"),
        ),
        (json!("triangle"), json!("triangle")),
        (json!("unknown"), json!("unknown")),
        (Value::Null, Value::Null),
    ];
    for ty in ["line", "arrow"] {
        for (legacy, current) in table {
            let r = restore(api_linear(
                ty,
                "x",
                json!({ "startArrowhead": legacy, "endArrowhead": legacy }),
            ));
            assert_eq!(
                (&r["startArrowhead"], &r["endArrowhead"]),
                (current, current),
                "{ty} {legacy}"
            );
        }
    }
}

/// Legacy `draw` restores as `line` without `polygon`; lines lose their
/// bindings (`restore.ts:612-655`).
#[test]
fn draw_becomes_line() {
    let r = restore(api_linear(
        "line",
        "d",
        json!({
            "type": "draw",
            "polygon": true,
            "startBinding": { "elementId": "x", "mode": "orbit", "fixedPoint": [0, 0] },
            "points": [[0, 0], [10, 0], [10, 10], [0, 0]]
        }),
    ));
    assert_eq!(r["type"], json!("line"));
    assert_eq!(r["startBinding"], Value::Null);
    // `polygon` is only restored for `line`; `draw` keeps what it had.
    assert_eq!(r["polygon"], json!(true));
    let line = restore(api_linear(
        "line",
        "l",
        json!({ "polygon": true, "points": [[0, 0], [10, 0], [0, 0]] }),
    ));
    assert_eq!(line["polygon"], json!(false));
}

/// The 75,000 px cap is inclusive: exactly `MAX_LINEAR_PX` is kept.
#[test]
fn cap_boundary() {
    assert_eq!(MAX_LINEAR_PX, 75_000.0);
    let at = restore(api_linear(
        "line",
        "l",
        json!({ "points": [[0, 0], [75000, 10]] }),
    ));
    assert_eq!(at["isDeleted"], json!(false));
    let over = restore(api_linear(
        "line",
        "l",
        json!({ "points": [[0, 0], [75000.5, 10]] }),
    ));
    assert_eq!(over["isDeleted"], json!(true));
}

/// Elbow arrows keep `fixedSegments` only when it is non-empty and the
/// arrow has at least 4 points (`restore.ts:702-712`).
#[test]
fn fixed_segments_rule() {
    let four = json!([[0, 0], [50, 0], [50, 50], [100, 50]]);
    let three = json!([[0, 0], [50, 0], [50, 50]]);
    let segments = json!([{ "index": 2, "start": [50, 0], "end": [50, 50] }]);
    let table: &[(Value, Value, Value)] = &[
        (four.clone(), segments.clone(), segments.clone()),
        (four.clone(), json!([]), Value::Null),
        (three, segments.clone(), Value::Null),
        (four.clone(), Value::Null, Value::Null),
    ];
    for (points, fixed, want) in table {
        let r = restore(api_linear(
            "arrow",
            "e",
            json!({ "elbowed": true, "points": points, "fixedSegments": fixed }),
        ));
        assert_eq!(&r["fixedSegments"], want, "{points} {fixed}");
    }
    // Only elbow arrows: a simple arrow's fixedSegments is left as it was.
    let simple = restore(api_linear(
        "arrow",
        "s",
        json!({ "points": four, "fixedSegments": [] }),
    ));
    assert_eq!(simple["fixedSegments"], json!([]));
}

/// Bindings with a `mode` are kept (`elementId` required), fixed points
/// normalised (`binding.ts:2752-2778`); elbow arrows default `mode` to
/// "orbit" (`restore.ts:315-325`).
#[test]
fn bindings_with_mode() {
    let r = restore(api_linear(
        "arrow",
        "a",
        json!({
            "startBinding": { "elementId": "r", "mode": "inside", "fixedPoint": [0.5, 20] },
            "endBinding": { "mode": "orbit", "fixedPoint": [0.2, 0.2] }
        }),
    ));
    assert_eq!(
        r["startBinding"],
        json!({ "elementId": "r", "mode": "inside", "fixedPoint": [0.5001, 10] })
    );
    assert_eq!(r["endBinding"], Value::Null);
    let elbow = restore(api_linear(
        "arrow",
        "e",
        json!({
            "elbowed": true,
            "startBinding": { "elementId": "r", "fixedPoint": null, "focus": 0 }
        }),
    ));
    assert_eq!(
        elbow["startBinding"],
        json!({ "elementId": "r", "fixedPoint": [0.5001, 0.5001], "focus": 0, "mode": "orbit" })
    );
}

/// A legacy binding (no `mode`) to an element that exists is migrated with
/// geometry the environment supplies (`restore.ts:362-418`); the request
/// names the arrow with its restored points and the target, and without
/// an answer the binding is dropped, as when upstream's repair fails.
#[test]
fn legacy_binding_migration() {
    struct Geometry(Vec<(BindingEnd, Value, Value)>);
    impl RestoreEnv for Geometry {
        fn now(&mut self) -> f64 {
            1.0
        }
        fn random_id(&mut self) -> String {
            "id".into()
        }
        fn random_integer(&mut self) -> f64 {
            0.0
        }
        fn migrate_legacy_binding(
            &mut self,
            request: LegacyBindingRequest<'_>,
        ) -> Option<LegacyBinding> {
            self.0.push((
                request.end,
                request.arrow["points"].clone(),
                request.bound_element["id"].clone(),
            ));
            (request.end == BindingEnd::End).then(|| LegacyBinding {
                mode: json!("orbit"),
                fixed_point: json!([0, 0.5001]),
            })
        }
    }
    let arrow = obj(api_linear(
        "arrow",
        "a",
        json!({
            "points": [[5, 5], [100, 5]],
            "startBinding": { "elementId": "r0", "focus": 0, "gap": 1 },
            "endBinding": { "elementId": "r1", "focus": 0, "gap": 5 }
        }),
    ));
    let all = [
        arrow.clone(),
        obj(api("rectangle", "r0", json!({ "x": -50 }))),
        obj(api("rectangle", "r1", json!({ "x": 100 }))),
    ];
    let targets = ElementsMap::new(&all);
    let mut env = Geometry(Vec::new());
    let r = restore_element(&arrow, &targets, None, RestoreOptions::default(), &mut env)
        .expect("restores")
        .expect("an arrow");
    assert_eq!(
        env.0,
        [
            (BindingEnd::Start, json!([[5, 5], [100, 5]]), json!("r0")),
            (BindingEnd::End, json!([[5, 5], [100, 5]]), json!("r1")),
        ]
    );
    assert_eq!(r["startBinding"], Value::Null);
    assert_eq!(
        r["endBinding"],
        json!({ "mode": "orbit", "elementId": "r1", "fixedPoint": [0, 0.5001] })
    );
    // TestEnv has no geometry: the binding is dropped.
    let dropped = restore_element(
        &arrow,
        &targets,
        None,
        RestoreOptions::default(),
        &mut TestEnv::default(),
    )
    .expect("restores")
    .expect("an arrow");
    assert_eq!(dropped["endBinding"], Value::Null);
}

/// Sticky notes (`restore.ts:732-740`, `newElement.ts:185-228`):
/// `baseHeight ?? maxHeight ?? height`, never-transparent colours, solid
/// fill, at least 75 x 75, height at least baseHeight; each normalisation
/// that changes something bumps the version.
#[test]
fn sticky_notes() {
    let note = |fields: Value| {
        let mut n = obj(api(
            "stickynote",
            "s",
            json!({ "backgroundColor": "#ffdf6b", "width": 250, "height": 250 }),
        ));
        n.extend(obj(fields));
        Value::Object(n)
    };
    let kept = restore(note(json!({ "baseHeight": 250 })));
    assert_eq!(
        (&kept["version"], &kept["baseHeight"]),
        (&json!(1), &json!(250))
    );
    let legacy = restore(note(json!({ "maxHeight": 200 })));
    assert_eq!(legacy["baseHeight"], json!(200));
    assert_eq!(legacy["version"], json!(1));
    let small = restore(note(json!({ "width": 20, "height": 30, "baseHeight": 10 })));
    assert_eq!(
        (&small["width"], &small["height"], &small["baseHeight"]),
        (&json!(75), &json!(75), &json!(75))
    );
    let styled = restore(note(json!({
        "baseHeight": 250,
        "backgroundColor": "rgba(0,0,0,0)",
        "strokeColor": "#0000",
        "fillStyle": "hachure"
    })));
    assert_eq!(styled["backgroundColor"], json!("#ffdf6b"));
    assert_eq!(styled["strokeColor"], json!("#1e1e1e"));
    assert_eq!(styled["fillStyle"], json!("solid"));
    assert_eq!(styled["version"], json!(2));
}

/// Sticky note colours go through `isTransparent` (`colors.ts:389-391`,
/// excali-core's tinycolor2 port in `color.rs`, whose own tables are
/// `tests/color.rs` and `app-state.json`): a colour with alpha 0 becomes
/// the default, anything else is kept, and what tinycolor throws on
/// (`newElement.ts:185-199`) fails the element.
#[test]
fn sticky_note_colours_use_is_transparent() {
    let note = |background: Value| {
        let mut n = obj(api(
            "stickynote",
            "s",
            json!({ "width": 250, "height": 250, "baseHeight": 250 }),
        ));
        n.insert("backgroundColor".to_owned(), background);
        Value::Object(n)
    };
    for (color, transparent) in [
        (json!("transparent"), true),
        (json!(" TRANSPARENT "), true),
        (json!("#fff0"), true),
        (json!("#ffffff00"), true),
        (json!("rgba(0, 0, 0, 0)"), true),
        (json!("hsla(120, 50%, 50%, 0.0)"), true),
        (json!({ "a": 0 }), true),
        (json!({ "a": "0" }), true),
        (json!("#fff"), false),
        (json!("rgba(0, 0, 0, 0.5)"), false),
        (json!("red"), false),
        (json!({ "a": 0.5 }), false),
        (json!(5), false),
        (json!(["transparent"]), false),
    ] {
        let want = if transparent {
            json!("#ffdf6b")
        } else {
            color.clone()
        };
        assert_eq!(
            restore(note(color.clone()))["backgroundColor"],
            want,
            "{color}"
        );
    }
    for falsy in [json!(""), json!(0), json!(null)] {
        assert_eq!(
            restore(note(falsy.clone()))["backgroundColor"],
            json!("#ffdf6b"),
            "{falsy}"
        );
    }
    assert_eq!(
        restore_opts(
            note(json!({ "a": { "toString": 1 } })),
            RestoreOptions::default()
        ),
        Err(RestoreError::NoPrimitiveValue)
    );
    assert_eq!(
        restore_opts(
            note(json!({ "hasOwnProperty": 1, "a": 0 })),
            RestoreOptions::default()
        ),
        Err(RestoreError::HasOwnPropertyNotFunction)
    );
}

/// `ElementsMap` is `arrayToMap`: keyed by `id`, the last element of an id
/// winning, ids compared as JS `Map` keys.
#[test]
fn elements_map() {
    let elements = [
        obj(json!({ "id": "a", "n": 1 })),
        obj(json!({ "id": 7, "n": 2 })),
        obj(json!({ "id": "a", "n": 3 })),
        obj(json!({ "n": 4 })),
    ];
    let map = ElementsMap::new(&elements);
    assert_eq!(map.len(), 3);
    assert_eq!(map.get(&json!("a")).map(|e| e["n"].clone()), Some(json!(3)));
    assert_eq!(map.get(&json!(7.0)).map(|e| e["n"].clone()), Some(json!(2)));
    assert_eq!(map.get(&json!("7")), None);
    assert_eq!(map.get(&json!(null)), None);
}

/// `TestEnv::random_integer` is upstream's `randomInteger()` after
/// `reseed(1)` (`packages/common/src/random.ts:9-14`): `Math.floor` of
/// roughjs `Random(1).next() * 2^31`, checked against the recorded
/// `Random.next()` sequence in `goldens/random.json`.
#[test]
fn test_env_random_integer_is_roughjs_random() {
    let goldens: Value =
        serde_json::from_str(include_str!("../../../goldens/random.json")).expect("goldens parse");
    let seed1 = goldens["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .find(|c| c["seed"] == json!(1))
        .expect("seed 1");
    let mut env = TestEnv::default();
    for value in seed1["values"].as_array().expect("values") {
        let next = value.as_f64().expect("number");
        assert_eq!(env.random_integer(), (next * 2f64.powi(31)).floor());
    }
}
