//! The welcome screen (`components/welcome-screen/*`, research
//! `ui-design-system.md` §3.8): `WelcomeScreen.Center` (the Excalidraw
//! logo, the heading and a menu with Open and Help) and the three hints
//! (`MenuHint`, `ToolbarHint`, `HelpHint`), each an arrow drawn towards the
//! control it points at. Upstream tunnels each part to its slot in the
//! layer UI (`LayerUI.tsx:245`, `:355-357`, `:655`; `Footer.tsx:77`); the
//! host puts them in the same places, while `renderWelcomeScreen`
//! (`App.tsx:2516-2522`) holds: not loading, `showWelcomeScreen`, the
//! preferred selection tool active, not in zen mode and no elements at all.
//!
//! [`welcome_screen_center`], [`menu_hint`], [`toolbar_hint`] and
//! [`help_hint`] build the DOM upstream's default `WelcomeScreen` leaves
//! (`tests/hints.rs` holds each form factor and platform of
//! `tests/fixtures/hints.json` to it); a click on a menu item reports its
//! [`WelcomeScreenEvent`], whose [`WelcomeScreenEvent::action`] the host
//! executes. [`WELCOME_SCREEN_CSS`] is `WelcomeScreen.scss` with
//! `ExcalidrawLogo.scss`; [`excalidraw_logo`] is `<ExcalidrawLogo withText
//! />` as React writes it ([`EXCALIDRAW_LOGO_HTML`]).
//!
//! Not ported: the hosted app's own welcome screen
//! (`excalidraw-app/components/AppWelcomeScreen.tsx`: its storage warning
//! heading, live collaboration and Excalidraw+ sign-up items), which is the
//! excalidraw.com app's, not the editor's.

use std::rc::Rc;

use excali_editor::actions::{get_shortcut_from_shortcut_name, ActionName, KeyLabels};
use excali_scene::shape::Theme;

use crate::dom::{Element, Node};
use crate::editor_interface::FormFactor;
use crate::icons::{self, Icon};

/// Upstream's `WelcomeScreen.scss` and `ExcalidrawLogo.scss`, compiled
/// (generated by `tools/goldens/hints.mjs`).
pub const WELCOME_SCREEN_CSS: &str = include_str!("welcome_screen.css");

/// `<ExcalidrawLogo withText />` as React renders it (generated by
/// `tools/goldens/hints.mjs`).
pub const EXCALIDRAW_LOGO_HTML: &str = include_str!("excalidraw_logo.html");

/// The `data-excali-ui` value of the `<style>` holding
/// [`WELCOME_SCREEN_CSS`].
const STYLESHEET_ID: &str = "welcome-screen";

/// Adds [`WELCOME_SCREEN_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(WELCOME_SCREEN_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings of the welcome screen (`locales/en.json`); the key
/// itself for any other.
pub fn welcome_text(key: &str) -> &str {
    match key {
        "welcomeScreen.defaults.menuHint" => "Export, preferences, and more...",
        "welcomeScreen.defaults.center_heading" => "Diagrams. Made. Simple.",
        "welcomeScreen.defaults.toolbarHint" => "Pick a tool & Start drawing!",
        "welcomeScreen.defaults.helpHint" => "Shortcuts & help",
        "buttons.load" => "Open",
        "helpDialog.title" => "Help",
        other => other,
    }
}

/// A welcome screen menu item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WelcomeScreenEvent {
    /// `MenuItemLoadScene`: `actionLoadScene`.
    LoadScene,
    /// `MenuItemHelp`: `actionShortcuts`.
    Help,
}

impl WelcomeScreenEvent {
    /// The action the item executes.
    pub fn action(self) -> ActionName {
        match self {
            WelcomeScreenEvent::LoadScene => ActionName::LoadScene,
            WelcomeScreenEvent::Help => ActionName::ToggleShortcuts,
        }
    }

    /// The item's label key.
    pub fn label_key(self) -> &'static str {
        match self {
            WelcomeScreenEvent::LoadScene => "buttons.load",
            WelcomeScreenEvent::Help => "helpDialog.title",
        }
    }

    fn icon(self) -> &'static Icon {
        match self {
            WelcomeScreenEvent::LoadScene => &icons::LoadIcon,
            WelcomeScreenEvent::Help => &icons::HelpIcon,
        }
    }

    fn shortcut(self, is_darwin: bool) -> String {
        match self {
            WelcomeScreenEvent::LoadScene => {
                get_shortcut_from_shortcut_name("loadScene", 0, is_darwin, &KeyLabels::EN)
            }
            WelcomeScreenEvent::Help => "?".into(),
        }
    }
}

/// Called with the menu item clicked.
pub type OnWelcomeScreenEvent = Rc<dyn Fn(WelcomeScreenEvent)>;

/// What the welcome screen reads.
#[derive(Clone)]
pub struct WelcomeScreenProps {
    /// `editorInterface.formFactor`: a phone shows no shortcuts.
    pub form_factor: FormFactor,
    /// `appState.viewModeEnabled`: no Open item.
    pub view_mode_enabled: bool,
    pub is_darwin: bool,
    pub on_event: Option<OnWelcomeScreenEvent>,
}

/// The menu's items, in order (`WelcomeScreen.Center.tsx:98-101`).
pub fn menu_items(props: &WelcomeScreenProps) -> Vec<WelcomeScreenEvent> {
    let mut out = Vec::new();
    if !props.view_mode_enabled {
        out.push(WelcomeScreenEvent::LoadScene);
    }
    out.push(WelcomeScreenEvent::Help);
    out
}

fn icon_node(icon: &Icon) -> Option<Element> {
    icon.element(Theme::Light)
}

/// `WelcomeScreenMenuItem` (`WelcomeScreen.Center.tsx:34-60`).
fn menu_item(props: &WelcomeScreenProps, item: WelcomeScreenEvent) -> Element {
    let shortcut = item.shortcut(props.is_darwin);
    let mut button = Element::new("button")
        .attr("type", "button")
        .attr("class", "welcome-screen-menu-item ")
        .child(
            Element::new("div")
                .attr("class", "welcome-screen-menu-item__icon")
                .child_opt(icon_node(item.icon())),
        )
        .child(
            Element::new("div")
                .attr("class", "welcome-screen-menu-item__text")
                .child(Node::text(welcome_text(item.label_key()))),
        );
    if !shortcut.is_empty() && props.form_factor != FormFactor::Phone {
        button = button.child(
            Element::new("div")
                .attr("class", "welcome-screen-menu-item__shortcut")
                .child(Node::text(shortcut)),
        );
    }
    if let Some(on_event) = props.on_event.clone() {
        button = button.on("click", move |_| on_event(item));
    }
    button
}

/// `<ExcalidrawLogo withText />` (`ExcalidrawLogo.tsx`): `div.ExcalidrawLogo
/// is-small` with the icon and the wordmark.
pub fn excalidraw_logo() -> Element {
    icons::parse_markup(EXCALIDRAW_LOGO_HTML.trim_end())
}

/// `WelcomeScreen.Center` with its default children
/// (`WelcomeScreen.Center.tsx:91-108`).
pub fn welcome_screen_center(props: &WelcomeScreenProps) -> Element {
    let menu = Element::new("div")
        .attr("class", "welcome-screen-menu")
        .children_from(
            menu_items(props)
                .into_iter()
                .map(|item| Node::Element(menu_item(props, item))),
        );
    Element::new("div")
        .attr("class", "welcome-screen-center")
        .child(
            Element::new("div")
                .attr(
                    "class",
                    "welcome-screen-center__logo excalifont welcome-screen-decor",
                )
                .child(excalidraw_logo()),
        )
        .child(
            Element::new("div")
                .attr(
                    "class",
                    "welcome-screen-center__heading welcome-screen-decor excalifont",
                )
                .child(Node::text(welcome_text(
                    "welcomeScreen.defaults.center_heading",
                ))),
        )
        .child(menu)
}

const HINT_CLASS: &str = "excalifont welcome-screen-decor welcome-screen-decor-hint";

/// `WelcomeScreen.Hints.MenuHint` (`WelcomeScreen.Hints.tsx:9-22`): the
/// arrow up to the main menu, then the label.
pub fn menu_hint() -> Element {
    Element::new("div")
        .attr(
            "class",
            format!("{HINT_CLASS} welcome-screen-decor-hint--menu"),
        )
        .child_opt(icon_node(&icons::WelcomeScreenMenuArrow))
        .child(
            Element::new("div")
                .attr("class", "welcome-screen-decor-hint__label")
                .child(Node::text(welcome_text("welcomeScreen.defaults.menuHint"))),
        )
}

/// `WelcomeScreen.Hints.ToolbarHint` (`WelcomeScreen.Hints.tsx:24-37`):
/// the label, then the arrow up to the toolbar.
pub fn toolbar_hint() -> Element {
    Element::new("div")
        .attr(
            "class",
            format!("{HINT_CLASS} welcome-screen-decor-hint--toolbar"),
        )
        .child(
            Element::new("div")
                .attr("class", "welcome-screen-decor-hint__label")
                .child(Node::text(welcome_text(
                    "welcomeScreen.defaults.toolbarHint",
                ))),
        )
        .child_opt(icon_node(&icons::WelcomeScreenTopToolbarArrow))
}

/// `WelcomeScreen.Hints.HelpHint` (`WelcomeScreen.Hints.tsx:39-50`): the
/// label, then the arrow down to the help button.
pub fn help_hint() -> Element {
    Element::new("div")
        .attr(
            "class",
            format!("{HINT_CLASS} welcome-screen-decor-hint--help"),
        )
        .child(
            Element::new("div").child(Node::text(welcome_text("welcomeScreen.defaults.helpHint"))),
        )
        .child_opt(icon_node(&icons::WelcomeScreenHelpArrow))
}
