//! Top-picks drag and drop (`components/TopPicksDnD/topPicksDnD.tsx`):
//! pinning a value (a colour, later a font family) to a picker's top-picks
//! strip by dragging it there from the popup or the trigger, and reordering
//! the strip by dragging a pick, with pointer events and a ghost that
//! follows the pointer. The colour picker's use is
//! `ColorPicker/colorTopPicksDnD.ts`, in [`crate::color_picker`].
//!
//! [`TopPicksDnd`] holds `useTopPicksDnD`'s controller. Its session logic
//! is pure: pointer events, time and the strip's layout come in as
//! arguments ([`TopPicksDnd::pointer_down`], [`TopPicksDnd::pointer_move`],
//! [`TopPicksDnd::pointer_up`], [`TopPicksDnd::advance`] for upstream's
//! `setTimeout`s, [`TopPicksDnd::frame`] for its `requestAnimationFrame`),
//! and what upstream writes to the DOM comes out as state: the drag state
//! the strip renders ([`TopPicksDnd::drag_state`]), the ghosts in
//! `document.body` ([`TopPicksDnd::ghosts`], [`ghost_element`]) and the
//! body's class ([`TopPicksDnd::body_active`]). In a browser,
//! [`TopPicksDnd::start_drag`] runs a session from a pointerdown: it
//! listens on the window, reads `performance.now()` and the registered
//! strip's layout ([`TopPicksDnd::set_strip`]), keeps the ghosts' elements
//! in step and tells the host ([`TopPicksDnd::set_listener`]) when to render
//! again and which picks a drop made.

use std::cell::RefCell;
use std::rc::{Rc, Weak};

use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement, KeyboardEvent, PointerEvent};

use excali_scene::display::js;

use crate::dom::Element;

/// `TopPicksDnD.scss`, compiled (generated by
/// `tools/goldens/color-top-picks-dnd.mjs`).
pub const TOP_PICKS_DND_CSS: &str = include_str!("top_picks_dnd.css");

/// The `data-excali-ui` value of the `<style>` holding [`TOP_PICKS_DND_CSS`].
const STYLESHEET_ID: &str = "top-picks-dnd";

/// Adds [`TOP_PICKS_DND_CSS`] to `document`'s head once.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(TOP_PICKS_DND_CSS));
    if let Some(head) = document.head() {
        head.append_child(&style)?;
    }
    Ok(())
}

/// `GHOST_CLASS` (`topPicksDnD.tsx:17`).
pub const GHOST_CLASS: &str = "excalidraw-top-picks-dnd-ghost";
/// `BODY_CLASS` (`topPicksDnD.tsx:18`): on `document.body` while a drag is
/// active.
pub const BODY_CLASS: &str = "excalidraw-top-picks-dnd-active";
/// `DRAG_THRESHOLD` (`topPicksDnD.tsx:19`): how far (px) the pointer moves
/// before a press becomes a drag.
pub const DRAG_THRESHOLD: f64 = 10.0;
/// `DRAG_TIME_THRESHOLD_MS` (`topPicksDnD.tsx:22`): how long the pointer is
/// held before a press becomes a drag.
pub const DRAG_TIME_THRESHOLD_MS: f64 = 100.0;
/// The released ghost fades after this long (`topPicksDnD.tsx:331-333`).
const FADE_AFTER_MS: f64 = 160.0;
/// ...and is removed after this long (`topPicksDnD.tsx:334-336`).
const REMOVE_AFTER_MS: f64 = 340.0;
/// The click after a drop is swallowed for this long
/// (`suppressNextClick`, `topPicksDnD.tsx:367-377`).
const SUPPRESS_CLICK_MS: f64 = 100.0;

/// A client rect.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Rect {
    pub left: f64,
    pub top: f64,
    pub width: f64,
    pub height: f64,
}

impl Rect {
    pub fn right(&self) -> f64 {
        self.left + self.width
    }

    pub fn bottom(&self) -> f64 {
        self.top + self.height
    }

    fn of(el: &web_sys::Element) -> Rect {
        let r = el.get_bounding_client_rect();
        Rect {
            left: r.left(),
            top: r.top(),
            width: r.width(),
            height: r.height(),
        }
    }
}

/// `DragOrigin` (`topPicksDnD.tsx:24-29`): a value dragged from outside
/// the strip (dropping replaces the hovered pick) or a pick of the strip
/// (dropping reorders).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DragOrigin {
    Source,
    Pick(usize),
}

/// `TopPicksDragState` (`topPicksDnD.tsx:31-41`): what the strip renders
/// while a drag is active.
#[derive(Clone, Debug, PartialEq)]
pub struct TopPicksDragState<T> {
    pub value: T,
    pub origin: DragOrigin,
    /// The hovered slot; `None` outside the strip.
    pub over_index: Option<usize>,
    /// The slot of an already pinned identical value, which blocks the
    /// drop.
    pub duplicate_index: Option<usize>,
    /// The signed distance between slot centres.
    pub slot_span: f64,
}

/// `getTopPickReorderOffset` (`topPicksDnD.tsx:102-130`): the translation
/// (px) moving the pick at `index` to where it would be if the pick being
/// reordered were dropped now.
pub fn get_top_pick_reorder_offset<T>(state: Option<&TopPicksDragState<T>>, index: usize) -> f64 {
    let Some(state) = state else {
        return 0.0;
    };
    let (DragOrigin::Pick(from), Some(to)) = (state.origin, state.over_index) else {
        return 0.0;
    };
    if from == to {
        return 0.0;
    }
    let (index, from, to) = (index as i64, from as i64, to as i64);
    let mut new_index = index;
    if index == from {
        new_index = to;
    } else {
        if index > from {
            new_index -= 1;
        }
        if new_index >= to {
            new_index += 1;
        }
    }
    (new_index - index) as f64 * state.slot_span
}

/// `TopPicksDnDOutline` (`topPicksDnD.tsx:134-138`): the "marching ants"
/// around the strip while a drag is active.
pub fn top_picks_dnd_outline() -> Element {
    Element::svg("svg")
        .attr("class", "top-picks-dnd__outline")
        .attr("aria-hidden", "true")
        .child(Element::svg("rect"))
}

/// The strip's layout (`measureStrip`, `topPicksDnD.tsx:188-215`): its
/// rect and its picks' in index order.
#[derive(Clone, Debug, PartialEq)]
pub struct StripLayout {
    pub strip: Rect,
    pub slots: Vec<Rect>,
}

/// A ghost as `document.body` holds it: its classes in the order they
/// were added, its size and its `translate`.
#[derive(Clone, Debug, PartialEq)]
pub struct Ghost {
    /// The session that made it ([`TopPicksDnd::pointer_down`]'s).
    pub id: u64,
    pub classes: Vec<String>,
    pub width: f64,
    pub height: f64,
    pub x: f64,
    pub y: f64,
}

impl Ghost {
    pub fn class(&self) -> String {
        self.classes.join(" ")
    }

    /// The inline style upstream writes: `width`, `height`, `transform`.
    pub fn style(&self) -> [(&'static str, String); 3] {
        [
            ("width", format!("{}px", self.width)),
            ("height", format!("{}px", self.height)),
            (
                "transform",
                format!("translate({}px, {}px)", self.x, self.y),
            ),
        ]
    }

    fn toggle(&mut self, modifier: &str, on: bool) {
        let class = format!("{GHOST_CLASS}--{modifier}");
        let has = self.classes.contains(&class);
        if on && !has {
            self.classes.push(class);
        } else if !on && has {
            self.classes.retain(|c| *c != class);
        }
    }
}

/// The ghost's element around its `content` (`activate`,
/// `topPicksDnD.tsx:238-247`): the content gets `…-ghost__content`.
pub fn ghost_element(ghost: &Ghost, content: Element) -> Element {
    let class = match content.attribute("class") {
        Some(c) if !c.is_empty() => format!("{c} {GHOST_CLASS}__content"),
        _ => format!("{GHOST_CLASS}__content"),
    };
    let mut el = Element::new("div").attr("class", ghost.class());
    for (property, value) in ghost.style() {
        el = el.style(property, value);
    }
    el.child(content.attr("class", class))
}

/// A pointerdown that may start a drag (`begin`, `topPicksDnD.tsx:458-519`).
#[derive(Clone, Debug)]
pub struct PointerDown<T> {
    pub pointer_id: i32,
    pub button: i16,
    pub x: f64,
    pub y: f64,
    /// `performance.now()`.
    pub now: f64,
    /// `None` (a mixed selection's trigger) starts nothing.
    pub value: Option<T>,
    pub origin: DragOrigin,
    /// The source's rect: the ghost's size, and where it flies back to on
    /// a cancel.
    pub home: Rect,
}

/// What a pointerup did.
#[derive(Clone, Debug, PartialEq)]
pub struct DropOutcome<T> {
    /// The pointerup ended an active drag: upstream prevents its default
    /// and stops it, and swallows the click that follows.
    pub handled: bool,
    /// The strip's new picks (`onPicksChange`).
    pub picks: Option<Vec<T>>,
}

#[derive(Clone, Copy, Debug, PartialEq)]
enum TimerKind {
    Activation,
    Fade(u64),
    Remove(u64),
}

#[derive(Clone, Copy, Debug)]
struct Timer {
    due: f64,
    seq: u64,
    kind: TimerKind,
}

/// `DragSession` (`topPicksDnD.tsx:60-90`).
struct Session<T> {
    id: u64,
    pointer_id: i32,
    start_x: f64,
    start_y: f64,
    start_time: f64,
    last_x: f64,
    last_y: f64,
    value: T,
    origin: DragOrigin,
    home: Rect,
    activated: bool,
    /// The ghost following the pointer (its id), once activated and until
    /// released.
    ghost: Option<u64>,
    ghost_w: f64,
    ghost_h: f64,
    slot_rects: Vec<Rect>,
    slot_span: f64,
    hit_rect: Option<(f64, f64, f64, f64)>,
    over_index: Option<usize>,
    duplicate_index: Option<usize>,
}

struct Core<T> {
    enabled: bool,
    picks: Vec<T>,
    is_same: fn(&T, &T) -> bool,
    session: Option<Session<T>>,
    drag_state: Option<TopPicksDragState<T>>,
    ghosts: Vec<Ghost>,
    timers: Vec<Timer>,
    seq: u64,
    frames: Vec<u64>,
    body_active: bool,
    suppress_click_until: Option<f64>,
    next_id: u64,
}

impl<T: Clone> Core<T> {
    fn schedule(&mut self, due: f64, kind: TimerKind) {
        self.seq += 1;
        self.timers.push(Timer {
            due,
            seq: self.seq,
            kind,
        });
    }

    fn clear_activation(&mut self) {
        self.timers.retain(|t| t.kind != TimerKind::Activation);
    }

    fn ghost_mut(&mut self, id: Option<u64>) -> Option<&mut Ghost> {
        let id = id?;
        self.ghosts.iter_mut().find(|g| g.id == id)
    }

    fn publish(&mut self) {
        self.drag_state =
            self.session
                .as_ref()
                .filter(|s| s.activated)
                .map(|s| TopPicksDragState {
                    value: s.value.clone(),
                    origin: s.origin,
                    over_index: s.over_index,
                    duplicate_index: s.duplicate_index,
                    slot_span: s.slot_span,
                });
    }

    fn measure_strip(&mut self, layout: Option<StripLayout>) -> bool {
        let (Some(session), Some(layout)) = (self.session.as_mut(), layout) else {
            return false;
        };
        let Some(first) = layout.slots.first().copied() else {
            return false;
        };
        // the strip is evenly spaced; the sign flips under RTL
        session.slot_span = match layout.slots.get(1) {
            Some(second) => second.left - first.left,
            None => first.width + 4.0,
        };
        session.slot_rects = layout.slots;
        let pad_x = (session.slot_span.abs() / 2.0).max(10.0);
        let strip = layout.strip;
        session.hit_rect = Some((
            strip.left - pad_x,
            strip.right() + pad_x,
            strip.top - 14.0,
            strip.bottom() + 14.0,
        ));
        true
    }

    fn position_ghost(&mut self, x: f64, y: f64) {
        let Some(s) = &self.session else {
            return;
        };
        let (id, w, h) = (s.ghost, s.ghost_w, s.ghost_h);
        if let Some(g) = self.ghost_mut(id) {
            g.x = x - w / 2.0;
            g.y = y - h / 2.0;
        }
    }

    fn set_ghost_size(&mut self, width: f64, height: f64, x: f64, y: f64) {
        let Some(s) = self.session.as_mut() else {
            return;
        };
        if s.ghost.is_none() {
            return;
        }
        if s.ghost_w != width || s.ghost_h != height {
            s.ghost_w = width;
            s.ghost_h = height;
            let id = s.ghost;
            if let Some(g) = self.ghost_mut(id) {
                g.width = width;
                g.height = height;
            }
            self.position_ghost(x, y);
        }
    }

    fn activate(&mut self, x: f64, y: f64) {
        let Some(s) = self.session.as_mut() else {
            return;
        };
        let rect = s.home;
        s.ghost = Some(s.id);
        s.ghost_w = rect.width;
        s.ghost_h = rect.height;
        s.activated = true;
        let id = s.id;
        self.ghosts.push(Ghost {
            id,
            classes: vec![GHOST_CLASS.to_owned()],
            width: rect.width,
            height: rect.height,
            x: 0.0,
            y: 0.0,
        });
        self.position_ghost(x, y);
        // the spawn frame paints at rest, then the ghost lifts
        self.frames.push(id);
        self.body_active = true;
        self.publish();
    }

    fn hit_test(&mut self, x: f64, y: f64) {
        let Some(s) = &self.session else {
            return;
        };
        let Some((left, right, top, bottom)) = s.hit_rect else {
            return;
        };
        let mut over_index = None;
        let mut duplicate_index = None;
        if x >= left && x <= right && y >= top && y <= bottom {
            let mut best = 0;
            let mut best_distance = f64::INFINITY;
            for (index, rect) in s.slot_rects.iter().enumerate() {
                let distance = (x - (rect.left + rect.width / 2.0)).abs();
                if distance < best_distance {
                    best_distance = distance;
                    best = index;
                }
            }
            if s.origin == DragOrigin::Source {
                match self.picks.iter().position(|p| (self.is_same)(p, &s.value)) {
                    Some(duplicate) => duplicate_index = Some(duplicate),
                    None => over_index = Some(best),
                }
            } else {
                over_index = Some(best);
            }
        }
        if over_index != s.over_index || duplicate_index != s.duplicate_index {
            let id = s.ghost;
            if let Some(s) = self.session.as_mut() {
                s.over_index = over_index;
                s.duplicate_index = duplicate_index;
            }
            if let Some(g) = self.ghost_mut(id) {
                g.toggle("over", over_index.is_some());
                g.toggle("blocked", duplicate_index.is_some());
            }
            self.publish();
        }
        // over the strip the ghost morphs to the slot's size
        let Some(s) = &self.session else {
            return;
        };
        let size = match over_index {
            Some(i) => s.slot_rects[i],
            None => s.home,
        };
        self.set_ghost_size(size.width, size.height, x, y);
    }

    fn release_ghost(&mut self, rect: Rect, now: f64) {
        let Some(id) = self.session.as_mut().and_then(|s| s.ghost.take()) else {
            return;
        };
        if let Some(g) = self.ghost_mut(Some(id)) {
            g.toggle("dropping", true);
            g.width = rect.width;
            g.height = rect.height;
            g.x = rect.left;
            g.y = rect.top;
        }
        self.schedule(now + FADE_AFTER_MS, TimerKind::Fade(id));
        self.schedule(now + REMOVE_AFTER_MS, TimerKind::Remove(id));
    }

    fn dispose(&mut self) {
        self.body_active = false;
        self.clear_activation();
        self.session = None;
        self.drag_state = None;
    }

    fn cancel_drag(&mut self, animate: bool, now: f64) {
        let Some(s) = &self.session else {
            return;
        };
        let home = s.home;
        if let Some(id) = s.ghost {
            if animate {
                self.release_ghost(home, now);
            } else {
                self.ghosts.retain(|g| g.id != id);
            }
        }
        self.dispose();
    }

    fn try_activate(&mut self, x: f64, y: f64, layout: Option<StripLayout>) {
        if self.session.as_ref().is_none_or(|s| s.activated) {
            return;
        }
        if !self.measure_strip(layout) {
            self.dispose();
            return;
        }
        self.activate(x, y);
        self.hit_test(x, y);
    }

    fn accepts(&self, button: i16, has_value: bool, strip: bool) -> bool {
        self.enabled && self.session.is_none() && button == 0 && has_value && strip
    }
}

/// `useTopPicksDnD`'s controller (`topPicksDnD.tsx:140-633`) for picks of
/// `T`: a cheap handle, cloned into the strip's and the sources'
/// listeners.
pub struct TopPicksDnd<T: 'static>(Rc<Inner<T>>);

impl<T> Clone for TopPicksDnd<T> {
    fn clone(&self) -> Self {
        TopPicksDnd(self.0.clone())
    }
}

/// What the browser driver tells the host.
#[derive(Clone, Debug, PartialEq)]
pub enum TopPicksDndEvent<T> {
    /// The drag state changed: render the strip again.
    StateChanged,
    /// A drop made these the strip's picks (`onPicksChange`).
    PicksChange(Vec<T>),
}

/// Called with each [`TopPicksDndEvent`].
pub type OnTopPicksDndEvent<T> = Rc<dyn Fn(TopPicksDndEvent<T>)>;

struct Inner<T> {
    core: RefCell<Core<T>>,
    web: RefCell<Web<T>>,
}

type Listener = Closure<dyn FnMut(Event)>;

/// The browser side: the registered strip, the ghosts' elements, the
/// window listeners of a session, the pending timer and frame.
struct Web<T> {
    strip: Option<web_sys::Element>,
    listener: Option<OnTopPicksDndEvent<T>>,
    contents: Vec<(u64, web_sys::Element)>,
    ghost_els: Vec<(u64, HtmlElement)>,
    listeners: Vec<(&'static str, Listener)>,
    /// The pending `setTimeout`'s handle.
    timer: Option<i32>,
    /// A frame is requested.
    frame: bool,
}

impl<T: Clone + PartialEq + 'static> TopPicksDnd<T> {
    /// A controller whose pins identical to an existing pick (by `is_same`)
    /// are refused. Disabled until [`Self::set_enabled`].
    pub fn new(is_same: fn(&T, &T) -> bool) -> Self {
        TopPicksDnd(Rc::new(Inner {
            core: RefCell::new(Core {
                enabled: false,
                picks: Vec::new(),
                is_same,
                session: None,
                drag_state: None,
                ghosts: Vec::new(),
                timers: Vec::new(),
                seq: 0,
                frames: Vec::new(),
                body_active: false,
                suppress_click_until: None,
                next_id: 0,
            }),
            web: RefCell::new(Web {
                strip: None,
                listener: None,
                contents: Vec::new(),
                ghost_els: Vec::new(),
                listeners: Vec::new(),
                timer: None,
                frame: false,
            }),
        }))
    }

    /// Whether drags may start (`enabled`).
    pub fn set_enabled(&self, enabled: bool) {
        self.0.core.borrow_mut().enabled = enabled;
    }

    /// The picks the strip shows now (`picks`), which a drop edits.
    pub fn set_picks(&self, picks: Vec<T>) {
        self.0.core.borrow_mut().picks = picks;
    }

    pub fn drag_state(&self) -> Option<TopPicksDragState<T>> {
        self.0.core.borrow().drag_state.clone()
    }

    /// The ghosts in `document.body`, oldest first.
    pub fn ghosts(&self) -> Vec<Ghost> {
        self.0.core.borrow().ghosts.clone()
    }

    /// Whether `document.body` has [`BODY_CLASS`].
    pub fn body_active(&self) -> bool {
        self.0.core.borrow().body_active
    }

    /// When the next of upstream's timers is due.
    pub fn next_due(&self) -> Option<f64> {
        let core = self.0.core.borrow();
        core.timers.iter().map(|t| t.due).reduce(f64::min)
    }

    /// Starts a session (`begin`): the session's id, which its ghost
    /// carries; `None` when disabled, a session is running, not the
    /// primary button, no value or no strip (`strip`).
    pub fn pointer_down(&self, down: PointerDown<T>, strip: bool) -> Option<u64> {
        let mut core = self.0.core.borrow_mut();
        let value = down.value.clone();
        if !core.accepts(down.button, value.is_some(), strip) {
            return None;
        }
        core.next_id += 1;
        let id = core.next_id;
        core.session = Some(Session {
            id,
            pointer_id: down.pointer_id,
            start_x: down.x,
            start_y: down.y,
            start_time: down.now,
            last_x: down.x,
            last_y: down.y,
            value: value?,
            origin: down.origin,
            home: down.home,
            activated: false,
            ghost: None,
            ghost_w: 0.0,
            ghost_h: 0.0,
            slot_rects: Vec::new(),
            slot_span: 0.0,
            hit_rect: None,
            over_index: None,
            duplicate_index: None,
        });
        Some(id)
    }

    /// `onPointerMove` (`topPicksDnD.tsx:410-449`): whether upstream
    /// prevents the move's default (an active drag).
    pub fn pointer_move(
        &self,
        pointer_id: i32,
        x: f64,
        y: f64,
        now: f64,
        measure: &dyn Fn() -> Option<StripLayout>,
    ) -> bool {
        let mut core = self.0.core.borrow_mut();
        let Some(s) = core.session.as_mut() else {
            return false;
        };
        if s.pointer_id != pointer_id {
            return false;
        }
        s.last_x = x;
        s.last_y = y;
        if !s.activated {
            if js::hypot(x - s.start_x, y - s.start_y) < DRAG_THRESHOLD {
                // back inside the click tolerance: a delayed activation no
                // longer applies
                core.clear_activation();
                return false;
            }
            let elapsed = now - s.start_time;
            if elapsed < DRAG_TIME_THRESHOLD_MS {
                // a fast sloppy click, likely: wait out the grace period
                if !core.timers.iter().any(|t| t.kind == TimerKind::Activation) {
                    core.schedule(
                        now + (DRAG_TIME_THRESHOLD_MS - elapsed),
                        TimerKind::Activation,
                    );
                }
                return false;
            }
            core.try_activate(x, y, measure());
            if !core.session.as_ref().is_some_and(|s| s.activated) {
                return false;
            }
        }
        core.position_ghost(x, y);
        core.hit_test(x, y);
        true
    }

    /// `onPointerUp` (`topPicksDnD.tsx:451-490`).
    pub fn pointer_up(&self, pointer_id: i32, now: f64) -> DropOutcome<T> {
        let mut core = self.0.core.borrow_mut();
        let none = DropOutcome {
            handled: false,
            picks: None,
        };
        let Some(s) = &core.session else {
            return none;
        };
        if s.pointer_id != pointer_id {
            return none;
        }
        let (activated, over_index, origin, value, home) =
            (s.activated, s.over_index, s.origin, s.value.clone(), s.home);
        if !activated {
            // never became a drag: the click happens
            core.dispose();
            return none;
        }
        core.suppress_click_until = Some(now + SUPPRESS_CLICK_MS);
        let mut picks = None;
        match over_index {
            Some(over) => {
                match origin {
                    DragOrigin::Source => {
                        if !core.picks.iter().any(|p| (core.is_same)(p, &value)) {
                            let mut next = core.picks.clone();
                            if over < next.len() {
                                next[over] = value;
                            }
                            picks = Some(next);
                        }
                    }
                    DragOrigin::Pick(from) if from != over => {
                        let mut next = core.picks.clone();
                        if from < next.len() {
                            let moved = next.remove(from);
                            next.insert(over.min(next.len()), moved);
                        }
                        picks = Some(next);
                    }
                    DragOrigin::Pick(_) => {}
                }
                let target = core.session.as_ref().map(|s| s.slot_rects[over]);
                core.release_ghost(target.unwrap_or(home), now);
            }
            None => core.release_ghost(home, now),
        }
        core.dispose();
        DropOutcome {
            handled: true,
            picks,
        }
    }

    /// `onPointerCancel` (`topPicksDnD.tsx:492-496`).
    pub fn pointer_cancel(&self, pointer_id: i32, now: f64) {
        let mut core = self.0.core.borrow_mut();
        if core
            .session
            .as_ref()
            .is_some_and(|s| s.pointer_id == pointer_id)
        {
            core.cancel_drag(true, now);
        }
    }

    /// `onKeyDown` (`topPicksDnD.tsx:498-504`): Escape cancels an active
    /// drag; whether it was handled.
    pub fn key_down(&self, key: &str, now: f64) -> bool {
        let mut core = self.0.core.borrow_mut();
        if key == "Escape" && core.session.as_ref().is_some_and(|s| s.activated) {
            core.cancel_drag(true, now);
            return true;
        }
        false
    }

    /// Runs upstream's timers due by `now`, in order: the delayed
    /// activation, and each released ghost's fade and removal.
    pub fn advance(&self, now: f64, measure: &dyn Fn() -> Option<StripLayout>) {
        let mut core = self.0.core.borrow_mut();
        loop {
            let due = core
                .timers
                .iter()
                .filter(|t| t.due <= now)
                .min_by(|a, b| a.due.total_cmp(&b.due).then(a.seq.cmp(&b.seq)))
                .copied();
            let Some(timer) = due else {
                break;
            };
            core.timers.retain(|t| t.seq != timer.seq);
            match timer.kind {
                TimerKind::Activation => {
                    let Some(s) = &core.session else {
                        continue;
                    };
                    // the pointer may have come back inside the tolerance
                    // after the last move seen: never activate from there
                    let (x, y) = (s.last_x, s.last_y);
                    if js::hypot(x - s.start_x, y - s.start_y) >= DRAG_THRESHOLD {
                        core.try_activate(x, y, measure());
                    }
                }
                TimerKind::Fade(id) => {
                    if let Some(g) = core.ghost_mut(Some(id)) {
                        g.toggle("fade", true);
                    }
                }
                TimerKind::Remove(id) => core.ghosts.retain(|g| g.id != id),
            }
        }
    }

    /// The next animation frame: a ghost spawned since the last one lifts,
    /// unless its drag already ended.
    pub fn frame(&self) {
        let mut core = self.0.core.borrow_mut();
        for id in std::mem::take(&mut core.frames) {
            let live = core.session.as_ref().and_then(|s| s.ghost) == Some(id);
            if live {
                if let Some(g) = core.ghost_mut(Some(id)) {
                    g.toggle("lifted", true);
                }
            }
        }
    }

    /// Whether the click that reaches the window now is the one after a
    /// drop, which upstream swallows; consumes the suppression.
    pub fn take_click_suppression(&self, now: f64) -> bool {
        let until = self.0.core.borrow_mut().suppress_click_until.take();
        until.is_some_and(|until| now < until)
    }

    /// Cancels a session without animating its ghost (the picker
    /// unmounted mid-drag).
    pub fn destroy(&self) {
        self.0.core.borrow_mut().cancel_drag(false, 0.0);
        self.unlisten();
        self.sync();
    }

    // -- browser --------------------------------------------------------------

    /// Registers the strip (`setStripEl`): its `[data-top-pick-index]`
    /// children are the slots.
    pub fn set_strip(&self, strip: Option<web_sys::Element>) {
        self.0.web.borrow_mut().strip = strip;
    }

    /// Who hears what the browser driver does.
    pub fn set_listener(&self, listener: Option<OnTopPicksDndEvent<T>>) {
        self.0.web.borrow_mut().listener = listener;
    }

    /// Starts a drag from `event` (a source's or a pick's pointerdown),
    /// with the ghost's content and home rect that `create_ghost` makes
    /// from the source element (`createGhost`, called before the session
    /// starts since the source may be rendered again).
    pub fn start_drag(
        &self,
        event: &Event,
        value: Option<T>,
        origin: DragOrigin,
        create_ghost: impl FnOnce(&web_sys::Element) -> (web_sys::Element, Rect),
    ) {
        let Some(e) = event.dyn_ref::<PointerEvent>() else {
            return;
        };
        let strip = self.0.web.borrow().strip.clone();
        let accepted = self.0.core.borrow().accepts(
            e.button(),
            value.is_some(),
            strip.as_ref().is_some_and(|s| s.is_connected()),
        );
        if !accepted {
            return;
        }
        let Some(source) = e
            .current_target()
            .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
        else {
            return;
        };
        let (content, home) = create_ghost(&source);
        let down = PointerDown {
            pointer_id: e.pointer_id(),
            button: e.button(),
            x: f64::from(e.client_x()),
            y: f64::from(e.client_y()),
            now: now(),
            value,
            origin,
            home,
        };
        let Some(id) = self.pointer_down(down, true) else {
            return;
        };
        self.0.web.borrow_mut().contents.push((id, content));
        self.listen();
    }

    fn measure(&self) -> Option<StripLayout> {
        let strip = self.0.web.borrow().strip.clone()?;
        let list = strip.query_selector_all("[data-top-pick-index]").ok()?;
        let mut slots: Vec<(usize, Rect)> = (0..list.length())
            .filter_map(|i| list.item(i))
            .filter_map(|n| n.dyn_into::<web_sys::Element>().ok())
            .map(|el| {
                let index = el
                    .get_attribute("data-top-pick-index")
                    .and_then(|i| i.parse().ok())
                    .unwrap_or(0);
                (index, Rect::of(&el))
            })
            .collect();
        slots.sort_by_key(|(i, _)| *i);
        Some(StripLayout {
            strip: Rect::of(&strip),
            slots: slots.into_iter().map(|(_, r)| r).collect(),
        })
    }

    /// The window listeners of a session (capture phase).
    fn listen(&self) {
        let weak = Rc::downgrade(&self.0);
        let make = |handler: fn(&TopPicksDnd<T>, &Event)| -> Listener {
            let weak: Weak<Inner<T>> = weak.clone();
            Closure::new(move |e: Event| {
                if let Some(inner) = weak.upgrade() {
                    handler(&TopPicksDnd(inner), &e);
                }
            })
        };
        let listeners: Vec<(&'static str, Listener)> = vec![
            ("pointermove", make(Self::on_pointer_move)),
            ("pointerup", make(Self::on_pointer_up)),
            ("pointercancel", make(Self::on_pointer_cancel)),
            ("keydown", make(Self::on_key_down)),
        ];
        if let Some(window) = web_sys::window() {
            for (name, f) in &listeners {
                let _ = window.add_event_listener_with_callback_and_bool(
                    name,
                    f.as_ref().unchecked_ref(),
                    true,
                );
            }
        }
        self.0.web.borrow_mut().listeners = listeners;
    }

    fn unlisten(&self) {
        let listeners = std::mem::take(&mut self.0.web.borrow_mut().listeners);
        if let Some(window) = web_sys::window() {
            for (name, f) in &listeners {
                let _ = window.remove_event_listener_with_callback_and_bool(
                    name,
                    f.as_ref().unchecked_ref(),
                    true,
                );
            }
        }
    }

    fn on_pointer_move(&self, e: &Event) {
        let Some(p) = e.dyn_ref::<PointerEvent>() else {
            return;
        };
        let before = self.drag_state();
        let measure = || self.measure();
        let prevent = self.pointer_move(
            p.pointer_id(),
            f64::from(p.client_x()),
            f64::from(p.client_y()),
            now(),
            &measure,
        );
        if prevent {
            e.prevent_default();
        }
        self.after(before, None);
    }

    fn on_pointer_up(&self, e: &Event) {
        let Some(p) = e.dyn_ref::<PointerEvent>() else {
            return;
        };
        let before = self.drag_state();
        let outcome = self.pointer_up(p.pointer_id(), now());
        if outcome.handled {
            e.prevent_default();
            e.stop_propagation();
            self.suppress_next_click();
            self.settle_strip();
        }
        self.after(before, outcome.picks);
    }

    fn on_pointer_cancel(&self, e: &Event) {
        let Some(p) = e.dyn_ref::<PointerEvent>() else {
            return;
        };
        let before = self.drag_state();
        self.pointer_cancel(p.pointer_id(), now());
        if before.is_some() {
            self.settle_strip();
        }
        self.after(before, None);
    }

    fn on_key_down(&self, e: &Event) {
        let Some(k) = e.dyn_ref::<KeyboardEvent>() else {
            return;
        };
        let before = self.drag_state();
        if self.key_down(&k.key(), now()) {
            e.prevent_default();
            e.stop_propagation();
            self.settle_strip();
        }
        self.after(before, None);
    }

    /// After a call into the session: the ghosts' elements, the body
    /// class, the window listeners, the next timer and frame, and the
    /// host told what changed.
    fn after(&self, before: Option<TopPicksDragState<T>>, picks: Option<Vec<T>>) {
        self.sync();
        if self.0.core.borrow().session.is_none() {
            self.unlisten();
        }
        self.schedule();
        let listener = self.0.web.borrow().listener.clone();
        if let Some(listener) = listener {
            if let Some(picks) = picks {
                listener(TopPicksDndEvent::PicksChange(picks));
            }
            if self.drag_state() != before {
                listener(TopPicksDndEvent::StateChanged);
            }
        }
    }

    /// Makes `document.body`'s ghosts and class what the session holds.
    fn sync(&self) {
        let Some(document) = web_sys::window().and_then(|w| w.document()) else {
            return;
        };
        let Some(body) = document.body() else {
            return;
        };
        let (ghosts, active) = {
            let core = self.0.core.borrow();
            (core.ghosts.clone(), core.body_active)
        };
        let _ = body.class_list().toggle_with_force(BODY_CLASS, active);
        let mut web = self.0.web.borrow_mut();
        web.ghost_els.retain(|(id, el)| {
            let keep = ghosts.iter().any(|g| g.id == *id);
            if !keep {
                el.remove();
            }
            keep
        });
        for ghost in &ghosts {
            let el = match web.ghost_els.iter().find(|(id, _)| *id == ghost.id) {
                Some((_, el)) => el.clone(),
                None => {
                    let Some(el) = document
                        .create_element("div")
                        .ok()
                        .and_then(|e| e.dyn_into::<HtmlElement>().ok())
                    else {
                        continue;
                    };
                    if let Some(pos) = web.contents.iter().position(|(id, _)| *id == ghost.id) {
                        let (_, content) = web.contents.remove(pos);
                        let _ = content
                            .class_list()
                            .add_1(&format!("{GHOST_CLASS}__content"));
                        let _ = el.append_child(&content);
                    }
                    let _ = body.append_child(&el);
                    web.ghost_els.push((ghost.id, el.clone()));
                    el
                }
            };
            el.set_class_name(&ghost.class());
            let style = el.style();
            for (property, value) in ghost.style() {
                let _ = style.set_property(property, &value);
            }
        }
        web.contents.retain(|(id, _)| {
            self.0
                .core
                .borrow()
                .session
                .as_ref()
                .is_some_and(|s| s.id == *id)
        });
    }

    /// `settleStripInstantly` (`topPicksDnD.tsx:340-365`): cancels the
    /// picks' reorder-preview transitions before the strip renders its
    /// final order.
    fn settle_strip(&self) {
        let Some(strip) = self.0.web.borrow().strip.clone() else {
            return;
        };
        let Ok(list) = strip.query_selector_all("[data-top-pick-index]") else {
            return;
        };
        let picks: Vec<HtmlElement> = (0..list.length())
            .filter_map(|i| list.item(i))
            .filter_map(|n| n.dyn_into::<HtmlElement>().ok())
            .collect();
        for pick in &picks {
            let _ = pick.style().set_property("transition", "none");
            let _ = pick.style().set_property("transform", "none");
        }
        if let Some(s) = strip.dyn_ref::<HtmlElement>() {
            let _ = s.offset_width();
        }
        for pick in &picks {
            let _ = pick.style().remove_property("transition");
        }
    }

    /// `suppressNextClick` (`topPicksDnD.tsx:367-377`): the next click on
    /// the window, within [`SUPPRESS_CLICK_MS`], goes nowhere.
    fn suppress_next_click(&self) {
        let Some(window) = web_sys::window() else {
            return;
        };
        let weak = Rc::downgrade(&self.0);
        let f = Closure::once_into_js(move |e: Event| {
            if let Some(inner) = weak.upgrade() {
                if TopPicksDnd(inner).take_click_suppression(now()) {
                    e.prevent_default();
                    e.stop_propagation();
                }
            }
        });
        let options = web_sys::AddEventListenerOptions::new();
        options.set_capture(true);
        options.set_once(true);
        let _ = window.add_event_listener_with_callback_and_add_event_listener_options(
            "click",
            f.unchecked_ref(),
            &options,
        );
    }

    /// One `setTimeout` for the next due timer, and a frame when a ghost
    /// waits to lift.
    fn schedule(&self) {
        let Some(window) = web_sys::window() else {
            return;
        };
        if let Some(handle) = self.0.web.borrow_mut().timer.take() {
            window.clear_timeout_with_handle(handle);
        }
        if let Some(due) = self.next_due() {
            let weak = Rc::downgrade(&self.0);
            let f = Closure::once_into_js(move || {
                if let Some(inner) = weak.upgrade() {
                    let dnd = TopPicksDnd(inner);
                    dnd.0.web.borrow_mut().timer = None;
                    let before = dnd.drag_state();
                    let measure = || dnd.measure();
                    dnd.advance(now(), &measure);
                    dnd.after(before, None);
                }
            });
            let delay = (due - now()).max(0.0).ceil() as i32;
            if let Ok(handle) = window
                .set_timeout_with_callback_and_timeout_and_arguments_0(f.unchecked_ref(), delay)
            {
                self.0.web.borrow_mut().timer = Some(handle);
            }
        }
        let wants_frame = !self.0.core.borrow().frames.is_empty();
        if wants_frame && !self.0.web.borrow().frame {
            let weak = Rc::downgrade(&self.0);
            let f = Closure::once_into_js(move || {
                if let Some(inner) = weak.upgrade() {
                    let dnd = TopPicksDnd(inner);
                    dnd.0.web.borrow_mut().frame = false;
                    let before = dnd.drag_state();
                    dnd.frame();
                    dnd.after(before, None);
                }
            });
            if window.request_animation_frame(f.unchecked_ref()).is_ok() {
                self.0.web.borrow_mut().frame = true;
            }
        }
    }
}

/// `performance.now()`.
fn now() -> f64 {
    web_sys::window()
        .and_then(|w| w.performance())
        .map(|p| p.now())
        .unwrap_or(0.0)
}
