//! The chrome's building blocks, as upstream's hand-rolled UI kit has them
//! (`site/content/research/ui-design-system.md` §9): [`island`],
//! [`stack_row`] / [`stack_col`], [`button`], [`icon_button`] (the
//! `ToolIcon` button every toolbar uses), [`radio_group`], [`range`],
//! [`text_field`], [`popover`], [`modal`] and [`dialog`], and [`tooltip`].
//!
//! Upstream counterpart: `packages/excalidraw/components/Island.tsx`,
//! `Stack.tsx`, `Button.tsx`, `IconButton.tsx`, `RadioGroup.tsx`,
//! `Range.tsx`, `TextField.tsx`, `Popover.tsx`, `Modal.tsx`, `Dialog.tsx`
//! and `Tooltip.tsx`, and their stylesheets.
//!
//! Each primitive is a function from props to an [`Element`](crate::dom::Element)
//! with upstream's class names, attributes and inline style
//! (`tests/ui_primitives.rs` holds every one to the DOM React leaves for
//! upstream's component); behaviour that needs the document (focus, the
//! tooltip div, the modal portal) runs from the element's listeners and
//! mount hooks. The styles are upstream's SCSS compiled
//! ([`PRIMITIVES_CSS`]), sized by the design system's tokens
//! ([`SIZE_TOKENS`]): 2rem buttons, 1rem icons, a 0.25rem space factor,
//! radii of 0.375rem and 0.5rem. They apply inside an element with the
//! class `excalidraw` (the editor container; a modal's portal container
//! carries it too).

mod button;
mod icon_button;
pub mod icons;
mod island;
mod modal;
mod popover;
mod radio_group;
mod range;
mod stack;
mod text_field;
mod tooltip;

pub use button::{button, ButtonProps, ButtonType};
pub use icon_button::{icon_button, IconButtonKind, IconButtonProps, IconButtonSize};
pub use island::{island, IslandProps};
pub use modal::{
    dialog, dialog_size, dialog_tab_target, modal, open_modal, DialogProps, DialogSize, ModalProps,
    OpenModal, CLOSE_LABEL,
};
pub use popover::{
    popover, popover_fit_style, popover_tab_target, PopoverProps, TrapFocus, POPOVER_CONTAINER_GAP,
};
pub use radio_group::{radio_group, RadioGroupChoice, RadioGroupProps};
pub use range::{range, range_progress, RangeProps};
pub use stack::{stack_col, stack_row, Align, JustifyContent, StackProps};
pub use text_field::{text_field, TextFieldProps, TextFieldType, TextFieldValue};
pub use tooltip::{
    hide_tooltip, show_tooltip, tooltip, tooltip_position, tooltip_width_limits, Rect,
    TooltipOptions, TooltipPlacement, TooltipProps, TOOLTIP_DELAY, TOOLTIP_MARGIN,
    TOOLTIP_WARM_WINDOW,
};

use wasm_bindgen::JsValue;
use web_sys::Document;

/// `--default-button-size` (`css/theme.scss:46`): tool buttons.
pub const DEFAULT_BUTTON_SIZE: &str = "2rem";
/// `--default-icon-size` (`theme.scss:47`).
pub const DEFAULT_ICON_SIZE: &str = "1rem";
/// `--lg-button-size` (`theme.scss:48`).
pub const LG_BUTTON_SIZE: &str = "2.25rem";
/// `--lg-icon-size` (`theme.scss:49`).
pub const LG_ICON_SIZE: &str = "1rem";
/// `--space-factor` (`theme.scss:79`): the spacing unit Island padding and
/// Stack gaps multiply.
pub const SPACE_FACTOR: &str = "0.25rem";
/// `--border-radius-md` (`theme.scss:148`).
pub const BORDER_RADIUS_MD: &str = "0.375rem";
/// `--border-radius-lg` (`theme.scss:149`).
pub const BORDER_RADIUS_LG: &str = "0.5rem";

/// The sizing tokens `.excalidraw` declares.
pub const SIZE_TOKENS: &[(&str, &str)] = &[
    ("--default-button-size", DEFAULT_BUTTON_SIZE),
    ("--default-icon-size", DEFAULT_ICON_SIZE),
    ("--lg-button-size", LG_BUTTON_SIZE),
    ("--lg-icon-size", LG_ICON_SIZE),
    ("--space-factor", SPACE_FACTOR),
    ("--border-radius-md", BORDER_RADIUS_MD),
    ("--border-radius-lg", BORDER_RADIUS_LG),
];

/// The sizes redeclared on screens at least 1921 device pixels wide
/// (`theme.scss:171-176`).
pub const LARGE_SCREEN_TOKENS: &[(&str, &str)] = &[
    ("--default-button-size", "2.25rem"),
    ("--default-icon-size", "1.25rem"),
    ("--lg-button-size", "2.375rem"),
    ("--lg-icon-size", "1.25rem"),
];

/// Upstream's `css/theme.scss` and the primitives' stylesheets, compiled
/// (generated by `tools/goldens/ui-primitives.mjs`).
pub const PRIMITIVES_CSS: &str = include_str!("primitives.css");

/// The `data-excali-ui` value of the `<style>` holding [`PRIMITIVES_CSS`].
const STYLESHEET_ID: &str = "primitives";

/// Adds [`PRIMITIVES_CSS`] to `document`'s head once.
pub fn install_stylesheet(document: &Document) -> Result<(), JsValue> {
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(PRIMITIVES_CSS));
    let head = document
        .head()
        .ok_or_else(|| JsValue::from_str("the document has no head"))?;
    head.append_child(&style)?;
    Ok(())
}

/// `${n}px`, as React writes a number into a pixel style.
pub(crate) fn px(n: f64) -> String {
    format!("{}px", excali_core::json::number_to_string(n))
}

/// A number as React writes it into an attribute or a custom property
/// (`String(n)`).
pub(crate) fn number(n: f64) -> String {
    excali_core::json::number_to_string(n)
}

/// `queryFocusableElements` (`packages/common/src/utils.ts:715-726`): the
/// buttons, links, inputs, selects, textareas and tabindexed divs and
/// labels in `container`, without negative tab indices or disabled form
/// controls (`element.disabled`, which only form controls have).
pub(crate) fn focusable_elements(container: &web_sys::Element) -> Vec<web_sys::HtmlElement> {
    use wasm_bindgen::JsCast;
    let Ok(list) = container
        .query_selector_all("button, a, input, select, textarea, div[tabindex], label[tabindex]")
    else {
        return Vec::new();
    };
    (0..list.length())
        .filter_map(|i| list.item(i))
        .filter_map(|n| n.dyn_into::<web_sys::HtmlElement>().ok())
        .filter(|el| {
            let control = matches!(
                el.local_name().as_str(),
                "button" | "input" | "select" | "textarea"
            );
            el.tab_index() > -1 && !(control && el.has_attribute("disabled"))
        })
        .collect()
}
