//! The font picker (`components/FontPicker/*`): the three top picks
//! (`FontPicker.tsx`: Excalifont "Hand-drawn", Nunito "Normal", Comic
//! Shanns "Code", or the customised `appState.fontTopPicks` padded with
//! them), the trigger (`FontPickerTrigger.tsx`), and the popup
//! (`FontPickerList.tsx`) with the search box (`QuickSearch.tsx`), the "In
//! this scene" and "Available fonts" groups, the "old" badge of deprecated
//! fonts and the keyboard map ([`font_picker_key_handler`],
//! `keyboardNavHandlers.ts`).
//!
//! [`font_picker`] builds the DOM for the host's state
//! ([`FontPickerProps`]); what the user does comes back as
//! [`FontPickerEvent`]s, which [`FontPickerState::dispatch`] applies the
//! way `actionChangeFontFamily`'s panel and `perform` update the app state
//! (`actions/actionProperties.tsx:1160-1540`), returning the callbacks
//! upstream's picker makes on the way. Previewing the hovered font on the
//! selected elements is that action's element update, not the picker's.
//! Outside compact mode the strip is customisable (`fontTopPicksDnD.ts`
//! over [`crate::top_picks_dnd`]): a list row dragged onto a pick pins its
//! font there (an already pinned one is refused), a pick dragged along the
//! strip reorders it, and the strip's context menu and the tip's reset link
//! clear `appState.fontTopPicks` ([`FontPickerEvent::TopPicksChange`]).
//!
//! See `site/content/research/ui-design-system.md` section 3.13.

use std::rc::Rc;

use excali_core::constants::FONT_TOP_PICKS_SLOTS;
use excali_core::element::FontFamily;
use excali_scene::shape::Theme;
use excali_text::font_assets::{registered_families, registered_family};
use excali_text::font_metadata::{font_metadata, get_font_family_string};
use serde_json::{Map, Value};
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement, HtmlInputElement, KeyboardEvent};

use crate::color_picker::{place_beside, KeyInput, StylesPanelMode};
use crate::dom::{class_names, Element, Node};
use crate::icons::{self, Icon};
use crate::main_menu::menu_group;
use crate::primitives::{icon_button, island, IconButtonKind, IconButtonProps, IslandProps};
use crate::top_picks_dnd::{
    context_menu, context_menu_trigger, get_top_pick_reorder_offset, hide_others,
    top_picks_dnd_outline, top_picks_tip, DragOrigin, Rect, TipReset, TopPicksDnd,
    TopPicksDndEvent,
};

/// `FontPicker.scss`, `QuickSearch.scss`, `ScrollableList.scss` and
/// `TopPicksDnD.scss`, compiled (generated by `tools/goldens/font-picker.mjs`).
pub const FONT_PICKER_CSS: &str = include_str!("font_picker.css");

/// The `data-excali-ui` value of the `<style>` holding [`FONT_PICKER_CSS`].
const STYLESHEET_ID: &str = "font-picker";

/// Adds [`FONT_PICKER_CSS`] to `document`'s head once, after the dropdown
/// menu's stylesheet ([`crate::main_menu::install_stylesheet`], whose
/// items the list uses, and which it installs first).
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::main_menu::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(FONT_PICKER_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    head.append_child(&style)?;
    Ok(())
}

/// The English strings of the picker (`locales/en.json`); the key itself
/// for any other.
pub fn font_picker_text(key: &str) -> &str {
    match key {
        "labels.handDrawn" => "Hand-drawn",
        "labels.normal" => "Normal",
        "labels.code" => "Code",
        "labels.showFonts" => "Show font picker",
        "labels.fontFamily" => "Font family",
        "quickSearch.placeholder" => "Quick search",
        "fontList.badge.old" => "old",
        "fontList.sceneFonts" => "In this scene",
        "fontList.availableFonts" => "Available fonts",
        "fontList.empty" => "No fonts found",
        "fontList.topPicksTip" => "Tip: drag any font onto your top picks to pin it",
        "fontList.resetTopPicks" => "Reset to default top picks",
        "buttons.reset" => "Reset",
        other => other,
    }
}

// -- fonts -------------------------------------------------------------------------

/// A default top pick (`DEFAULT_FONTS`, `FontPicker.tsx:42-63`).
#[derive(Clone, Copy, Debug)]
pub struct DefaultFont {
    pub value: FontFamily,
    pub icon: &'static Icon,
    /// Its label's locale key.
    pub text_key: &'static str,
    pub test_id: &'static str,
}

/// The three default top picks.
pub const DEFAULT_FONTS: [DefaultFont; FONT_TOP_PICKS_SLOTS] = [
    DefaultFont {
        value: FontFamily::EXCALIFONT,
        icon: &icons::FreedrawIcon,
        text_key: "labels.handDrawn",
        test_id: "font-family-hand-drawn",
    },
    DefaultFont {
        value: FontFamily::NUNITO,
        icon: &icons::FontFamilyNormalIcon,
        text_key: "labels.normal",
        test_id: "font-family-normal",
    },
    DefaultFont {
        value: FontFamily::COMIC_SHANNS,
        icon: &icons::FontFamilyCodeIcon,
        text_key: "labels.code",
        test_id: "font-family-code",
    },
];

fn default_font(family: FontFamily) -> Option<&'static DefaultFont> {
    DEFAULT_FONTS.iter().find(|f| f.value == family)
}

/// `isDefaultFont` (`FontPicker.tsx:82-88`).
pub fn is_default_font(family: Option<FontFamily>) -> bool {
    family.is_some_and(|f| f.0 != 0 && default_font(f).is_some())
}

/// `getFontTopPicks` (`FontPicker.tsx:67-80`): the customised picks,
/// deduplicated and capped, padded with the defaults they lack.
pub fn get_font_top_picks(top_picks: &[FontFamily]) -> Vec<FontFamily> {
    let mut picks: Vec<FontFamily> = Vec::new();
    for f in top_picks {
        if !picks.contains(f) {
            picks.push(*f);
        }
    }
    picks.truncate(FONT_TOP_PICKS_SLOTS);
    for f in DEFAULT_FONTS.iter().map(|f| f.value) {
        if picks.len() >= FONT_TOP_PICKS_SLOTS {
            break;
        }
        if !picks.contains(&f) {
            picks.push(f);
        }
    }
    picks
}

/// The strip's picks: the customised ones when there are any, else the
/// defaults (`FontPicker.tsx:239-241`).
pub fn top_picks(custom: Option<&[FontFamily]>) -> Vec<FontFamily> {
    match custom {
        Some(p) if !p.is_empty() => get_font_top_picks(p),
        _ => DEFAULT_FONTS.iter().map(|f| f.value).collect(),
    }
}

/// `getFontFamilyIcon` (`FontPickerList.tsx:76-95`).
pub fn font_family_icon(family: FontFamily) -> &'static Icon {
    match family {
        FontFamily::EXCALIFONT | FontFamily::VIRGIL => &icons::FreedrawIcon,
        FontFamily::LILITA_ONE => &icons::FontFamilyHeadingIcon,
        FontFamily::COMIC_SHANNS | FontFamily::CASCADIA => &icons::FontFamilyCodeIcon,
        _ => &icons::FontFamilyNormalIcon,
    }
}

/// `getFontFamilyLabel` (`FontPickerList.tsx:97-104`): the `FONT_FAMILY`
/// name, else the registered family's name, else "Unknown".
pub fn font_family_label(family: FontFamily) -> String {
    if FontFamily::ELEMENT_FAMILIES.contains(&family) {
        if let Some(name) = family.name() {
            return name.to_owned();
        }
    }
    registered_family(family)
        .map(|r| r.family.to_owned())
        .unwrap_or_else(|| "Unknown".to_owned())
}

/// `getFontFamilyString({fontFamily})` (`common/src/utils.ts:123-136`),
/// the CSS family list an item's label is set in.
pub fn font_family_string(family: FontFamily) -> String {
    get_font_family_string(family)
}

/// A list item (`FontDescriptor`, `FontPickerList.tsx:55-64`).
#[derive(Clone, Debug, PartialEq)]
pub struct FontDescriptor {
    pub value: FontFamily,
    pub icon: &'static Icon,
    pub text: String,
    /// Badged "old" and left out of "Available fonts" unless
    /// `showDeprecatedFonts`.
    pub deprecated: bool,
}

/// Every family of the registry but the private and fallback ones, sorted
/// by label, case-insensitively (`FontPickerList.tsx:128-156`).
pub fn all_fonts() -> Vec<FontDescriptor> {
    let mut fonts: Vec<FontDescriptor> = registered_families()
        .iter()
        .filter(|r| font_metadata(r.id).is_some_and(|m| !m.private && !m.fallback))
        .map(|r| FontDescriptor {
            value: r.id,
            icon: font_family_icon(r.id),
            text: font_family_label(r.id),
            deprecated: font_metadata(r.id).is_some_and(|m| m.deprecated),
        })
        .collect();
    fonts.sort_by_key(|f| f.text.to_lowercase());
    fonts
}

/// What the list shows besides the search: the scene's families
/// (`app.fonts.getSceneFamilies()`) and the host's `showDeprecatedFonts`.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct FontListContext {
    pub scene_families: Vec<FontFamily>,
    pub show_deprecated_fonts: bool,
}

/// The two groups after the search (`FontPickerList.tsx:158-190,
/// 263-271`).
#[derive(Clone, Debug, Default, PartialEq)]
pub struct FilteredFonts {
    /// "In this scene": every font the scene uses, deprecated or not.
    pub scene: Vec<FontDescriptor>,
    /// "Available fonts": the rest, without the deprecated ones unless
    /// shown.
    pub available: Vec<FontDescriptor>,
}

impl FilteredFonts {
    /// Both groups in order (`filteredFonts`).
    pub fn all(&self) -> impl Iterator<Item = &FontDescriptor> {
        self.scene.iter().chain(&self.available)
    }
}

/// The list's fonts whose label contains `search` (already trimmed and
/// lowercased, as QuickSearch passes it).
pub fn filtered_fonts(cx: &FontListContext, search: &str) -> FilteredFonts {
    let mut out = FilteredFonts::default();
    for font in all_fonts() {
        if !font.text.to_lowercase().contains(search) {
            continue;
        }
        if cx.scene_families.contains(&font.value) {
            out.scene.push(font);
        } else if cx.show_deprecated_fonts || !font.deprecated {
            out.available.push(font);
        }
    }
    out
}

/// `hoveredFont` (`FontPickerList.tsx:192-222`): the hovered font, else
/// the selected one, if listed. With a search leaving neither listed, the
/// list hovers its first font, or leaves when it has none: that callback
/// is returned too.
pub fn hovered_font(
    filtered: &FilteredFonts,
    state: &FontPickerState,
) -> (Option<FontFamily>, Option<FontPickerEvent>) {
    let find = |f: FontFamily| filtered.all().find(|x| x.value == f).map(|x| x.value);
    let font = match (state.hovered, state.selected) {
        (Some(h), _) => find(h),
        (None, Some(s)) => find(s),
        (None, None) => None,
    };
    let effect =
        (font.is_none() && !state.search.is_empty()).then(|| match filtered.all().next() {
            Some(first) => FontPickerEvent::Hover(first.value),
            None => FontPickerEvent::Leave,
        });
    (font, effect)
}

// -- keyboard ------------------------------------------------------------------------

/// What a key does in the list.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FontPickerKeyEffect {
    /// Shift+F: focus the search box.
    FocusSearch,
    /// Escape: `onClose`.
    Close,
    Select(FontFamily),
    Hover(FontFamily),
}

/// Whether the list handled a key (and so prevents its default and stops
/// it), and what it does.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FontPickerKeyOutcome {
    pub handled: bool,
    pub effect: Option<FontPickerKeyEffect>,
}

/// `fontPickerKeyHandler` (`keyboardNavHandlers.ts:17-68`) over the
/// listed fonts in order (`filtered`), the arrows wrapping around.
pub fn font_picker_key_handler(
    event: &KeyInput,
    hovered: Option<FontFamily>,
    filtered: &[FontFamily],
) -> FontPickerKeyOutcome {
    let handled = |effect| FontPickerKeyOutcome {
        handled: true,
        effect,
    };
    let index = hovered.and_then(|h| filtered.iter().position(|f| *f == h));
    if !event.ctrl_or_cmd && event.shift && event.key.to_lowercase() == "f" {
        return handled(Some(FontPickerKeyEffect::FocusSearch));
    }
    match event.key.as_str() {
        "Escape" => handled(Some(FontPickerKeyEffect::Close)),
        "Enter" => handled(index.map(|i| FontPickerKeyEffect::Select(filtered[i]))),
        "ArrowDown" => {
            let next = match index {
                Some(i) => filtered.get((i + 1) % filtered.len()),
                None => filtered.first(),
            };
            handled(next.map(|f| FontPickerKeyEffect::Hover(*f)))
        }
        "ArrowUp" => {
            let prev = match index {
                Some(i) => filtered.get((i + filtered.len() - 1) % filtered.len()),
                None => filtered.last(),
            };
            handled(prev.map(|f| FontPickerKeyEffect::Hover(*f)))
        }
        _ => FontPickerKeyOutcome {
            handled: false,
            effect: None,
        },
    }
}

// -- state -----------------------------------------------------------------------------

/// What the picker asks of its host: its callbacks (`FontPickerProps`,
/// `FontPicker.tsx:199-211`), the trigger's `setAppState`, and the search
/// the list keeps.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FontPickerEvent {
    /// `onSelect`: a top pick, a list item or Enter.
    Select(FontFamily),
    /// `onHover`: an item under the pointer or the arrows.
    Hover(FontFamily),
    /// `onLeave`: the pointer left the popup.
    Leave,
    /// `onPopupChange`: the popup opened or closed.
    PopupChange(bool),
    /// The trigger's `setAppState`: closes `openPopup` when it is
    /// "fontFamily" (`FontPickerTrigger.tsx:44-48`).
    TriggerSelect,
    /// `onTopPicksChange`: a drop's new picks, or `None` (the strip's
    /// context menu, the tip's reset link) for the defaults.
    TopPicksChange(Option<Vec<FontFamily>>),
    /// The strip's context menu opens at this client point, or closes:
    /// the host keeps it in [`FontPickerProps::top_picks_menu`].
    TopPicksMenu(Option<(i32, i32)>),
    /// A drag's state changed: render again.
    DragChange,
    /// The search box's term, trimmed and lowercased (the list's own
    /// state, debounced by 20 ms upstream).
    Search(String),
}

/// Called with each [`FontPickerEvent`].
pub type OnFontPickerEvent = Rc<dyn Fn(FontPickerEvent)>;

/// The app state the picker reads and its host writes, and the list's
/// search.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct FontPickerState {
    /// `appState.openPopup`.
    pub open_popup: Option<String>,
    /// The selection's font family (`currentItemFontFamily` with no text
    /// selected), `None` when mixed.
    pub selected: Option<FontFamily>,
    /// `appState.currentHoveredFontFamily`.
    pub hovered: Option<FontFamily>,
    /// `appState.fontTopPicks`.
    pub top_picks: Option<Vec<FontFamily>>,
    /// The list's search term; cleared when it closes.
    pub search: String,
}

fn family_of(v: Option<&Value>) -> Option<FontFamily> {
    v.and_then(Value::as_u64)
        .and_then(|n| u32::try_from(n).ok())
        .map(FontFamily)
}

impl FontPickerState {
    /// The picker's state from the app state and the selection's font
    /// family (the panel's `getFormValue`, `actionProperties.tsx:1371-1415`).
    pub fn from_app_state(app_state: &Map<String, Value>, selected: Option<FontFamily>) -> Self {
        FontPickerState {
            open_popup: app_state
                .get("openPopup")
                .and_then(Value::as_str)
                .map(str::to_owned),
            selected,
            hovered: family_of(app_state.get("currentHoveredFontFamily")),
            top_picks: app_state
                .get("fontTopPicks")
                .and_then(Value::as_array)
                .map(|a| a.iter().filter_map(|v| family_of(Some(v))).collect()),
            search: String::new(),
        }
    }

    /// `appState.openPopup === "fontFamily"`.
    pub fn is_open(&self) -> bool {
        self.open_popup.as_deref() == Some("fontFamily")
    }

    /// What the host's update does with one callback
    /// (`actionProperties.tsx:1440-1540` batching into `perform`).
    fn apply(&mut self, event: &FontPickerEvent) {
        match event {
            FontPickerEvent::Select(f) => {
                self.open_popup = None;
                self.hovered = None;
                self.selected = Some(*f);
            }
            FontPickerEvent::Hover(f) => self.hovered = Some(*f),
            FontPickerEvent::Leave => self.hovered = None,
            FontPickerEvent::PopupChange(true) => self.open_popup = Some("fontFamily".into()),
            FontPickerEvent::PopupChange(false) => self.hovered = None,
            FontPickerEvent::TriggerSelect => {
                if self.is_open() {
                    self.open_popup = None;
                }
            }
            FontPickerEvent::TopPicksChange(p) => self.top_picks = p.clone(),
            FontPickerEvent::Search(term) => self.search = term.clone(),
            FontPickerEvent::TopPicksMenu(_) | FontPickerEvent::DragChange => {}
        }
    }

    /// The list's search hover, if any (see [`hovered_font`]).
    fn settle(&mut self, cx: &FontListContext) -> Vec<FontPickerEvent> {
        if !self.is_open() {
            return Vec::new();
        }
        let (_, effect) = hovered_font(&filtered_fonts(cx, &self.search), self);
        match effect {
            Some(e) => {
                self.apply(&e);
                vec![e]
            }
            None => Vec::new(),
        }
    }

    /// The first render: an open list calls `onOpen` as it mounts
    /// (`FontPickerList.tsx:264-271`). Returns the callbacks made.
    pub fn mount(&mut self, cx: &FontListContext) -> Vec<FontPickerEvent> {
        if !self.is_open() {
            return Vec::new();
        }
        let open = FontPickerEvent::PopupChange(true);
        self.apply(&open);
        let mut calls = vec![open];
        calls.extend(self.settle(cx));
        calls
    }

    /// Applies an event and what follows from it: the list calls `onOpen`
    /// as it mounts and `onClose` as it unmounts, and hovers on a search.
    /// Returns the host callbacks made, in order (a search, the menu's
    /// point and a drag's render are the picker's own and not among them).
    pub fn dispatch(
        &mut self,
        event: FontPickerEvent,
        cx: &FontListContext,
    ) -> Vec<FontPickerEvent> {
        let was_open = self.is_open();
        self.apply(&event);
        let mut calls = Vec::new();
        if !matches!(
            event,
            FontPickerEvent::Search(_)
                | FontPickerEvent::TopPicksMenu(_)
                | FontPickerEvent::DragChange
        ) {
            calls.push(event);
        }
        let open = self.is_open();
        if was_open && !open {
            let close = FontPickerEvent::PopupChange(false);
            self.apply(&close);
            calls.push(close);
            self.search.clear();
        } else if !was_open && open {
            calls.extend(self.mount(cx));
        } else {
            calls.extend(self.settle(cx));
        }
        calls
    }
}

// -- top picks customisation -------------------------------------------------------

/// The font picker's drag and drop (`FontPickerDnD`,
/// `fontTopPicksDnD.ts:84`).
pub type FontPickerDnd = TopPicksDnd<FontFamily>;

/// A new [`FontPickerDnd`] (`useFontTopPicksDnD`,
/// `fontTopPicksDnD.ts:92-106`): a font pinned already is refused.
pub fn font_picker_dnd() -> FontPickerDnd {
    TopPicksDnd::new(|a, b| a == b)
}

/// What a list row does with the pointer over it (`onMouseMove`,
/// `FontPickerList.tsx:328-333`): previews its font unless it is the
/// hovered one, or a drag is passing over it.
pub fn hover_event(
    dragging: bool,
    hovered: Option<FontFamily>,
    value: FontFamily,
) -> Option<FontPickerEvent> {
    (!dragging && hovered != Some(value)).then_some(FontPickerEvent::Hover(value))
}

/// Where a ghost comes from: a list row, or a pick of the strip showing
/// these picks.
#[derive(Clone, Copy, Debug)]
pub enum FontGhostSource<'a> {
    Row,
    Pick(&'a [FontFamily]),
}

/// The computed style `createFontGhost` samples (`fontTopPicksDnD.ts:30-40,
/// 44-50, 55-63`): the template pick's colours, border and radius, its
/// icon's size, and the source's glyph sample's font size. An empty value
/// is not written.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct FontGhostStyle {
    pub background_color: String,
    pub color: String,
    pub border_width: String,
    pub border_color: String,
    pub border_radius: String,
    pub icon_size: Option<(f64, f64)>,
    pub sample_font_size: String,
}

/// The pick whose look a ghost takes (`fontTopPicksDnD.ts:24-29`): a
/// dragged pick's own, else the first pick that is not the selected font's
/// (`[data-top-pick-index]:not(.active)`), else the first.
pub fn ghost_template_index(picks: &[FontFamily], selected: Option<FontFamily>) -> usize {
    picks.iter().position(|p| Some(*p) != selected).unwrap_or(0)
}

/// The ghost's content (`createFontGhost`, `fontTopPicksDnD.ts:19-66`): a
/// strip-button tile with the font's icon, or a pick's glyph sample,
/// never the whole list row.
pub fn font_ghost(
    family: FontFamily,
    source: FontGhostSource<'_>,
    style: &FontGhostStyle,
) -> Element {
    let set = |el: Element, property: &str, value: &str| {
        if value.is_empty() {
            el
        } else {
            el.style(property.to_owned(), value.to_owned())
        }
    };
    let mut tile = Element::new("div").attr("class", "excalidraw-font-dnd-ghost-tile");
    tile = set(tile, "background-color", &style.background_color);
    tile = set(tile, "color", &style.color);
    tile = tile.style("border-style", "solid");
    tile = set(tile, "border-width", &style.border_width);
    tile = set(tile, "border-color", &style.border_color);
    tile = set(tile, "border-radius", &style.border_radius);
    let icon_of = |i: &Icon| {
        let el = i
            .element(Theme::Light)
            .unwrap_or_else(|| panic!("icons.tsx has no {}", i.name));
        match style.icon_size {
            Some((w, h)) => el
                .style("width", format!("{w}px"))
                .style("height", format!("{h}px")),
            None => el,
        }
    };
    let content = match source {
        FontGhostSource::Row => icon_of(font_family_icon(family)),
        FontGhostSource::Pick(picks) if needs_glyph_sample(family, picks) => {
            let sample = Element::new("span")
                .attr("class", "FontPicker__top-pick-sample")
                .style("font-family", font_family_string(family));
            set(sample, "font-size", &style.sample_font_size)
                .style("line-height", "1")
                .child("Aa")
        }
        FontGhostSource::Pick(_) => icon_of(pick_icon(family)),
    };
    tile.child(content)
}

/// Where the ghost spawns and flies back to (`fontTopPicksDnD.ts:67-82`):
/// a pick's own rect, or the template's size centred on the list row's
/// icon (`anchor`).
pub fn font_ghost_rect(is_pick: bool, template: Rect, anchor: Rect) -> Rect {
    if is_pick {
        return template;
    }
    Rect {
        left: anchor.left + anchor.width / 2.0 - template.width / 2.0,
        top: anchor.top + anchor.height / 2.0 - template.height / 2.0,
        width: template.width,
        height: template.height,
    }
}

/// [`font_ghost`] and [`font_ghost_rect`] from the rendered DOM: the
/// source, the registered strip's template pick and their computed style.
fn browser_ghost(
    source: &web_sys::Element,
    strip: Option<&web_sys::Element>,
    family: FontFamily,
    picks: &[FontFamily],
) -> (web_sys::Element, Rect) {
    let is_pick = source.has_attribute("data-top-pick-index");
    let template = if is_pick {
        Some(source.clone())
    } else {
        strip.and_then(|s| {
            s.query_selector("[data-top-pick-index]:not(.active)")
                .ok()
                .flatten()
                .or_else(|| s.query_selector("[data-top-pick-index]").ok().flatten())
        })
    }
    .unwrap_or_else(|| source.clone());
    let window = web_sys::window();
    let computed = |el: &web_sys::Element, property: &str| {
        window
            .as_ref()
            .and_then(|w| w.get_computed_style(el).ok().flatten())
            .and_then(|s| s.get_property_value(property).ok())
            .unwrap_or_default()
    };
    let icon = source.query_selector("svg").ok().flatten();
    let style = FontGhostStyle {
        background_color: computed(&template, "background-color"),
        color: computed(&template, "color"),
        border_width: computed(&template, "border-top-width"),
        border_color: computed(&template, "border-top-color"),
        border_radius: computed(&template, "border-top-left-radius"),
        icon_size: template.query_selector("svg").ok().flatten().map(|svg| {
            let r = Rect::of(&svg);
            (r.width, r.height)
        }),
        sample_font_size: source
            .query_selector(".FontPicker__top-pick-sample")
            .ok()
            .flatten()
            .map(|s| computed(&s, "font-size"))
            .unwrap_or_default(),
    };
    let ghost_source = if is_pick {
        FontGhostSource::Pick(picks)
    } else {
        FontGhostSource::Row
    };
    let ghost = font_ghost(family, ghost_source, &style);
    let content = source
        .owner_document()
        .and_then(|d| crate::dom::create_detached(&Node::Element(ghost), &d).ok())
        .and_then(|n| n.dyn_into::<web_sys::Element>().ok())
        .unwrap_or_else(|| source.clone());
    let anchor = Rect::of(icon.as_ref().unwrap_or(source));
    (
        content,
        font_ghost_rect(is_pick, Rect::of(&template), anchor),
    )
}

/// Lets `el` start a drag of `family` from `origin` while the strip is
/// customisable (`startSourceDrag`, `startPickDrag`); `picks` are the
/// strip's.
fn draggable(
    el: Element,
    props: &FontPickerProps,
    family: FontFamily,
    origin: DragOrigin,
    picks: &[FontFamily],
) -> Element {
    if !props.customizable() {
        return el;
    }
    let dnd = props.dnd.clone();
    let picks = picks.to_vec();
    el.on("pointerdown", move |e: &Event| {
        let Some(dnd) = &dnd else {
            return;
        };
        let strip = dnd.strip();
        dnd.start_drag(e, Some(family), origin, |source| {
            browser_ghost(source, strip.as_ref(), family, &picks)
        });
    })
}

// -- DOM ---------------------------------------------------------------------------------

/// The picker's props: the state and what it is rendered in.
#[derive(Clone)]
pub struct FontPickerProps {
    pub state: FontPickerState,
    /// The styles panel's layout: the strip and the search only in
    /// [`StylesPanelMode::Full`] (`compactMode` otherwise).
    pub mode: StylesPanelMode,
    pub list: FontListContext,
    /// The badge's border (`DropdownMenuItem.tsx:85`).
    pub theme: Theme,
    /// `editorInterface.formFactor === "phone"`: the popup's left margin,
    /// and below the trigger.
    pub phone: bool,
    /// Cmd rather than Ctrl is the command key.
    pub is_darwin: bool,
    /// The popup's id, which the trigger's `aria-controls` names.
    pub popup_id: String,
    pub on_event: Option<OnFontPickerEvent>,
    /// The strip's context menu is open at this client point.
    pub top_picks_menu: Option<(i32, i32)>,
    /// The drag and drop ([`font_picker_dnd`]), kept by the host across
    /// renders.
    pub dnd: Option<FontPickerDnd>,
}

impl FontPickerProps {
    fn compact(&self) -> bool {
        self.mode != StylesPanelMode::Full
    }

    /// `isTopPicksCustomizable` (`FontPicker.tsx:234-235`): the strip is
    /// shown, so it can be customised.
    fn customizable(&self) -> bool {
        !self.compact()
    }

    fn customized(&self) -> bool {
        self.state.top_picks.as_ref().is_some_and(|p| !p.is_empty())
    }

    fn handler(&self, event: FontPickerEvent) -> impl Fn(&Event) + 'static {
        let on_event = self.on_event.clone();
        move |_| emit(&on_event, event.clone())
    }
}

fn emit(on_event: &Option<OnFontPickerEvent>, event: FontPickerEvent) {
    if let Some(f) = on_event {
        f(event);
    }
}

fn icon(icon: &Icon) -> Node {
    icon.element(Theme::Light)
        .unwrap_or_else(|| panic!("icons.tsx has no {}", icon.name))
        .into()
}

/// `ButtonSeparator` (`components/ButtonSeparator.tsx`).
fn button_separator() -> Node {
    Element::new("div")
        .style("width", "1px")
        .style("height", "1rem")
        .style("background-color", "var(--default-border-color)")
        .style("margin", "0 auto")
        .into()
}

/// `needsGlyphSample` (`FontPicker.tsx:101-113`): a non-default pick whose
/// icon another pick shows too gets an "Aa" in its own font.
fn needs_glyph_sample(family: FontFamily, picks: &[FontFamily]) -> bool {
    if default_font(family).is_some() {
        return false;
    }
    let icon = pick_icon(family).name;
    picks
        .iter()
        .any(|p| *p != family && pick_icon(*p).name == icon)
}

/// `getTopPickFont` (`FontPicker.tsx:90-99`): the default's icon, label
/// and test id, else the family's own.
fn pick_icon(family: FontFamily) -> &'static Icon {
    default_font(family).map_or_else(|| font_family_icon(family), |d| d.icon)
}

fn pick_label(family: FontFamily) -> String {
    default_font(family).map_or_else(
        || font_family_label(family),
        |d| font_picker_text(d.text_key).to_owned(),
    )
}

fn pick_test_id(family: FontFamily) -> String {
    default_font(family).map_or_else(
        || format!("font-family-{}", family.0),
        |d| d.test_id.to_owned(),
    )
}

/// `FontTopPicks` (`FontPicker.tsx:115-187`) in its `TopPicksContextMenu`
/// trigger: the picks, which a drag moves and marks, around the drag's
/// outline.
fn top_picks_strip(props: &FontPickerProps) -> Node {
    let picks = top_picks(props.state.top_picks.as_deref());
    let drag_state = props.dnd.as_ref().and_then(|d| d.drag_state());
    let state = drag_state.as_ref();
    let buttons = picks.iter().enumerate().map(|(index, family)| {
        let family = *family;
        let content = if needs_glyph_sample(family, &picks) {
            Element::new("span")
                .attr("class", "FontPicker__top-pick-sample")
                .style("font-family", font_family_string(family))
                .child("Aa")
                .into()
        } else {
            icon(pick_icon(family))
        };
        let offset = get_top_pick_reorder_offset(state, index);
        let el = Element::new("button")
            .attr("type", "button")
            .attr("title", pick_label(family))
            .attr("data-testid", pick_test_id(family))
            .attr(
                "class",
                class_names([
                    ("top-picks-dnd__pick", true),
                    ("active", props.state.selected == Some(family)),
                    (
                        "is-dnd-source",
                        state.is_some_and(|s| s.origin == DragOrigin::Pick(index)),
                    ),
                    (
                        "is-dnd-target",
                        state.is_some_and(|s| {
                            s.origin == DragOrigin::Source && s.over_index == Some(index)
                        }),
                    ),
                    (
                        "is-dnd-duplicate",
                        state.is_some_and(|s| s.duplicate_index == Some(index)),
                    ),
                ]),
            )
            .style_opt(
                "transform",
                (offset != 0.0).then(|| format!("translateX({offset}px)")),
            )
            .on("click", props.handler(FontPickerEvent::Select(family)))
            .attr("data-top-pick-index", index.to_string())
            .child(content);
        draggable(el, props, family, DragOrigin::Pick(index), &picks).into()
    });
    let mut slots = Element::new("div")
        .attr(
            "class",
            class_names([
                ("FontPicker__top-picks-slots top-picks-dnd", true),
                ("is-dnd-active", drag_state.is_some()),
            ]),
        )
        .child_opt(drag_state.is_some().then(top_picks_dnd_outline))
        .children_from(buttons);
    if let Some(dnd) = props.dnd.clone() {
        slots = slots.on_mount(move |el| dnd.set_strip(Some(el.clone())));
    }
    let on_event = props.on_event.clone();
    let open = props.state.is_open();
    let on_open: Rc<dyn Fn(i32, i32)> = Rc::new(move |x, y| {
        emit(&on_event, FontPickerEvent::TopPicksMenu(Some((x, y))));
        // radix's popover closes as the menu takes the focus
        if open {
            emit(&on_event, FontPickerEvent::PopupChange(false));
        }
    });
    context_menu_trigger(
        Element::new("div")
            .attr("class", "buttonList FontPicker__top-picks")
            .child(slots),
        props.top_picks_menu.is_some(),
        on_open,
    )
    .into()
}

/// `FontPickerTrigger` (`FontPickerTrigger.tsx`): radix's
/// `Popover.Trigger` (asChild) around a toggle IconButton.
fn trigger(props: &FontPickerProps) -> Node {
    let open = props.state.is_open();
    let mut style = vec![("border".to_owned(), "none".to_owned())];
    if props.compact() {
        // MOBILE_ACTION_BUTTON_BG
        style.insert(
            0,
            ("background".into(), "var(--mobile-action-button-bg)".into()),
        );
        style.push(("width".into(), "2rem".into()));
        style.push(("height".into(), "2rem".into()));
    }
    let label = font_picker_text("labels.showFonts");
    let on_event = props.on_event.clone();
    let button = icon_button(IconButtonProps {
        kind: IconButtonKind::Toggle { checked: open },
        icon: Some(icon(&icons::TextIcon)),
        title: Some(label.to_owned()),
        aria_label: label.to_owned(),
        class_name: "standalone properties-trigger".into(),
        test_id: Some("font-family-show-fonts".into()),
        style,
        ..IconButtonProps::default()
    });
    Element::new("div")
        .attr("type", "button")
        .attr("aria-haspopup", "dialog")
        .attr("aria-expanded", open.to_string())
        .attr("aria-controls", props.popup_id.as_str())
        .attr("data-state", if open { "open" } else { "closed" })
        .attr("data-openpopup", "fontFamily")
        .attr("class", "properties-trigger")
        .on("click", move |e: &Event| {
            e.prevent_default();
            e.stop_propagation();
            // the IconButton's onSelect, then radix's toggle
            emit(&on_event, FontPickerEvent::TriggerSelect);
            emit(&on_event, FontPickerEvent::PopupChange(!open));
        })
        .child(button)
        .into()
}

/// `DropDownMenuItemBadge` of the red type (`DropdownMenuItem.tsx:70-114`).
fn old_badge(theme: Theme) -> Element {
    Element::new("div")
        .attr("class", "DropDownMenuItemBadge")
        .style("display", "inline-flex")
        .style("margin-left", "auto")
        .style("padding", "2px 4px")
        .style("border-radius", "6px")
        .style("font-size", "9px")
        .style("font-family", "Cascadia, monospace")
        .style(
            "border",
            if theme == Theme::Light {
                "1.5px solid white"
            } else {
                "none"
            },
        )
        .style("background-color", "pink")
        .style("color", "darkred")
        .child(font_picker_text("fontList.badge.old"))
}

/// `getDropdownMenuItemClassName("", selected, hovered)`
/// (`dropdownMenu/common.ts:9-17`), spaces and all.
fn item_class(selected: bool, hovered: bool) -> String {
    format!(
        "dropdown-menu-item dropdown-menu-item-base  {} {}",
        if selected {
            "dropdown-menu-item--selected"
        } else {
            ""
        },
        if hovered {
            "dropdown-menu-item--hovered"
        } else {
            ""
        }
    )
    .trim()
    .to_owned()
}

/// `FontPickerListItem` (`FontPickerList.tsx:283-345`).
fn list_item(
    props: &FontPickerProps,
    font: &FontDescriptor,
    order: usize,
    hovered: Option<FontFamily>,
) -> Node {
    let is_hovered = hovered == Some(font.value);
    let is_selected = props.state.selected == Some(font.value);
    let value = font.value;
    let on_event = props.on_event.clone();
    let dnd = props.dnd.clone();
    let mut el = Element::new("button")
        .attr("type", "button")
        .attr("value", value.0.to_string())
        .attr("class", item_class(is_selected, is_hovered))
        .attr("title", font.text.as_str())
        .attr("tabindex", if is_selected { "0" } else { "-1" })
        .on("click", props.handler(FontPickerEvent::Select(value)))
        .on("mousemove", move |_| {
            let dragging = dnd.as_ref().is_some_and(|d| d.drag_state().is_some());
            if let Some(e) = hover_event(dragging, hovered, value) {
                emit(&on_event, e);
            }
        })
        .child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__icon")
                .child(icon(font.icon)),
        )
        .child(
            Element::new("div")
                .style("font-family", font_family_string(value))
                .attr("class", "dropdown-menu-item__text")
                .child(
                    // Ellipsify (Ellipsify.tsx)
                    Element::new("span")
                        .style("text-overflow", "ellipsis")
                        .style("overflow", "hidden")
                        .style("white-space", "nowrap")
                        .child(font.text.as_str()),
                ),
        )
        .child_opt(font.deprecated.then(|| {
            Element::new("div")
                .attr("class", "dropdown-menu-item__badge")
                .child(old_badge(props.theme))
        }));
    el = draggable(el, props, value, DragOrigin::Source, &[]);
    if is_hovered {
        // the first item scrolls so its group title shows
        let block = if order == 0 { "end" } else { "nearest" };
        el = el.on_mount(move |dom| scroll_into_view(dom, block));
    }
    el.into()
}

fn scroll_into_view(el: &web_sys::Element, block: &str) {
    let Some(f) = js_sys::Reflect::get(el, &"scrollIntoView".into())
        .ok()
        .and_then(|f| f.dyn_into::<js_sys::Function>().ok())
    else {
        return;
    };
    let options = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&options, &"block".into(), &block.into());
    let _ = f.call1(el, &options);
}

/// The list's `TopPicksTip` (`FontPickerList.tsx:420-427`), with the reset
/// link while the picks are customised.
fn tip(props: &FontPickerProps) -> Node {
    let on_event = props.on_event.clone();
    let reset = props.customized().then(|| TipReset {
        title: font_picker_text("fontList.resetTopPicks"),
        label: font_picker_text("buttons.reset"),
        on_reset: Rc::new(move || emit(&on_event, FontPickerEvent::TopPicksChange(None))),
    });
    top_picks_tip(
        Some("FontPicker__tip"),
        font_picker_text("fontList.topPicksTip"),
        reset,
    )
}

/// `QuickSearch` (`components/QuickSearch.tsx`).
fn quick_search(props: &FontPickerProps) -> Node {
    let on_event = props.on_event.clone();
    Element::new("div")
        .attr("class", "QuickSearch__wrapper")
        .child(icon(&icons::searchIcon))
        .child(
            Element::new("input")
                .attr("class", "QuickSearch__input")
                .attr("type", "text")
                .attr("placeholder", font_picker_text("quickSearch.placeholder"))
                .on("input", move |e: &Event| {
                    let Some(input) = e
                        .target()
                        .and_then(|t| t.dyn_into::<HtmlInputElement>().ok())
                    else {
                        return;
                    };
                    emit(
                        &on_event,
                        FontPickerEvent::Search(input.value().trim().to_lowercase()),
                    );
                }),
        )
        .into()
}

/// `FontPickerList` (`FontPickerList.tsx:106-435`) in its
/// `PropertiesPopover`: radix's popper wrapper and the dialog content
/// with the island and the arrow.
fn popup(props: &FontPickerProps) -> Node {
    let filtered = filtered_fonts(&props.list, &props.state.search);
    let hovered = hovered_font(&filtered, &props.state).0;
    let values: Vec<FontFamily> = filtered.all().map(|f| f.value).collect();

    let mut groups = Vec::new();
    if !filtered.scene.is_empty() {
        let items = filtered
            .scene
            .iter()
            .enumerate()
            .map(|(i, f)| list_item(props, f, i, hovered))
            .collect();
        groups.push(menu_group(Some(font_picker_text("fontList.sceneFonts")), "", items).into());
    }
    if !filtered.available.is_empty() {
        let offset = filtered.scene.len();
        let items = filtered
            .available
            .iter()
            .enumerate()
            .map(|(i, f)| list_item(props, f, i + offset, hovered))
            .collect();
        groups
            .push(menu_group(Some(font_picker_text("fontList.availableFonts")), "", items).into());
    }
    let list = Element::new("div")
        .attr(
            "class",
            "ScrollableList__wrapper dropdown-menu fonts manual-hover",
        )
        .attr("role", "menu");
    let list = if groups.is_empty() {
        list.child(
            Element::new("div")
                .attr("class", "empty")
                .child(font_picker_text("fontList.empty")),
        )
    } else {
        list.children_from(groups)
    };
    let mut body = Vec::new();
    if !props.compact() {
        body.push(quick_search(props));
    }
    body.push(list.into());
    // only while the top picks are customisable
    if props.customizable() {
        body.push(tip(props));
    }

    let keydown = {
        let on_event = props.on_event.clone();
        let is_darwin = props.is_darwin;
        move |e: &Event| {
            let Some(k) = e.dyn_ref::<KeyboardEvent>() else {
                return;
            };
            let input = KeyInput {
                key: k.key(),
                code: k.code(),
                shift: k.shift_key(),
                ctrl_or_cmd: if is_darwin {
                    k.meta_key()
                } else {
                    k.ctrl_key()
                },
            };
            let out = font_picker_key_handler(&input, hovered, &values);
            if !out.handled {
                return;
            }
            e.prevent_default();
            e.stop_propagation();
            match out.effect {
                Some(FontPickerKeyEffect::FocusSearch) => focus_search(e),
                Some(FontPickerKeyEffect::Close) => {
                    emit(&on_event, FontPickerEvent::PopupChange(false))
                }
                Some(FontPickerKeyEffect::Select(f)) => emit(&on_event, FontPickerEvent::Select(f)),
                Some(FontPickerKeyEffect::Hover(f)) => emit(&on_event, FontPickerEvent::Hover(f)),
                None => {}
            }
        }
    };

    let arrow = Element::new("span").child(
        Element::svg("svg")
            .attr("width", "20")
            .attr("height", "10")
            .attr("viewBox", "0 0 30 10")
            .attr("preserveAspectRatio", "none")
            .style("fill", "var(--popup-bg-color)")
            .style("filter", "drop-shadow(rgba(0, 0, 0, 0.05) 0px 3px 2px)")
            .style("display", "block")
            .child(Element::svg("polygon").attr("points", "0,0 30,0 15,10")),
    );
    let content = Element::new("div")
        .attr("class", "focus-visible-none properties-content")
        .attr("data-prevent-outside-click", "true")
        .attr("data-state", "open")
        .attr("id", props.popup_id.as_str())
        .attr("role", "dialog")
        .attr("tabindex", "-1")
        .style(
            "--radix-popover-content-transform-origin",
            "var(--radix-popper-transform-origin)",
        )
        .style(
            "--radix-popover-content-available-width",
            "var(--radix-popper-available-width)",
        )
        .style(
            "--radix-popover-content-available-height",
            "var(--radix-popper-available-height)",
        )
        .style(
            "--radix-popover-trigger-width",
            "var(--radix-popper-anchor-width)",
        )
        .style(
            "--radix-popover-trigger-height",
            "var(--radix-popper-anchor-height)",
        )
        .style("z-index", "var(--zIndex-ui-styles-popup)")
        .style_opt("margin-left", props.phone.then_some("0.5rem"))
        // radix's DismissableLayer: a layer under a modal one (the strip's
        // context menu) takes no pointer events
        .style_opt(
            "pointer-events",
            (props.customizable() && props.top_picks_menu.is_some()).then_some("none"),
        )
        .on("keydown", keydown)
        .on("pointerleave", props.handler(FontPickerEvent::Leave))
        .child(island(
            IslandProps {
                padding: Some(3.0),
                style: vec![("width".into(), "15rem".into())],
                ..IslandProps::default()
            },
            body,
        ))
        .child(arrow)
        // radix's FocusScope focuses the first tabbable element as it opens
        .on_mount(|content| {
            let target = content
                .query_selector("input, [tabindex=\"0\"]")
                .ok()
                .flatten()
                .unwrap_or_else(|| content.clone());
            if let Some(h) = target.dyn_ref::<HtmlElement>() {
                let _ = h.focus();
            }
        });
    let trigger_id = props.popup_id.clone();
    let below = props.phone;
    Element::new("div")
        .attr("data-radix-popper-content-wrapper", "")
        .child(content)
        .on_mount(move |wrapper| place_popup(wrapper, &trigger_id, below))
        .into()
}

/// Shift+F inside the popup: back to the search box.
fn focus_search(e: &Event) {
    let content = e
        .current_target()
        .and_then(|t| t.dyn_into::<web_sys::Element>().ok());
    if let Some(input) = content
        .and_then(|c| c.query_selector(".QuickSearch__input").ok().flatten())
        .and_then(|i| i.dyn_into::<HtmlElement>().ok())
    {
        let _ = input.focus();
    }
}

/// Places the popup beside its trigger once mounted, as the colour
/// picker's is (radix's `side="right"`, `align="start"`, below on a
/// phone).
fn place_popup(wrapper: &web_sys::Element, trigger_id: &str, below: bool) {
    let Some(document) = wrapper.owner_document() else {
        return;
    };
    let selector = format!("[aria-controls=\"{trigger_id}\"]");
    if let Ok(Some(trigger)) = document.query_selector(&selector) {
        place_beside(wrapper, &trigger, below);
    }
}

/// `FontPicker` (`FontPicker.tsx:212-303`): the popup when open (portaled
/// into the editor container, which radix does before the picker's own
/// element), then the picker: the top-picks strip and a separator unless
/// compact, and the trigger.
///
/// While customisable, the strip's context menu follows when open
/// (portaled into the container, and radix hides the rest from assistive
/// technology meanwhile), and the drag and drop is told the picks and
/// whom to tell of a drop.
pub fn font_picker(props: &FontPickerProps) -> Vec<Node> {
    let compact = props.compact();
    let customizable = props.customizable();
    if let Some(dnd) = &props.dnd {
        dnd.set_enabled(customizable);
        dnd.set_picks(top_picks(props.state.top_picks.as_deref()));
        let on_event = props.on_event.clone();
        dnd.set_listener(Some(Rc::new(move |event| {
            emit(
                &on_event,
                match event {
                    TopPicksDndEvent::PicksChange(picks) => {
                        FontPickerEvent::TopPicksChange(Some(picks))
                    }
                    TopPicksDndEvent::StateChanged => FontPickerEvent::DragChange,
                },
            );
        })));
    }
    let container = Element::new("div")
        .attr("role", "dialog")
        .attr("aria-modal", "true")
        .attr(
            "class",
            class_names([
                ("FontPicker__container", true),
                ("FontPicker__container--compact", compact),
            ]),
        )
        .child_opt((!compact).then(|| top_picks_strip(props)))
        .child_opt((!compact).then(button_separator))
        .child(trigger(props));
    let mut out = Vec::new();
    if props.state.is_open() {
        out.push(popup(props));
    }
    out.push(container.into());
    if let (true, Some(at)) = (customizable, props.top_picks_menu) {
        let emit_on = |event: FontPickerEvent| -> Rc<dyn Fn()> {
            let on_event = props.on_event.clone();
            Rc::new(move || emit(&on_event, event.clone()))
        };
        out = hide_others(out);
        out.push(context_menu(
            font_picker_text("fontList.resetTopPicks"),
            props.customized(),
            at,
            emit_on(FontPickerEvent::TopPicksChange(None)),
            emit_on(FontPickerEvent::TopPicksMenu(None)),
        ));
    }
    out
}
