#!/usr/bin/env python3
"""Glyph-advance fixture for excali-text's font tests (ex-302).

For every vendored face in crates/excali-text/src/font_faces_table.rs this
reads the font file with fontTools (an implementation independent of the
port's WOFF2 decoder and table parser) and records its unitsPerEm, the
advance of glyph 0 (.notdef) and the advance of up to eight sample code
points. A sample is a code point the face's cmap maps inside its
unicode-range and that the browser would draw with this face: among the
family's faces of the same weight, the last registered one whose range and
cmap cover it (CSS Fonts 4, unicode-range). The Rust tests check that a
single character measures advance * size / unitsPerEm through FontStore.

  advances.py write   regenerate crates/excali-text/tests/fixtures/font-advances.json
  advances.py check   exit 1 if the committed fixture differs

Needs fontTools with brotli (for WOFF2): pip install fonttools==4.60.2 brotli==1.2.0.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TABLE = ROOT / "crates" / "excali-text" / "src" / "font_faces_table.rs"
FONTS = ROOT / "fonts"
OUT = ROOT / "crates" / "excali-text" / "tests" / "fixtures" / "font-advances.json"
SAMPLES = 8

ROW = re.compile(
    r'FontFaceDescriptor \{ family: "([^"]+)", upstream: (?:Some\("[^"]*"\)|None), '
    r'vendored: (?:Some\("([^"]*)"\)|None), unicode_range: (?:Some\("([^"]*)"\)|None), '
    r'weight: (?:Some\("([^"]*)"\)|None) \}'
)


def parse_range(value: str | None) -> list[tuple[int, int]]:
    if value is None:
        return [(0, 0x10FFFF)]
    out = []
    for part in value.split(","):
        part = part.strip()[2:]
        if "-" in part:
            a, b = part.split("-")
            out.append((int(a, 16), int(b, 16)))
        elif "?" in part:
            out.append((int(part.replace("?", "0"), 16), int(part.replace("?", "f"), 16)))
        else:
            out.append((int(part, 16), int(part, 16)))
    return out


def in_range(ranges: list[tuple[int, int]], cp: int) -> bool:
    return any(a <= cp <= b for a, b in ranges)


def faces() -> list[dict]:
    from fontTools.ttLib import TTFont

    out = []
    for family, vendored, urange, weight in ROW.findall(TABLE.read_text()):
        if not vendored:
            continue
        font = TTFont(FONTS / vendored)
        cmap = {cp: g for cp, g in font.getBestCmap().items() if g != ".notdef"}
        hmtx = font["hmtx"].metrics
        out.append({
            "family": family,
            "file": vendored,
            "weight": int(weight or 400),
            "ranges": parse_range(urange or None),
            "units_per_em": font["head"].unitsPerEm,
            "notdef_advance": hmtx[font.getGlyphOrder()[0]][0],
            "cmap": cmap,
            "hmtx": hmtx,
        })
    return out


def build() -> dict:
    all_faces = faces()
    result = []
    for i, face in enumerate(all_faces):
        siblings = [f for f in all_faces if f["family"] == face["family"] and f["weight"] == face["weight"]]
        later = siblings[siblings.index(face) + 1:]
        drawn = [
            cp for cp in sorted(face["cmap"])
            if in_range(face["ranges"], cp)
            and not any(in_range(f["ranges"], cp) and cp in f["cmap"] for f in later)
        ]
        step = max(1, len(drawn) // SAMPLES)
        picks = drawn[::step][:SAMPLES]
        result.append({
            "family": face["family"],
            "file": face["file"],
            "weight": face["weight"],
            "unitsPerEm": face["units_per_em"],
            "notdefAdvance": face["notdef_advance"],
            "advances": [[cp, face["hmtx"][face["cmap"][cp]][0]] for cp in picks],
        })
    return {
        "description": (
            "unitsPerEm, .notdef advance and sample glyph advances of every vendored face, "
            "read with fontTools; generated by scripts/fonts/advances.py."
        ),
        "faces": result,
    }


def render(data: dict) -> str:
    return json.dumps(data, indent=1, ensure_ascii=True) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] not in ("write", "check"):
        print(__doc__, file=sys.stderr)
        return 2
    data = build()
    text = render(data)
    if argv[1] == "write":
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)} ({len(data['faces'])} faces)")
        return 0
    if not OUT.is_file() or OUT.read_text() != text:
        print(f"{OUT.relative_to(ROOT)} is stale; run scripts/fonts/advances.py write", file=sys.stderr)
        return 1
    print("font advance fixture OK")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
