//! The convert element type popup (ex-535) against upstream's own
//! `ConvertElementTypePopup` rendered by React into jsdom.
//!
//! Fixture: `tests/fixtures/convert-popup.json`, written by
//! `tools/goldens/convert-popup.mjs` from the pinned checkout: per case the
//! scene, the selection, the app state keys over the defaults, and the DOM
//! (`{tag, attrs, style, children}`, icons as `{icon: name}`). The
//! stylesheet is the same generator's.

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::rc::Rc;

use excali_core::app_state::AppState;
use excali_core::element::Element as SceneElement;
use excali_editor::convert_element_type::{ConvertElementTypePopup, ConvertibleType};
use excali_editor::scene::Scene;
use excali_scene::shape::Theme;
use excali_ui::convert_popup::{convert_popup, CONVERT_POPUP_CSS};
use excali_ui::dom::Node;
use serde_json::{json, Map, Value};

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/convert-popup.json")).unwrap()
}

fn tree(node: &Node) -> Value {
    match node {
        Node::Text(text) => Value::String(text.clone()),
        Node::Element(el) => {
            let attrs: BTreeMap<_, _> = el
                .attributes()
                .iter()
                .map(|(k, v)| (k.clone(), Value::String(v.clone())))
                .collect();
            let style: BTreeMap<_, _> = el
                .style_properties()
                .iter()
                .map(|(k, v)| (k.clone(), Value::String(v.clone())))
                .collect();
            let children: Vec<Value> = el.children().iter().map(tree).collect();
            json!({ "tag": el.tag(), "attrs": attrs, "style": style, "children": children })
        }
    }
}

/// An `{icon: name}` of the fixture as the icon's own tree.
fn expand(v: &Value) -> Value {
    match v {
        Value::Object(o) if o.contains_key("icon") => {
            let name = o["icon"].as_str().unwrap();
            let icon = excali_ui::icons::icon(name).unwrap_or_else(|| panic!("no icon {name}"));
            tree(&Node::Element(icon.element(Theme::Light).unwrap()))
        }
        Value::Object(o) => Value::Object(o.iter().map(|(k, x)| (k.clone(), expand(x))).collect()),
        Value::Array(a) => Value::Array(a.iter().map(expand).collect()),
        _ => v.clone(),
    }
}

fn app_state(case: &Value) -> AppState {
    let mut state = AppState::default();
    state.insert("offsetLeft", json!(0));
    state.insert("offsetTop", json!(0));
    for (k, v) in case["appState"].as_object().unwrap() {
        state.insert(k.clone(), v.clone());
    }
    let ids: Map<String, Value> = case["selected"]
        .as_array()
        .unwrap()
        .iter()
        .map(|id| (id.as_str().unwrap().to_owned(), Value::Bool(true)))
        .collect();
    state.insert("selectedElementIds", Value::Object(ids));
    state
}

fn scene(case: &Value) -> Scene {
    Scene::new(
        case["elements"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| SceneElement::from_map(e.as_object().unwrap().clone()).unwrap())
            .collect(),
    )
}

#[test]
fn popup_matches_upstream() {
    let f = fixture();
    let cases = f["cases"].as_array().unwrap();
    assert!(cases.len() >= 12);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let panel = ConvertElementTypePopup::panel(&scene(case), &app_state(case))
            .unwrap_or_else(|| panic!("{name}: no panel"));
        let got = tree(&Node::Element(convert_popup(&panel, None)));
        let want = expand(&case["dom"][0]);
        assert_eq!(got, want, "{name}");
    }
}

#[test]
fn a_button_names_its_type() {
    let f = fixture();
    let case = &f["cases"][6];
    assert_eq!(case["name"], "line");
    let panel = ConvertElementTypePopup::panel(&scene(case), &app_state(case)).unwrap();
    let picked: Rc<RefCell<Vec<ConvertibleType>>> = Rc::default();
    let sink = picked.clone();
    let popup = convert_popup(
        &panel,
        Some(Rc::new(move |kind| sink.borrow_mut().push(kind))),
    );
    // the buttons carry their type in order, each bound to its click
    let ids: Vec<String> = popup
        .children()
        .iter()
        .filter_map(|c| match c {
            Node::Element(b) => b.attribute("data-testid").map(str::to_owned),
            Node::Text(_) => None,
        })
        .collect();
    assert_eq!(
        ids,
        [
            "toolbar-line",
            "toolbar-sharpArrow",
            "toolbar-curvedArrow",
            "toolbar-elbowArrow"
        ]
    );
    assert!(picked.borrow().is_empty());
}

#[test]
fn stylesheet_is_upstreams() {
    assert!(CONVERT_POPUP_CSS.starts_with("/* Generated by tools/goldens/convert-popup.mjs"));
    assert!(CONVERT_POPUP_CSS.contains(".excalidraw .ConvertElementTypePopup {"));
    assert!(CONVERT_POPUP_CSS
        .contains(".excalidraw .ConvertElementTypePopup:focus {\n  outline: none;"));
}
