//! The search menu: upstream's `SearchMenu` (`components/SearchMenu.tsx`),
//! the content of the default sidebar's search tab
//! ([`crate::library_sidebar::LibrarySidebarProps::search_menu`]), and
//! `actionToggleSearchMenu` (`actions/actionToggleSearchMenu.ts`), which
//! Ctrl/Cmd+F runs.
//!
//! Layout (research `ui-design-system.md` §3.6, `SearchMenu.tsx:340-519`):
//! the search field, the match count with the next and previous buttons
//! (or "No matches found..."), then the matches in two groups, "Frames"
//! (frame names) before "Texts", each under its title; the focused match
//! is highlighted and scrolls itself into view.
//!
//! [`search_menu`] builds the DOM for a [`SearchMenuState`] (the menu's
//! atoms, `searchQueryAtom` and `searchItemInFocusAtom`, and its React
//! state); what the user does comes back as [`SearchMenuEvent`]s, which
//! the host runs through [`update`], and window keys through
//! [`key_down`]. Each returns the [`SearchEffect`]s upstream's handlers and
//! effects have, in their order: app state patches (`searchMatches`,
//! `openSidebar`), the focused match's functional update
//! ([`focus_search_matches`]), the viewport navigation to the focused match
//! ([`SearchEffect::SetViewport`], `app.viewport.setViewport` with a 300 ms
//! animation and the UI's offsets), focusing the search field, and
//! [`SearchEffect::ScheduleSearch`]: `handleSearch` is debounced by
//! [`SEARCH_DEBOUNCE_MS`], so the host (re)starts a timer that calls
//! [`run_pending`]. [`mount`] and [`unmount`] are the component's mount and
//! cleanup effects; [`sync`] its search effect when the scene changes.
//!
//! Positions in texts are UTF-16 code units, as JavaScript counts them.
//! Text is measured through a [`TextMetricsProvider`].
//!
//! Not here: drawing the matches on the interactive canvas
//! (`renderer/interactiveScene.ts`, `renderSearchMatches`).

use std::rc::Rc;

use excali_core::element::{Element as SceneElement, ElementKind, FontFamily, TextAlign};
use excali_editor::viewport::{viewport_coords_to_scene_coords, Fit, Offsets, ViewportState};
use excali_scene::export::get_frame_like_title;
use excali_text::font_metadata::{get_font_string, get_line_height};
use excali_text::text_measurements::{measure_text, normalize_text, TextMetricsProvider};
use serde_json::{json, Map, Value};

use crate::dom::{class_names, Element, Node};
use crate::icons;
use crate::library_sidebar::{CANVAS_SEARCH_TAB, DEFAULT_SIDEBAR_NAME};
use crate::primitives::{button, text_field, ButtonProps, TextFieldProps, TextFieldValue};
use excali_scene::shape::Theme;

/// SearchMenu.scss, compiled (generated by `tools/goldens/search-menu.mjs`).
pub const SEARCH_MENU_CSS: &str = include_str!("search_menu.css");

/// The `data-excali-ui` value of the `<style>` holding [`SEARCH_MENU_CSS`].
const STYLESHEET_ID: &str = "search-menu";

/// `SEARCH_DEBOUNCE` (`SearchMenu.tsx:61`): `handleSearch`'s debounce.
pub const SEARCH_DEBOUNCE_MS: u32 = 350;

/// `CLASSES.SEARCH_MENU_INPUT_WRAPPER` (`common/src/constants.ts:115`).
pub const SEARCH_MENU_INPUT_WRAPPER: &str = "layer-ui__search-inputWrapper";

/// `FONT_SIZE_LEGIBILITY_THRESHOLD` (`SearchMenu.tsx:226`).
const FONT_SIZE_LEGIBILITY_THRESHOLD: f64 = 14.0;

/// `FRAME_STYLE.nameFontSize` and `strokeWidth` (`common/src/constants.ts`).
const FRAME_NAME_FONT_SIZE: f64 = 14.0;
const FRAME_STROKE_WIDTH: f64 = 2.0;

/// Adds [`SEARCH_MENU_CSS`] to `document`'s head once, after the library
/// sidebar's stylesheet (and the primitives' it installs first).
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::library_sidebar::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(SEARCH_MENU_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let sidebar = document.query_selector("style[data-excali-ui=\"library-sidebar\"]")?;
    let next = sidebar.and_then(|s| s.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings the menu reads (`locales/en.json`); the key itself
/// for any other.
pub fn search_text(key: &str) -> &str {
    match key {
        "search.title" => "Find on canvas",
        "search.noMatch" => "No matches found...",
        "search.singleResult" => "result",
        "search.multipleResults" => "results",
        "search.placeholder" => "Find text on canvas...",
        "search.frames" => "Frames",
        "search.texts" => "Texts",
        other => other,
    }
}

// -- the toggle -------------------------------------------------------------------

/// What `actionToggleSearchMenu.perform` does.
#[derive(Debug, Clone, PartialEq)]
pub enum SearchToggle {
    /// A dialog is open: nothing (`false`).
    None,
    /// The search tab is open: its field is focused and selected (`false`).
    FocusInput,
    /// The app state keys to set (`openSidebar` on the search tab,
    /// `openDialog: null`), captured eventually.
    Open(Map<String, Value>),
}

/// `actionToggleSearchMenu.perform` (`actionToggleSearchMenu.ts:26-51`).
pub fn toggle_search_menu(app_state: &Map<String, Value>) -> SearchToggle {
    if app_state.get("openDialog").is_some_and(|d| !d.is_null()) {
        return SearchToggle::None;
    }
    let open = app_state.get("openSidebar");
    let on_search = open.and_then(|o| o.get("name")).and_then(Value::as_str)
        == Some(DEFAULT_SIDEBAR_NAME)
        && open.and_then(|o| o.get("tab")).and_then(Value::as_str) == Some(CANVAS_SEARCH_TAB);
    if on_search {
        return SearchToggle::FocusInput;
    }
    let mut patch = Map::new();
    patch.insert(
        "openSidebar".into(),
        json!({ "name": DEFAULT_SIDEBAR_NAME, "tab": CANVAS_SEARCH_TAB }),
    );
    patch.insert("openDialog".into(), Value::Null);
    SearchToggle::Open(patch)
}

// -- UTF-16 helpers ---------------------------------------------------------------

fn units(s: &str) -> Vec<u16> {
    s.encode_utf16().collect()
}

fn string(units: &[u16]) -> String {
    String::from_utf16_lossy(units)
}

/// `String.prototype.slice(start, end)` on code units, clamped.
fn slice(units: &[u16], start: usize, end: usize) -> &[u16] {
    let end = end.min(units.len());
    let start = start.min(end);
    &units[start..end]
}

/// ECMAScript's `\s`: white space and line terminators.
fn is_js_space(u: u16) -> bool {
    matches!(
        u,
        0x09..=0x0d
            | 0x20
            | 0xa0
            | 0x1680
            | 0x2000..=0x200a
            | 0x2028
            | 0x2029
            | 0x202f
            | 0x205f
            | 0x3000
            | 0xfeff
    )
}

/// `text.split(/\s+/)`.
fn split_whitespace(text: &[u16]) -> Vec<&[u16]> {
    let mut out = Vec::new();
    let mut start = 0;
    let mut i = 0;
    while i < text.len() {
        if is_js_space(text[i]) {
            out.push(&text[start..i]);
            while i < text.len() && is_js_space(text[i]) {
                i += 1;
            }
            start = i;
        } else {
            i += 1;
        }
    }
    out.push(&text[start..]);
    out
}

fn join(words: &[&[u16]], sep: u16) -> Vec<u16> {
    let mut out = Vec::new();
    for (i, w) in words.iter().enumerate() {
        if i > 0 {
            out.push(sep);
        }
        out.extend_from_slice(w);
    }
    out
}

/// `Canonicalize` of a case-insensitive, non-unicode RegExp: the code
/// unit upper-cased when that is one code unit and does not map a
/// non-ASCII unit to ASCII.
fn canonicalize(u: u16) -> u16 {
    let Some(c) = char::from_u32(u32::from(u)) else {
        return u;
    };
    let mut upper = c.to_uppercase();
    let (Some(first), None) = (upper.next(), upper.next()) else {
        return u;
    };
    let mut buf = [0u16; 2];
    let encoded = first.encode_utf16(&mut buf);
    if encoded.len() != 1 {
        return u;
    }
    let cu = encoded[0];
    if u >= 128 && cu < 128 {
        return u;
    }
    cu
}

/// The start of every match of `new RegExp(escape(query), "gi")` in
/// `text`, as `regex.exec` finds them one after another.
fn find_matches(text: &[u16], query: &[u16]) -> Vec<usize> {
    let mut out = Vec::new();
    if query.is_empty() {
        return out;
    }
    let q: Vec<u16> = query.iter().map(|&u| canonicalize(u)).collect();
    let mut i = 0;
    while i + q.len() <= text.len() {
        if text[i..i + q.len()]
            .iter()
            .zip(&q)
            .all(|(&a, &b)| canonicalize(a) == b)
        {
            out.push(i);
            i += q.len();
        } else {
            i += 1;
        }
    }
    out
}

// -- the search -------------------------------------------------------------------

/// A match's preview (`getMatchPreview`): the words around the match, the
/// query's position in it, and whether words were left out on either side.
#[derive(Debug, Clone, PartialEq)]
pub struct MatchPreview {
    /// In UTF-16 code units.
    pub index_in_search_query: usize,
    pub preview_text: String,
    pub more_before: bool,
    pub more_after: bool,
}

/// `getMatchPreview(text, index, searchQuery)` (`SearchMenu.tsx:537-590`):
/// two words before the match (at most 20 code units) and five after.
pub fn get_match_preview(text: &str, index: usize, search_query: &str) -> MatchPreview {
    const WORDS_BEFORE: i64 = 2;
    const WORDS_AFTER: usize = 5;
    const MAX_ALLOWED_CHARS: usize = 20;
    let text = units(text);
    let query = units(search_query);

    let substr_before_query = slice(&text, 0, index);
    let words_before_query = split_whitespace(substr_before_query);
    let is_query_complete_before = substr_before_query.last() == Some(&0x20);
    let start_word_index = words_before_query.len() as i64
        - WORDS_BEFORE
        - 1
        - if is_query_complete_before { 0 } else { 1 };
    let from = if start_word_index <= 0 {
        0
    } else {
        start_word_index as usize
    };
    let mut words_before = join(
        &words_before_query[from.min(words_before_query.len())..],
        0x20,
    );
    if is_query_complete_before {
        words_before.push(0x20);
    }
    if words_before.len() > MAX_ALLOWED_CHARS {
        words_before = words_before[words_before.len() - MAX_ALLOWED_CHARS..].to_vec();
    }

    let substr_after_query = slice(&text, index + query.len(), text.len());
    let words_after = split_whitespace(substr_after_query);
    let is_query_complete_after = substr_after_query.first() != Some(&0x20);
    let take = if is_query_complete_after {
        WORDS_AFTER + 1
    } else {
        WORDS_AFTER
    };
    let mut words_after_string = Vec::new();
    if !is_query_complete_after {
        words_after_string.push(0x20);
    }
    words_after_string.extend(join(&words_after[..take.min(words_after.len())], 0x20));

    let mut preview = words_before.clone();
    preview.extend_from_slice(&query);
    preview.extend(words_after_string);
    MatchPreview {
        index_in_search_query: words_before.len(),
        preview_text: string(&preview),
        more_before: start_word_index > 0,
        more_after: words_after.len() > take,
    }
}

/// `indexOf(search, from)` on code units.
fn index_of(haystack: &[u16], needle: &[u16], from: usize) -> Option<usize> {
    if needle.is_empty() {
        return Some(from.min(haystack.len()));
    }
    (from..=haystack.len().saturating_sub(needle.len()))
        .find(|&i| i + needle.len() <= haystack.len() && haystack[i..i + needle.len()] == *needle)
}

/// `normalizeWrappedText(wrappedText, originalText)`
/// (`SearchMenu.tsx:592-625`): each wrapped line padded with the spaces
/// wrapping dropped before the next line, so positions in the original
/// text fall on the same lines.
pub fn normalize_wrapped_text(wrapped_text: &str, original_text: &str) -> String {
    let wrapped = units(wrapped_text);
    let original = units(original_text);
    let lines: Vec<&[u16]> = wrapped.split(|&u| u == 0x0a).collect();
    let mut normalized: Vec<Vec<u16>> = Vec::new();
    let mut original_index = 0usize;
    for (i, line) in lines.iter().enumerate() {
        let mut current = line.to_vec();
        if let Some(next) = lines.get(i + 1).filter(|l| !l.is_empty()) {
            // indexOf returns -1 when absent, never more than the current end
            if let Some(at) = index_of(&original, next, original_index) {
                let end = current.len() + original_index;
                if at > end {
                    current.extend(std::iter::repeat_n(0x20, at - end));
                }
            }
        }
        original_index += current.len();
        normalized.push(current);
    }
    string(&join(
        &normalized.iter().map(Vec::as_slice).collect::<Vec<_>>(),
        0x0a,
    ))
}

/// Where a match shows on the canvas (`SearchMatch["matchedLines"]`): per
/// line it spans, the offset from the element's position and the size.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MatchedLine {
    pub offset_x: f64,
    pub offset_y: f64,
    pub width: f64,
    pub height: f64,
    pub show_on_canvas: bool,
}

impl MatchedLine {
    /// As the app state holds it.
    pub fn to_json(&self) -> Value {
        json!({
            "offsetX": self.offset_x,
            "offsetY": self.offset_y,
            "width": self.width,
            "height": self.height,
            "showOnCanvas": self.show_on_canvas,
        })
    }
}

/// `getMatchedLines(textElement, searchQuery, index)`
/// (`SearchMenu.tsx:627-728`): the lines of the rendered (wrapped) text the
/// match at `index` of the original text spans, measured in the element's
/// font. Not a text element: none.
pub fn get_matched_lines(
    element: &SceneElement,
    search_query: &str,
    index: usize,
    metrics: &dyn TextMetricsProvider,
) -> Vec<MatchedLine> {
    let ElementKind::Text(text) = &element.kind else {
        return Vec::new();
    };
    let normalized = units(&normalize_wrapped_text(&text.text, &text.original_text));
    let font = get_font_string(text.font_size, text.font_family);
    let measure = |s: &[u16]| measure_text(&string(s), &font, text.line_height, metrics);

    struct Range<'a> {
        line: &'a [u16],
        start: i64,
        end: i64,
        number: usize,
    }
    let mut ranges = Vec::new();
    let mut current = 0i64;
    for (number, line) in normalized.split(|&u| u == 0x0a).enumerate() {
        let start = current;
        let end = start + line.len() as i64 - 1;
        ranges.push(Range {
            line,
            start,
            end,
            number,
        });
        current = end + 1;
    }

    let original = units(&text.original_text);
    let query_len = units(search_query).len();
    let mut start_index = index as i64;
    let mut remaining = slice(&original, index, index + query_len).to_vec();
    let mut out = Vec::new();
    for range in &ranges {
        if remaining.is_empty() {
            break;
        }
        if start_index >= range.start && start_index <= range.end {
            let capacity = (range.end + 1 - start_index) as usize;
            let text_to_start = slice(range.line, 0, (start_index - range.start) as usize);
            let matched_word = slice(&remaining, 0, capacity).to_vec();
            remaining = slice(&remaining, capacity, remaining.len()).to_vec();

            let mut offset = measure(text_to_start);
            // measureText measures "" as a space
            if text_to_start.is_empty() {
                offset.width = 0.0;
            }
            if text.text_align != TextAlign::Left && !range.line.is_empty() {
                let line_width = measure(range.line).width;
                let space_to_start = if text.text_align == TextAlign::Center {
                    (element.base.width - line_width) / 2.0
                } else {
                    element.base.width - line_width
                };
                offset.width += space_to_start;
            }
            let size = measure(&matched_word);
            out.push(MatchedLine {
                offset_x: offset.width,
                offset_y: range.number as f64 * offset.height,
                width: size.width,
                height: size.height,
                show_on_canvas: true,
            });
            start_index += capacity as i64;
        }
    }
    out
}

/// `getMatchInFrame(frame, searchQuery, index, zoomValue)`
/// (`SearchMenu.tsx:730-770`): the match in the frame's name, drawn above
/// the frame in Assistant at the name's font size; shown on the canvas
/// when it ends within the frame's zoomed width. Not a frame: none.
pub fn get_match_in_frame(
    frame: &SceneElement,
    search_query: &str,
    index: usize,
    zoom: f64,
    metrics: &dyn TextMetricsProvider,
) -> Vec<MatchedLine> {
    let Some(name) = get_frame_like_title(frame) else {
        return Vec::new();
    };
    let text = units(name);
    let query_len = units(search_query).len();
    let matched = slice(&text, index, index + query_len);
    let prefix = slice(&text, 0, index);
    let font = get_font_string(FRAME_NAME_FONT_SIZE, FontFamily::ASSISTANT);
    let line_height = get_line_height(FontFamily::ASSISTANT);
    let mut offset = measure_text(&string(prefix), &font, line_height, metrics);
    if prefix.is_empty() {
        offset.width = 0.0;
    }
    let size = measure_text(&string(matched), &font, line_height, metrics);
    vec![MatchedLine {
        offset_x: offset.width,
        offset_y: -offset.height - FRAME_STROKE_WIDTH,
        width: size.width,
        height: size.height,
        show_on_canvas: offset.width + size.width <= frame.base.width * zoom,
    }]
}

/// Which group a match is in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatchKind {
    /// A frame's (or AI frame's) name.
    Frame,
    Text,
}

/// A match (`SearchMatchItem`): the element, what was searched, where.
#[derive(Debug, Clone, PartialEq)]
pub struct SearchMatchItem {
    pub element_id: String,
    pub kind: MatchKind,
    /// The element's position and font when searched (a frame's name is
    /// drawn in Assistant at the name's size).
    pub x: f64,
    pub y: f64,
    pub font_size: f64,
    pub font_family: FontFamily,
    /// The trimmed query.
    pub search_query: String,
    /// In UTF-16 code units of the searched text.
    pub index: usize,
    pub preview: MatchPreview,
    pub matched_lines: Vec<MatchedLine>,
}

/// What a search reads: the scene, the visible elements, the view and the
/// text measurement.
pub struct SearchContext<'a> {
    /// The scene's elements; deleted ones are skipped.
    pub elements: &'a [SceneElement],
    /// `app.scene.getSceneNonce()`: a search is redone when it changes.
    pub scene_nonce: u64,
    /// The ids of `app.visibleElements`.
    pub visible_ids: &'a [String],
    /// The viewport: scroll, zoom, the canvas's CSS size and offset.
    pub view: ViewportState,
    /// `app.viewport.getOffsets()`: the UI covering the canvas plus the
    /// padding, in viewport px.
    pub padding: Offsets,
    pub metrics: &'a dyn TextMetricsProvider,
}

/// `handleSearch`'s search (`SearchMenu.tsx:776-866`), undebounced: the
/// matches of `search_query` (trimmed, case-insensitive) in the texts'
/// original text and the frames' names, each sorted by `y`, frames first;
/// and the index of the first match whose element is visible (`-1` for
/// none; `None` for an empty query).
pub fn handle_search(
    search_query: &str,
    cx: &SearchContext<'_>,
) -> (Vec<SearchMatchItem>, Option<i64>) {
    if search_query.is_empty() {
        return (Vec::new(), None);
    }
    let live: Vec<&SceneElement> = cx.elements.iter().filter(|e| !e.base.is_deleted).collect();
    let mut texts: Vec<&SceneElement> = live
        .iter()
        .copied()
        .filter(|e| matches!(e.kind, ElementKind::Text(_)))
        .collect();
    let mut frames: Vec<&SceneElement> = live
        .iter()
        .copied()
        .filter(|e| matches!(e.kind, ElementKind::Frame(_) | ElementKind::MagicFrame(_)))
        .collect();
    texts.sort_by(|a, b| a.base.y.total_cmp(&b.base.y));
    frames.sort_by(|a, b| a.base.y.total_cmp(&b.base.y));
    let query = units(search_query);

    let mut text_matches = Vec::new();
    for el in texts {
        let ElementKind::Text(t) = &el.kind else {
            continue;
        };
        for index in find_matches(&units(&t.original_text), &query) {
            let preview = get_match_preview(&t.original_text, index, search_query);
            let matched_lines = get_matched_lines(el, search_query, index, cx.metrics);
            if !matched_lines.is_empty() {
                text_matches.push(SearchMatchItem {
                    element_id: el.base.id.clone(),
                    kind: MatchKind::Text,
                    x: el.base.x,
                    y: el.base.y,
                    font_size: t.font_size,
                    font_family: t.font_family,
                    search_query: search_query.to_owned(),
                    index,
                    preview,
                    matched_lines,
                });
            }
        }
    }

    let mut frame_matches = Vec::new();
    for el in frames {
        let Some(name) = get_frame_like_title(el) else {
            continue;
        };
        for index in find_matches(&units(name), &query) {
            let preview = get_match_preview(name, index, search_query);
            let matched_lines =
                get_match_in_frame(el, search_query, index, cx.view.zoom, cx.metrics);
            frame_matches.push(SearchMatchItem {
                element_id: el.base.id.clone(),
                kind: MatchKind::Frame,
                x: el.base.x,
                y: el.base.y,
                font_size: FRAME_NAME_FONT_SIZE,
                font_family: FontFamily::ASSISTANT,
                search_query: search_query.to_owned(),
                index,
                preview,
                matched_lines,
            });
        }
    }

    let mut items = frame_matches;
    items.extend(text_matches);
    let focus = items
        .iter()
        .position(|m| cx.visible_ids.contains(&m.element_id))
        .map_or(-1, |i| i as i64);
    (items, Some(focus))
}

/// `appState.searchMatches` for a search's matches: `null` for none, else
/// no match focused.
pub fn search_matches_value(items: &[SearchMatchItem]) -> Value {
    if items.is_empty() {
        return Value::Null;
    }
    json!({
        "focusedId": null,
        "matches": items.iter().map(|m| json!({
            "id": m.element_id,
            "focus": false,
            "matchedLines": m.matched_lines.iter().map(MatchedLine::to_json).collect::<Vec<_>>(),
        })).collect::<Vec<_>>(),
    })
}

/// The focus effect's functional update (`SearchMenu.tsx:174-197`) of the
/// current `searchMatches`: the match at `focus` focused and its id
/// `focusedId`; `None` (no update) while there are no matches.
pub fn focus_search_matches(current: &Value, focus: Option<i64>) -> Option<Value> {
    let matches = current.get("matches")?.as_array()?;
    let at = focus.and_then(|i| usize::try_from(i).ok());
    let focused_id = at
        .and_then(|i| matches.get(i))
        .and_then(|m| m.get("id"))
        .filter(|id| id.as_str().is_some_and(|s| !s.is_empty()))
        .cloned()
        .unwrap_or(Value::Null);
    let matches = matches
        .iter()
        .enumerate()
        .map(|(i, m)| {
            let mut m = m.as_object().cloned().unwrap_or_default();
            m.insert("focus".into(), json!(Some(i) == at));
            Value::Object(m)
        })
        .collect::<Vec<_>>();
    Some(json!({ "focusedId": focused_id, "matches": matches }))
}

// -- the state machine ------------------------------------------------------------

/// A debounced search waiting for its timer.
#[derive(Debug, Clone, PartialEq)]
pub struct PendingSearch {
    /// The trimmed query.
    pub query: String,
    /// From the field's `onChange` (sets the focus and ends `isSearching`),
    /// or from the search effect.
    pub from_input: bool,
}

/// The menu's state: `searchQueryAtom` (kept while the menu is closed),
/// `searchItemInFocusAtom`, and the component's state and refs.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SearchMenuState {
    /// `searchQueryAtom`: the field's value.
    pub input: String,
    /// `searchItemInFocusAtom`: the focused match; `-1` when a search found
    /// no visible match.
    pub focus_index: Option<i64>,
    pub is_searching: bool,
    /// `searchMatches.items`.
    pub matches: Vec<SearchMatchItem>,
    /// `searchedQueryRef`.
    pub searched_query: Option<String>,
    /// `lastSceneNonceRef`.
    pub last_scene_nonce: Option<u64>,
    /// The debounced `handleSearch` call waiting.
    pub pending: Option<PendingSearch>,
}

impl SearchMenuState {
    /// `searchQuery`: the field's value trimmed.
    pub fn search_query(&self) -> &str {
        excali_core::color::js_trim(&self.input)
    }
}

/// What the menu's handlers and effects do, in order.
#[derive(Debug, Clone, PartialEq)]
pub enum SearchEffect {
    /// `setAppState` with these keys.
    SetAppState(Map<String, Value>),
    /// `setAppState` with [`focus_search_matches`] of the current
    /// `searchMatches` (nothing when it returns `None`).
    FocusMatches(Option<i64>),
    /// `app.viewport.setViewport({target, fit, animation: {duration: 300},
    /// offsets: {ui: true}})`: `target` is the focused match's bounds.
    SetViewport { target: [f64; 4], fit: Fit },
    /// Focus and select the search field.
    FocusInput,
    /// (Re)start the [`SEARCH_DEBOUNCE_MS`] timer that calls
    /// [`run_pending`].
    ScheduleSearch,
}

/// What the user does in the menu.
#[derive(Debug, Clone, PartialEq)]
pub enum SearchMenuEvent {
    /// The field's value.
    Input(String),
    /// The next button (`collapseDownIcon`), Enter or ArrowDown.
    Next,
    /// The previous button (`upIcon`) or ArrowUp.
    Previous,
    /// A match clicked, by its index among all matches.
    Select(usize),
}

fn search_matches_patch(items: &[SearchMatchItem]) -> SearchEffect {
    let mut patch = Map::new();
    patch.insert("searchMatches".into(), search_matches_value(items));
    SearchEffect::SetAppState(patch)
}

/// The search effect (`SearchMenu.tsx:103-138`): unless a search from the
/// field is under way, a query or scene the matches are not for schedules
/// a search.
fn search_effect(state: &mut SearchMenuState, scene_nonce: u64) -> Vec<SearchEffect> {
    if state.is_searching {
        return Vec::new();
    }
    let query = state.search_query().to_owned();
    let stale = state.searched_query.as_deref() != Some(query.as_str())
        || state.last_scene_nonce != Some(scene_nonce);
    let scheduled = state
        .pending
        .as_ref()
        .is_some_and(|p| p.query == query && !p.from_input);
    if !stale || scheduled {
        return Vec::new();
    }
    state.searched_query = None;
    state.pending = Some(PendingSearch {
        query,
        from_input: false,
    });
    vec![SearchEffect::ScheduleSearch]
}

/// The menu mounted (in the search tab): its search effect runs.
pub fn mount(state: &mut SearchMenuState, scene_nonce: u64) -> Vec<SearchEffect> {
    search_effect(state, scene_nonce)
}

/// The scene changed while the menu is open: its search effect runs again.
pub fn sync(state: &mut SearchMenuState, scene_nonce: u64) -> Vec<SearchEffect> {
    search_effect(state, scene_nonce)
}

/// The cleanup when the menu unmounts (`SearchMenu.tsx:260-271`): no
/// focus, the refs reset, no matches in the app state. The query stays.
pub fn unmount(state: &mut SearchMenuState) -> Vec<SearchEffect> {
    state.focus_index = None;
    state.searched_query = None;
    state.last_scene_nonce = None;
    state.is_searching = false;
    state.pending = None;
    let mut patch = Map::new();
    patch.insert("searchMatches".into(), Value::Null);
    vec![SearchEffect::SetAppState(patch)]
}

/// The debounce timer fired: `handleSearch` runs with the last call's
/// query, then its callback and the effects of what it changed.
pub fn run_pending(state: &mut SearchMenuState, cx: &SearchContext<'_>) -> Vec<SearchEffect> {
    let Some(pending) = state.pending.take() else {
        return Vec::new();
    };
    let (items, focus) = handle_search(&pending.query, cx);
    let mut effects = vec![search_matches_patch(&items)];
    state.matches = items;
    state.searched_query = Some(pending.query);
    state.last_scene_nonce = Some(cx.scene_nonce);
    let before = state.focus_index;
    if pending.from_input {
        state.focus_index = focus;
        state.is_searching = false;
    }
    if state.focus_index != before {
        effects.push(SearchEffect::FocusMatches(state.focus_index));
    }
    // the viewport effect runs for the new matches
    effects.extend(navigate(state, cx));
    effects.extend(search_effect(state, cx.scene_nonce));
    effects
}

/// The viewport effect (`SearchMenu.tsx:199-258`): the focused match,
/// laid out as a text of the query in the match's font, navigated to when
/// it is not wholly in view or too small to read at this zoom.
fn navigate(state: &SearchMenuState, cx: &SearchContext<'_>) -> Vec<SearchEffect> {
    let Some(item) = state
        .focus_index
        .and_then(|i| usize::try_from(i).ok())
        .and_then(|i| state.matches.get(i))
    else {
        return Vec::new();
    };
    let first = item.matched_lines.first();
    let x = item.x + first.map_or(0.0, |l| l.offset_x);
    let y = item.y + first.map_or(0.0, |l| l.offset_y);
    let font = get_font_string(item.font_size, item.font_family);
    let size = measure_text(
        &normalize_text(&item.search_query),
        &font,
        get_line_height(item.font_family),
        cx.metrics,
    );
    let target = [x, y, x + size.width, y + size.height];
    let zoom = cx.view.zoom;
    let is_text_tiny = item.font_size * zoom < FONT_SIZE_LEGIBILITY_THRESHOLD;
    let p = &cx.padding;
    let v = &cx.view;
    let (left, top) =
        viewport_coords_to_scene_coords(v.offset_left + p.left, v.offset_top + p.top, v);
    let (right, bottom) = viewport_coords_to_scene_coords(
        v.offset_left + v.width - p.right,
        v.offset_top + v.height - p.bottom,
        v,
    );
    let in_view =
        target[0] >= left && target[1] >= top && target[2] <= right && target[3] <= bottom;
    if in_view && !is_text_tiny {
        return Vec::new();
    }
    let fit = if is_text_tiny && item.font_size < FONT_SIZE_LEGIBILITY_THRESHOLD {
        Fit::Contain
    } else {
        Fit::ScaleDown
    };
    vec![SearchEffect::SetViewport { target, fit }]
}

/// The focus set: when it changed, the focus effect and the viewport
/// effect run.
fn set_focus(
    state: &mut SearchMenuState,
    focus: Option<i64>,
    cx: &SearchContext<'_>,
) -> Vec<SearchEffect> {
    if state.focus_index == focus {
        return Vec::new();
    }
    state.focus_index = focus;
    let mut effects = vec![SearchEffect::FocusMatches(focus)];
    effects.extend(navigate(state, cx));
    effects
}

/// `goToNextItem` (`SearchMenu.tsx:140-150`).
fn next_index(state: &SearchMenuState) -> Option<Option<i64>> {
    let n = state.matches.len() as i64;
    (n > 0).then(|| Some(state.focus_index.map_or(0, |i| (i + 1) % n)))
}

/// `goToPreviousItem` (`SearchMenu.tsx:152-164`).
fn previous_index(state: &SearchMenuState) -> Option<Option<i64>> {
    let n = state.matches.len() as i64;
    (n > 0).then(|| {
        Some(
            state
                .focus_index
                .map_or(0, |i| if i - 1 < 0 { n - 1 } else { i - 1 }),
        )
    })
}

/// Runs a [`SearchMenuEvent`]: updates the state and returns the effects.
pub fn update(
    state: &mut SearchMenuState,
    event: SearchMenuEvent,
    cx: &SearchContext<'_>,
) -> Vec<SearchEffect> {
    match event {
        SearchMenuEvent::Input(value) => {
            state.input = value;
            state.is_searching = true;
            state.pending = Some(PendingSearch {
                query: state.search_query().to_owned(),
                from_input: true,
            });
            vec![SearchEffect::ScheduleSearch]
        }
        SearchMenuEvent::Next => match next_index(state) {
            Some(focus) => set_focus(state, focus, cx),
            None => Vec::new(),
        },
        SearchMenuEvent::Previous => match previous_index(state) {
            Some(focus) => set_focus(state, focus, cx),
            None => Vec::new(),
        },
        SearchMenuEvent::Select(index) => set_focus(state, Some(index as i64), cx),
    }
}

/// A window `keydown` as the menu's capture listener reads it.
#[derive(Debug, Clone, Copy)]
pub struct SearchKey<'a> {
    pub key: &'a str,
    /// Cmd on Apple platforms, Ctrl elsewhere.
    pub ctrl_or_cmd: bool,
    /// The target is inside `.layer-ui__search`.
    pub in_search: bool,
    /// The search field has the focus.
    pub input_focused: bool,
    /// `appState.openDialog` / `openPopup` are set.
    pub open_dialog: bool,
    pub open_popup: bool,
}

/// What [`key_down`] did.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SearchKeyOutcome {
    pub prevent_default: bool,
    pub stop_propagation: bool,
    pub effects: Vec<SearchEffect>,
}

/// The menu's window `keydown` listener (capture phase,
/// `SearchMenu.tsx:279-338`): Escape closes the sidebar (no dialog or
/// popup open); Ctrl/Cmd+F is taken from the browser and focuses the
/// field; in the menu, Enter and ArrowDown go to the next match, ArrowUp
/// to the previous.
pub fn key_down(
    state: &mut SearchMenuState,
    key: &SearchKey<'_>,
    cx: &SearchContext<'_>,
) -> SearchKeyOutcome {
    let mut out = SearchKeyOutcome::default();
    if key.key == "Escape" && !key.open_dialog && !key.open_popup {
        out.prevent_default = true;
        out.stop_propagation = true;
        let mut patch = Map::new();
        patch.insert("openSidebar".into(), Value::Null);
        out.effects.push(SearchEffect::SetAppState(patch));
        return out;
    }
    if key.ctrl_or_cmd && key.key == "f" {
        out.prevent_default = true;
        out.stop_propagation = true;
        if key.open_dialog {
            return out;
        }
        if !key.input_focused {
            out.effects.push(SearchEffect::FocusInput);
        }
    }
    if key.in_search && !state.matches.is_empty() {
        let step = match key.key {
            "Enter" | "ArrowDown" => next_index(state),
            "ArrowUp" => previous_index(state),
            _ => None,
        };
        if let Some(focus) = step {
            out.stop_propagation = true;
            out.effects.extend(set_focus(state, focus, cx));
        }
    }
    out
}

// -- the DOM ------------------------------------------------------------------------

/// How the search field takes the focus when the menu is built.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputFocus {
    /// Not at all.
    None,
    /// Focused with its value selected (`selectOnRender`, the first build).
    Select,
    /// Focused with this selection (in UTF-16 code units): a build that
    /// replaces a field that had the focus.
    Restore(u32, u32),
}

/// A handler of the menu's events.
pub type OnSearchMenuEvent = Rc<dyn Fn(SearchMenuEvent)>;

/// [`search_menu`]'s props.
pub struct SearchMenuProps<'a> {
    pub state: &'a SearchMenuState,
    pub focus: InputFocus,
    pub on_event: Option<OnSearchMenuEvent>,
}

fn emit(on_event: &Option<OnSearchMenuEvent>, event: SearchMenuEvent) {
    if let Some(f) = on_event {
        f(event);
    }
}

fn icon(icon: &icons::Icon) -> Node {
    icon.element(Theme::Light)
        .map(Node::Element)
        .unwrap_or_else(|| Node::text(""))
}

/// `<div class="layer-ui__search">` (`SearchMenu.tsx:346-432`): the field,
/// the count and navigation, the matches.
pub fn search_menu(props: SearchMenuProps<'_>) -> Element {
    let state = props.state;
    let on_change = props.on_event.clone();
    let mut field = text_field(TextFieldProps {
        value: TextFieldValue::Controlled(state.input.clone()),
        on_change: Some(Rc::new(move |value| {
            emit(&on_change, SearchMenuEvent::Input(value))
        })),
        class_name: Some(SEARCH_MENU_INPUT_WRAPPER.into()),
        placeholder: Some(search_text("search.placeholder").into()),
        icon: Some(icon(&icons::searchIcon)),
        select_on_render: props.focus == InputFocus::Select,
        ..TextFieldProps::default()
    });
    if let InputFocus::Restore(start, end) = props.focus {
        field = field.on_mount(move |el| {
            let Ok(Some(input)) = el.query_selector("input") else {
                return;
            };
            if let Some(input) = wasm_bindgen::JsCast::dyn_ref::<web_sys::HtmlInputElement>(&input)
            {
                let _ = input.focus();
                let _ = input.set_selection_range(start, end);
            }
        });
    }
    let header = Element::new("div")
        .attr("class", "layer-ui__search-header")
        .child(field);

    let n = state.matches.len();
    let mut count = Element::new("div").attr("class", "layer-ui__search-count");
    if n > 0 {
        let match_count = format!(
            "{n} {}",
            if n == 1 {
                search_text("search.singleResult")
            } else {
                search_text("search.multipleResults")
            }
        );
        let label = match state.focus_index {
            Some(i) if i > -1 => Element::new("div")
                .child(Node::text((i + 1).to_string()))
                .child(Node::text(" / "))
                .child(Node::text(match_count)),
            _ => Element::new("div").child(Node::text(match_count)),
        };
        let nav = |event: SearchMenuEvent, glyph: &icons::Icon| {
            let on_event = props.on_event.clone();
            button(
                ButtonProps {
                    class_name: "result-nav-btn".into(),
                    on_select: Some(Rc::new(move || emit(&on_event, event.clone()))),
                    ..ButtonProps::default()
                },
                vec![icon(glyph)],
            )
        };
        count = count.child(label).child(
            Element::new("div")
                .attr("class", "result-nav")
                .child(nav(SearchMenuEvent::Next, &icons::collapseDownIcon))
                .child(nav(SearchMenuEvent::Previous, &icons::upIcon)),
        );
    } else if !state.search_query().is_empty()
        && state
            .searched_query
            .as_deref()
            .is_some_and(|q| !q.is_empty())
    {
        count = count.child(
            Element::new("div")
                .style("margin", "1rem auto")
                .child(Node::text(search_text("search.noMatch"))),
        );
    }

    Element::new("div")
        .attr("class", "layer-ui__search")
        .child(header)
        .child(count)
        .child(match_list(&props))
}

/// `MatchList` (`SearchMenu.tsx:465-521`): the frames' group, a divider
/// when texts follow, the texts' group.
fn match_list(props: &SearchMenuProps<'_>) -> Element {
    let state = props.state;
    let frames: Vec<&SearchMatchItem> = state
        .matches
        .iter()
        .filter(|m| m.kind == MatchKind::Frame)
        .collect();
    let texts: Vec<&SearchMatchItem> = state
        .matches
        .iter()
        .filter(|m| m.kind == MatchKind::Text)
        .collect();
    let group = |title_icon: &icons::Icon, title: &str| {
        Element::new("div")
            .attr("class", "layer-ui__search-result-container")
            .child(
                Element::new("div")
                    .attr("class", "layer-ui__search-result-title")
                    .child(
                        Element::new("div")
                            .attr("class", "title-icon")
                            .child(icon(title_icon)),
                    )
                    .child(Element::new("div").child(Node::text(title))),
            )
    };
    let mut list = Element::new("div");
    if !frames.is_empty() {
        let mut container = group(&icons::frameToolIcon, search_text("search.frames"));
        for (i, m) in frames.iter().enumerate() {
            container = container.child(list_item(props, m, i));
        }
        if !texts.is_empty() {
            container = container.child(Element::new("div").attr("class", "layer-ui__divider"));
        }
        list = list.child(container);
    }
    if !texts.is_empty() {
        let mut container = group(&icons::TextIcon, search_text("search.texts"));
        for (i, m) in texts.iter().enumerate() {
            container = container.child(list_item(props, m, i + frames.len()));
        }
        list = list.child(container);
    }
    list
}

/// `ListItem` (`SearchMenu.tsx:434-463`): the preview with the query in
/// bold, `...` where words were left out; the focused one is `active` and
/// scrolls itself into view.
fn list_item(props: &SearchMenuProps<'_>, m: &SearchMatchItem, index: usize) -> Element {
    let preview = units(&m.preview.preview_text);
    let at = m.preview.index_in_search_query;
    // MatchList renders again only for new matches or a new focus
    // (`areEqual`), so with the query they were searched with
    let len = units(&m.search_query).len();
    let highlighted = props.state.focus_index == Some(index as i64);
    let before = string(slice(&preview, 0, at));
    let query = string(slice(&preview, at, at + len));
    let after = string(slice(&preview, at + len, preview.len()));
    let mut text = Element::new("div").attr("class", "preview-text");
    for part in [if m.preview.more_before { "..." } else { "" }, &before] {
        if !part.is_empty() {
            text = text.child(Node::text(part));
        }
    }
    let mut bold = Element::new("b");
    if !query.is_empty() {
        bold = bold.child(Node::text(query));
    }
    text = text.child(bold);
    for part in [
        after.as_str(),
        if m.preview.more_after { "..." } else { "" },
    ] {
        if !part.is_empty() {
            text = text.child(Node::text(part));
        }
    }
    let on_event = props.on_event.clone();
    let mut el = Element::new("div")
        .attr("tabindex", "-1")
        .attr(
            "class",
            class_names([("layer-ui__result-item", true), ("active", highlighted)]),
        )
        .child(text)
        .on("click", move |_| {
            emit(&on_event, SearchMenuEvent::Select(index))
        });
    if highlighted {
        el = el.on_mount(scroll_into_view);
    }
    el
}

/// `scrollIntoView({ behavior: "auto", block: "nearest" })`.
fn scroll_into_view(el: &web_sys::Element) {
    let options = web_sys::ScrollIntoViewOptions::new();
    let _ = js_sys::Reflect::set(&options, &"behavior".into(), &"auto".into());
    options.set_block(web_sys::ScrollLogicalPosition::Nearest);
    el.scroll_into_view_with_scroll_into_view_options(&options);
}
