//! [`ActionName`]: the `ActionName` union (`actions/types.ts:45-144`).

/// An action's name: the 99 members of upstream's `ActionName` union, in
/// declaration order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ActionName {
    Copy,
    Cut,
    Paste,
    CopyAsPng,
    CopyAsSvg,
    CopyText,
    SendBackward,
    BringForward,
    SendToBack,
    BringToFront,
    CopyStyles,
    SelectAll,
    PasteStyles,
    GridMode,
    ZenMode,
    ObjectsSnapMode,
    ArrowBinding,
    MidpointSnapping,
    Stats,
    ChangeStrokeColor,
    ChangeBackgroundColor,
    ChangeBucketFillBackgroundColor,
    ChangeFillStyle,
    ChangeStrokeWidth,
    ChangeSloppiness,
    ChangeFreedrawMode,
    ChangeStrokeStyle,
    ChangeArrowhead,
    ChangeArrowType,
    ChangeArrowProperties,
    ChangeOpacity,
    ChangeFontSize,
    Undo,
    Redo,
    Finalize,
    ChangeProjectName,
    ChangeExportBackground,
    ChangeExportEmbedScene,
    ChangeExportScale,
    SaveToActiveFile,
    SaveFileToDisk,
    LoadScene,
    DuplicateSelection,
    DeleteSelectedElements,
    ChangeViewBackgroundColor,
    ClearCanvas,
    ZoomIn,
    ZoomOut,
    ResetZoom,
    ZoomToFit,
    ZoomToFitSelection,
    ZoomToFitSelectionInViewport,
    ChangeFontFamily,
    ChangeTextAlign,
    ChangeVerticalAlign,
    ToggleFullScreen,
    ToggleShortcuts,
    Group,
    Ungroup,
    GoToCollaborator,
    AddToLibrary,
    ChangeRoundness,
    AlignTop,
    AlignBottom,
    AlignLeft,
    AlignRight,
    AlignVerticallyCentered,
    AlignHorizontallyCentered,
    DistributeHorizontally,
    DistributeVertically,
    FlipHorizontal,
    FlipVertical,
    Deselect,
    ViewMode,
    ExportWithDarkMode,
    ToggleTheme,
    IncreaseFontSize,
    DecreaseFontSize,
    UnbindText,
    Hyperlink,
    BindText,
    UnlockAllElements,
    ToggleElementLock,
    ToggleLinearEditor,
    SelectAllElementsInFrame,
    RemoveAllElementsFromFrame,
    UpdateFrameRendering,
    CreateContainerFromText,
    WrapTextInContainer,
    CommandPalette,
    AutoResize,
    ElementStats,
    SearchMenu,
    CopyElementLink,
    LinkToElement,
    CropEditor,
    WrapSelectionInFrame,
    ToggleShapeSwitch,
    TogglePolygon,
}

impl ActionName {
    /// Every action name, in the union's declaration order.
    pub const ALL: [ActionName; 99] = [
        ActionName::Copy,
        ActionName::Cut,
        ActionName::Paste,
        ActionName::CopyAsPng,
        ActionName::CopyAsSvg,
        ActionName::CopyText,
        ActionName::SendBackward,
        ActionName::BringForward,
        ActionName::SendToBack,
        ActionName::BringToFront,
        ActionName::CopyStyles,
        ActionName::SelectAll,
        ActionName::PasteStyles,
        ActionName::GridMode,
        ActionName::ZenMode,
        ActionName::ObjectsSnapMode,
        ActionName::ArrowBinding,
        ActionName::MidpointSnapping,
        ActionName::Stats,
        ActionName::ChangeStrokeColor,
        ActionName::ChangeBackgroundColor,
        ActionName::ChangeBucketFillBackgroundColor,
        ActionName::ChangeFillStyle,
        ActionName::ChangeStrokeWidth,
        ActionName::ChangeSloppiness,
        ActionName::ChangeFreedrawMode,
        ActionName::ChangeStrokeStyle,
        ActionName::ChangeArrowhead,
        ActionName::ChangeArrowType,
        ActionName::ChangeArrowProperties,
        ActionName::ChangeOpacity,
        ActionName::ChangeFontSize,
        ActionName::Undo,
        ActionName::Redo,
        ActionName::Finalize,
        ActionName::ChangeProjectName,
        ActionName::ChangeExportBackground,
        ActionName::ChangeExportEmbedScene,
        ActionName::ChangeExportScale,
        ActionName::SaveToActiveFile,
        ActionName::SaveFileToDisk,
        ActionName::LoadScene,
        ActionName::DuplicateSelection,
        ActionName::DeleteSelectedElements,
        ActionName::ChangeViewBackgroundColor,
        ActionName::ClearCanvas,
        ActionName::ZoomIn,
        ActionName::ZoomOut,
        ActionName::ResetZoom,
        ActionName::ZoomToFit,
        ActionName::ZoomToFitSelection,
        ActionName::ZoomToFitSelectionInViewport,
        ActionName::ChangeFontFamily,
        ActionName::ChangeTextAlign,
        ActionName::ChangeVerticalAlign,
        ActionName::ToggleFullScreen,
        ActionName::ToggleShortcuts,
        ActionName::Group,
        ActionName::Ungroup,
        ActionName::GoToCollaborator,
        ActionName::AddToLibrary,
        ActionName::ChangeRoundness,
        ActionName::AlignTop,
        ActionName::AlignBottom,
        ActionName::AlignLeft,
        ActionName::AlignRight,
        ActionName::AlignVerticallyCentered,
        ActionName::AlignHorizontallyCentered,
        ActionName::DistributeHorizontally,
        ActionName::DistributeVertically,
        ActionName::FlipHorizontal,
        ActionName::FlipVertical,
        ActionName::Deselect,
        ActionName::ViewMode,
        ActionName::ExportWithDarkMode,
        ActionName::ToggleTheme,
        ActionName::IncreaseFontSize,
        ActionName::DecreaseFontSize,
        ActionName::UnbindText,
        ActionName::Hyperlink,
        ActionName::BindText,
        ActionName::UnlockAllElements,
        ActionName::ToggleElementLock,
        ActionName::ToggleLinearEditor,
        ActionName::SelectAllElementsInFrame,
        ActionName::RemoveAllElementsFromFrame,
        ActionName::UpdateFrameRendering,
        ActionName::CreateContainerFromText,
        ActionName::WrapTextInContainer,
        ActionName::CommandPalette,
        ActionName::AutoResize,
        ActionName::ElementStats,
        ActionName::SearchMenu,
        ActionName::CopyElementLink,
        ActionName::LinkToElement,
        ActionName::CropEditor,
        ActionName::WrapSelectionInFrame,
        ActionName::ToggleShapeSwitch,
        ActionName::TogglePolygon,
    ];

    /// The name as upstream spells it (`action.name`).
    pub const fn as_str(self) -> &'static str {
        match self {
            ActionName::Copy => "copy",
            ActionName::Cut => "cut",
            ActionName::Paste => "paste",
            ActionName::CopyAsPng => "copyAsPng",
            ActionName::CopyAsSvg => "copyAsSvg",
            ActionName::CopyText => "copyText",
            ActionName::SendBackward => "sendBackward",
            ActionName::BringForward => "bringForward",
            ActionName::SendToBack => "sendToBack",
            ActionName::BringToFront => "bringToFront",
            ActionName::CopyStyles => "copyStyles",
            ActionName::SelectAll => "selectAll",
            ActionName::PasteStyles => "pasteStyles",
            ActionName::GridMode => "gridMode",
            ActionName::ZenMode => "zenMode",
            ActionName::ObjectsSnapMode => "objectsSnapMode",
            ActionName::ArrowBinding => "arrowBinding",
            ActionName::MidpointSnapping => "midpointSnapping",
            ActionName::Stats => "stats",
            ActionName::ChangeStrokeColor => "changeStrokeColor",
            ActionName::ChangeBackgroundColor => "changeBackgroundColor",
            ActionName::ChangeBucketFillBackgroundColor => "changeBucketFillBackgroundColor",
            ActionName::ChangeFillStyle => "changeFillStyle",
            ActionName::ChangeStrokeWidth => "changeStrokeWidth",
            ActionName::ChangeSloppiness => "changeSloppiness",
            ActionName::ChangeFreedrawMode => "changeFreedrawMode",
            ActionName::ChangeStrokeStyle => "changeStrokeStyle",
            ActionName::ChangeArrowhead => "changeArrowhead",
            ActionName::ChangeArrowType => "changeArrowType",
            ActionName::ChangeArrowProperties => "changeArrowProperties",
            ActionName::ChangeOpacity => "changeOpacity",
            ActionName::ChangeFontSize => "changeFontSize",
            ActionName::Undo => "undo",
            ActionName::Redo => "redo",
            ActionName::Finalize => "finalize",
            ActionName::ChangeProjectName => "changeProjectName",
            ActionName::ChangeExportBackground => "changeExportBackground",
            ActionName::ChangeExportEmbedScene => "changeExportEmbedScene",
            ActionName::ChangeExportScale => "changeExportScale",
            ActionName::SaveToActiveFile => "saveToActiveFile",
            ActionName::SaveFileToDisk => "saveFileToDisk",
            ActionName::LoadScene => "loadScene",
            ActionName::DuplicateSelection => "duplicateSelection",
            ActionName::DeleteSelectedElements => "deleteSelectedElements",
            ActionName::ChangeViewBackgroundColor => "changeViewBackgroundColor",
            ActionName::ClearCanvas => "clearCanvas",
            ActionName::ZoomIn => "zoomIn",
            ActionName::ZoomOut => "zoomOut",
            ActionName::ResetZoom => "resetZoom",
            ActionName::ZoomToFit => "zoomToFit",
            ActionName::ZoomToFitSelection => "zoomToFitSelection",
            ActionName::ZoomToFitSelectionInViewport => "zoomToFitSelectionInViewport",
            ActionName::ChangeFontFamily => "changeFontFamily",
            ActionName::ChangeTextAlign => "changeTextAlign",
            ActionName::ChangeVerticalAlign => "changeVerticalAlign",
            ActionName::ToggleFullScreen => "toggleFullScreen",
            ActionName::ToggleShortcuts => "toggleShortcuts",
            ActionName::Group => "group",
            ActionName::Ungroup => "ungroup",
            ActionName::GoToCollaborator => "goToCollaborator",
            ActionName::AddToLibrary => "addToLibrary",
            ActionName::ChangeRoundness => "changeRoundness",
            ActionName::AlignTop => "alignTop",
            ActionName::AlignBottom => "alignBottom",
            ActionName::AlignLeft => "alignLeft",
            ActionName::AlignRight => "alignRight",
            ActionName::AlignVerticallyCentered => "alignVerticallyCentered",
            ActionName::AlignHorizontallyCentered => "alignHorizontallyCentered",
            ActionName::DistributeHorizontally => "distributeHorizontally",
            ActionName::DistributeVertically => "distributeVertically",
            ActionName::FlipHorizontal => "flipHorizontal",
            ActionName::FlipVertical => "flipVertical",
            ActionName::Deselect => "deselect",
            ActionName::ViewMode => "viewMode",
            ActionName::ExportWithDarkMode => "exportWithDarkMode",
            ActionName::ToggleTheme => "toggleTheme",
            ActionName::IncreaseFontSize => "increaseFontSize",
            ActionName::DecreaseFontSize => "decreaseFontSize",
            ActionName::UnbindText => "unbindText",
            ActionName::Hyperlink => "hyperlink",
            ActionName::BindText => "bindText",
            ActionName::UnlockAllElements => "unlockAllElements",
            ActionName::ToggleElementLock => "toggleElementLock",
            ActionName::ToggleLinearEditor => "toggleLinearEditor",
            ActionName::SelectAllElementsInFrame => "selectAllElementsInFrame",
            ActionName::RemoveAllElementsFromFrame => "removeAllElementsFromFrame",
            ActionName::UpdateFrameRendering => "updateFrameRendering",
            ActionName::CreateContainerFromText => "createContainerFromText",
            ActionName::WrapTextInContainer => "wrapTextInContainer",
            ActionName::CommandPalette => "commandPalette",
            ActionName::AutoResize => "autoResize",
            ActionName::ElementStats => "elementStats",
            ActionName::SearchMenu => "searchMenu",
            ActionName::CopyElementLink => "copyElementLink",
            ActionName::LinkToElement => "linkToElement",
            ActionName::CropEditor => "cropEditor",
            ActionName::WrapSelectionInFrame => "wrapSelectionInFrame",
            ActionName::ToggleShapeSwitch => "toggleShapeSwitch",
            ActionName::TogglePolygon => "togglePolygon",
        }
    }

    /// The action named `name` (case-sensitive).
    pub fn from_name(name: &str) -> Option<ActionName> {
        ActionName::ALL.into_iter().find(|a| a.as_str() == name)
    }
}
