//! The capability, permissions and documentation agree with the commands.

mod support;

use std::path::Path;

use support::{capability, permission_files, CRATE};
use tauri_plugin_excali::COMMANDS;

#[test]
fn build_rs_generates_a_permission_for_every_command() {
    let build = std::fs::read_to_string(Path::new(CRATE).join("build.rs")).unwrap();
    let list = COMMANDS
        .iter()
        .map(|c| format!("\"{c}\""))
        .collect::<Vec<_>>()
        .join(", ");
    assert!(
        build.contains(&format!("const COMMANDS: &[&str] = &[{list}];")),
        "build.rs lists other commands than src/lib.rs"
    );
    for command in COMMANDS {
        let file = Path::new(CRATE)
            .join("permissions/autogenerated/commands")
            .join(format!("{command}.toml"));
        assert!(file.is_file(), "{} is missing", file.display());
    }
}

#[test]
fn the_default_permission_allows_every_command() {
    let default = permission_files()
        .into_iter()
        .find_map(|f| f.default)
        .expect("permissions/default.toml has no [default]");
    let expected: Vec<String> = COMMANDS
        .iter()
        .map(|c| format!("allow-{}", c.replace('_', "-")))
        .collect();
    assert_eq!(default.permissions, expected);
}

#[test]
fn the_capability_grants_the_default_permission_to_the_main_window() {
    let capability = capability();
    assert_eq!(capability.identifier, "excali");
    assert_eq!(capability.windows, ["main"]);
    let permissions: Vec<String> = capability
        .permissions
        .iter()
        .map(|p| p.identifier().get().to_owned())
        .collect();
    assert_eq!(permissions, ["excali:default"]);
}

#[test]
fn the_tauri_page_documents_every_command() {
    let page =
        std::fs::read_to_string(Path::new(CRATE).join("../../site/content/architecture/tauri.md"))
            .unwrap();
    for command in COMMANDS {
        assert!(
            page.contains(&format!("| `{command}` |")),
            "site/content/architecture/tauri.md has no row for {command}"
        );
    }
    let capability =
        std::fs::read_to_string(Path::new(CRATE).join("capabilities/excali.json")).unwrap();
    assert!(
        page.contains(capability.trim()),
        "site/content/architecture/tauri.md does not quote capabilities/excali.json"
    );
}
