//! The footer: the desktop `Footer` (`components/footer/Footer.tsx`) with
//! `ZoomActions`, `UndoRedoActions` and `ExitZenModeButton`
//! (`components/Actions.tsx:877-929`), the `HelpButton`
//! (`components/HelpButton.tsx`), and the panels the zoom and history
//! actions render there (`actions/actionCanvas.tsx` `actionZoomIn`,
//! `actionZoomOut`, `actionResetZoom`; `actions/actionHistory.tsx`
//! `createUndoAction`, `createRedoAction`).
//!
//! Layout (`Footer.tsx:37-91`, research `ui-design-system.md` §3.4): on
//! the left, in the "Canvas actions" section, zoom out, the zoom level
//! (reset zoom) and zoom in, then undo and redo; the host's centre content
//! (`FooterCenterTunnel`); on the right the welcome screen's help hint and
//! the help button; last the exit-zen-mode button, shown by the host's
//! `showExitZenModeBtn` (`disable-zen-mode--visible`). Zen mode fades the
//! left, undo/redo and right groups out in place (the transition classes);
//! view mode drops undo/redo; the zoom actions need navigation enabled.
//!
//! [`footer`] builds the DOM upstream leaves (`tests/footer.rs` holds every
//! case of `tests/fixtures/footer.json` to it); a click on a control
//! reports its [`FooterControl`], whose [`FooterControl::action`] the host
//! runs: the zoom actions with `excali_editor::viewport::perform_zoom_action`
//! ([`FooterControl::zoom_action`]), undo and redo with the history, help
//! with [`toggle_shortcuts`] and exit zen with [`toggle_zen_mode`]. The
//! styles are the footer's rules of upstream's stylesheets ([`FOOTER_CSS`]);
//! zen mode's own look needs the container's `excalidraw--zen-mode` class,
//! which is the host's.
//!
//! Not ported here: the phone layout's footer (`MobileMenu.tsx`), where the
//! history buttons take `MOBILE_ACTION_BUTTON_BG`, and the actions'
//! analytics.

use std::rc::Rc;

use excali_core::app_state::AppState;
use excali_editor::actions::{get_shortcut_key, ActionName, KeyLabels};
use excali_editor::viewport::ZoomAction;
use excali_scene::display::{number_to_string, to_fixed};
use excali_scene::shape::Theme;
use serde_json::{json, Value};

use crate::dom::{class_names, Element, Node};
use crate::icons;
use crate::primitives::{
    icon_button, stack_col, stack_row, tooltip, Align, IconButtonProps, StackProps, TooltipProps,
};

/// The footer's rules of upstream's `css/styles.scss`,
/// `components/LayerUI.scss`, `components/Actions.scss`,
/// `components/footer/FooterCenter.scss` and `css/app.scss`, compiled
/// (generated by `tools/goldens/footer.mjs`).
pub const FOOTER_CSS: &str = include_str!("footer.css");

/// The `data-excali-ui` value of the `<style>` holding [`FOOTER_CSS`].
const STYLESHEET_ID: &str = "footer";

/// Adds [`FOOTER_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(FOOTER_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// `CLASSES.ZOOM_ACTIONS` (`common/src/constants.ts:114`).
pub const ZOOM_ACTIONS: &str = "zoom-actions";

/// The English strings of the footer (`locales/en.json`); the key itself
/// for any other.
pub fn footer_text(key: &str) -> &str {
    match key {
        "buttons.zoomIn" => "Zoom in",
        "buttons.zoomOut" => "Zoom out",
        "buttons.resetZoom" => "Reset zoom",
        "buttons.undo" => "Undo",
        "buttons.redo" => "Redo",
        "buttons.exitZenMode" => "Exit zen mode",
        "helpDialog.title" => "Help",
        "headings.canvasActions" => "Canvas actions",
        other => other,
    }
}

/// The zoom level the reset button shows: `${(zoom * 100).toFixed(0)}%`.
pub fn reset_zoom_label(zoom: f64) -> String {
    format!("{}%", number_to_string(to_fixed(zoom * 100.0, 0)))
}

/// The footer's controls, in order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FooterControl {
    ZoomOut,
    ResetZoom,
    ZoomIn,
    Undo,
    Redo,
    Help,
    ExitZenMode,
}

impl FooterControl {
    /// Every control, in the footer's order.
    pub const ALL: [FooterControl; 7] = [
        FooterControl::ZoomOut,
        FooterControl::ResetZoom,
        FooterControl::ZoomIn,
        FooterControl::Undo,
        FooterControl::Redo,
        FooterControl::Help,
        FooterControl::ExitZenMode,
    ];

    /// The control's name, as the fixture records it.
    pub fn name(self) -> &'static str {
        match self {
            FooterControl::ZoomOut => "zoomOut",
            FooterControl::ResetZoom => "resetZoom",
            FooterControl::ZoomIn => "zoomIn",
            FooterControl::Undo => "undo",
            FooterControl::Redo => "redo",
            FooterControl::Help => "help",
            FooterControl::ExitZenMode => "exitZenMode",
        }
    }

    /// The action a click runs: the panel's `updateData` (zoom, history) or
    /// `actionManager.executeAction` (`actionShortcuts`,
    /// `actionToggleZenMode`).
    pub fn action(self) -> ActionName {
        match self {
            FooterControl::ZoomOut => ActionName::ZoomOut,
            FooterControl::ResetZoom => ActionName::ResetZoom,
            FooterControl::ZoomIn => ActionName::ZoomIn,
            FooterControl::Undo => ActionName::Undo,
            FooterControl::Redo => ActionName::Redo,
            FooterControl::Help => ActionName::ToggleShortcuts,
            FooterControl::ExitZenMode => ActionName::ZenMode,
        }
    }

    /// The zoom action a zoom control runs.
    pub fn zoom_action(self) -> Option<ZoomAction> {
        match self {
            FooterControl::ZoomOut => Some(ZoomAction::ZoomOut),
            FooterControl::ResetZoom => Some(ZoomAction::ResetZoom),
            FooterControl::ZoomIn => Some(ZoomAction::ZoomIn),
            _ => None,
        }
    }

    /// The button's `aria-label`; the exit-zen-mode button has none.
    pub fn aria_label(self) -> Option<&'static str> {
        Some(footer_text(match self {
            FooterControl::ZoomOut => "buttons.zoomOut",
            FooterControl::ResetZoom => "buttons.resetZoom",
            FooterControl::ZoomIn => "buttons.zoomIn",
            FooterControl::Undo => "buttons.undo",
            FooterControl::Redo => "buttons.redo",
            FooterControl::Help => "helpDialog.title",
            FooterControl::ExitZenMode => return None,
        }))
    }

    /// The label of the control's tooltip (shown after a delay); the
    /// exit-zen-mode button has none. `is_darwin` picks Cmd over Ctrl
    /// (`getShortcutKey`).
    pub fn tooltip(self, is_darwin: bool) -> Option<String> {
        let label = self.aria_label()?;
        let key = |shortcut: &str| get_shortcut_key(shortcut, is_darwin, &KeyLabels::EN);
        Some(match self {
            FooterControl::ZoomIn => format!("{label} — {}", key("CtrlOrCmd++")),
            FooterControl::ZoomOut => format!("{label} — {}", key("CtrlOrCmd+-")),
            FooterControl::Help => format!("{label} — ?"),
            _ => label.to_owned(),
        })
    }
}

/// Receives the control a click was on.
pub type OnFooterEvent = Rc<dyn Fn(FooterControl)>;

/// The footer's props.
#[derive(Clone)]
pub struct FooterProps {
    /// `appState.zoom.value`.
    pub zoom: f64,
    /// `appState.zenModeEnabled`.
    pub zen_mode: bool,
    /// `appState.viewModeEnabled`.
    pub view_mode: bool,
    /// `history.isUndoStackEmpty`.
    pub undo_stack_empty: bool,
    /// `history.isRedoStackEmpty`.
    pub redo_stack_empty: bool,
    /// `app.isNavigationEnabled()`.
    pub navigation_enabled: bool,
    /// `showExitZenModeBtn`.
    pub show_exit_zen_mode_button: bool,
    /// `renderWelcomeScreen`.
    pub render_welcome_screen: bool,
    /// `defaultUIEnabled`.
    pub default_ui_enabled: bool,
    /// `zoomUIEnabled`.
    pub zoom_ui_enabled: bool,
    /// A Mac: the zoom tooltips read Cmd.
    pub is_darwin: bool,
    /// The editor container's id (`useExcalidrawContainer().id`), prefixing
    /// the section heading's id.
    pub container_id: String,
    /// `FooterCenterTunnel.Out`.
    pub footer_center: Option<Node>,
    /// `WelcomeScreenHelpHintTunnel.Out`, while the welcome screen renders.
    pub welcome_screen_help_hint: Option<Node>,
    pub on_event: Option<OnFooterEvent>,
}

impl Default for FooterProps {
    fn default() -> FooterProps {
        FooterProps {
            zoom: 1.0,
            zen_mode: false,
            view_mode: false,
            undo_stack_empty: true,
            redo_stack_empty: true,
            navigation_enabled: true,
            show_exit_zen_mode_button: false,
            render_welcome_screen: false,
            default_ui_enabled: true,
            zoom_ui_enabled: true,
            is_darwin: false,
            container_id: String::new(),
            footer_center: None,
            welcome_screen_help_hint: None,
            on_event: None,
        }
    }
}

fn icon_node(name: &str) -> Node {
    let icon = icons::icon(name).unwrap_or_else(|| panic!("icons.tsx has no {name}"));
    Node::Element(
        icon.element(Theme::Light)
            .unwrap_or_else(|| panic!("{name} is a path list")),
    )
}

fn on_click(props: &FooterProps, control: FooterControl) -> impl Fn(&web_sys::Event) + 'static {
    let on_event = props.on_event.clone();
    move |_| {
        if let Some(f) = &on_event {
            f(control);
        }
    }
}

fn with_tooltip(
    props: &FooterProps,
    control: FooterControl,
    class_name: Option<&str>,
    style: Vec<(String, String)>,
    child: Element,
) -> Node {
    let label = control.tooltip(props.is_darwin).unwrap_or_default();
    Node::Element(
        tooltip(
            TooltipProps {
                label,
                class_name: class_name.map(str::to_owned),
                style,
                delay: true,
                ..TooltipProps::default()
            },
            vec![Node::Element(child)],
        )
        .expect("an enabled tooltip"),
    )
}

/// A zoom or history panel's `IconButton`.
fn action_button(
    props: &FooterProps,
    control: FooterControl,
    class_name: &str,
    icon: Option<&str>,
    disabled: bool,
    test_id: Option<&str>,
    children: Vec<Node>,
) -> Element {
    let handler = on_click(props, control);
    icon_button(IconButtonProps {
        icon: icon.map(icon_node),
        aria_label: control.aria_label().unwrap_or_default().into(),
        class_name: class_name.into(),
        disabled,
        test_id: test_id.map(str::to_owned),
        children,
        on_click: Some(Rc::new(move |e: &web_sys::Event| handler(e))),
        ..IconButtonProps::default()
    })
}

/// `ZoomActions` (`Actions.tsx:877-889`) with the three zoom panels.
fn zoom_actions(props: &FooterProps) -> Node {
    use excali_core::constants::{MAX_ZOOM, MIN_ZOOM};
    let zoom_out = with_tooltip(
        props,
        FooterControl::ZoomOut,
        Some("zoom-out-button-wrapper"),
        Vec::new(),
        action_button(
            props,
            FooterControl::ZoomOut,
            "zoom-out-button zoom-button",
            Some("ZoomOutIcon"),
            props.zoom <= MIN_ZOOM,
            None,
            Vec::new(),
        ),
    );
    let reset = with_tooltip(
        props,
        FooterControl::ResetZoom,
        Some("reset-zoom-button-wrapper"),
        vec![("height".into(), "100%".into())],
        action_button(
            props,
            FooterControl::ResetZoom,
            "reset-zoom-button zoom-button",
            None,
            false,
            None,
            vec![Node::text(reset_zoom_label(props.zoom))],
        ),
    );
    let zoom_in = with_tooltip(
        props,
        FooterControl::ZoomIn,
        Some("zoom-in-button-wrapper"),
        Vec::new(),
        action_button(
            props,
            FooterControl::ZoomIn,
            "zoom-in-button zoom-button",
            Some("ZoomInIcon"),
            props.zoom >= MAX_ZOOM,
            None,
            Vec::new(),
        ),
    );
    Node::Element(stack_col(
        StackProps {
            gap: Some(1.0),
            class_name: Some(ZOOM_ACTIONS.into()),
            ..StackProps::default()
        },
        vec![Node::Element(stack_row(
            StackProps {
                align: Some(Align::Center),
                ..StackProps::default()
            },
            vec![zoom_out, reset, zoom_in],
        ))],
    ))
}

/// `UndoRedoActions` (`Actions.tsx:891-910`) with the history panels.
fn undo_redo_actions(props: &FooterProps) -> Node {
    let class = class_names([
        ("zen-mode-transition", true),
        (
            "layer-ui__wrapper__footer-left--transition-bottom",
            props.zen_mode,
        ),
    ]);
    let history = |control: FooterControl, container: &str, icon: &str, empty: bool, id: &str| {
        Node::Element(
            Element::new("div")
                .attr("class", container)
                .child(with_tooltip(
                    props,
                    control,
                    None,
                    Vec::new(),
                    action_button(props, control, "", Some(icon), empty, Some(id), Vec::new()),
                )),
        )
    };
    Node::Element(
        Element::new("div")
            .attr("class", format!("undo-redo-buttons {class}"))
            .child(history(
                FooterControl::Undo,
                "undo-button-container",
                "UndoIcon",
                props.undo_stack_empty,
                "button-undo",
            ))
            .child(history(
                FooterControl::Redo,
                "redo-button-container",
                "RedoIcon",
                props.redo_stack_empty,
                "button-redo",
            )),
    )
}

/// `Section heading="canvasActions"` (`Section.tsx`).
fn canvas_actions_section(props: &FooterProps, children: Vec<Node>) -> Node {
    let title_id = format!("{}-canvasActions-title", props.container_id);
    Node::Element(
        Element::new("section")
            .attr("aria-labelledby", title_id.clone())
            .child(
                Element::new("h2")
                    .attr("class", "visually-hidden")
                    .attr("id", title_id)
                    .child(footer_text("headings.canvasActions")),
            )
            .children_from(children),
    )
}

/// `HelpButton` (`HelpButton.tsx`).
fn help_button(props: &FooterProps) -> Node {
    let handler = on_click(props, FooterControl::Help);
    with_tooltip(
        props,
        FooterControl::Help,
        None,
        Vec::new(),
        Element::new("button")
            .attr("class", "help-icon")
            .attr("type", "button")
            .attr("aria-label", footer_text("helpDialog.title"))
            .child(icon_node("HelpIcon"))
            .on("click", handler),
    )
}

/// `ExitZenModeButton` (`Actions.tsx:912-929`).
fn exit_zen_mode_button(props: &FooterProps) -> Node {
    Node::Element(
        Element::new("button")
            .attr("type", "button")
            .attr(
                "class",
                class_names([
                    ("disable-zen-mode", true),
                    ("disable-zen-mode--visible", props.show_exit_zen_mode_button),
                ]),
            )
            .child(footer_text("buttons.exitZenMode"))
            .on("click", on_click(props, FooterControl::ExitZenMode)),
    )
}

/// The desktop footer (`Footer`, `Footer.tsx:14-96`).
pub fn footer(props: FooterProps) -> Element {
    let zoom = props.zoom_ui_enabled && props.navigation_enabled;
    let mut el = Element::new("footer").attr("role", "contentinfo").attr(
        "class",
        "layer-ui__wrapper__footer App-menu App-menu_bottom",
    );
    if props.default_ui_enabled || zoom {
        let mut section = Vec::new();
        if zoom {
            section.push(zoom_actions(&props));
        }
        if props.default_ui_enabled && !props.view_mode {
            section.push(undo_redo_actions(&props));
        }
        el = el.child(
            Element::new("div")
                .attr(
                    "class",
                    class_names([
                        ("layer-ui__wrapper__footer-left zen-mode-transition", true),
                        (
                            "layer-ui__wrapper__footer-left--transition-left",
                            props.zen_mode,
                        ),
                    ]),
                )
                .child(stack_col(
                    StackProps {
                        gap: Some(2.0),
                        ..StackProps::default()
                    },
                    vec![canvas_actions_section(&props, section)],
                )),
        );
    }
    el = el.child_opt(props.footer_center.clone());
    if props.default_ui_enabled || props.render_welcome_screen {
        let mut inner = Element::new("div").style("position", "relative");
        if props.render_welcome_screen {
            inner = inner.child_opt(props.welcome_screen_help_hint.clone());
        }
        if props.default_ui_enabled {
            inner = inner.child(help_button(&props));
        }
        el = el.child(
            Element::new("div")
                .attr(
                    "class",
                    class_names([
                        ("layer-ui__wrapper__footer-right zen-mode-transition", true),
                        ("transition-right", props.zen_mode),
                    ]),
                )
                .child(inner),
        );
    }
    if props.default_ui_enabled {
        el = el.child(exit_zen_mode_button(&props));
    }
    el
}

/// `actionShortcuts.perform` (`actions/actionMenu.tsx:9-35`): opens the
/// help dialog, or closes it when open, closing any menu and popup.
/// Returns whether the container takes the focus back (`focusContainer`,
/// when the dialog closes).
pub fn toggle_shortcuts(app_state: &mut AppState) -> bool {
    let open = app_state
        .get("openDialog")
        .and_then(|d| d.get("name"))
        .and_then(Value::as_str)
        == Some("help");
    app_state.insert(
        "openDialog",
        if open {
            Value::Null
        } else {
            json!({ "name": "help" })
        },
    );
    app_state.insert("openMenu", Value::Null);
    app_state.insert("openPopup", Value::Null);
    open
}

/// `actionToggleZenMode.perform` (`actions/actionToggleZenMode.tsx:18-26`).
pub fn toggle_zen_mode(app_state: &mut AppState) {
    let on = app_state
        .get("zenModeEnabled")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    app_state.insert("zenModeEnabled", Value::Bool(!on));
}
