//! The colour picker (`components/ColorPicker/*`): the top-picks strip
//! (`TopPicks.tsx`), the trigger swatch that shows the active colour, and
//! the popup (`ColorPicker.tsx`, `Picker.tsx`) with the most-used custom
//! colours (`CustomColorList.tsx`), the 5×3 palette with its q…b hotkeys
//! (`PickerColorList.tsx`), the shades of the picked hue (`ShadeList.tsx`),
//! the hex input with the eye-dropper trigger (`ColorInput.tsx`), and the
//! keyboard map ([`keyboard`], `keyboardNavHandlers.ts`); the eye dropper
//! itself is [`eye_dropper`] (`EyeDropper.tsx`).
//!
//! [`color_picker`] builds the DOM for the host's state
//! ([`ColorPickerProps`]); what the user does comes back as
//! [`ColorPickerEvent`]s, which the host applies with the state functions
//! here ([`toggle_popup`], [`close_popup`], [`toggle_eye_dropper`],
//! [`escape`], [`change_hex_input`]) and renders again. The palettes and
//! colour helpers are `packages/common/src/colors.ts`'s, in
//! [`excali_core::color`]. With `customizableTopPicks`
//! ([`ColorPickerProps::customizable_top_picks`], `colorTopPicksDnD.ts`)
//! a swatch or the trigger dragged onto the strip pins its colour, a pick
//! dragged along the strip reorders it (both through
//! [`crate::top_picks_dnd`]), the strip's context menu resets it and the
//! popup shows the tip; the host keeps the picks in
//! `appState.colorTopPicks` ([`color_top_picks_update`]).
//!
//! See `site/content/research/ui-design-system.md` sections 2 and 3.12.

pub mod eye_dropper;
pub mod keyboard;

use std::rc::Rc;

use excali_core::color::{
    apply_dark_mode_filter, color_to_hex, is_color_dark, is_transparent, js_trim,
    normalize_input_color, PaletteColor, PaletteEntry, COLOR_OUTLINE_CONTRAST_THRESHOLD,
    DEFAULT_CANVAS_BACKGROUND_PICKS, DEFAULT_ELEMENT_BACKGROUND_COLOR_INDEX,
    DEFAULT_ELEMENT_BACKGROUND_PICKS, DEFAULT_ELEMENT_STROKE_COLOR_INDEX,
    DEFAULT_ELEMENT_STROKE_PICKS, MAX_CUSTOM_COLORS_USED_IN_CANVAS,
};
use excali_core::element::Element as SceneElement;
use excali_editor::actions::{get_shortcut_key, KeyLabels};
use excali_scene::shape::Theme;
use wasm_bindgen::JsCast;
use web_sys::{Event, HtmlElement, HtmlInputElement, KeyboardEvent};

use crate::dom::{class_names, Element, Node};
use crate::icons;
use crate::primitives::{island, IslandProps};
use crate::top_picks_dnd::{
    context_menu, context_menu_trigger, get_top_pick_reorder_offset, hide_others,
    top_picks_dnd_outline, top_picks_tip, DragOrigin, Rect, TipReset, TopPicksDnd,
    TopPicksDndEvent,
};

pub use eye_dropper::{
    eye_dropper_cursor, position_element_beside_cursor, preview_border_color, sample_point,
    sampled_colors, ContainerRect, EyeDropper, EyeDropperProps,
};
pub use keyboard::{
    color_picker_key_nav_handler, KeyInput, KeyNavEffect, KeyNavOutcome, KeyNavState,
};

/// `ColorPicker.scss` and `EyeDropper.scss`, compiled (generated by
/// `tools/goldens/color-picker.mjs`).
pub const COLOR_PICKER_CSS: &str = include_str!("color_picker.css");

/// The `data-excali-ui` value of the `<style>` holding [`COLOR_PICKER_CSS`].
const STYLESHEET_ID: &str = "color-picker";

/// Adds [`COLOR_PICKER_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(COLOR_PICKER_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    crate::top_picks_dnd::install_stylesheet(document)
}

/// The English strings of the picker (`locales/en.json`); the key itself
/// for any other.
pub fn color_picker_text(key: &str) -> &str {
    match key {
        "labels.stroke" => "Stroke",
        "labels.background" => "Background",
        "labels.canvasBackground" => "Canvas background",
        "labels.colorPicker" => "Color picker",
        "labels.showStroke" => "Show stroke color picker",
        "labels.showBackground" => "Show background color picker",
        "labels.eyeDropper" => "Pick color from canvas",
        "colorPicker.color" => "Color",
        "colorPicker.mostUsedCustomColors" => "Most used custom colors",
        "colorPicker.colors" => "Colors",
        "colorPicker.shades" => "Shades",
        "colorPicker.hexCode" => "Hex code",
        "colorPicker.noShades" => "No shades available for this color",
        "colorPicker.invalidColor" => "Not a valid color",
        "colorPicker.invalidHexLength" => "Hex code must be 3, 4, 6, or 8 characters",
        "colorPicker.topPicksTip" => "Tip: drag any color onto your top picks to pin it",
        "colorPicker.resetTopPicks" => "Reset to default top picks",
        "buttons.reset" => "Reset",
        "colors.transparent" => "Transparent",
        "colors.black" => "Black",
        "colors.white" => "White",
        "colors.gray" => "Gray",
        "colors.red" => "Red",
        "colors.pink" => "Pink",
        "colors.grape" => "Grape",
        "colors.violet" => "Violet",
        "colors.blue" => "Blue",
        "colors.cyan" => "Cyan",
        "colors.teal" => "Teal",
        "colors.green" => "Green",
        "colors.yellow" => "Yellow",
        "colors.orange" => "Orange",
        "colors.bronze" => "Bronze",
        other => other,
    }
}

/// `ColorPickerType` (`colorPickerUtils.ts:104-107`): which colour a
/// picker edits; also its `appState.openPopup` value.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ColorPickerType {
    CanvasBackground,
    ElementBackground,
    ElementStroke,
}

impl ColorPickerType {
    pub fn as_str(self) -> &'static str {
        match self {
            ColorPickerType::CanvasBackground => "canvasBackground",
            ColorPickerType::ElementBackground => "elementBackground",
            ColorPickerType::ElementStroke => "elementStroke",
        }
    }

    /// The picker whose popup `open_popup` is (`isColorPickerPopup`,
    /// `ColorPicker.tsx:260-265`).
    pub fn from_popup(open_popup: &str) -> Option<ColorPickerType> {
        [
            ColorPickerType::CanvasBackground,
            ColorPickerType::ElementBackground,
            ColorPickerType::ElementStroke,
        ]
        .into_iter()
        .find(|t| t.as_str() == open_popup)
    }
}

/// `ActiveColorPickerSectionAtomType` (`colorPickerUtils.ts:95-101`): the
/// popup section the keyboard works in.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Section {
    Custom,
    BaseColors,
    Shades,
    Hex,
}

impl Section {
    pub fn as_str(self) -> &'static str {
        match self {
            Section::Custom => "custom",
            Section::BaseColors => "baseColors",
            Section::Shades => "shades",
            Section::Hex => "hex",
        }
    }
}

/// `useStylesPanelMode()`: how the styles panel is laid out.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum StylesPanelMode {
    #[default]
    Full,
    Compact,
    Mobile,
}

/// `colorPickerHotkeyBindings` (`colorPickerUtils.ts:38-42`): the palette's
/// keys, row by row.
pub const COLOR_PICKER_HOTKEY_BINDINGS: [&str; 15] = [
    "q", "w", "e", "r", "t", "a", "s", "d", "f", "g", "z", "x", "c", "v", "b",
];

/// A colour's palette entry and shade.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ColorObj {
    pub color_name: &'static str,
    /// `None` for a single colour (transparent, white, black).
    pub shade: Option<usize>,
}

/// `getColorNameAndShadeFromColor` (`colorPickerUtils.ts:12-36`): the
/// first palette entry holding `color`; `None` for no colour or one the
/// palette does not have.
pub fn get_color_name_and_shade(palette: &[PaletteEntry], color: Option<&str>) -> Option<ColorObj> {
    let color = color.filter(|c| !c.is_empty())?;
    palette.iter().find_map(|(name, value)| match value {
        PaletteColor::Shades(shades) => shades.iter().position(|s| *s == color).map(|i| ColorObj {
            color_name: name,
            shade: Some(i),
        }),
        PaletteColor::Single(c) => (*c == color).then_some(ColorObj {
            color_name: name,
            shade: None,
        }),
    })
}

/// `isCustomColor` (`colorPickerUtils.ts:44-53`): the palette does not
/// hold `color`.
pub fn is_custom_color(color: &str, palette: &[PaletteEntry]) -> bool {
    !palette.iter().any(|(_, value)| match value {
        PaletteColor::Shades(shades) => shades.contains(&color),
        PaletteColor::Single(c) => *c == color,
    })
}

/// `getMostUsedCustomColors` (`colorPickerUtils.ts:55-93`): the custom
/// (non-palette, not fully transparent) stroke or background colours of
/// the live elements, most used first (ties in first-use order), at most
/// [`MAX_CUSTOM_COLORS_USED_IN_CANVAS`]. The canvas background picker
/// reads the background colours.
pub fn get_most_used_custom_colors(
    elements: &[SceneElement],
    ty: ColorPickerType,
    palette: &[PaletteEntry],
) -> Vec<String> {
    let mut counts: Vec<(&str, usize)> = Vec::new();
    for element in elements.iter().filter(|e| !e.base.is_deleted) {
        let color = match ty {
            ColorPickerType::ElementStroke => element.base.stroke_color.as_str(),
            _ => element.base.background_color.as_str(),
        };
        if is_transparent(color) || !is_custom_color(color, palette) {
            continue;
        }
        match counts.iter_mut().find(|(c, _)| *c == color) {
            Some(entry) => entry.1 += 1,
            None => counts.push((color, 1)),
        }
    }
    // Array.prototype.sort is stable
    counts.sort_by_key(|c| std::cmp::Reverse(c.1));
    counts
        .into_iter()
        .take(MAX_CUSTOM_COLORS_USED_IN_CANVAS)
        .map(|(c, _)| c.to_owned())
        .collect()
}

/// The custom colours a picker opens with (`Picker.tsx:84-89`): none for
/// the canvas background, else [`get_most_used_custom_colors`]. Upstream
/// samples them once, when the popup opens.
pub fn picker_custom_colors(
    ty: ColorPickerType,
    elements: &[SceneElement],
    palette: &[PaletteEntry],
) -> Vec<String> {
    match ty {
        ColorPickerType::CanvasBackground => Vec::new(),
        _ => get_most_used_custom_colors(elements, ty, palette),
    }
}

/// The section the popup starts in (`Picker.tsx:103-122`, run while no
/// section is active): none for a custom colour missing from the custom
/// list, the custom list for one in it, the shades for a hue, else the
/// palette.
pub fn initial_section(
    color: Option<&str>,
    palette: &[PaletteEntry],
    custom_colors: &[String],
) -> Option<Section> {
    let is_custom = color.is_some_and(|c| !c.is_empty() && is_custom_color(c, palette));
    let listed = color.is_some_and(|c| custom_colors.iter().any(|x| x == c));
    if is_custom && !listed {
        None
    } else if is_custom {
        Some(Section::Custom)
    } else if get_color_name_and_shade(palette, color).is_some_and(|o| o.shade.is_some()) {
        Some(Section::Shades)
    } else {
        Some(Section::BaseColors)
    }
}

/// The shade the palette's hues show (`Picker.tsx:124-130`): the picked
/// colour's, else the element default's for the picker.
pub fn initial_active_shade(ty: ColorPickerType, obj: Option<&ColorObj>) -> usize {
    obj.and_then(|o| o.shade).unwrap_or(match ty {
        ColorPickerType::ElementBackground => DEFAULT_ELEMENT_BACKGROUND_COLOR_INDEX,
        _ => DEFAULT_ELEMENT_STROKE_COLOR_INDEX,
    })
}

// -- state ---------------------------------------------------------------------

/// `appState.openPopup` after the trigger is pressed
/// (`ColorPicker.tsx:462-474`): closed when this picker's popup is open,
/// else this picker's (switching from any other popup).
pub fn toggle_popup(open_popup: Option<&str>, ty: ColorPickerType) -> Option<String> {
    if open_popup == Some(ty.as_str()) {
        None
    } else {
        Some(ty.as_str().to_owned())
    }
}

/// `appState.openPopup` after the popup closes (`onClose`,
/// `ColorPicker.tsx:151-156`): cleared only while it is still this
/// picker's. The active section is cleared too.
pub fn close_popup(open_popup: Option<&str>, ty: ColorPickerType) -> Option<String> {
    if open_popup == Some(ty.as_str()) {
        None
    } else {
        open_popup.map(str::to_owned)
    }
}

/// Whether a top pick moves `openPopup` to its own picker
/// (`ColorPicker.tsx:431-443`): another colour picker's popup is open.
/// Upstream defers that update a tick so it does not overwrite the colour
/// change.
pub fn top_pick_follows_focus(open_popup: Option<&str>, ty: ColorPickerType) -> bool {
    open_popup
        .and_then(ColorPickerType::from_popup)
        .is_some_and(|open| open != ty)
}

/// `activeEyeDropperAtom`'s value (`EyeDropper.tsx:39-51`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EyeDropperState {
    /// Opened with Alt held: it stays while Alt is.
    pub keep_open_on_alt: bool,
    /// The picker whose colour it picks.
    pub picker: ColorPickerType,
}

/// `onEyeDropperToggle(force)` (`ColorPicker.tsx:181-203`): `Some(true)`
/// (Alt) opens it, or keeps it, open while Alt is held; otherwise it
/// toggles, and `Some(false)` (Alt released) closes it.
pub fn toggle_eye_dropper(
    state: Option<EyeDropperState>,
    force: Option<bool>,
    ty: ColorPickerType,
) -> Option<EyeDropperState> {
    if force == Some(true) {
        let state = state.unwrap_or(EyeDropperState {
            keep_open_on_alt: true,
            picker: ty,
        });
        return Some(EyeDropperState {
            keep_open_on_alt: true,
            ..state
        });
    }
    if force == Some(false) || state.is_some() {
        None
    } else {
        Some(EyeDropperState {
            keep_open_on_alt: false,
            picker: ty,
        })
    }
}

/// What Escape does in the popup (`onEscape`, `ColorPicker.tsx:204-211`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EscapeOutcome {
    /// The eye dropper is on: turn it off.
    CancelEyeDropper,
    /// Close the popup (`openPopup: null`).
    ClosePopup,
}

/// [`EscapeOutcome`] for the eye dropper's state.
pub fn escape(eye_dropper: Option<EyeDropperState>) -> EscapeOutcome {
    if eye_dropper.is_some() {
        EscapeOutcome::CancelEyeDropper
    } else {
        EscapeOutcome::ClosePopup
    }
}

/// `ColorInput`'s own state (`ColorInput.tsx:32-33`): what the input
/// holds and the error it shows.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct HexInputState {
    pub inner_value: String,
    /// The error's locale key (`colorPicker.invalidHexLength` or
    /// `colorPicker.invalidColor`).
    pub error: Option<&'static str>,
}

impl HexInputState {
    /// The input showing `color` without an error: when the picker opens,
    /// when the colour changes, and on blur (`ColorInput.tsx:37-39, 94-97`).
    pub fn for_color(color: &str) -> HexInputState {
        HexInputState {
            inner_value: color.to_owned(),
            error: None,
        }
    }
}

/// A change of the hex input: the colour it picks (`onChange`), if any,
/// and the input's state.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HexChange {
    pub color: Option<String>,
    pub state: HexInputState,
}

/// `changeColor` (`ColorInput.tsx:41-60`): the typed value lowercased and
/// trimmed picks its colour ([`normalize_input_color`]) when it is one;
/// otherwise empty is no error, hex digits of the wrong length are
/// `invalidHexLength`, anything else `invalidColor`.
pub fn change_hex_input(value: &str) -> HexChange {
    let value = js_trim(&value.to_lowercase()).to_owned();
    let color = normalize_input_color(&value);
    let error = if color.is_some() || value.is_empty() {
        None
    } else {
        let digits = value.strip_prefix('#').unwrap_or(&value);
        if !digits.is_empty()
            && digits
                .bytes()
                .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        {
            Some("colorPicker.invalidHexLength")
        } else {
            Some("colorPicker.invalidColor")
        }
    };
    HexChange {
        color,
        state: HexInputState {
            inner_value: value,
            error,
        },
    }
}

/// What the input shows for its state (`value`, `ColorInput.tsx:92`):
/// the value without one leading `#`.
pub fn hex_input_value(inner_value: &str) -> String {
    inner_value
        .strip_prefix('#')
        .unwrap_or(inner_value)
        .to_owned()
}

// -- top picks customisation ---------------------------------------------------

/// The `appState.colorTopPicks` slots (`types.ts:573-583`): where a
/// customisable strip keeps its picks.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ColorTopPicksSlot {
    ElementStroke,
    ElementBackground,
    BucketFill,
    StickyNoteStroke,
    StickyNoteBackground,
}

impl ColorTopPicksSlot {
    pub const ALL: [ColorTopPicksSlot; 5] = [
        ColorTopPicksSlot::ElementStroke,
        ColorTopPicksSlot::ElementBackground,
        ColorTopPicksSlot::BucketFill,
        ColorTopPicksSlot::StickyNoteStroke,
        ColorTopPicksSlot::StickyNoteBackground,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            ColorTopPicksSlot::ElementStroke => "elementStroke",
            ColorTopPicksSlot::ElementBackground => "elementBackground",
            ColorTopPicksSlot::BucketFill => "bucketFill",
            ColorTopPicksSlot::StickyNoteStroke => "stickyNoteStroke",
            ColorTopPicksSlot::StickyNoteBackground => "stickyNoteBackground",
        }
    }
}

/// `isSameColor` (`colorTopPicksDnD.ts:14-20`): value equality of colours,
/// so `#fff`, `#ffffff` and `white` cannot take two slots.
pub fn is_same_color<S: AsRef<str> + ?Sized>(a: &S, b: &S) -> bool {
    let (a, b) = (a.as_ref(), b.as_ref());
    if a.to_lowercase() == b.to_lowercase() {
        return true;
    }
    color_to_hex(a).is_some_and(|hex| Some(hex) == color_to_hex(b))
}

/// The `updateData` patch that stores a slot's picks
/// (`ColorPicker.tsx:387-415`): `colorTopPicks` with the slot set to
/// `picks`, or cleared (`null`, the defaults again) for `None`.
pub fn color_top_picks_update(
    color_top_picks: &serde_json::Map<String, serde_json::Value>,
    slot: ColorTopPicksSlot,
    picks: Option<&[String]>,
) -> serde_json::Value {
    let mut next = color_top_picks.clone();
    next.insert(
        slot.as_str().to_owned(),
        picks.map_or(serde_json::Value::Null, |p| serde_json::json!(p)),
    );
    serde_json::json!({ "colorTopPicks": next })
}

/// Whether the strip can be customised (`isTopPicksCustomizable`,
/// `ColorPicker.tsx:370`): a slot, and the full styles panel.
fn is_top_picks_customizable(props: &ColorPickerProps) -> bool {
    props.customizable_top_picks.is_some() && !props.compact()
}

/// The user's pinned picks when the strip is customisable and has any
/// (`customTopPicks`, `ColorPicker.tsx:373-376`).
fn custom_top_picks(props: &ColorPickerProps) -> Option<&[String]> {
    (is_top_picks_customizable(props) && !props.color_top_picks.is_empty())
        .then_some(props.color_top_picks.as_slice())
}

/// The picks the strip shows, which a drag edits (`effectiveTopPicks`,
/// `ColorPicker.tsx:380-385`): the pinned ones, else the host's, else the
/// stroke or background defaults.
pub fn effective_top_picks(props: &ColorPickerProps) -> Vec<String> {
    if let Some(custom) = custom_top_picks(props) {
        return custom.to_vec();
    }
    let defaults = match props.ty {
        ColorPickerType::ElementStroke => DEFAULT_ELEMENT_STROKE_PICKS,
        _ => DEFAULT_ELEMENT_BACKGROUND_PICKS,
    };
    props
        .top_picks
        .unwrap_or(defaults)
        .iter()
        .map(|c| (*c).to_owned())
        .collect()
}

/// The ghost's swatch (`createColorGhost`, `colorTopPicksDnD.ts:22-39`):
/// the checkerboard for a transparent colour, else the colour the source
/// renders (`rendered`, its computed background, which dark mode remaps),
/// or the colour itself when it renders none.
pub fn color_ghost(color: &str, rendered: Option<&str>) -> Element {
    if is_transparent(color) {
        return Element::new("div")
            .attr("class", "excalidraw-color-dnd-ghost-swatch is-transparent");
    }
    let background = rendered
        .filter(|r| !r.is_empty() && *r != "rgba(0, 0, 0, 0)")
        .unwrap_or(color);
    Element::new("div")
        .attr("class", "excalidraw-color-dnd-ghost-swatch")
        .style("background-color", background)
}

/// The colour picker's drag and drop (`ColorPickerDnD`).
pub type ColorPickerDnd = TopPicksDnd<String>;

/// A new [`ColorPickerDnd`] (`useColorTopPicksDnD`,
/// `colorTopPicksDnD.ts:49-64`).
pub fn color_picker_dnd() -> ColorPickerDnd {
    TopPicksDnd::new(is_same_color)
}

/// Lets `el` start a drag of `value` from `origin` while the strip is
/// customisable (`startSourceDrag`, `startPickDrag`).
fn draggable(
    el: Element,
    props: &ColorPickerProps,
    value: Option<&str>,
    origin: DragOrigin,
) -> Element {
    if !is_top_picks_customizable(props) {
        return el;
    }
    let dnd = props.dnd.clone();
    let value = value.map(str::to_owned);
    el.on("pointerdown", move |e: &Event| {
        let Some(dnd) = &dnd else {
            return;
        };
        let color = value.clone();
        dnd.start_drag(e, value.clone(), origin, |source| {
            let color = color.unwrap_or_default();
            let rendered = web_sys::window()
                .and_then(|w| w.get_computed_style(source).ok().flatten())
                .and_then(|s| s.get_property_value("background-color").ok());
            let ghost = color_ghost(&color, rendered.as_deref());
            let content = source
                .owner_document()
                .and_then(|d| crate::dom::create_detached(&Node::Element(ghost), &d).ok())
                .and_then(|n| n.dyn_into::<web_sys::Element>().ok())
                .unwrap_or_else(|| source.clone());
            let r = source.get_bounding_client_rect();
            let home = Rect {
                left: r.left(),
                top: r.top(),
                width: r.width(),
                height: r.height(),
            };
            (content, home)
        });
    })
}

// -- DOM -----------------------------------------------------------------------

/// What the user did.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ColorPickerEvent {
    /// A top pick was clicked: `onChange(color)`, and when
    /// [`top_pick_follows_focus`] the popup moves to this picker.
    TopPick(String),
    /// The trigger was pressed: [`toggle_popup`].
    Trigger,
    /// A swatch of the popup was clicked: `onChange(color)` and the
    /// section it is in.
    Pick { color: String, section: Section },
    /// A key in the popup that the keyboard map handled.
    Key(KeyNavOutcome),
    /// The hex input's value changed: [`change_hex_input`].
    HexInput(String),
    /// The hex input took the focus: the section is [`Section::Hex`].
    HexFocus,
    /// The hex input lost the focus: [`HexInputState::for_color`].
    HexBlur,
    /// The eye-dropper trigger was clicked: [`toggle_eye_dropper`] with
    /// no force.
    EyeDropperTrigger,
    /// A drop made these the strip's picks: the host stores them
    /// ([`color_top_picks_update`]).
    TopPicksChange(Vec<String>),
    /// The strip's context menu or the tip reset the picks: the host
    /// clears the slot ([`color_top_picks_update`] with `None`).
    ResetTopPicks,
    /// The strip's context menu opens at this client point, or closes.
    TopPicksMenu(Option<(i32, i32)>),
    /// A drag's state changed: render again.
    DragChange,
}

/// Called with each [`ColorPickerEvent`].
pub type OnColorPickerEvent = Rc<dyn Fn(ColorPickerEvent)>;

/// The picker's props and state (`ColorPickerProps`, `ColorPicker.tsx:51-73`,
/// with the app and editor state it reads).
#[derive(Clone)]
pub struct ColorPickerProps {
    pub ty: ColorPickerType,
    /// The active colour; `None` for a mixed selection.
    pub color: Option<String>,
    /// The trigger's and the hex input's `aria-label`.
    pub label: String,
    /// The popup's palette; `None` for a hex input only (the canvas
    /// background).
    pub palette: Option<&'static [PaletteEntry]>,
    /// The strip's colours; `None` for the type's defaults.
    pub top_picks: Option<[&'static str; 5]>,
    /// Palette colours hidden in the popup, keeping the grid positions.
    pub excluded_colors: Vec<String>,
    pub theme: Theme,
    /// `appState.openPopup` is this picker's.
    pub open: bool,
    pub mode: StylesPanelMode,
    /// `editorInterface.formFactor === "phone"`: no eye dropper, and the
    /// popup below the trigger in portrait.
    pub phone: bool,
    /// The platform names Alt "Option".
    pub is_darwin: bool,
    /// The most-used custom colours ([`picker_custom_colors`] when the
    /// popup opened).
    pub custom_colors: Vec<String>,
    /// The active section ([`initial_section`] when none is).
    pub section: Option<Section>,
    /// The eye dropper is on.
    pub eye_dropper_active: bool,
    /// The hex input's state.
    pub hex: HexInputState,
    /// The popup's id, which the trigger's `aria-controls` names.
    pub popup_id: String,
    pub on_event: Option<OnColorPickerEvent>,
    /// `customizableTopPicks`: the `appState.colorTopPicks` slot the strip
    /// is customised in; `None` for a fixed strip.
    pub customizable_top_picks: Option<ColorTopPicksSlot>,
    /// That slot's picks (`appState.colorTopPicks[slot]`; empty for none).
    pub color_top_picks: Vec<String>,
    /// The strip's context menu is open at this client point.
    pub top_picks_menu: Option<(i32, i32)>,
    /// The drag and drop ([`color_picker_dnd`]), kept by the host across
    /// renders.
    pub dnd: Option<ColorPickerDnd>,
}

impl ColorPickerProps {
    fn compact(&self) -> bool {
        self.mode != StylesPanelMode::Full
    }

    fn emit(&self, event: ColorPickerEvent) {
        if let Some(f) = &self.on_event {
            f(event);
        }
    }

    fn handler(&self, event: ColorPickerEvent) -> impl Fn(&Event) + 'static {
        let on_event = self.on_event.clone();
        move |_| {
            if let Some(f) = &on_event {
                f(event.clone());
            }
        }
    }

    fn display_color(&self, color: &str) -> String {
        apply_dark_mode_filter(color, self.theme == Theme::Dark)
    }
}

fn outline() -> Node {
    Element::new("div")
        .attr("class", "color-picker__button-outline")
        .into()
}

fn icon(name: &str) -> Node {
    icons::icon(name)
        .and_then(|i| i.element(Theme::Light))
        .unwrap_or_else(|| panic!("icons.tsx has no {name}"))
        .into()
}

/// `ButtonSeparator` (`components/ButtonSeparator.tsx`).
fn button_separator() -> Node {
    Element::new("div")
        .style("width", "1px")
        .style("height", "1rem")
        .style("background-color", "var(--default-border-color)")
        .style("margin", "0 auto")
        .into()
}

/// `TopPicks` (`TopPicks.tsx:39-132`) in its `TopPicksContextMenu`
/// trigger (`TopPicksContextMenu.tsx:11-50`) while customisable.
fn top_picks(props: &ColorPickerProps) -> Node {
    let customizable = is_top_picks_customizable(props);
    let colors: Vec<String> = match custom_top_picks(props) {
        Some(custom) => custom.to_vec(),
        None => props
            .top_picks
            .unwrap_or(match props.ty {
                ColorPickerType::ElementStroke => DEFAULT_ELEMENT_STROKE_PICKS,
                ColorPickerType::ElementBackground => DEFAULT_ELEMENT_BACKGROUND_PICKS,
                ColorPickerType::CanvasBackground => DEFAULT_CANVAS_BACKGROUND_PICKS,
            })
            .iter()
            .map(|c| (*c).to_owned())
            .collect(),
    };
    let drag_state = props
        .dnd
        .as_ref()
        .filter(|_| customizable)
        .and_then(|d| d.drag_state());
    let buttons = colors.iter().enumerate().map(|(index, color)| {
        let offset = get_top_pick_reorder_offset(drag_state.as_ref(), index);
        let state = drag_state.as_ref();
        let class = class_names([
            ("color-picker__button top-picks-dnd__pick", true),
            ("active", props.color.as_deref() == Some(color.as_str())),
            ("is-transparent", color == "transparent" || color.is_empty()),
            (
                "has-outline",
                !is_color_dark(color, Some(COLOR_OUTLINE_CONTRAST_THRESHOLD)),
            ),
            (
                "is-dnd-source",
                state.is_some_and(|s| s.origin == DragOrigin::Pick(index)),
            ),
            (
                "is-dnd-target",
                state
                    .is_some_and(|s| s.origin == DragOrigin::Source && s.over_index == Some(index)),
            ),
            (
                "is-dnd-duplicate",
                state.is_some_and(|s| s.duplicate_index == Some(index)),
            ),
        ]);
        let el = Element::new("button")
            .attr("class", class)
            .style("--swatch-color", props.display_color(color))
            .style_opt(
                "transform",
                (offset != 0.0).then(|| format!("translateX({offset}px)")),
            )
            .attr("type", "button")
            .attr("title", color.as_str())
            .on(
                "click",
                props.handler(ColorPickerEvent::TopPick(color.clone())),
            )
            .attr("data-testid", format!("color-top-pick-{color}"))
            .attr("data-top-pick-index", index.to_string())
            .child(outline());
        draggable(el, props, Some(color), DragOrigin::Pick(index)).into()
    });
    let mut strip = Element::new("div")
        .attr(
            "class",
            class_names([
                ("color-picker__top-picks top-picks-dnd", true),
                ("is-dnd-active", drag_state.is_some()),
            ]),
        )
        .child_opt(drag_state.is_some().then(top_picks_dnd_outline))
        .children_from(buttons);
    if customizable {
        let on_event = props.on_event.clone();
        let on_open: Rc<dyn Fn(i32, i32)> = Rc::new(move |x, y| {
            if let Some(f) = &on_event {
                f(ColorPickerEvent::TopPicksMenu(Some((x, y))));
            }
        });
        strip = context_menu_trigger(strip, props.top_picks_menu.is_some(), on_open);
        if let Some(dnd) = props.dnd.clone() {
            strip = strip.on_mount(move |el| dnd.set_strip(Some(el.clone())));
        }
    }
    strip.into()
}

/// The popup's `TopPicksTip` (`Picker.tsx:222-229`), with the reset
/// link while the picks are pinned.
fn tip(props: &ColorPickerProps) -> Node {
    let on_event = props.on_event.clone();
    let reset = custom_top_picks(props).is_some().then(|| TipReset {
        title: color_picker_text("colorPicker.resetTopPicks"),
        label: color_picker_text("buttons.reset"),
        on_reset: Rc::new(move || {
            if let Some(f) = &on_event {
                f(ColorPickerEvent::ResetTopPicks);
            }
        }),
    });
    top_picks_tip(None, color_picker_text("colorPicker.topPicksTip"), reset)
}

/// `ColorPickerTrigger` (`ColorPicker.tsx:267-351`), a radix
/// `Popover.Trigger`.
fn trigger(props: &ColorPickerProps) -> Node {
    let color = props.color.as_deref().filter(|c| !c.is_empty());
    let display = color.map(|c| props.display_color(c));
    let class = class_names([
        ("color-picker__button active-color properties-trigger", true),
        ("is-transparent", color.is_none_or(|c| c == "transparent")),
        (
            "has-outline",
            color.is_none_or(|c| !is_color_dark(c, Some(COLOR_OUTLINE_CONTRAST_THRESHOLD))),
        ),
        ("compact-sizing", props.compact()),
        ("mobile-border", props.mode == StylesPanelMode::Mobile),
    ]);
    let title = color_picker_text(match props.ty {
        ColorPickerType::ElementStroke => "labels.showStroke",
        _ => "labels.showBackground",
    });
    let on_event = props.on_event.clone();
    let mut button = Element::new("button")
        .attr("type", "button")
        .attr("aria-haspopup", "dialog")
        .attr("aria-expanded", props.open.to_string())
        .attr("aria-controls", props.popup_id.as_str())
        .attr("data-state", if props.open { "open" } else { "closed" })
        .attr("class", class)
        .attr("aria-label", props.label.as_str())
        .style_opt("--swatch-color", display.clone())
        .attr("title", title)
        .attr("data-openpopup", props.ty.as_str())
        .on("click", move |e: &Event| {
            e.prevent_default();
            e.stop_propagation();
            if let Some(f) = &on_event {
                f(ColorPickerEvent::Trigger);
            }
        })
        .child(
            Element::new("div")
                .attr("class", "color-picker__button-outline")
                .child_opt(color.is_none().then(|| icon("slashIcon"))),
        );
    if let (true, Some(display), ColorPickerType::ElementStroke) =
        (props.compact(), &display, props.ty)
    {
        let text = if is_color_dark(display, Some(COLOR_OUTLINE_CONTRAST_THRESHOLD)) {
            "#fff"
        } else {
            "#111"
        };
        button = button.child(
            Element::new("div")
                .attr("class", "color-picker__button-background")
                .child(
                    Element::new("span")
                        .style("color", text)
                        .child(icon("strokeIcon")),
                ),
        );
    }
    // the active colour can be dragged onto the strip to pin it
    draggable(button, props, props.color.as_deref(), DragOrigin::Source).into()
}

/// `HotkeyLabel` (`HotkeyLabel.tsx`).
fn hotkey_label(color: &str, key: &str, is_shade: bool) -> Node {
    Element::new("div")
        .attr("class", "color-picker__button__hotkey-label")
        .style(
            "color",
            if is_color_dark(color, None) {
                "#fff"
            } else {
                "#000"
            },
        )
        .child_opt(is_shade.then(|| Node::text("⇧")))
        .child(Node::text(key))
        .into()
}

/// `PickerHeading` (`PickerHeading.tsx`).
fn heading(key: &str) -> Node {
    Element::new("div")
        .attr("class", "color-picker__heading")
        .child(Node::text(color_picker_text(key)))
        .into()
}

/// Focuses the element once mounted (the lists' `btnRef.current.focus()`).
fn focus_on_mount(el: Element, focus: bool) -> Element {
    if focus {
        el.on_mount(|dom| {
            if let Some(h) = dom.dyn_ref::<HtmlElement>() {
                let _ = h.focus();
            }
        })
    } else {
        el
    }
}

/// `CustomColorList` (`CustomColorList.tsx`).
fn custom_color_list(props: &ColorPickerProps, focus: bool) -> Node {
    let label = color_picker_text("colorPicker.mostUsedCustomColors");
    let buttons = props.custom_colors.iter().enumerate().map(|(i, c)| {
        let display = props.display_color(c);
        let active = props.color.as_deref() == Some(c.as_str());
        let el = Element::new("button")
            .attr("tabindex", "-1")
            .attr("type", "button")
            .attr(
                "class",
                class_names([
                    (
                        "color-picker__button color-picker__button--large has-outline",
                        true,
                    ),
                    ("active", active),
                    ("is-transparent", c == "transparent" || c.is_empty()),
                ]),
            )
            .on(
                "click",
                props.handler(ColorPickerEvent::Pick {
                    color: c.clone(),
                    section: Section::Custom,
                }),
            )
            .attr("title", c.as_str())
            .attr("aria-label", label)
            .style("--swatch-color", display.as_str())
            .child(outline())
            .child(hotkey_label(&display, &(i + 1).to_string(), false));
        let el = draggable(el, props, Some(c), DragOrigin::Source);
        focus_on_mount(el, focus && active).into()
    });
    Element::new("div")
        .attr("class", "color-picker-content--default")
        .children_from(buttons)
        .into()
}

/// `PickerColorList` (`PickerColorList.tsx`): the palette in its 5×3 grid.
fn picker_color_list(
    props: &ColorPickerProps,
    palette: &[PaletteEntry],
    active_shade: usize,
    focus: bool,
) -> Node {
    let obj = get_color_name_and_shade(palette, props.color.as_deref());
    let show_hotkey = props.mode != StylesPanelMode::Mobile;
    let buttons = palette.iter().enumerate().map(|(index, (key, value))| {
        let color = match value {
            PaletteColor::Shades(shades) => shades.get(active_shade).copied(),
            PaletteColor::Single(c) => Some(*c),
        }
        .filter(|c| !c.is_empty())
        .unwrap_or("transparent");
        if props.excluded_colors.iter().any(|c| c == color) {
            // an invisible placeholder keeps the grid positions and hotkeys
            return Element::new("div")
                .attr("class", "color-picker__button color-picker__button--large")
                .style("visibility", "hidden")
                .attr("aria-hidden", "true")
                .into();
        }
        let keybinding = COLOR_PICKER_HOTKEY_BINDINGS
            .get(index)
            .copied()
            .unwrap_or("undefined");
        let display = props.display_color(color);
        // t(`colors.${key.replace(/\d+/, "")}`, null, "")
        let name: String = {
            let start = key.find(|c: char| c.is_ascii_digit());
            match start {
                Some(s) => {
                    let end = key[s..]
                        .find(|c: char| !c.is_ascii_digit())
                        .map_or(key.len(), |e| s + e);
                    format!("{}{}", &key[..s], &key[end..])
                }
                None => (*key).to_owned(),
            }
        };
        let locale_key = format!("colors.{name}");
        let label = match color_picker_text(&locale_key) {
            l if l == locale_key => "",
            l => l,
        };
        let hex = if color.starts_with('#') {
            format!(" {color}")
        } else {
            String::new()
        };
        let active = obj.is_some_and(|o| o.color_name == *key);
        let el = Element::new("button")
            .attr("tabindex", "-1")
            .attr("type", "button")
            .attr(
                "class",
                class_names([
                    ("color-picker__button color-picker__button--large", true),
                    ("has-outline", !is_color_dark(color, Some(255.0))),
                    ("active", active),
                    ("is-transparent", color == "transparent"),
                ]),
            )
            .on(
                "click",
                props.handler(ColorPickerEvent::Pick {
                    color: color.to_owned(),
                    section: Section::BaseColors,
                }),
            )
            .attr("title", format!("{label}{hex} — {keybinding}"))
            .attr("aria-label", format!("{label} — {keybinding}"))
            .style("--swatch-color", display.as_str())
            .attr("data-testid", format!("color-{key}"))
            .child(outline())
            .child_opt(show_hotkey.then(|| hotkey_label(&display, keybinding, false)));
        let el = draggable(el, props, Some(color), DragOrigin::Source);
        focus_on_mount(el, focus && active).into()
    });
    Element::new("div")
        .attr("class", "color-picker-content--default")
        .children_from(buttons)
        .into()
}

/// `ShadeList` (`ShadeList.tsx`): the picked hue's five shades, or a
/// placeholder.
fn shade_list(props: &ColorPickerProps, palette: &[PaletteEntry], focus: bool) -> Node {
    let color = props
        .color
        .as_deref()
        .filter(|c| !c.is_empty())
        .unwrap_or("transparent");
    let show_hotkey = props.mode != StylesPanelMode::Mobile;
    let obj = get_color_name_and_shade(palette, Some(color));
    let shades = obj.and_then(|o| {
        palette
            .iter()
            .find(|e| e.0 == o.color_name)
            .and_then(|e| match e.1 {
                PaletteColor::Shades(s) => Some((o, s)),
                PaletteColor::Single(_) => None,
            })
    });
    if let Some((obj, shades)) = shades {
        let buttons = shades.iter().enumerate().map(|(i, c)| {
            let display = props.display_color(c);
            let active = obj.shade == Some(i);
            let el = Element::new("button")
                .attr("tabindex", "-1")
                .attr("type", "button")
                .attr(
                    "class",
                    class_names([
                        ("color-picker__button color-picker__button--large", true),
                        ("active", active),
                    ]),
                )
                .attr("aria-label", "Shade")
                .attr("title", format!("{} - {}", obj.color_name, i + 1))
                .style("--swatch-color", display.as_str())
                .on(
                    "click",
                    props.handler(ColorPickerEvent::Pick {
                        color: (*c).to_owned(),
                        section: Section::Shades,
                    }),
                )
                .child(outline())
                .child_opt(show_hotkey.then(|| hotkey_label(&display, &(i + 1).to_string(), true)));
            let el = draggable(el, props, Some(c), DragOrigin::Source);
            focus_on_mount(el, focus && active).into()
        });
        return Element::new("div")
            .attr("class", "color-picker-content--default shades")
            .children_from(buttons)
            .into();
    }
    Element::new("div")
        .attr("class", "color-picker-content--default")
        .style("position", "relative")
        .attr("tabindex", "-1")
        .child(
            Element::new("button")
                .attr("type", "button")
                .attr("tabindex", "-1")
                .attr(
                    "class",
                    "color-picker__button color-picker__button--large color-picker__button--no-focus-visible",
                ),
        )
        .child(
            Element::new("div")
                .attr("tabindex", "-1")
                .style("position", "absolute")
                .style("top", "0")
                .style("left", "0")
                .style("right", "0")
                .style("bottom", "0")
                .style("display", "flex")
                .style("align-items", "center")
                .style("justify-content", "center")
                .style("text-align", "center")
                .style("font-size", "0.75rem")
                .child(Node::text(color_picker_text("colorPicker.noShades"))),
        )
        .into()
}

/// `ColorInput` (`ColorInput.tsx:98-153`) under its heading
/// (`ColorPicker.tsx:106-120`).
fn color_input(props: &ColorPickerProps) -> Node {
    let error = props.hex.error;
    let on_event = props.on_event.clone();
    let emit = move |event: ColorPickerEvent| {
        if let Some(f) = &on_event {
            f(event);
        }
    };
    let input = {
        let (on_input, on_blur, on_focus) = (emit.clone(), emit.clone(), emit.clone());
        let el = Element::new("input")
            .style("border", "0")
            .style("padding", "0")
            .attr("spellcheck", "false")
            .attr("class", "color-picker-input")
            .attr("aria-label", props.label.as_str())
            .attr("aria-invalid", error.is_some().to_string())
            .attr("value", hex_input_value(&props.hex.inner_value))
            .attr("tabindex", "-1")
            .attr("placeholder", color_picker_text("colorPicker.color"))
            .on("input", move |e: &Event| {
                if let Some(input) = e
                    .target()
                    .and_then(|t| t.dyn_into::<HtmlInputElement>().ok())
                {
                    on_input(ColorPickerEvent::HexInput(input.value()));
                }
            })
            .on("blur", move |_| on_blur(ColorPickerEvent::HexBlur))
            .on("focus", move |_| on_focus(ColorPickerEvent::HexFocus))
            .on("keydown", |e: &Event| {
                let Some(e) = e.dyn_ref::<KeyboardEvent>() else {
                    return;
                };
                match e.key().as_str() {
                    "Tab" => return,
                    "Escape" => {
                        // the eye-dropper trigger takes the focus
                        let trigger = e
                            .target()
                            .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
                            .and_then(|t| t.parent_element())
                            .and_then(|p| {
                                p.query_selector(".excalidraw-eye-dropper-trigger")
                                    .ok()
                                    .flatten()
                            })
                            .and_then(|t| t.dyn_into::<HtmlElement>().ok());
                        if let Some(t) = trigger {
                            let _ = t.focus();
                        }
                    }
                    _ => {}
                }
                e.stop_propagation();
            });
        focus_on_mount(el, props.section == Some(Section::Hex))
    };
    let mut label = Element::new("div")
        .attr(
            "class",
            class_names([
                ("color-picker__input-label", true),
                ("has-error", error.is_some()),
            ]),
        )
        .child(
            Element::new("div")
                .attr("class", "color-picker__input-hash")
                .child(Node::text("#")),
        )
        .child(input);
    if !props.phone {
        let alt = get_shortcut_key("Alt", props.is_darwin, &KeyLabels::EN);
        let title = format!("{} — I or {alt} ", color_picker_text("labels.eyeDropper"));
        label = label
            .child(
                Element::new("div")
                    .style("width", "1px")
                    .style("height", "1.25rem")
                    .style("background-color", "var(--default-border-color)"),
            )
            .child(
                Element::new("div")
                    .attr(
                        "class",
                        class_names([
                            ("excalidraw-eye-dropper-trigger", true),
                            ("selected", props.eye_dropper_active),
                        ]),
                    )
                    .on("click", move |_| emit(ColorPickerEvent::EyeDropperTrigger))
                    .attr("title", title)
                    .child(icon("eyeDropperIcon")),
            );
    }
    Element::new("div")
        .child(heading("colorPicker.hexCode"))
        .child(
            Element::new("div")
                .attr("class", "color-picker__input-label-container")
                .child(label)
                .child_opt(error.map(|key| {
                    Element::new("div")
                        .attr("class", "color-picker__error-message")
                        .attr("role", "alert")
                        .child(Node::text(color_picker_text(key)))
                })),
        )
        .into()
}

/// The keyboard map's state for the props.
fn key_nav<'a>(
    props: &'a ColorPickerProps,
    palette: &'a [PaletteEntry],
    excluded: &'a [&'a str],
) -> KeyNavState<'a> {
    let obj = get_color_name_and_shade(palette, props.color.as_deref());
    KeyNavState {
        section: props.section,
        palette,
        color: props.color.as_deref(),
        custom_colors: &props.custom_colors,
        active_shade: initial_active_shade(props.ty, obj.as_ref()),
        excluded_colors: excluded,
    }
}

/// `Picker` (`Picker.tsx:52-230`).
fn picker(props: &ColorPickerProps, palette: &'static [PaletteEntry]) -> Node {
    let title = if props.compact() {
        match props.ty {
            ColorPickerType::ElementStroke => Some("labels.stroke"),
            ColorPickerType::ElementBackground => Some("labels.background"),
            ColorPickerType::CanvasBackground => None,
        }
    } else {
        None
    };
    let obj = get_color_name_and_shade(palette, props.color.as_deref());
    let active_shade = initial_active_shade(props.ty, obj.as_ref());
    let section = props.section;
    let has_custom_focus = section == Some(Section::Custom)
        && props
            .custom_colors
            .iter()
            .any(|c| props.color.as_deref() == Some(c.as_str()));
    let has_focus_target = match section {
        Some(Section::Custom) => has_custom_focus,
        Some(Section::BaseColors) => obj.is_some(),
        Some(Section::Shades) => obj.is_some_and(|o| o.shade.is_some()),
        Some(Section::Hex) => true,
        None => false,
    };

    let keydown = {
        let props = props.clone();
        move |e: &Event| {
            let Some(e) = e.dyn_ref::<KeyboardEvent>() else {
                return;
            };
            let excluded: Vec<&str> = props.excluded_colors.iter().map(String::as_str).collect();
            let state = key_nav(&props, palette, &excluded);
            let event = KeyInput {
                key: e.key(),
                code: e.code(),
                shift: e.shift_key(),
                ctrl_or_cmd: if props.is_darwin {
                    e.meta_key()
                } else {
                    e.ctrl_key()
                },
            };
            let outcome = color_picker_key_nav_handler(&event, &state);
            if outcome.handled {
                e.prevent_default();
                e.stop_propagation();
                props.emit(ColorPickerEvent::Key(outcome));
            }
        }
    };

    let mut content = Element::new("div")
        .on("keydown", keydown)
        .attr("class", "color-picker-content properties-content")
        .attr("tabindex", "-1")
        .child_opt(title.map(|key| {
            Element::new("div")
                .attr("class", "color-picker__title")
                .child(Node::text(color_picker_text(key)))
        }));
    if !props.custom_colors.is_empty() {
        content = content.child(
            Element::new("div")
                .child(heading("colorPicker.mostUsedCustomColors"))
                .child(custom_color_list(props, section == Some(Section::Custom))),
        );
    }
    content = content
        .child(
            Element::new("div")
                .child(heading("colorPicker.colors"))
                .child(picker_color_list(
                    props,
                    palette,
                    active_shade,
                    section == Some(Section::BaseColors),
                )),
        )
        .child(
            Element::new("div")
                .child(heading("colorPicker.shades"))
                .child(shade_list(props, palette, section == Some(Section::Shades))),
        )
        .child(color_input(props))
        // only while the top picks are customisable
        .child_opt(is_top_picks_customizable(props).then(|| tip(props)));
    // the picker takes the focus when no section's control does
    let content = focus_on_mount(content, !has_focus_target);
    Element::new("div")
        .attr("role", "dialog")
        .attr("aria-modal", "true")
        .attr("aria-label", color_picker_text("labels.colorPicker"))
        .child(content)
        .into()
}

/// Places the popup beside the trigger once mounted, as radix's
/// `Popover.Content` does with floating-ui (`side="right"`,
/// `align="start"`, `alignOffset={-16}`, `sideOffset={20}`; below and
/// centred on a phone in portrait), flipping to the left when it would
/// leave the editor container, and points the arrow at the trigger.
fn place_popup(wrapper: &web_sys::Element, trigger_id: &str, below: bool) {
    let Some(document) = wrapper.owner_document() else {
        return;
    };
    let selector = format!("[aria-controls=\"{trigger_id}\"]");
    if let Ok(Some(trigger)) = document.query_selector(&selector) {
        place_beside(wrapper, &trigger, below);
    }
}

/// [`place_popup`] beside `trigger`: a `PropertiesPopover`'s radix popper
/// wrapper, whose first child is the content and whose content's last
/// child is the arrow (the styles panel's popovers are placed this way
/// too).
pub(crate) fn place_beside(wrapper: &web_sys::Element, trigger: &web_sys::Element, below: bool) {
    let Some(content) = wrapper.first_element_child() else {
        return;
    };
    let t = trigger.get_bounding_client_rect();
    let c = content.get_bounding_client_rect();
    let bounds = wrapper
        .closest(".excalidraw")
        .ok()
        .flatten()
        .map(|e| e.get_bounding_client_rect());
    let (right_edge, bottom_edge, left_edge, top_edge) = match &bounds {
        Some(b) => (b.right(), b.bottom(), b.left(), b.top()),
        None => (
            f64::INFINITY,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::NEG_INFINITY,
        ),
    };
    let (side, x, y) = if below {
        let x = t.left() + (t.width() - c.width()) / 2.0;
        ("bottom", x, t.bottom() + 20.0)
    } else {
        let right = t.right() + 20.0;
        let (side, x) =
            if right + c.width() > right_edge && t.left() - 20.0 - c.width() >= left_edge {
                ("left", t.left() - 20.0 - c.width())
            } else {
                ("right", right)
            };
        let y = (t.top() - 16.0).min(bottom_edge - c.height()).max(top_edge);
        (side, x, y)
    };
    let align = if below { "center" } else { "start" };
    let _ = content.set_attribute("data-side", side);
    let _ = content.set_attribute("data-align", align);
    if let Some(w) = wrapper.dyn_ref::<HtmlElement>() {
        let style = w.style();
        let _ = style.set_property("position", "fixed");
        let _ = style.set_property("left", "0px");
        let _ = style.set_property("top", "0px");
        let _ = style.set_property("transform", &format!("translate({x}px, {y}px)"));
        let _ = style.set_property("min-width", "max-content");
        let _ = style.set_property("z-index", "var(--zIndex-ui-styles-popup)");
    }
    // the arrow points at the trigger's middle
    if let Some(arrow) = content
        .last_element_child()
        .and_then(|a| a.dyn_into::<HtmlElement>().ok())
    {
        let style = arrow.style();
        let _ = style.set_property("position", "absolute");
        match side {
            "bottom" => {
                let left = t.left() + t.width() / 2.0 - x - 10.0;
                let _ = style.set_property("left", &format!("{left}px"));
                let _ = style.set_property("top", "0px");
                let _ = style.set_property("transform-origin", "center 0");
                let _ = style.set_property("transform", "rotate(180deg)");
            }
            _ => {
                let top = t.top() + t.height() / 2.0 - y - 10.0;
                let _ = style.set_property("top", &format!("{top}px"));
                let (edge, transform, origin) = if side == "right" {
                    (
                        "left",
                        "translateY(50%) rotate(90deg) translateX(-50%)",
                        "0 0",
                    )
                } else {
                    (
                        "right",
                        "translateY(50%) rotate(-90deg) translateX(50%)",
                        "100% 0",
                    )
                };
                let _ = style.set_property(edge, "0px");
                let _ = style.set_property("transform-origin", origin);
                let _ = style.set_property("transform", transform);
            }
        }
    }
}

/// `PropertiesPopover` (`PropertiesPopover.tsx`) holding the popup
/// content (`ColorPickerPopupContent`, `ColorPicker.tsx:75-258`): radix's
/// popper wrapper and the dialog content with the island and the arrow.
fn popup(props: &ColorPickerProps) -> Node {
    let body = match props.palette {
        Some(palette) => picker(props, palette),
        None => color_input(props),
    };
    let arrow = Element::new("span").child(
        Element::svg("svg")
            .attr("width", "20")
            .attr("height", "10")
            .attr("viewBox", "0 0 30 10")
            .attr("preserveAspectRatio", "none")
            .style("fill", "var(--popup-bg-color)")
            .style("filter", "drop-shadow(rgba(0, 0, 0, 0.05) 0px 3px 2px)")
            .style("display", "block")
            .child(Element::svg("polygon").attr("points", "0,0 30,0 15,10")),
    );
    let content = Element::new("div")
        .attr("class", "focus-visible-none")
        .attr("data-prevent-outside-click", "true")
        .attr("data-state", "open")
        .attr("id", props.popup_id.as_str())
        .attr("role", "dialog")
        .attr("tabindex", "-1")
        .style(
            "--radix-popover-content-transform-origin",
            "var(--radix-popper-transform-origin)",
        )
        .style(
            "--radix-popover-content-available-width",
            "var(--radix-popper-available-width)",
        )
        .style(
            "--radix-popover-content-available-height",
            "var(--radix-popper-available-height)",
        )
        .style(
            "--radix-popover-trigger-width",
            "var(--radix-popper-anchor-width)",
        )
        .style(
            "--radix-popover-trigger-height",
            "var(--radix-popper-anchor-height)",
        )
        .style("z-index", "var(--zIndex-ui-styles-popup)")
        .style_opt("margin-left", props.phone.then_some("0.5rem"))
        // radix's DismissableLayer: a layer under a modal one (the strip's
        // context menu) takes no pointer events
        .style_opt(
            "pointer-events",
            (is_top_picks_customizable(props) && props.top_picks_menu.is_some()).then_some("none"),
        )
        .child(island(
            IslandProps {
                padding: Some(3.0),
                style: vec![("max-width".into(), "13rem".into())],
                ..IslandProps::default()
            },
            vec![body],
        ))
        .child(arrow);
    let trigger_id = props.popup_id.clone();
    // a phone in portrait: below and centred (no landscape detection here)
    let below = props.phone;
    Element::new("div")
        .attr("data-radix-popper-content-wrapper", "")
        .child(content)
        .on_mount(move |wrapper| place_popup(wrapper, &trigger_id, below))
        .into()
}

/// `ColorPicker` (`ColorPicker.tsx:353-508`): the popup when open (portaled
/// into the editor container, which radix does before the picker's own
/// element), then the picker: the top-picks strip and a separator unless
/// the styles panel is compact, and the trigger.
///
/// While customisable, the strip's context menu follows when open
/// (portaled into the container, and radix hides the rest from assistive
/// technology meanwhile), and the drag and drop is told the picks and
/// whom to tell of a drop.
pub fn color_picker(props: &ColorPickerProps) -> Vec<Node> {
    let compact = props.compact();
    let customizable = is_top_picks_customizable(props);
    if let Some(dnd) = &props.dnd {
        dnd.set_enabled(customizable);
        dnd.set_picks(effective_top_picks(props));
        let on_event = props.on_event.clone();
        dnd.set_listener(Some(Rc::new(move |event| {
            if let Some(f) = &on_event {
                f(match event {
                    TopPicksDndEvent::PicksChange(picks) => ColorPickerEvent::TopPicksChange(picks),
                    TopPicksDndEvent::StateChanged => ColorPickerEvent::DragChange,
                });
            }
        })));
    }
    let container = Element::new("div")
        .attr("role", "dialog")
        .attr("aria-modal", "true")
        .attr(
            "class",
            class_names([
                ("color-picker-container", true),
                ("color-picker-container--no-top-picks", compact),
            ]),
        )
        .child_opt((!compact).then(|| top_picks(props)))
        .child_opt((!compact).then(button_separator))
        .child(trigger(props));
    let mut out = Vec::new();
    if props.open {
        out.push(popup(props));
    }
    out.push(container.into());
    if let (true, Some(at)) = (customizable, props.top_picks_menu) {
        let emit = |event: ColorPickerEvent| {
            let on_event = props.on_event.clone();
            Rc::new(move || {
                if let Some(f) = &on_event {
                    f(event.clone());
                }
            }) as Rc<dyn Fn()>
        };
        out = hide_others(out);
        out.push(context_menu(
            color_picker_text("colorPicker.resetTopPicks"),
            custom_top_picks(props).is_some(),
            at,
            emit(ColorPickerEvent::ResetTopPicks),
            emit(ColorPickerEvent::TopPicksMenu(None)),
        ));
    }
    out
}
