//! Bucket fill parity (ex-704).
//!
//! `tests/fixtures/bucket-fill.json` is upstream's own
//! `packages/element/src/bucketFill.ts` at the pinned commit, generated by
//! `tools/goldens/bucket-fill-fixtures.mjs`: every call
//! `packages/element/tests/bucketFill.test.ts` makes (the test run as
//! written, `upstream-*`) and seeded random scenes of closed and open
//! outlines (`random-*`), each with what upstream answered. Every call is
//! reproduced exactly: `computeBucketFillPolygon`'s owner, boundary ids,
//! scene points and insertion (or its failure reason), and
//! `isRestylableFill`.
//!
//! The tests after the replay restate a few of `bucketFill.test.ts`'s
//! assertions on the port directly, and those of
//! `packages/excalidraw/tests/bucketFill.test.tsx` that are about what a
//! click does to the scene (`App.bucketFill.ts`'s `fill`).

use excali_core::element::Element;
use excali_core::element::{ElementKind, FillStyle};
use excali_editor::bucket_fill::{
    bucket_fill_click, compute_bucket_fill_polygon, get_bucket_fill_background_color,
    is_bucket_fill_compatible, is_restylable_fill, renders_opaque_fill, BucketFillClick,
    BucketFillFailureReason, BucketFillOptions, BucketFillOutcome, Placement,
};
use excali_scene::bounds::ElementsMap;
use serde_json::{json, Value};

const FIXTURE: &str = include_str!("fixtures/bucket-fill.json");

fn cases() -> Vec<Value> {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("bucket-fill.json parses");
    fixture["cases"].as_array().expect("cases").clone()
}

fn element(value: &Value) -> Element {
    Element::from_map(value.as_object().expect("an element").clone())
        .expect("an element upstream built")
}

fn elements(call: &Value) -> Vec<Element> {
    call["elements"]
        .as_array()
        .expect("elements")
        .iter()
        .map(element)
        .collect()
}

fn point(value: &Value) -> [f64; 2] {
    [value[0].as_f64().expect("x"), value[1].as_f64().expect("y")]
}

fn points(value: &Value) -> Vec<[f64; 2]> {
    value
        .as_array()
        .expect("points")
        .iter()
        .map(point)
        .collect()
}

/// `{ ...DEFAULT_BUCKET_FILL_OPTIONS, ...options }`.
fn options(value: &Value) -> BucketFillOptions {
    let mut options = BucketFillOptions::default();
    let Some(given) = value.as_object() else {
        return options;
    };
    for (key, v) in given {
        let v = v.as_f64().expect("a number");
        match key.as_str() {
            "snapEpsilon" => options.snap_epsilon = v,
            "gapTolerance" => options.gap_tolerance = v,
            "minArea" => options.min_area = v,
            "maxBoundarySegments" => options.max_boundary_segments = v as usize,
            "maxGeneratedPoints" => options.max_generated_points = v as usize,
            "fallbackSearchRadius" => options.fallback_search_radius = v,
            other => panic!("unknown option {other}"),
        }
    }
    options
}

fn reason(value: &str) -> BucketFillFailureReason {
    match value {
        "no_owner" => BucketFillFailureReason::NoOwner,
        "open_region" => BucketFillFailureReason::OpenRegion,
        "too_complex" => BucketFillFailureReason::TooComplex,
        "too_small" => BucketFillFailureReason::TooSmall,
        "invalid_polygon" => BucketFillFailureReason::InvalidPolygon,
        other => panic!("unknown reason {other}"),
    }
}

/// What the port answered, in the fixture's JSON shape.
fn compute(call: &Value) -> Value {
    let scene = elements(call);
    let map = ElementsMap::new(scene.iter());
    let refs: Vec<&Element> = scene.iter().collect();
    match compute_bucket_fill_polygon(
        point(&call["point"]),
        &refs,
        &map,
        &options(&call["options"]),
    ) {
        Ok(fill) => json!({
            "ok": true,
            "ownerId": fill.owner_id,
            "boundaryElementIds": fill.boundary_element_ids,
            "scenePoints": fill.scene_points,
            "insertion": {
                "placement": match fill.insertion.placement {
                    Placement::Above => "above",
                    Placement::Below => "below",
                },
                "elementId": fill.insertion.element_id,
            },
        }),
        Err(reason) => json!({ "ok": false, "reason": reason.as_str() }),
    }
}

#[test]
fn replays_every_upstream_call() {
    let mut calls = 0;
    let mut failures = Vec::new();
    for case in cases() {
        let id = case["id"].as_str().expect("id");
        for (k, call) in case["calls"].as_array().expect("calls").iter().enumerate() {
            calls += 1;
            let (expected, actual) = match call["fn"].as_str().expect("fn") {
                "computeBucketFillPolygon" => (call["result"].clone(), compute(call)),
                "isRestylableFill" => {
                    let scene = elements(call);
                    let map = ElementsMap::new(scene.iter());
                    let hit = element(&call["hitElement"]);
                    let answer = is_restylable_fill(&hit, &points(&call["scenePoints"]), &map);
                    (call["result"].clone(), Value::Bool(answer))
                }
                other => panic!("unknown fn {other}"),
            };
            if !same(&expected, &actual) {
                failures.push(format!(
                    "{id} call {k} ({}):\n  expected {}\n  actual   {}",
                    call["fn"],
                    truncate(&expected),
                    truncate(&actual)
                ));
            }
        }
    }
    assert!(calls > 700, "only {calls} calls in the fixture");
    assert!(
        failures.is_empty(),
        "{} of {calls} calls differ from upstream:\n{}",
        failures.len(),
        failures
            .iter()
            .take(12)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// JSON equality with numbers compared as doubles (upstream writes `0`, the
/// port `0.0`): every coordinate must be the same double.
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(x, y)| same(x, y))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

fn truncate(value: &Value) -> String {
    let text = value.to_string();
    if text.len() > 600 {
        format!("{}…", &text[..600])
    } else {
        text
    }
}

#[test]
fn the_fixture_covers_every_outcome() {
    let mut seen = std::collections::BTreeSet::new();
    for case in cases() {
        for call in case["calls"].as_array().expect("calls") {
            let result = &call["result"];
            if call["fn"] == "isRestylableFill" {
                seen.insert(format!("restylable-{result}"));
            } else if result["ok"] == true {
                let owner = if result["ownerId"].is_null() {
                    "ownerless"
                } else {
                    "owned"
                };
                let placement = result["insertion"]["placement"]
                    .as_str()
                    .expect("placement");
                seen.insert(format!("ok-{owner}"));
                seen.insert(format!("ok-{placement}"));
            } else {
                let reason = reason(result["reason"].as_str().expect("reason"));
                seen.insert(reason.as_str().to_string());
            }
        }
    }
    for outcome in [
        "ok-owned",
        "ok-ownerless",
        "ok-above",
        "ok-below",
        "no_owner",
        "open_region",
        "too_complex",
        "too_small",
        "invalid_polygon",
        "restylable-true",
        "restylable-false",
    ] {
        assert!(
            seen.contains(outcome),
            "no call with outcome {outcome}: {seen:?}"
        );
    }
}

// -- bucketFill.test.ts's assertions, restated on the port -----------------------

fn rectangle(id: &str, x: f64, y: f64, w: f64, h: f64, extra: Value) -> Element {
    let mut value = json!({
        "id": id, "type": "rectangle", "x": x, "y": y, "width": w, "height": h,
        "angle": 0, "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
        "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
        "opacity": 100, "groupIds": [], "frameId": null, "index": null, "roundness": null,
        "seed": 1, "version": 1, "versionNonce": 0, "isDeleted": false,
        "boundElements": null, "updated": 1, "link": null, "locked": false,
    });
    for (k, v) in extra.as_object().expect("extra") {
        value[k] = v.clone();
    }
    element(&value)
}

fn area(points: &[[f64; 2]]) -> f64 {
    let mut sum = 0.0;
    let n = points.len();
    for i in 0..n {
        let [x0, y0] = points[(i + n - 1) % n];
        let [x1, y1] = points[i];
        sum += (x0 + x1) * (y0 - y1);
    }
    (sum / 2.0).abs()
}

#[test]
fn fills_a_simple_rectangle_below_its_transparent_owner() {
    let rect = rectangle("r", 0.0, 0.0, 100.0, 100.0, json!({}));
    let map = ElementsMap::new([&rect]);
    let fill =
        compute_bucket_fill_polygon([50.0, 50.0], &[&rect], &map, &BucketFillOptions::default())
            .expect("a fill");
    assert_eq!(fill.owner_id.as_deref(), Some("r"));
    assert!(fill.boundary_element_ids.is_empty());
    assert_eq!(fill.insertion.placement, Placement::Below);
    assert_eq!(fill.insertion.element_id, "r");
    assert_eq!(fill.scene_points.first(), fill.scene_points.last());
    assert!((area(&fill.scene_points) - 10000.0).abs() < 5.0);
}

#[test]
fn open_canvas_has_no_owner() {
    let rect = rectangle("r", 0.0, 0.0, 100.0, 100.0, json!({}));
    let map = ElementsMap::new([&rect]);
    let result = compute_bucket_fill_polygon(
        [500.0, 500.0],
        &[&rect],
        &map,
        &BucketFillOptions::default(),
    );
    assert_eq!(result.err(), Some(BucketFillFailureReason::NoOwner));
    let empty = ElementsMap::new([]);
    let result =
        compute_bucket_fill_polygon([0.0, 0.0], &[], &empty, &BucketFillOptions::default());
    assert_eq!(result.err(), Some(BucketFillFailureReason::NoOwner));
}

#[test]
fn a_fill_is_restylable_on_the_same_region_only() {
    let rect = rectangle("r", 0.0, 0.0, 100.0, 100.0, json!({}));
    let map = ElementsMap::new([&rect]);
    let fill =
        compute_bucket_fill_polygon([50.0, 50.0], &[&rect], &map, &BucketFillOptions::default())
            .expect("a fill");
    let [ox, oy] = fill.scene_points[0];
    let local: Vec<[f64; 2]> = fill
        .scene_points
        .iter()
        .map(|[x, y]| [x - ox, y - oy])
        .collect();
    let (min_x, max_x) = local
        .iter()
        .fold((f64::MAX, f64::MIN), |(a, b), p| (a.min(p[0]), b.max(p[0])));
    let (min_y, max_y) = local
        .iter()
        .fold((f64::MAX, f64::MIN), |(a, b), p| (a.min(p[1]), b.max(p[1])));
    let paint = element(&json!({
        "id": "fill", "type": "line", "x": ox, "y": oy, "width": max_x - min_x,
        "height": max_y - min_y, "angle": 0, "strokeColor": "transparent",
        "backgroundColor": "#ffc9c9", "fillStyle": "solid", "strokeWidth": 1,
        "strokeStyle": "solid", "roughness": 0, "opacity": 100, "groupIds": [],
        "frameId": null, "index": null, "roundness": null, "seed": 1, "version": 1,
        "versionNonce": 0, "isDeleted": false, "boundElements": null, "updated": 1,
        "link": null, "locked": false, "points": local, "polygon": true,
        "lastCommittedPoint": null, "startBinding": null, "endBinding": null,
        "startArrowhead": null, "endArrowhead": null,
    }));
    assert!(is_bucket_fill_compatible(&paint));
    assert!(renders_opaque_fill(&paint));
    assert!(!renders_opaque_fill(&rect));
    let scene = [&rect, &paint];
    let map = ElementsMap::new(scene);
    assert!(is_restylable_fill(&paint, &fill.scene_points, &map));
    let half: Vec<[f64; 2]> = vec![
        [0.0, 0.0],
        [50.0, 0.0],
        [50.0, 100.0],
        [0.0, 100.0],
        [0.0, 0.0],
    ];
    assert!(!is_restylable_fill(&paint, &half, &map));
    assert!(!is_restylable_fill(&rect, &fill.scene_points, &map));
}

// -- the tool: packages/excalidraw/tests/bucketFill.test.tsx ------------------------

/// A click with the tool at `point` on `scene` (all non-deleted), with
/// `hit` the element under the pointer.
fn click<'a>(
    point: [f64; 2],
    scene: &'a [&'a Element],
    map: &'a ElementsMap<'a>,
    hit: Option<&'a Element>,
    background_color: &'a str,
) -> BucketFillOutcome {
    bucket_fill_click(&BucketFillClick {
        point,
        elements: scene,
        elements_map: map,
        elements_including_deleted: scene,
        hit_element: hit,
        top_layer_frame_id: None,
        background_color,
        fill_style: FillStyle::Solid,
        opacity: 100.0,
        id: "fill",
        seed: 7.0,
        timestamp: 1.0,
    })
}

/// `seedRectangle()`: the owner the app tests click into.
fn seed_rectangle() -> Element {
    rectangle("rect", 20.0, 20.0, 120.0, 100.0, json!({}))
}

fn inserted(outcome: BucketFillOutcome) -> (Element, Option<usize>) {
    match outcome {
        BucketFillOutcome::Insert { fill, index } => (*fill, index),
        other => panic!("expected an insert, got {other:?}"),
    }
}

#[test]
fn creates_an_unselected_line_polygon_with_the_current_background_color() {
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, index) = inserted(click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"));
    let ElementKind::Line(line) = &fill.kind else {
        panic!("not a line");
    };
    assert!(line.polygon);
    assert_eq!(fill.base.background_color, "#ffec99");
    assert_eq!(fill.base.stroke_color, "transparent");
    assert_eq!(fill.base.fill_style, FillStyle::Solid);
    assert_eq!(fill.base.stroke_width, 1.0);
    assert_eq!(fill.base.roughness, 0.0);
    assert!(fill.base.roundness.is_none());
    assert!(fill.base.custom_data.is_none());
    // normalized: points[0] is [0, 0], and the polygon is explicitly closed
    assert_eq!(line.linear.points.first(), Some(&[0.0, 0.0]));
    assert_eq!(line.linear.points.last(), Some(&[0.0, 0.0]));
    // immediately below the owner
    assert_eq!(index, Some(0));
    assert!(is_bucket_fill_compatible(&fill));
}

#[test]
fn re_clicking_a_filled_region_restyles_instead_of_stacking() {
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, _) = inserted(click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"));
    let scene = [&fill, &rect];
    let map = ElementsMap::new(scene);
    // the same colour: nothing changes
    assert_eq!(
        click([80.0, 70.0], &scene, &map, Some(&fill), "#ffec99"),
        BucketFillOutcome::Unchanged
    );
    // a changed colour restyles the existing fill
    assert_eq!(
        click([80.0, 70.0], &scene, &map, Some(&fill), "#ffc9c9"),
        BucketFillOutcome::Restyle {
            element_id: "fill".into(),
            background_color: "#ffc9c9".into(),
            fill_style: FillStyle::Solid,
            opacity: 100.0,
        }
    );
}

#[test]
fn restyles_an_orphaned_fill_even_when_no_region_can_be_derived() {
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, _) = inserted(click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"));
    // the rectangle is deleted: only the paint is left
    let scene = [&fill];
    let map = ElementsMap::new(scene);
    assert!(matches!(
        click([80.0, 70.0], &scene, &map, Some(&fill), "#ffc9c9"),
        BucketFillOutcome::Restyle { .. }
    ));
}

#[test]
fn clicking_a_since_subdivided_part_of_a_filled_region_creates_a_new_fill() {
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, _) = inserted(click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"));
    let splitter = element(&json!({
        "id": "splitter", "type": "line", "x": 10, "y": 70, "width": 140, "height": 0,
        "angle": 0, "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
        "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
        "opacity": 100, "groupIds": [], "frameId": null, "index": null, "roundness": null,
        "seed": 1, "version": 1, "versionNonce": 0, "isDeleted": false,
        "boundElements": null, "updated": 1, "link": null, "locked": false,
        "points": [[0, 0], [140, 0]], "polygon": false, "lastCommittedPoint": null,
        "startBinding": null, "endBinding": null, "startArrowhead": null,
        "endArrowhead": null,
    }));
    let scene = [&fill, &rect, &splitter];
    let map = ElementsMap::new(scene);
    let (top, _) = inserted(click([80.0, 45.0], &scene, &map, Some(&fill), "#ffec99"));
    assert!(
        area(match &top.kind {
            ElementKind::Line(line) => &line.linear.points,
            _ => panic!("not a line"),
        }) < 0.6 * 12000.0
    );
}

#[test]
fn falls_back_to_green_when_the_shared_background_color_is_transparent() {
    assert_eq!(
        get_bucket_fill_background_color("transparent", false),
        "#b2f2bb"
    );
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, _) = inserted(click(
        [80.0, 70.0],
        &scene,
        &map,
        Some(&rect),
        "transparent",
    ));
    assert_eq!(fill.base.background_color, "#b2f2bb");
}

#[test]
fn inserts_the_overlap_fill_below_the_lowest_participant_or_above_a_coverer() {
    for (background, expected) in [("transparent", 0), ("#ff0000", 1)] {
        let below = rectangle(
            "below",
            0.0,
            0.0,
            100.0,
            100.0,
            json!({ "backgroundColor": background }),
        );
        let owner = rectangle("owner", 50.0, 50.0, 100.0, 100.0, json!({}));
        let scene = [&below, &owner];
        let map = ElementsMap::new(scene);
        let (_, index) = inserted(click([75.0, 75.0], &scene, &map, Some(&owner), "#ffec99"));
        assert_eq!(index, Some(expected), "below {background}");
    }
}

#[test]
fn does_nothing_on_empty_canvas_and_toasts_on_an_open_region() {
    let rect = seed_rectangle();
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    assert_eq!(
        click([400.0, 400.0], &scene, &map, None, "#ffec99"),
        BucketFillOutcome::Nothing
    );
    // an owner buried under opaque paint: nothing bounds the click
    let cover = element(&json!({
        "id": "cover", "type": "line", "x": 0, "y": 0, "width": 160, "height": 140,
        "angle": 0, "strokeColor": "transparent", "backgroundColor": "#ffc9c9",
        "fillStyle": "solid", "strokeWidth": 1, "strokeStyle": "solid", "roughness": 0,
        "opacity": 100, "groupIds": [], "frameId": null, "index": null, "roundness": null,
        "seed": 1, "version": 1, "versionNonce": 0, "isDeleted": false,
        "boundElements": null, "updated": 1, "link": null, "locked": false,
        "points": [[0, 0], [160, 0], [160, 140], [0, 140], [0, 0]], "polygon": true,
        "lastCommittedPoint": null, "startBinding": null, "endBinding": null,
        "startArrowhead": null, "endArrowhead": null,
    }));
    let scene = [&rect, &cover];
    let map = ElementsMap::new(scene);
    assert_eq!(
        click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"),
        BucketFillOutcome::Toast("bucketfill.noRegion")
    );
}

#[test]
fn a_fill_takes_its_owners_frame_and_groups() {
    let rect = rectangle(
        "rect",
        20.0,
        20.0,
        120.0,
        100.0,
        json!({ "frameId": "frame", "groupIds": ["g1", "g2"] }),
    );
    let scene = [&rect];
    let map = ElementsMap::new(scene);
    let (fill, _) = inserted(click([80.0, 70.0], &scene, &map, Some(&rect), "#ffec99"));
    assert_eq!(fill.base.frame_id.as_deref(), Some("frame"));
    let groups: Vec<String> = fill.base.group_ids.iter().map(|g| g.to_string()).collect();
    assert_eq!(groups, ["g1", "g2"]);
}
