//! Image cropping parity (ex-713).
//!
//! `tests/fixtures/crop.json` is upstream's own
//! `packages/element/src/cropElement.ts` at the pinned commit, generated by
//! `tools/goldens/crop-fixtures.mjs`: `cropElement` from every handle on
//! images at every flip, several angles and with existing crops, pointers
//! near and far beyond the image, with and without a kept aspect ratio;
//! `getUncroppedWidthAndHeight`, `getUncroppedImageElement` and
//! `getFlipAdjustedCropPosition`; and the `UI.crop` chains of upstream's
//! `packages/element/tests/cropElement.test.tsx`, replayed here with that
//! test's own assertions.

use std::collections::HashMap;

use excali_core::element::{Element, ElementBase, ElementKind, ImageCrop, ImageFields, Radians};
use excali_editor::crop::{
    crop_element, get_flip_adjusted_crop_position, get_uncropped_image_element,
    get_uncropped_width_and_height, MINIMAL_CROP_SIZE,
};
use excali_editor::tools::PointerType;
use excali_editor::transform_handles::{get_transform_handles, OmitSides, TransformHandleType};
use excali_scene::bounds::ElementsMap;
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/crop.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("crop.json parses")
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("a number, got {v}"))
}

fn crop_of(v: &Value) -> Option<ImageCrop> {
    if v.is_null() {
        return None;
    }
    Some(ImageCrop {
        x: num(&v["x"]),
        y: num(&v["y"]),
        width: num(&v["width"]),
        height: num(&v["height"]),
        natural_width: num(&v["naturalWidth"]),
        natural_height: num(&v["naturalHeight"]),
    })
}

fn image(id: &str, x: f64, y: f64, width: f64, height: f64) -> Element {
    let mut base = ElementBase::new(id, x, y, 1.0, 1.0);
    base.width = width;
    base.height = height;
    Element::new_image(base, ImageFields::default())
}

fn image_from(id: &str, v: &Value) -> Element {
    let mut element = image(
        id,
        num(&v["x"]),
        num(&v["y"]),
        num(&v["width"]),
        num(&v["height"]),
    );
    element.base.angle = Radians(num(&v["angle"]));
    let ElementKind::Image(fields) = &mut element.kind else {
        unreachable!()
    };
    fields.scale = [num(&v["scale"][0]), num(&v["scale"][1])];
    fields.crop = crop_of(&v["crop"]);
    element
}

fn crop_field(element: &Element) -> Option<ImageCrop> {
    match &element.kind {
        ElementKind::Image(fields) => fields.crop,
        _ => panic!("an image"),
    }
}

/// `{ x, y, width, height, crop }` equal number for number.
fn assert_geometry(what: &str, x: f64, y: f64, w: f64, h: f64, crop: Option<ImageCrop>, v: &Value) {
    assert_eq!(x, num(&v["x"]), "{what}: x");
    assert_eq!(y, num(&v["y"]), "{what}: y");
    assert_eq!(w, num(&v["width"]), "{what}: width");
    assert_eq!(h, num(&v["height"]), "{what}: height");
    assert_eq!(crop, crop_of(&v["crop"]), "{what}: crop");
}

fn assert_state(what: &str, element: &Element, v: &Value) {
    let b = &element.base;
    assert_geometry(what, b.x, b.y, b.width, b.height, crop_field(element), v);
}

#[test]
fn minimal_crop_size_is_upstreams() {
    assert_eq!(MINIMAL_CROP_SIZE, num(&fixture()["minimalCropSize"]));
}

#[test]
fn uncropped_size_image_and_flip_adjusted_position_match_upstream() {
    let f = fixture();
    let images = f["images"].as_array().expect("images");
    assert_eq!(images.len(), 60);
    for img in images {
        let id = img["id"].as_str().unwrap();
        let element = image_from(id, &img["element"]);
        let map = ElementsMap::new([&element]);

        let (w, h) = get_uncropped_width_and_height(&element);
        assert_eq!(
            w,
            num(&img["uncroppedSize"]["width"]),
            "{id}: uncropped width"
        );
        assert_eq!(
            h,
            num(&img["uncroppedSize"]["height"]),
            "{id}: uncropped height"
        );

        let uncropped = get_uncropped_image_element(&element, &map);
        assert_state(&format!("{id}: uncropped"), &uncropped, &img["uncropped"]);
        assert_eq!(uncropped.base.angle, element.base.angle, "{id}: angle kept");

        for (natural, key) in [(false, "flipAdjusted"), (true, "flipAdjustedNatural")] {
            let got = get_flip_adjusted_crop_position(&element, natural);
            let want = &img[key];
            match got {
                None => assert!(want.is_null(), "{id}: {key}"),
                Some([x, y]) => {
                    assert_eq!(x, num(&want["x"]), "{id}: {key} x");
                    assert_eq!(y, num(&want["y"]), "{id}: {key} y");
                }
            }
        }
    }
}

#[test]
fn crop_element_matches_upstream() {
    let f = fixture();
    let images: HashMap<&str, &Value> = f["images"]
        .as_array()
        .unwrap()
        .iter()
        .map(|i| (i["id"].as_str().unwrap(), i))
        .collect();
    let cases = f["cases"].as_array().expect("cases");
    assert!(cases.len() > 8000);
    for c in cases {
        let id = c["id"].as_str().unwrap();
        let img = images[c["image"].as_str().unwrap()];
        let element = image_from("img", &img["element"]);
        let map = ElementsMap::new([&element]);
        let handle = TransformHandleType::parse(c["handle"].as_str().unwrap()).expect("a handle");
        let ratio = if c["widthAspectRatio"].is_null() {
            None
        } else {
            Some(num(&c["widthAspectRatio"]))
        };
        let update = crop_element(
            &element,
            &map,
            handle,
            num(&img["naturalWidth"]),
            num(&img["naturalHeight"]),
            num(&c["pointer"][0]),
            num(&c["pointer"][1]),
            ratio,
        );
        assert_geometry(
            id,
            update.x,
            update.y,
            update.width,
            update.height,
            update.crop,
            &c["result"],
        );
    }
}

/// `expect(a).toBeCloseTo(b, digits)`: `|a - b| < 10^-digits / 2`.
fn close_to(a: f64, b: f64, digits: i32) -> bool {
    (a - b).abs() < 10f64.powi(-digits) / 2.0
}

/// Replays one `UI.crop` chain; returns the image after every step.
fn replay(seq: &Value) -> Vec<(String, Element)> {
    let natural_width = num(&seq["naturalWidth"]);
    let natural_height = num(&seq["naturalHeight"]);
    let id = seq["id"].as_str().unwrap();
    let mut images: Vec<(String, Element)> = Vec::new();
    let mut after = Vec::new();
    for (i, step) in seq["steps"].as_array().unwrap().iter().enumerate() {
        let name = step["image"].as_str().unwrap().to_owned();
        let what = format!("{id} step {i}");
        let slot = images.iter().position(|(n, _)| *n == name);
        match step["op"].as_str().unwrap() {
            "create" => {
                let element = image(&name, 0.0, 0.0, num(&step["width"]), num(&step["height"]));
                match slot {
                    Some(s) => images[s].1 = element,
                    None => images.push((name.clone(), element)),
                }
            }
            "duplicate" => {
                let from = step["from"].as_str().unwrap();
                let mut copy = images.iter().find(|(n, _)| n == from).unwrap().1.clone();
                copy.base.id = name.clone();
                images.push((name.clone(), copy));
            }
            "crop" => {
                let s = slot.expect("an image to crop");
                let handle = TransformHandleType::parse(step["handle"].as_str().unwrap()).unwrap();
                let updated = {
                    let element = &images[s].1;
                    let map = ElementsMap::new(images.iter().map(|(_, e)| e));
                    // tests/helpers/ui.ts:626-645
                    let coords = get_transform_handles(
                        element,
                        1.0,
                        &map,
                        PointerType::Mouse,
                        &OmitSides::default(),
                    )
                    .get(handle)
                    .expect("the handle is laid out");
                    let pointer = [
                        coords[0] + coords[2] / 2.0 + num(&step["move"][0]),
                        coords[1] + coords[3] / 2.0 + num(&step["move"][1]),
                    ];
                    assert_eq!(pointer[0], num(&step["pointer"][0]), "{what}: pointer x");
                    assert_eq!(pointer[1], num(&step["pointer"][1]), "{what}: pointer y");
                    let ratio = step["keepAspectRatio"]
                        .as_bool()
                        .unwrap()
                        .then(|| element.base.width / element.base.height);
                    let update = crop_element(
                        element,
                        &map,
                        handle,
                        natural_width,
                        natural_height,
                        pointer[0],
                        pointer[1],
                        ratio,
                    );
                    let mut next = element.clone();
                    update.apply_to(&mut next);
                    next
                };
                images[s].1 = updated;
            }
            op => panic!("{what}: unknown op {op}"),
        }
        let current = &images.iter().find(|(n, _)| *n == name).unwrap().1;
        assert_state(&what, current, &step["state"]);
        after.push((name, current.clone()));
    }
    after
}

fn sequences(f: &Value, name: &str) -> Vec<Value> {
    let out: Vec<Value> = f["sequences"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|s| s["sequence"] == name)
        .cloned()
        .collect();
    assert_eq!(out.len(), 4, "{name}: one chain per natural size");
    out
}

fn size(e: &Element) -> (f64, f64) {
    (e.base.width, e.base.height)
}

/// "Cropping changes the dimension" (cropElement.test.tsx:120-133).
#[test]
fn cropping_changes_the_dimension() {
    for seq in sequences(&fixture(), "changes-dimension") {
        let s = replay(&seq);
        assert!(s[1].1.base.width < 200.0);
        assert!(s[2].1.base.height < 100.0);
    }
}

/// "Cropping has minimal sizes" (cropElement.test.tsx:135-150).
#[test]
fn cropping_has_minimal_sizes() {
    for seq in sequences(&fixture(), "minimal-sizes") {
        let s = replay(&seq);
        let (w, _) = size(&s[1].1);
        assert!(w < 200.0 && w > 0.0);
        let (_, h) = size(&s[3].1);
        assert!(h < 100.0 && h > 0.0);
    }
}

/// "Preserve aspect ratio" (cropElement.test.tsx:152-213).
#[test]
fn preserve_aspect_ratio() {
    for seq in sequences(&fixture(), "preserve-aspect-ratio") {
        let s = replay(&seq);
        // max height, cropping should not change anything
        let (rw, rh) = size(&s[1].1);
        let (w, h) = size(&s[2].1);
        assert!(close_to(w, rw, 10) && close_to(h, rh, 10));
        // corner handle keeps the aspect ratio
        let (rw, rh) = size(&s[5].1);
        let (w, h) = size(&s[6].1);
        assert_eq!(w / h, rw / rh);
        assert!(w <= 200.0 + 0.0001 && h <= 100.0 + 0.0001);
        // a 50 x 50 square at the corner cannot grow from "n"
        let (w, h) = size(&s[9].1);
        assert!(close_to(w, h, 2));
        assert!(close_to(h, 50.0, 2));
        // max height reached
        let (w, h) = size(&s[10].1);
        assert!(close_to(w, h, 2));
        assert!(close_to(h, 100.0, 2));
        assert!(close_to(w, 100.0, 2));
    }
}

/// "Cropping works independently of duplication"
/// (cropElement.test.tsx:217-259).
#[test]
fn cropping_works_independently_of_duplication() {
    for seq in sequences(&fixture(), "duplication") {
        let s = replay(&seq);
        let image = &s[1].1;
        assert_eq!(size(&s[2].1), size(image));
        assert_eq!(size(&s[3].1), (200.0, 100.0));
        assert_ne!(image.base.width, 200.0);
        assert_ne!(image.base.height, 100.0);
        let (w, h) = size(&s[4].1);
        assert_ne!(w, 200.0);
        assert_ne!(h, 100.0);
    }
}

/// "Resizing should not affect crop", its crops
/// (cropElement.test.tsx:261-285): the "e" crop past the image's right
/// edge changes nothing.
#[test]
fn cropping_past_the_edge_keeps_the_crop() {
    for seq in sequences(&fixture(), "resize-keeps-crop") {
        let s = replay(&seq);
        let before = crop_field(&s[1].1).expect("cropped");
        let after = crop_field(&s[2].1).expect("still cropped");
        for (a, b) in [
            (before.x, after.x),
            (before.y, after.y),
            (before.width, after.width),
            (before.height, after.height),
            (before.natural_width, after.natural_width),
            (before.natural_height, after.natural_height),
        ] {
            assert!(close_to(a, b, 2), "{a} vs {b}");
        }
    }
}
