//! Editing parity (ex-712).
//!
//! `tests/fixtures/editing.json` is upstream's own selection, group,
//! element creation and editing code at the pinned commit, generated by
//! `tools/goldens/editing-fixtures.mjs` on the scenes of the gestures the
//! `<excali-editor>` element wires. Every case is replayed:
//!
//! - `within`: `getElementsWithinSelection` (`selection.ts:70`) for each
//!   box, in both box selection modes, with and without
//!   `excludeElementsInFrames`;
//! - `groups`: `selectGroupsForSelectedElements` (`groups.ts:68-196`);
//! - `new`: the element App creates for a drawing tool
//!   ([`new_element_for_tool`]), every field but the drawn ones;
//! - `drag`: `dragNewElement` (`dragElements.ts:294-406`);
//! - `perfect`: `getPerfectElementSize` (`sizeHelpers.ts:158-185`);
//! - `eraser`: `EraserTrail.addPointToPath` (`eraser/index.ts`), the ids
//!   to erase after every point;
//! - `delete`, `duplicate`, `group`, `ungroup` and `zindex`: the
//!   `perform`s of `actionDeleteSelected`, `actionDuplicateSelection`,
//!   `actionGroup`, `actionUngroup` and the four z-order actions
//!   ([`edit_actions`]): every element they return (seeds, nonces and
//!   fractional indices included) and the app state keys they set;
//! - `copy`: the clipboard JSON `actionCopy` writes;
//! - `paste`: `addElementsFromPasteOrLibrary` for pasted clipboard JSON at
//!   the pointer, the scene and the selection after;
//! - `library`: library items inserted (`LibraryMenuItems`'s click and
//!   App's drop): each item duplicated, `distributeLibraryItemsOnSquareGrid`
//!   and `addElementsFromPasteOrLibrary`.

use excali_core::app_state::{get_default_app_state, AppState, AppStateEnv};
use excali_core::element::Element;
use excali_core::fractional_index::ChangeStamp;
use excali_core::restore::RestoreEnv;
use excali_editor::edit_actions::{self, ActionResult};
use excali_editor::eraser::EraserTrail;
use excali_editor::groups::select_groups_for_selected_elements;
use excali_editor::new_element::{
    drag_new_element, get_perfect_element_size, new_element_for_tool, DragNewElement,
};
use excali_editor::scene::MutationEnv;
use excali_editor::selection::{get_elements_within_selection, BoxSelectionMode};
use excali_scene::bounds::ElementsMap;
use serde_json::{json, Map, Value};

const FIXTURE: &str = include_str!("fixtures/editing.json");

fn cases(kind: &str) -> Vec<Value> {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("editing.json parses");
    let cases: Vec<Value> = fixture["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .filter(|c| c["kind"] == kind)
        .cloned()
        .collect();
    assert!(!cases.is_empty(), "no {kind} cases");
    cases
}

fn elements(case: &Value) -> Vec<Element> {
    case["elements"]
        .as_array()
        .expect("elements")
        .iter()
        .map(|e| {
            Element::from_map(e.as_object().expect("an element").clone())
                .expect("an element upstream built")
        })
        .collect()
}

fn ids(elements: &[&Element]) -> Vec<String> {
    elements.iter().map(|e| e.base.id.clone()).collect()
}

#[test]
fn elements_within_selection_match_upstream() {
    for case in cases("within") {
        let scene = elements(&case);
        let all: Vec<&Element> = scene.iter().collect();
        let map = ElementsMap::new(all.iter().copied());
        for selection in case["selections"].as_array().unwrap() {
            let b: Vec<f64> = selection["box"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect();
            let bounds = [b[0], b[1], b[0] + b[2], b[1] + b[3]];
            for result in selection["results"].as_array().unwrap() {
                let mode = match result["mode"].as_str().unwrap() {
                    "contain" => BoxSelectionMode::Contain,
                    _ => BoxSelectionMode::Overlap,
                };
                let exclude = result["excludeElementsInFrames"].as_bool().unwrap();
                let got = ids(&get_elements_within_selection(
                    &all, bounds, &map, exclude, mode,
                ));
                let want: Vec<String> = result["ids"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_owned())
                    .collect();
                assert_eq!(
                    got, want,
                    "{} box {b:?} {mode:?} exclude {exclude}",
                    case["id"]
                );
            }
        }
    }
}

#[test]
fn group_selection_matches_upstream() {
    for case in cases("groups") {
        let scene = elements(&case);
        let all: Vec<&Element> = scene.iter().collect();
        let selected: Map<String, Value> = case["appState"]["selectedElementIds"]
            .as_object()
            .unwrap()
            .clone();
        let editing = case["appState"]["editingGroupId"].as_str();
        let got = select_groups_for_selected_elements(&selected, editing, &all);
        let want = &case["result"];
        assert_eq!(
            Value::Object(got.selected_element_ids.clone()),
            want["selectedElementIds"],
            "{}",
            case["id"]
        );
        // key order included: the ids are an object upstream iterates
        let got_keys: Vec<&String> = got.selected_element_ids.keys().collect();
        let want_keys: Vec<&String> = want["selectedElementIds"]
            .as_object()
            .unwrap()
            .keys()
            .collect();
        assert_eq!(got_keys, want_keys, "{}", case["id"]);
        assert_eq!(
            Value::Object(got.selected_group_ids.clone()),
            want["selectedGroupIds"],
            "{}",
            case["id"]
        );
        assert_eq!(
            got.editing_group_id.as_deref(),
            want["editingGroupId"].as_str(),
            "{}",
            case["id"]
        );
    }
}

/// `v` with every number as a double (JSON has one number type).
fn numbers(v: &Value) -> Value {
    match v {
        Value::Number(n) => json!(n.as_f64().unwrap()),
        Value::Array(a) => Value::Array(a.iter().map(numbers).collect()),
        Value::Object(o) => Value::Object(o.iter().map(|(k, v)| (k.clone(), numbers(v))).collect()),
        other => other.clone(),
    }
}

fn num(v: &Value) -> f64 {
    v.as_f64().expect("a number")
}

fn point(v: &Value) -> [f64; 2] {
    [num(&v[0]), num(&v[1])]
}

#[test]
fn new_elements_match_upstream() {
    for case in cases("new") {
        // upstream's test mode: currentItemRoundness "sharp"
        let mut app_state = get_default_app_state(&AppStateEnv {
            test_env: true,
            ..AppStateEnv::default()
        });
        for (k, v) in case["appState"].as_object().unwrap() {
            app_state.insert(k, v.clone());
        }
        let tool = case["tool"].as_str().unwrap();
        let element = new_element_for_tool(
            tool,
            &app_state,
            point(&case["origin"]),
            None,
            "x",
            7.0,
            1.0,
        )
        .unwrap_or_else(|| panic!("{} made nothing", case["id"]));
        let mut got = element.to_map();
        for key in ["id", "seed", "versionNonce", "updated"] {
            got.shift_remove(key);
        }
        assert_eq!(
            numbers(&Value::Object(got)),
            numbers(&case["element"]),
            "{}",
            case["id"]
        );
        assert_eq!(element.base.seed, 7.0);
    }
}

#[test]
fn drag_new_element_matches_upstream() {
    for case in cases("drag") {
        let mut map = case["element"].as_object().unwrap().clone();
        for (k, v) in [
            ("id", json!("x")),
            ("seed", json!(1)),
            ("versionNonce", json!(0)),
            ("updated", json!(1)),
        ] {
            map.insert(k.into(), v);
        }
        let element = Element::from_map(map).expect("an element");
        let tool = element.kind.element_type().as_str().to_owned();
        let origin = point(&case["origin"]);
        for drag in case["drags"].as_array().unwrap() {
            let to = point(&drag["to"]);
            let got = drag_new_element(&DragNewElement {
                element: &element,
                element_type: &tool,
                origin,
                pointer: to,
                width: (to[0] - origin[0]).abs(),
                height: (to[1] - origin[1]).abs(),
                maintain_aspect_ratio: drag["shouldMaintainAspectRatio"].as_bool().unwrap(),
                resize_from_center: drag["shouldResizeFromCenter"].as_bool().unwrap(),
                width_aspect_ratio: None,
            });
            let r = &drag["result"];
            let want = [
                num(&r["x"]),
                num(&r["y"]),
                num(&r["width"]),
                num(&r["height"]),
            ];
            let got = got.unwrap_or([
                element.base.x,
                element.base.y,
                element.base.width,
                element.base.height,
            ]);
            assert_eq!(got, want, "{} {drag}", case["id"]);
        }
    }
}

#[test]
fn perfect_element_size_matches_upstream() {
    for case in cases("perfect") {
        for item in case["items"].as_array().unwrap() {
            let got = get_perfect_element_size(
                item["type"].as_str().unwrap(),
                num(&item["width"]),
                num(&item["height"]),
            );
            let want = (
                num(&item["result"]["width"]),
                num(&item["result"]["height"]),
            );
            assert_eq!(got, want, "{item}");
        }
    }
}

#[test]
fn eraser_trail_matches_upstream() {
    for case in cases("eraser") {
        let scene = elements(&case);
        let visible: Vec<&Element> = scene.iter().filter(|e| !e.base.is_deleted).collect();
        for path in case["paths"].as_array().unwrap() {
            let points: Vec<[f64; 2]> = path["points"]
                .as_array()
                .unwrap()
                .iter()
                .map(point)
                .collect();
            let restore: Vec<bool> = path["restore"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_bool().unwrap())
                .collect();
            let mut trail = EraserTrail::default();
            trail.start_path(points[0][0], points[0][1]);
            for (i, step) in path["steps"].as_array().unwrap().iter().enumerate() {
                let p = points[i + 1];
                let got = trail.add_point_to_path(p[0], p[1], restore[i + 1], &visible, 1.0);
                let want: Vec<String> = step
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_owned())
                    .collect();
                assert_eq!(got, want, "{} {:?} step {i}", case["id"], points);
            }
        }
    }
}

// -- the edit actions ---------------------------------------------------------

/// Upstream's test mode after `reseed(1)`, which the generator runs before
/// each action: ids `id0`, `id1`, ..., timestamps 1, and `randomInteger()`
/// (seeds and version nonces) from roughjs' `Random(1)`, drawn in
/// upstream's order.
struct ActionEnv(excali_core::restore::TestEnv);

impl ActionEnv {
    fn new() -> ActionEnv {
        ActionEnv(excali_core::restore::TestEnv::default())
    }
}

impl RestoreEnv for ActionEnv {
    fn now(&mut self) -> f64 {
        1.0
    }

    fn random_id(&mut self) -> String {
        self.0.random_id()
    }

    fn random_integer(&mut self) -> f64 {
        self.0.random_integer()
    }
}

impl MutationEnv for ActionEnv {
    fn random_integer(&mut self) -> f64 {
        self.0.random_integer()
    }

    fn now(&mut self) -> f64 {
        1.0
    }
}

impl ChangeStamp for ActionEnv {
    fn version_nonce(&mut self) -> f64 {
        self.0.random_integer()
    }

    fn updated(&mut self) -> f64 {
        1.0
    }
}

/// The app state a case's action runs in: upstream's defaults in test mode
/// with the case's keys.
fn action_app_state(case: &Value) -> AppState {
    let mut app_state = get_default_app_state(&AppStateEnv {
        test_env: true,
        ..AppStateEnv::default()
    });
    app_state.insert("selectedElementIds", json!({}));
    app_state.insert("selectedGroupIds", json!({}));
    app_state.insert("editingGroupId", Value::Null);
    if let Some(keys) = case["appState"].as_object() {
        for (k, v) in keys {
            app_state.insert(k.clone(), v.clone());
        }
    }
    app_state
}

fn element_values(elements: &[Element]) -> Vec<Value> {
    elements
        .iter()
        .map(|e| numbers(&Value::Object(e.to_map())))
        .collect()
}

/// The elements an action returned, compared with upstream's in order and
/// one by one, every key (the drawn seeds and nonces included).
fn assert_elements(got: &[Element], want: &Value, what: &str) {
    let got = element_values(got);
    let want: Vec<Value> = want
        .as_array()
        .expect("elements")
        .iter()
        .map(numbers)
        .collect();
    let got_ids: Vec<&Value> = got.iter().map(|e| &e["id"]).collect();
    let want_ids: Vec<&Value> = want.iter().map(|e| &e["id"]).collect();
    assert_eq!(got_ids, want_ids, "{what}: order");
    for (g, w) in got.iter().zip(&want) {
        assert_eq!(g, w, "{what}: element {}", w["id"]);
    }
}

/// The app state keys an action set over `before`: upstream's app state
/// after it (none set when upstream returned its app state as it was), a
/// key the action leaves keeping its value.
fn assert_app_state(got: &Map<String, Value>, before: &AppState, want: &Value, what: &str) {
    match want {
        Value::Null => assert!(got.is_empty(), "{what}: app state {got:?}"),
        Value::Object(want) => {
            for (key, value) in want {
                let after = got.get(key).or_else(|| before.get(key));
                assert_eq!(after, Some(value), "{what}: {key}");
            }
            for key in got.keys() {
                assert!(want.contains_key(key), "{what}: unexpected {key}");
            }
        }
        other => panic!("{what}: app state {other}"),
    }
}

type ActionFn = fn(&[Element], &AppState, &mut ActionEnv) -> Option<ActionResult>;

fn replay_action(case: &Value, perform: ActionFn) {
    let what = case["id"].as_str().unwrap();
    let scene = elements(case);
    let app_state = action_app_state(case);
    let mut env = ActionEnv::new();
    let got = perform(&scene, &app_state, &mut env);
    let want = &case["result"];
    if want.is_null() {
        assert_eq!(got, None, "{what}: upstream returns false");
        return;
    }
    let got = got.unwrap_or_else(|| panic!("{what}: upstream performs"));
    let next = got.elements.clone().unwrap_or_else(|| scene.clone());
    assert_elements(&next, &want["elements"], what);
    assert_app_state(&got.app_state, &app_state, &want["appState"], what);
    assert_eq!(
        got.capture,
        want["captureUpdate"] == "IMMEDIATELY",
        "{what}: captureUpdate"
    );
}

#[test]
fn delete_selected_matches_upstream() {
    for case in cases("delete") {
        replay_action(&case, edit_actions::delete_selected);
    }
}

#[test]
fn duplicate_selection_matches_upstream() {
    for case in cases("duplicate") {
        replay_action(&case, edit_actions::duplicate_selection);
    }
}

#[test]
fn group_matches_upstream() {
    for case in cases("group") {
        replay_action(&case, edit_actions::group);
    }
}

#[test]
fn ungroup_matches_upstream() {
    for case in cases("ungroup") {
        replay_action(&case, edit_actions::ungroup);
    }
}

#[test]
fn z_index_actions_match_upstream() {
    for case in cases("zindex") {
        let perform: ActionFn = match case["action"].as_str().unwrap() {
            "bringToFront" => edit_actions::bring_to_front,
            "sendToBack" => edit_actions::send_to_back,
            "bringForward" => edit_actions::bring_forward,
            "sendBackward" => edit_actions::send_backward,
            other => panic!("action {other}"),
        };
        replay_action(&case, perform);
    }
}

#[test]
fn copy_matches_upstream() {
    for case in cases("copy") {
        let what = case["id"].as_str().unwrap();
        let scene = elements(&case);
        let app_state = action_app_state(&case);
        let mut env = ActionEnv::new();
        let got = edit_actions::copy_selected(&scene, &app_state, Some(&Map::new()), &mut env);
        let got: Value = serde_json::from_str(&got).unwrap_or_else(|e| panic!("{what}: {e}"));
        let want: Value = serde_json::from_str(case["clipboard"].as_str().unwrap()).unwrap();
        assert_eq!(numbers(&got), numbers(&want), "{what}");
    }
}

#[test]
fn paste_matches_upstream() {
    for case in cases("paste") {
        let what = case["id"].as_str().unwrap();
        let scene = elements(&case);
        let app_state = action_app_state(&Value::Null);
        let mut env = ActionEnv::new();
        let got = edit_actions::paste_elements(
            case["clipboard"].as_str().unwrap(),
            &scene,
            &app_state,
            point(&case["pointer"]),
            case["gridSize"].as_f64(),
            &mut env,
        )
        .unwrap_or_else(|| panic!("{what}: pastes"));
        let want = &case["result"];
        let next = got
            .elements
            .as_deref()
            .expect("the scene with the pasted elements");
        assert_elements(next, &want["elements"], what);
        assert_app_state(&got.app_state, &app_state, &want["appState"], what);
        assert!(got.capture, "{what}: the store captures the paste");
    }
}

/// Text that is not Excalidraw clipboard JSON pastes no elements (upstream
/// makes a text element of it, which the port leaves to the caller).
#[test]
fn paste_of_plain_text_pastes_no_elements() {
    let app_state = action_app_state(&Value::Null);
    let mut env = ActionEnv::new();
    for text in ["hello", "{\"type\":\"excalidraw/clipboard\"}", ""] {
        assert_eq!(
            edit_actions::paste_elements(text, &[], &app_state, [0.0, 0.0], None, &mut env),
            None,
            "{text}"
        );
    }
}

fn library_items(case: &Value) -> Vec<Vec<Element>> {
    case["items"]
        .as_array()
        .expect("items")
        .iter()
        .map(elements)
        .collect()
}

/// `distributeLibraryItemsOnSquareGrid` (`data/library.ts:405-493`) of the
/// items as `LibraryMenuItems.getInsertedElements` duplicates them.
#[test]
fn library_items_distribute_on_a_square_grid_as_upstream() {
    for case in cases("library") {
        let what = case["id"].as_str().unwrap();
        let mut env = ActionEnv::new();
        let duplicated = edit_actions::duplicate_library_items(&library_items(&case), &mut env)
            .unwrap_or_else(|e| panic!("{what}: {e:?}"));
        let got = edit_actions::distribute_library_items_on_square_grid(&duplicated);
        assert_elements(&got, &case["distributed"], what);
    }
}

/// Inserting library items (a click in the library, a drop on the canvas):
/// duplicated, distributed, then `addElementsFromPasteOrLibrary` at the
/// pointer, the sidebar left open only when docked and fitting.
#[test]
fn library_insertion_matches_upstream() {
    for case in cases("library") {
        let what = case["id"].as_str().unwrap();
        let scene = elements(&case);
        let mut app_state = action_app_state(&Value::Null);
        app_state.insert("openSidebar", json!({"name": "default", "tab": "library"}));
        let mut env = ActionEnv::new();
        let got = edit_actions::insert_library_items(
            &library_items(&case),
            &scene,
            &app_state,
            point(&case["pointer"]),
            case["gridSize"].as_f64(),
            case["dockedAndFits"].as_bool().unwrap(),
            &mut env,
        )
        .unwrap_or_else(|| panic!("{what}: inserts"));
        let want = &case["result"];
        let next = got.elements.as_deref().expect("the scene with the items");
        assert_elements(next, &want["elements"], what);
        assert_app_state(&got.app_state, &app_state, &want["appState"], what);
        assert!(got.capture, "{what}: the store captures the insertion");
    }
}

/// No items insert nothing.
#[test]
fn inserting_no_library_items_does_nothing() {
    let app_state = action_app_state(&Value::Null);
    let mut env = ActionEnv::new();
    assert_eq!(
        edit_actions::insert_library_items(&[], &[], &app_state, [0.0, 0.0], None, true, &mut env),
        None
    );
    assert!(edit_actions::distribute_library_items_on_square_grid(&[]).is_empty());
}
