//! Elbow arrow routing parity (ex-211).
//!
//! `tests/fixtures/elbow-routing.json` is upstream's own
//! `updateElbowArrowPoints(arrow, arrayToMap(elements), updates)`
//! (`packages/element/src/elbowArrow.ts:907-1167`) at the pinned commit,
//! generated by `tools/goldens/elbow-routing-fixtures.mjs`: unbound routes,
//! routes between bound elements of every bindable type (rotated, rounded,
//! overlapping, with arrowheads), fixed segment moves, releases, endpoint
//! drags, renormalisation and resizes, and the early returns. Every case is
//! reproduced number for number.
//!
//! `restoreElements` asks its environment for the re-route of an unbound
//! elbow arrow whose segments are not all axis-aligned
//! (`restore.ts:1076-1093`); [`RoutingEnv`] answers with this router, and
//! every `updateElbowArrowPoints` hook recorded in excali-core's
//! `restore-elements.json` is reproduced from its arguments, as is the
//! restored scene around it.

use excali_core::element::{Element, FixedPointBinding, FixedSegment};
use excali_core::json;
use excali_core::restore::{
    restore_elements, ElbowArrowRequest, RestoreElementsOptions, RestoreEnv, TestEnv,
};
use excali_editor::elbow_arrow::{
    update_elbow_arrow_points, ElbowArrowUpdate, ElbowArrowUpdates, ElementsMap, BASE_PADDING,
};
use excali_editor::restore_env::RoutingEnv;
use serde_json::{json, Map, Value};

const ROUTING: &str = include_str!("fixtures/elbow-routing.json");
const RESTORE: &str = include_str!("../../excali-core/tests/fixtures/restore-elements.json");

fn object(value: &Value) -> Map<String, Value> {
    value.as_object().expect("an object").clone()
}

fn element(value: &Value) -> Element {
    Element::from_map(object(value)).expect("an element upstream built")
}

/// The third argument as the fixture records it (JSON: a key holding
/// `null` is present, an absent key is `undefined`).
fn updates(value: &Value) -> ElbowArrowUpdates {
    let map = value.as_object().expect("updates object");
    let binding = |key: &str| {
        map.get(key).map(|b| {
            (!b.is_null())
                .then(|| serde_json::from_value::<FixedPointBinding>(b.clone()).expect("a binding"))
        })
    };
    ElbowArrowUpdates {
        points: map
            .get("points")
            .map(|p| serde_json::from_value::<Vec<[f64; 2]>>(p.clone()).expect("points")),
        fixed_segments: map.get("fixedSegments").map(|s| {
            (!s.is_null())
                .then(|| serde_json::from_value::<Vec<FixedSegment>>(s.clone()).expect("segments"))
        }),
        start_binding: binding("startBinding"),
        end_binding: binding("endBinding"),
        other_keys: map.keys().any(|k| {
            !matches!(
                k.as_str(),
                "points" | "fixedSegments" | "startBinding" | "endBinding"
            )
        }),
    }
}

/// JSON equality with numbers compared as the doubles they denote (the
/// fixture writes `39`, the port may hold `39.0`) and objects compared by
/// key, whatever their order.
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| same(p, q))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

fn route(case: &Value) -> ElbowArrowUpdate {
    let arrow = element(&case["arrow"]);
    let elements: Vec<Element> = case["elements"]
        .as_array()
        .expect("elements")
        .iter()
        .map(element)
        .collect();
    let map = ElementsMap::new(&elements);
    update_elbow_arrow_points(&arrow, &map, &updates(&case["updates"]))
        .unwrap_or_else(|e| panic!("{}: {e}", case["id"]))
}

fn cases() -> Vec<Value> {
    let fixture: Value = serde_json::from_str(ROUTING).expect("fixture parses");
    fixture["cases"].as_array().expect("cases").clone()
}

fn case(id: &str) -> Value {
    cases()
        .into_iter()
        .find(|c| c["id"] == id)
        .unwrap_or_else(|| panic!("no case {id}"))
}

/// Every fixture case, reported together.
#[test]
fn routes_match_upstream() {
    let cases = cases();
    assert!(cases.len() > 500, "the fixture has {} cases", cases.len());
    let mut failures = Vec::new();
    for case in &cases {
        let got = Value::Object(route(case).to_map());
        if !same(&got, &case["result"]) {
            failures.push(format!(
                "{}:\n  got      {}\n  upstream {}",
                case["id"].as_str().unwrap_or("?"),
                got,
                case["result"]
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

/// `elbowArrow.test.tsx` "can properly generate orthogonal arrow points":
/// `[0, 0] -> [0, 100] -> [90, 100] -> [90, 200]` at `(-45, -100.1)`.
#[test]
fn orthogonal_points_as_upstream_test() {
    let update = route(&case("upstream-orthogonal-points"));
    assert_eq!(
        update.points.as_deref(),
        Some(&[[0.0, 0.0], [0.0, 100.0], [90.0, 100.0], [90.0, 200.0]][..])
    );
    assert_eq!((update.x, update.y), (Some(-45.0), Some(-100.1)));
    assert_eq!((update.width, update.height), (Some(90.0), Some(200.0)));
}

/// `BASE_PADDING` (`elbowArrow.ts:111`) is 40: an arrow leaving the far
/// side of an element steps out to the dongle `BASE_PADDING` past the
/// element's box less the binding gaps before turning.
#[test]
fn base_padding_is_40() {
    assert_eq!(BASE_PADDING, 40.0);
    let rect = |id: &str, x: f64| {
        let mut e = element(&json!({
            "id": id, "type": "rectangle", "x": x, "y": 0, "width": 100, "height": 100,
            "angle": 0, "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
            "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
            "opacity": 100, "groupIds": [], "frameId": null, "index": null, "roundness": null,
            "seed": 1, "version": 1, "versionNonce": 0, "isDeleted": false,
            "boundElements": null, "updated": 1, "link": null, "locked": false
        }));
        e.base.id = id.to_owned();
        e
    };
    let a = rect("a", 0.0);
    let b = rect("b", 300.0);
    // start on a's left side (heading left), end on b's left side
    let arrow = element(&json!({
        "id": "arrow", "type": "arrow", "x": 0, "y": 50, "width": 300, "height": 0,
        "angle": 0, "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
        "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
        "opacity": 100, "groupIds": [], "frameId": null, "index": null, "roundness": null,
        "seed": 1, "version": 1, "versionNonce": 0, "isDeleted": false,
        "boundElements": null, "updated": 1, "link": null, "locked": false,
        "points": [[0, 0], [300, 0]],
        "startBinding": {"elementId": "a", "fixedPoint": [0, 0.5001], "mode": "orbit"},
        "endBinding": {"elementId": "b", "fixedPoint": [0, 0.5001], "mode": "orbit"},
        "startArrowhead": null, "endArrowhead": null, "elbowed": true,
        "fixedSegments": null, "startIsSpecial": null, "endIsSpecial": null
    }));
    let elements = [a, b, arrow.clone()];
    let update = update_elbow_arrow_points(
        &arrow,
        &ElementsMap::new(&elements),
        &ElbowArrowUpdates {
            points: Some(vec![[0.0, 0.0], [300.0, 0.0]]),
            ..ElbowArrowUpdates::default()
        },
    )
    .expect("routes");
    let points = update.points.expect("points");
    let x = update.x.expect("x");
    // the start is the fixed point itself, a's left edge
    assert_eq!(x, 0.0);
    // The first leg runs left past a's box grown by twice the binding gap
    // (2 * (5 + 2 / 2) = 12, elbowArrow.ts:1308-1320) to the dongle on the
    // dynamic box, BASE_PADDING - 2 * BASE_BINDING_GAP = 30 further out
    // (1370-1379): upstream's route is [0, 0], [-42, 0], [-42, 90.99...],
    // [200, 90.99...], [200, 0], [300, 0].
    let leftmost = points
        .iter()
        .map(|p| p[0] + x)
        .fold(f64::INFINITY, f64::min);
    assert_eq!(leftmost, -12.0 - (BASE_PADDING - 10.0));
    assert_eq!(points.len(), 6);
}

/// Bend penalty: with a clear straight run, the router never takes a detour
/// through extra bends (`bendMultiplier^3` on g, `elbowArrow.ts:1610-1613`).
#[test]
fn straight_run_has_no_bends() {
    let update = route(&json!({
        "id": "straight",
        "arrow": case("unbound-000")["arrow"],
        "elements": [case("unbound-000")["arrow"]],
        "updates": {"points": [[0, 0], [250, 0]]}
    }));
    assert_eq!(
        update.points.as_deref(),
        Some(&[[0.0, 0.0], [250.0, 0.0]][..])
    );
}

/// excali-core's recorded `updateElbowArrowPoints` hooks, answered by the
/// router from the same arguments.
#[test]
fn restore_hooks_are_reproduced() {
    let fixture: Value = serde_json::from_str(RESTORE).expect("restore fixture parses");
    let mut hooks = 0;
    for case in fixture["cases"].as_array().expect("cases") {
        let Some(recorded) = case["hooks"].as_array() else {
            continue;
        };
        let elements: Vec<Map<String, Value>> = case["result"]
            .as_array()
            .map(|r| r.iter().map(object).collect())
            .unwrap_or_default();
        for hook in recorded {
            if hook["hook"] != "updateElbowArrowPoints" {
                continue;
            }
            hooks += 1;
            let arrow = object(&hook["element"]);
            let points = hook["updates"]["points"]
                .as_array()
                .expect("points")
                .clone();
            let mut env = RoutingEnv::new(TestEnv::default());
            let answer = env
                .update_elbow_arrow_points(ElbowArrowRequest {
                    arrow: &arrow,
                    points: &points,
                    elements: &elements,
                })
                .unwrap_or_else(|| panic!("{}: no answer", case["id"]));
            assert!(
                same(&Value::Object(answer.clone()), &hook["result"]),
                "{}: got {}, upstream {}",
                case["id"],
                Value::Object(answer),
                hook["result"]
            );
        }
    }
    assert!(hooks >= 1, "the restore fixture records no elbow hook");
}

/// The restored scenes around those hooks: `restoreElements` with the
/// router as its environment writes exactly upstream's elements.
#[test]
fn restore_elements_with_router_matches_upstream() {
    let fixture: Value = serde_json::from_str(RESTORE).expect("restore fixture parses");
    let mut checked = 0;
    for case in fixture["cases"].as_array().expect("cases") {
        let elbow_hook = case["hooks"]
            .as_array()
            .is_some_and(|h| h.iter().any(|h| h["hook"] == "updateElbowArrowPoints"));
        if !elbow_hook || case["call"] != "restoreElements" {
            continue;
        }
        checked += 1;
        let opts = &case["opts"];
        let options = RestoreElementsOptions {
            refresh_dimensions: opts["refreshDimensions"] == true,
            repair_bindings: opts["repairBindings"] == true,
            delete_invisible_elements: opts["deleteInvisibleElements"] == true,
        };
        let elements = case["elements"].as_array().expect("elements").clone();
        let mut env = RoutingEnv::new(TestEnv::default());
        let restored = restore_elements(&elements, None, options, &mut env).expect("restores");
        let got = json::to_string_compact(&Value::Array(
            restored.into_iter().map(Value::Object).collect(),
        ));
        assert_eq!(
            got,
            json::to_string_compact(&case["result"]),
            "{}",
            case["id"]
        );
    }
    assert!(checked >= 1);
}

/// Without a route to take (an arrow already valid) restore never asks.
#[test]
fn valid_arrow_is_not_rerouted() {
    let elbow = case("fixed-stair-unbound-renormalize")["arrow"].clone();
    let mut env = RoutingEnv::new(TestEnv::default());
    let restored = restore_elements(
        std::slice::from_ref(&elbow),
        None,
        RestoreElementsOptions {
            repair_bindings: true,
            ..RestoreElementsOptions::default()
        },
        &mut env,
    )
    .expect("restores");
    assert_eq!(restored[0]["points"], elbow["points"]);
}
