//! Lasso selection parity (ex-705).
//!
//! `tests/fixtures/lasso.json` is upstream's own
//! `packages/excalidraw/lasso/index.ts` (`LassoTrail`) and `utils.ts`
//! (`getLassoSelectedElementIds`) at the pinned commit, generated by
//! `tools/goldens/lasso-fixtures.mjs`: every test of
//! `packages/excalidraw/tests/lasso.test.tsx` (`upstream-*`), run with its
//! own assertions, and seeded random scenes and paths (`random-*`), each
//! recorded as the ops that happened and the state after each.
//!
//! Every op is replayed: each `getLassoSelectedElementIds` call on its
//! inputs, and each trail op (`startPath`, `addPointToPath`,
//! `selectElementsFromIds`, `endPath`) on a [`LassoTrail`], checking the
//! selection it leaves (`selectedElementIds`, `selectedGroupIds`,
//! `selectedLinearElement`).

use excali_core::constants::DEFAULT_STROKE_STREAMLINE;
use excali_core::element::Element;
use excali_editor::lasso::{
    get_elements_segments, get_lasso_selected_element_ids, LassoInput, LassoScene, LassoSelection,
    LassoTrail,
};
use excali_editor::selection::BoxSelectionMode;
use excali_scene::bounds::ElementsMap;
use serde_json::{json, Map, Value};

const FIXTURE: &str = include_str!("fixtures/lasso.json");

fn cases() -> Vec<Value> {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("lasso.json parses");
    fixture["cases"].as_array().expect("cases").clone()
}

/// The scene's elements. lasso.test.tsx writes some freedraw elements
/// without `strokeOptions`; upstream's shape code reads a missing one as
/// variable width and the default streamline (`shape.ts:728`, `:1218`,
/// `:1274`, `:1290`), which is what `newFreeDrawElement` writes
/// (`newElement.ts:597-600`), so the port is given that.
fn scene(value: &Value) -> Vec<Element> {
    value
        .as_array()
        .expect("a scene")
        .iter()
        .map(|e| {
            let mut map = e.as_object().expect("an element").clone();
            if map["type"] == "freedraw" && !map.contains_key("strokeOptions") {
                map.insert(
                    "strokeOptions".into(),
                    json!({ "variability": "variable", "streamline": DEFAULT_STROKE_STREAMLINE }),
                );
            }
            Element::from_map(map).expect("an element upstream built")
        })
        .collect()
}

fn point(value: &Value) -> [f64; 2] {
    [value[0].as_f64().expect("x"), value[1].as_f64().expect("y")]
}

fn mode(value: &Value) -> BoxSelectionMode {
    BoxSelectionMode::from_name(value.as_str().expect("a mode"))
}

fn ids(value: &Value) -> Vec<String> {
    value
        .as_array()
        .expect("ids")
        .iter()
        .map(|v| v.as_str().expect("an id").to_owned())
        .collect()
}

fn object(value: &Value) -> Map<String, Value> {
    value.as_object().expect("an object").clone()
}

/// The app state a trail op leaves.
#[derive(Debug, Clone, PartialEq)]
struct Selection {
    selected_element_ids: Map<String, Value>,
    selected_group_ids: Map<String, Value>,
    selected_linear_element: Option<String>,
}

impl Selection {
    fn from_fixture(value: &Value) -> Selection {
        Selection {
            selected_element_ids: object(&value["selectedElementIds"]),
            selected_group_ids: object(&value["selectedGroupIds"]),
            selected_linear_element: value["selectedLinearElement"].as_str().map(str::to_owned),
        }
    }

    fn apply(&mut self, next: LassoSelection) {
        self.selected_element_ids = next.selected_element_ids;
        self.selected_group_ids = next.selected_group_ids;
        self.selected_linear_element = next.selected_linear_element;
    }
}

fn replay(case: &Value) -> usize {
    let id = case["id"].as_str().expect("an id");
    let scenes: Vec<Vec<Element>> = case["scenes"]
        .as_array()
        .expect("scenes")
        .iter()
        .map(scene)
        .collect();
    let mut trail = LassoTrail::default();
    // the trail's points so far (`originalPoints`: a repeat dropped)
    let mut points: Vec<[f64; 2]> = Vec::new();
    let mut state: Option<Selection> = None;
    let mut checked = 0;
    for (i, op) in case["ops"].as_array().expect("ops").iter().enumerate() {
        let at = || format!("{id} op {i} ({})", op["op"]);
        let elements = op.get("scene").map(|s| {
            let s = s.as_u64().expect("a scene index") as usize;
            &scenes[s]
        });
        let live: Vec<&Element> = elements
            .map(|es| es.iter().filter(|e| !e.base.is_deleted).collect())
            .unwrap_or_default();
        let map = ElementsMap::new(live.iter().copied());
        let lasso_scene = |selection: &Selection, zoom: f64, mode: BoxSelectionMode| LassoScene {
            elements: live.clone(),
            visible: live.clone(),
            zoom,
            scroll_x: 0.0,
            scroll_y: 0.0,
            mode,
            selected_element_ids: selection.selected_element_ids.clone(),
            editing_group_id: None,
        };
        match op["op"].as_str().expect("an op") {
            "ids" => {
                let all = elements.expect("a scene");
                let given: Vec<&Element> = match &op["elements"] {
                    Value::Null => live.clone(),
                    v => ids(v)
                        .iter()
                        .map(|id| all.iter().find(|e| &e.base.id == id).expect("an element"))
                        .collect(),
                };
                let path: Vec<[f64; 2]> = match &op["path"] {
                    Value::Null => points.clone(),
                    v => v.as_array().expect("a path").iter().map(point).collect(),
                };
                // the segments of what was given, as lasso.test.tsx and
                // updateSelection build them
                let segments_map = ElementsMap::new(all.iter());
                let segments = get_elements_segments(&given, &segments_map);
                let result = get_lasso_selected_element_ids(&LassoInput {
                    lasso_path: &path,
                    elements: &given,
                    elements_map: &map,
                    elements_segments: &segments,
                    simplify_distance: op["simplifyDistance"].as_f64(),
                    mode: mode(&op["mode"]),
                });
                assert_eq!(result, ids(&op["result"]), "{}", at());
            }
            "start" => {
                let prev = Selection::from_fixture(&op["prev"]);
                let mut next = state.take().unwrap_or_else(|| prev.clone());
                assert_eq!(next, prev, "{} (state before)", at());
                let [x, y] = point(&op["point"]);
                if let Some(cleared) = trail.start_path(x, y, op["keep"] == true) {
                    next.apply(cleared);
                }
                points = vec![[x, y]];
                assert_eq!(next, Selection::from_fixture(&op["state"]), "{}", at());
                state = Some(next);
            }
            "add" => {
                let mut next = state.take().expect("a state");
                let [x, y] = point(&op["point"]);
                let s = lasso_scene(&next, op["zoom"].as_f64().expect("zoom"), mode(&op["mode"]));
                if let Some(selection) = trail.add_point_to_path(x, y, op["keep"] == true, &s) {
                    next.apply(selection);
                }
                if points.last() != Some(&[x, y]) {
                    points.push([x, y]);
                }
                assert_eq!(trail.points(), points.as_slice(), "{} (points)", at());
                assert_eq!(next, Selection::from_fixture(&op["state"]), "{}", at());
                state = Some(next);
            }
            "select" => {
                let mut next = state.take().expect("a state");
                let s = lasso_scene(&next, 1.0, BoxSelectionMode::Contain);
                next.apply(trail.select_elements_from_ids(&ids(&op["ids"]), &s));
                assert_eq!(next, Selection::from_fixture(&op["state"]), "{}", at());
                state = Some(next);
            }
            "end" => {
                trail.end_path();
                assert!(!trail.has_current_trail(), "{}", at());
                points.clear();
            }
            other => panic!("{}: unknown op {other}", at()),
        }
        checked += 1;
    }
    checked
}

#[test]
fn every_case_replays_as_upstream_ran_it() {
    let cases = cases();
    assert_eq!(cases.len(), 137);
    let mut ops = 0;
    for case in &cases {
        ops += replay(case);
    }
    assert!(ops > 10_000, "{ops} ops");
}

fn upstream_case(name: &str) -> Value {
    cases()
        .into_iter()
        .find(|c| c["id"] == format!("upstream-{name}"))
        .unwrap_or_else(|| panic!("no case {name}"))
}

/// The selection the last trail op of an upstream test leaves.
fn final_selection(name: &str) -> Vec<String> {
    let case = upstream_case(name);
    let last = case["ops"]
        .as_array()
        .expect("ops")
        .iter()
        .rev()
        .find(|o| o.get("state").is_some())
        .expect("a state")
        .clone();
    let mut ids: Vec<String> = object(&last["state"]["selectedElementIds"])
        .into_iter()
        .filter(|(_, v)| v == &Value::Bool(true))
        .map(|(k, _)| k)
        .collect();
    ids.sort();
    ids
}

/// lasso.test.tsx:1911-1926: a lasso enclosing one rectangle and cutting
/// through another takes only the enclosed one in `contain` mode, both in
/// `overlap` mode.
#[test]
fn contain_takes_the_enclosed_overlap_the_crossed_too() {
    let base = "box-selection-mode-through-the-lasso-tool-lasso-enclosing-one-element-and-cutting-through-another";
    assert_eq!(
        final_selection(&format!(
            "{base}-selects-only-enclosed-elements-with-the-default-mode-contain"
        )),
        ["enclosed"]
    );
    assert_eq!(
        final_selection(&format!(
            "{base}-selects-intersected-elements-as-well-in-overlap-mode"
        )),
        ["crossed", "enclosed"]
    );
}

/// lasso.test.tsx:2137-2167: a freedraw dot has no outline and is tested
/// by the corners of its box.
#[test]
fn a_freedraw_dot_is_contained_by_its_box() {
    assert_eq!(
        final_selection(
            "box-selection-mode-through-the-lasso-tool-contains-elements-without-an-outline-such-as-a-freedraw-dot"
        ),
        ["dot"]
    );
}

/// A lasso crossing nothing leaves nothing selected, and a lasso that is
/// not started does nothing.
#[test]
fn a_trail_not_started_selects_nothing() {
    let mut trail = LassoTrail::default();
    let s = LassoScene {
        elements: Vec::new(),
        visible: Vec::new(),
        zoom: 1.0,
        scroll_x: 0.0,
        scroll_y: 0.0,
        mode: BoxSelectionMode::Contain,
        selected_element_ids: Map::new(),
        editing_group_id: None,
    };
    assert!(!trail.has_current_trail());
    assert_eq!(trail.add_point_to_path(1.0, 1.0, false, &s), None);
    assert!(trail.start_path(0.0, 0.0, true).is_none());
    assert!(trail.has_current_trail());
    assert_eq!(
        trail.start_path(0.0, 0.0, false),
        Some(LassoSelection::default())
    );
}
