//! Autoshape (draw-to-shape) recognition parity (ex-706).
//!
//! `tests/fixtures/shape-recognition.json` is upstream's own
//! `packages/element/src/convertToShape.ts` (`recognizeShape`,
//! `convertToShape`, on `packages/math/src/pca.ts`) at the pinned commit,
//! generated by `tools/goldens/shape-recognition-fixtures.mjs`: every
//! `recognizeShape` call of `packages/element/tests/recognizeShape.test.ts`
//! (`upstream-*`), run with its own assertions, seeded random strokes
//! (`random-*`) and `convertToShape` on a selection of them under varied
//! app states and frames (`convert-*`).
//!
//! Each recognize case checks the stroke features upstream extracted (to
//! the last bit), the bounding box and the recognized type; each convert
//! case checks the whole element upstream built.

use excali_core::app_state::AppState;
use excali_core::element::{Element, ElementType};
use excali_editor::convert_to_shape::{
    convert_to_shape, extract_features, recognize_shape, ConvertToShape, RecognizedShape,
};
use excali_scene::bounds::ElementsMap;
use serde_json::{json, Map, Value};

const FIXTURE: &str = include_str!("fixtures/shape-recognition.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("shape-recognition.json parses")
}

fn points(v: &Value) -> Vec<[f64; 2]> {
    v.as_array()
        .expect("points")
        .iter()
        .map(|p| [p[0].as_f64().expect("x"), p[1].as_f64().expect("y")])
        .collect()
}

fn previous(v: &Value) -> Option<ElementType> {
    v.as_str()
        .map(|t| ElementType::parse(t).unwrap_or_else(|| panic!("element type {t}")))
}

/// Structural equality with numbers compared exactly as doubles.
fn same(actual: &Value, expected: &Value) -> bool {
    match (actual, expected) {
        (Value::Number(a), Value::Number(b)) => a.as_f64() == b.as_f64(),
        (Value::Array(a), Value::Array(b)) => {
            a.len() == b.len() && a.iter().zip(b).all(|(x, y)| same(x, y))
        }
        (Value::Object(a), Value::Object(b)) => {
            a.len() == b.len() && a.iter().all(|(k, v)| b.get(k).is_some_and(|w| same(v, w)))
        }
        _ => actual == expected,
    }
}

fn report(failures: &[String], total: usize) {
    assert!(
        failures.is_empty(),
        "{} of {total} cases differ from upstream:\n{}",
        failures.len(),
        failures.iter().take(30).cloned().collect::<Vec<_>>().join("\n")
    );
}

#[test]
fn recognize_shape_matches_upstream() {
    let fixture = fixture();
    let cases = fixture["recognize"].as_array().expect("recognize");
    assert!(cases.len() > 700, "{} recognize cases", cases.len());
    let mut failures = Vec::new();
    for c in cases {
        let id = c["id"].as_str().expect("id");
        let pts = points(&c["points"]);
        let zoom = c["zoom"].as_f64().unwrap_or(1.0);
        let result = recognize_shape(&pts, previous(&c["previous"]), zoom);
        if result.shape.as_str() != c["type"] {
            failures.push(format!("{id}: type {} upstream {}", result.shape.as_str(), c["type"]));
        }
        if !same(&json!(result.bounding_box), &c["boundingBox"]) {
            failures.push(format!(
                "{id}: boundingBox {:?} upstream {}",
                result.bounding_box, c["boundingBox"]
            ));
        }
        if !c["features"].is_null() {
            let f = extract_features(&pts);
            let actual = json!({
                "gapRatio": f.gap_ratio,
                "elongation": f.elongation,
                "majorSkew": f.major_skew,
                "hullFillRatio": f.hull_fill_ratio,
                "cornerTurnShare": f.corner_turn_share,
                "kurtosisProduct": f.kurtosis_product,
                "shaftDeviationRatio": f.shaft_deviation_ratio,
            });
            if !same(&actual, &c["features"]) {
                failures.push(format!("{id}: features {actual} upstream {}", c["features"]));
            }
        }
    }
    report(&failures, cases.len());
}

fn app_state(v: &Value) -> AppState {
    let mut state = AppState::from_map(Map::new());
    for (key, value) in v.as_object().expect("appState") {
        state.insert(key.clone(), value.clone());
    }
    state
}

#[test]
fn convert_to_shape_matches_upstream() {
    let fixture = fixture();
    let cases = fixture["convert"].as_array().expect("convert");
    assert!(cases.len() > 100, "{} convert cases", cases.len());
    let mut failures = Vec::new();
    for c in cases {
        let id = c["id"].as_str().expect("id");
        let frames: Vec<Element> = c["frames"]
            .as_array()
            .expect("frames")
            .iter()
            .map(|f| Element::from_map(f.as_object().expect("frame").clone()).expect("frame"))
            .collect();
        let expected = &c["element"];
        // the element's id, seed and timestamp are upstream's randomId(),
        // randomInteger() and getUpdatedTimestamp() (test mode)
        let (eid, seed, stamp) = if expected.is_null() {
            ("unused".to_owned(), 0.0, 1.0)
        } else {
            (
                expected["id"].as_str().expect("id").to_owned(),
                expected["seed"].as_f64().expect("seed"),
                expected["updated"].as_f64().expect("updated"),
            )
        };
        let actual = convert_to_shape(&ConvertToShape {
            points: &points(&c["points"]),
            app_state: &app_state(&c["appState"]),
            elements_map: &ElementsMap::new(&frames),
            frames: &frames.iter().collect::<Vec<_>>(),
            previous: previous(&c["previous"]),
            id: &eid,
            seed,
            timestamp: stamp,
        });
        let actual = actual.map_or(Value::Null, |e| Value::Object(e.to_map()));
        if !same(&actual, expected) {
            failures.push(format!("{id}: {actual}\n  upstream {expected}"));
        }
    }
    report(&failures, cases.len());
}

#[test]
fn every_shape_is_recognized_somewhere() {
    let fixture = fixture();
    for shape in [
        RecognizedShape::Rectangle,
        RecognizedShape::Diamond,
        RecognizedShape::Ellipse,
        RecognizedShape::Line,
        RecognizedShape::Arrow,
        RecognizedShape::Freedraw,
    ] {
        assert!(
            fixture["recognize"]
                .as_array()
                .expect("recognize")
                .iter()
                .any(|c| c["type"] == shape.as_str()),
            "{}",
            shape.as_str()
        );
    }
}
