//! Snapping parity (ex-509).
//!
//! `tests/fixtures/snapping.json` is upstream's own
//! `packages/excalidraw/snapping.ts` and `renderer/renderSnaps.ts` at the
//! pinned commit, generated by `tools/goldens/snapping-fixtures.mjs`:
//! `getSnapDistance` (8 / zoom), `isSnappingEnabled`,
//! `isActiveToolNonLinearSnappable`, the element corners, the reference
//! points and visible gaps the snap cache holds, point and gap snaps of
//! dragged elements, snaps of resized and new elements, the pointer snap
//! lines, and every canvas call `renderSnaps` makes, on hand-written and
//! seeded random scenes, compared number for number.

use std::collections::HashSet;

use excali_core::element::Element;
use excali_editor::snapping::{
    get_elements_corners, get_reference_snap_points, get_snap_distance,
    get_snap_lines_at_pointer, get_visible_gaps, is_active_tool_non_linear_snappable,
    is_snapping_enabled, render_snaps, snap_dragged_elements, snap_new_element,
    snap_resizing_elements, CornersOptions, Gap, SnapAppState, SnapCache, SnapCanvasCall,
    SnapEvent, SnapLine, SnapLineDirection, SnapRenderState, VisibleGaps, SNAP_COLOR_DARK,
    SNAP_COLOR_DARK_ZEN, SNAP_COLOR_LIGHT,
};
use excali_editor::tools::ToolType;
use excali_editor::transform_handles::TransformHandleType;
use excali_editor::viewport::ViewportState;
use excali_scene::bounds::ElementsMap;
use excali_scene::shape::Theme;
use serde_json::{json, Value};

const FIXTURE: &str = include_str!("fixtures/snapping.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("snapping.json parses")
}

// -- values ---------------------------------------------------------------------------

fn elements(value: &Value) -> Vec<Element> {
    value
        .as_array()
        .expect("elements")
        .iter()
        .map(|v| {
            Element::from_map(v.as_object().expect("an element").clone())
                .expect("an element upstream built")
        })
        .collect()
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("a number, got {v}"))
}

fn point(v: &Value) -> [f64; 2] {
    [num(&v[0]), num(&v[1])]
}

fn points(v: &Value) -> Vec<[f64; 2]> {
    v.as_array().expect("points").iter().map(point).collect()
}

fn string(v: &Value) -> &str {
    v.as_str().unwrap_or_else(|| panic!("a string, got {v}"))
}

fn ids(v: &Value) -> Vec<&str> {
    v.as_array().expect("ids").iter().map(string).collect()
}

fn event(v: &Value) -> Option<SnapEvent> {
    if v.is_null() {
        None
    } else {
        Some(SnapEvent {
            ctrl_or_cmd: v["ctrlOrCmd"] == true,
        })
    }
}

fn tool(v: &Value) -> ToolType {
    ToolType::from_name(string(v)).unwrap_or_else(|| panic!("a tool, got {v}"))
}

fn state(v: &Value) -> SnapAppState {
    let or = |key: &str, default: f64| v.get(key).map(num).unwrap_or(default);
    SnapAppState {
        viewport: ViewportState {
            scroll_x: or("scrollX", 0.0),
            scroll_y: or("scrollY", 0.0),
            zoom: or("zoom", 1.0),
            width: or("width", 0.0),
            height: or("height", 0.0),
            offset_left: or("offsetLeft", 0.0),
            offset_top: or("offsetTop", 0.0),
            scroll_constraints: None,
        },
        objects_snap_mode_enabled: v["objectsSnapModeEnabled"] == true,
        grid_mode_enabled: v["gridModeEnabled"] == true,
        active_tool: tool(&v["activeTool"]),
        selected_elements_are_being_dragged: v["selectedElementsAreBeingDragged"] == true,
    }
}

// -- to JSON, the shape upstream serialises -------------------------------------------

fn pt(p: [f64; 2]) -> Value {
    json!([p[0], p[1]])
}

fn direction(d: SnapLineDirection) -> &'static str {
    match d {
        SnapLineDirection::Horizontal => "horizontal",
        SnapLineDirection::Vertical => "vertical",
    }
}

fn snap_line(line: &SnapLine) -> Value {
    match line {
        SnapLine::Points { points } => {
            json!({ "type": "points", "points": points.iter().map(|&p| pt(p)).collect::<Vec<_>>() })
        }
        SnapLine::Pointer { points, direction: d } => {
            json!({ "type": "pointer", "points": [pt(points[0]), pt(points[1])], "direction": direction(*d) })
        }
        SnapLine::Gap { direction: d, points } => {
            json!({ "type": "gap", "direction": direction(*d), "points": [pt(points[0]), pt(points[1])] })
        }
    }
}

fn snap_lines(lines: &[SnapLine]) -> Value {
    Value::Array(lines.iter().map(snap_line).collect())
}

fn gap(g: &Gap) -> Value {
    json!({
        "startBounds": g.start_bounds,
        "endBounds": g.end_bounds,
        "startSide": [pt(g.start_side[0]), pt(g.start_side[1])],
        "endSide": [pt(g.end_side[0]), pt(g.end_side[1])],
        "length": g.length,
        "overlap": g.overlap,
    })
}

fn gaps(g: &VisibleGaps) -> Value {
    json!({
        "horizontalGaps": g.horizontal_gaps.iter().map(gap).collect::<Vec<_>>(),
        "verticalGaps": g.vertical_gaps.iter().map(gap).collect::<Vec<_>>(),
    })
}

fn call(c: &SnapCanvasCall) -> Value {
    match *c {
        SnapCanvasCall::Save => json!(["save"]),
        SnapCanvasCall::Restore => json!(["restore"]),
        SnapCanvasCall::Translate(x, y) => json!(["translate", x, y]),
        SnapCanvasCall::LineWidth(w) => json!(["lineWidth", w]),
        SnapCanvasCall::StrokeStyle(s) => json!(["strokeStyle", s]),
        SnapCanvasCall::BeginPath => json!(["beginPath"]),
        SnapCanvasCall::MoveTo(x, y) => json!(["moveTo", x, y]),
        SnapCanvasCall::LineTo(x, y) => json!(["lineTo", x, y]),
        SnapCanvasCall::Stroke => json!(["stroke"]),
    }
}

/// Numbers compare as numbers (serde_json keeps 1 and 1.0 apart), and
/// exactly: the port does upstream's arithmetic in upstream's order.
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(a, b)| same(a, b))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

fn check(context: &str, actual: &Value, expected: &Value) {
    assert!(
        same(actual, expected),
        "{context}\n  expected {expected}\n  actual   {actual}"
    );
}

// -- tests -------------------------------------------------------------------------

#[test]
fn snap_distance_is_8_over_zoom() {
    let f = fixture();
    for c in f["snapDistance"].as_array().expect("snapDistance") {
        assert_eq!(get_snap_distance(num(&c["zoom"])), num(&c["result"]), "{c}");
    }
    assert_eq!(get_snap_distance(1.0), 8.0);
    assert_eq!(get_snap_distance(2.0), 4.0);
}

#[test]
fn non_linear_snappable_tools_match_upstream() {
    let f = fixture();
    let items = f["nonLinearSnappable"].as_array().expect("nonLinearSnappable");
    assert_eq!(items.len(), ToolType::ALL.len());
    for c in items {
        assert_eq!(
            is_active_tool_non_linear_snappable(tool(&c["tool"])),
            c["result"] == true,
            "{c}"
        );
    }
}

#[test]
fn is_snapping_enabled_matches_upstream() {
    let f = fixture();
    let (mut on, mut off) = (0, 0);
    for c in f["enabled"].as_array().expect("enabled") {
        let selected = elements(&c["selected"]);
        let selected: Vec<&Element> = selected.iter().collect();
        let result = is_snapping_enabled(&state(&c["state"]), event(&c["event"]), &selected);
        assert_eq!(result, c["result"] == true, "{c}");
        if result {
            on += 1
        } else {
            off += 1
        }
    }
    assert!(on > 50 && off > 50, "{on} on, {off} off");
}

struct Counts {
    corners: usize,
    drags: usize,
    snapped_drags: usize,
    resizes: usize,
    news: usize,
    pointers: usize,
    kinds: HashSet<String>,
}

fn count_kinds(counts: &mut Counts, lines: &[SnapLine]) {
    for line in lines {
        counts.kinds.insert(match line {
            SnapLine::Points { .. } => "points".to_string(),
            SnapLine::Pointer { direction: d, .. } => format!("pointer/{}", direction(*d)),
            SnapLine::Gap { direction: d, .. } => format!("gap/{}", direction(*d)),
        });
    }
}

#[test]
fn snapping_matches_upstream() {
    let f = fixture();
    let mut counts = Counts {
        corners: 0,
        drags: 0,
        snapped_drags: 0,
        resizes: 0,
        news: 0,
        pointers: 0,
        kinds: HashSet::new(),
    };
    for c in f["cases"].as_array().expect("cases") {
        let id = string(&c["id"]);
        let scene = elements(&c["elements"]);
        let all: Vec<&Element> = scene.iter().collect();
        let map = ElementsMap::new(scene.iter());
        let app = state(&c["state"]);
        let by_ids = |v: &Value| -> Vec<&Element> {
            let wanted = ids(v);
            all.iter().copied().filter(|e| wanted.contains(&e.base.id.as_str())).collect()
        };

        for (n, item) in c["corners"].as_array().expect("corners").iter().enumerate() {
            let opts = &item["opts"];
            let options = CornersOptions {
                omit_center: opts["omitCenter"] == true,
                bounding_box_corners: opts["boundingBoxCorners"] == true,
                drag_offset: opts
                    .get("dragOffset")
                    .map(|d| [num(&d["x"]), num(&d["y"])]),
            };
            let result = get_elements_corners(&by_ids(&item["ids"]), &map, options);
            let actual = Value::Array(result.into_iter().map(pt).collect());
            check(&format!("{id} corners {n}"), &actual, &item["result"]);
            counts.corners += 1;
        }

        let selected_ids: HashSet<&str> = ids(&c["selected"]).into_iter().collect();
        let selected = by_ids(&c["selected"]);
        let reference = get_reference_snap_points(&all, &selected, &app, &map);
        check(
            &format!("{id} reference points"),
            &Value::Array(reference.into_iter().map(pt).collect()),
            &c["referencePoints"],
        );
        let visible = get_visible_gaps(&all, &selected, &app, &map);
        check(&format!("{id} visible gaps"), &gaps(&visible), &c["visibleGaps"]);

        for (n, d) in c["drags"].as_array().expect("drags").iter().enumerate() {
            let context = format!("{id} drag {n} {}", d["dragOffset"]);
            let ev = event(&d["event"]);
            let mut cache = SnapCache::default();
            if d["cache"] == "app" {
                cache.maybe_cache_visible_gaps(&app, ev, &selected, &all, &map);
                cache.maybe_cache_reference_snap_points(&app, ev, &selected, &all, &map);
            }
            let mut offset = [num(&d["dragOffset"]["x"]), num(&d["dragOffset"]["y"])];
            let result =
                snap_dragged_elements(&all, &selected_ids, &mut offset, &cache, &app, ev, &map);
            let r = &d["result"];
            check(&format!("{context} offset"), &pt(offset), &r["dragOffset"]);
            check(&format!("{context} snapOffset"), &pt(result.snap_offset), &r["snapOffset"]);
            check(&format!("{context} snapLines"), &snap_lines(&result.snap_lines), &r["snapLines"]);
            counts.drags += 1;
            if result.snap_offset != [0.0, 0.0] {
                counts.snapped_drags += 1;
            }
            count_kinds(&mut counts, &result.snap_lines);
        }

        for (n, d) in c["resizes"].as_array().expect("resizes").iter().enumerate() {
            let context = format!("{id} resize {n} {} {}", d["handle"], d["dragOffset"]);
            let ev = event(&d["event"]);
            let latest = elements(&d["latest"]);
            let latest: Vec<&Element> = latest.iter().collect();
            let mut cache = SnapCache::default();
            cache.maybe_cache_reference_snap_points(&app, ev, &selected, &all, &map);
            let handle = match &d["handle"] {
                Value::String(h) => Some(TransformHandleType::parse(h).expect("a handle")),
                _ => None,
            };
            let result = snap_resizing_elements(
                &latest,
                &selected,
                &cache,
                &app,
                ev,
                point(&d["dragOffset"]),
                handle,
            );
            let r = &d["result"];
            check(&format!("{context} snapOffset"), &pt(result.snap_offset), &r["snapOffset"]);
            check(&format!("{context} snapLines"), &snap_lines(&result.snap_lines), &r["snapLines"]);
            counts.resizes += 1;
            count_kinds(&mut counts, &result.snap_lines);
        }

        for (n, d) in c["news"].as_array().expect("news").iter().enumerate() {
            let context = format!("{id} new {n}");
            let ev = event(&d["event"]);
            let element = elements(&json!([d["element"]])).remove(0);
            let mut cache = SnapCache::default();
            cache.maybe_cache_reference_snap_points(&app, ev, &[&element], &all, &map);
            let result = snap_new_element(
                &element,
                &cache,
                &app,
                ev,
                point(&d["origin"]),
                point(&d["dragOffset"]),
                &map,
            );
            let r = &d["result"];
            check(&format!("{context} snapOffset"), &pt(result.snap_offset), &r["snapOffset"]);
            check(&format!("{context} snapLines"), &snap_lines(&result.snap_lines), &r["snapLines"]);
            counts.news += 1;
            count_kinds(&mut counts, &result.snap_lines);
        }

        for (n, d) in c["pointers"].as_array().expect("pointers").iter().enumerate() {
            let context = format!("{id} pointer {n} {}", d["pointer"]);
            let result =
                get_snap_lines_at_pointer(&all, &app, point(&d["pointer"]), event(&d["event"]), &map);
            let r = &d["result"];
            check(&format!("{context} originOffset"), &pt(result.origin_offset), &r["originOffset"]);
            check(&format!("{context} snapLines"), &snap_lines(&result.snap_lines), &r["snapLines"]);
            counts.pointers += 1;
            count_kinds(&mut counts, &result.snap_lines);
        }
    }
    assert!(counts.corners >= 100, "{} corners", counts.corners);
    assert!(counts.drags >= 500, "{} drags", counts.drags);
    assert!(counts.snapped_drags >= 300, "{} snapped drags", counts.snapped_drags);
    assert!(counts.resizes >= 250, "{} resizes", counts.resizes);
    assert!(counts.news >= 150, "{} new elements", counts.news);
    assert!(counts.pointers >= 300, "{} pointers", counts.pointers);
    let mut kinds: Vec<_> = counts.kinds.into_iter().collect();
    kinds.sort();
    assert_eq!(
        kinds,
        [
            "gap/horizontal",
            "gap/vertical",
            "pointer/horizontal",
            "pointer/vertical",
            "points"
        ]
    );
}

fn parse_snap_line(v: &Value) -> SnapLine {
    let dir = |v: &Value| match string(v) {
        "horizontal" => SnapLineDirection::Horizontal,
        _ => SnapLineDirection::Vertical,
    };
    match string(&v["type"]) {
        "points" => SnapLine::Points {
            points: points(&v["points"]),
        },
        "pointer" => SnapLine::Pointer {
            points: [point(&v["points"][0]), point(&v["points"][1])],
            direction: dir(&v["direction"]),
        },
        "gap" => SnapLine::Gap {
            direction: dir(&v["direction"]),
            points: [point(&v["points"][0]), point(&v["points"][1])],
        },
        other => panic!("a snap line type, got {other}"),
    }
}

#[test]
fn render_snaps_matches_upstream() {
    let f = fixture();
    let mut colours = HashSet::new();
    let renders = f["renders"].as_array().expect("renders");
    assert!(renders.len() >= 100, "{} renders", renders.len());
    for (n, r) in renders.iter().enumerate() {
        let s = &r["state"];
        let lines: Vec<SnapLine> = r["snapLines"]
            .as_array()
            .expect("snapLines")
            .iter()
            .map(parse_snap_line)
            .collect();
        let calls = render_snaps(
            &lines,
            &SnapRenderState {
                theme: if s["theme"] == "dark" {
                    Theme::Dark
                } else {
                    Theme::Light
                },
                zen_mode_enabled: s["zenModeEnabled"] == true,
                zoom: num(&s["zoom"]),
                scroll_x: num(&s["scrollX"]),
                scroll_y: num(&s["scrollY"]),
            },
        );
        for c in &calls {
            if let SnapCanvasCall::StrokeStyle(colour) = c {
                colours.insert(*colour);
            }
        }
        let actual = Value::Array(calls.iter().map(call).collect());
        check(&format!("render {n} {s}"), &actual, &r["calls"]);
    }
    assert_eq!(SNAP_COLOR_LIGHT, "#ff6b6b");
    assert_eq!(SNAP_COLOR_DARK, "#ff9090");
    assert_eq!(SNAP_COLOR_DARK_ZEN, "#da5b5b");
    let mut colours: Vec<_> = colours.into_iter().collect();
    colours.sort();
    assert_eq!(colours, ["#da5b5b", "#ff6b6b", "#ff9090"]);
}
