//! Viewport parity (ex-505).
//!
//! `tests/fixtures/viewport.json` is upstream's own viewport code at the
//! pinned commit, generated by `tools/goldens/viewport.mjs`:
//! `getNormalizedZoom` (`scene/normalize.ts`), the coordinate transforms
//! (`packages/common/src/utils.ts:317-358`), `constrainScrollState`,
//! `getViewportForZoomWithScrollConstraints`, `zoomToFitBounds`,
//! `centerScrollOn`, `scrollBoundsIntoView`, `getClosestElementBounds` and
//! `getScrollToContentState` (`packages/excalidraw/viewport.ts`),
//! `AppViewport.translate` and `AppViewport.setViewport` step by step
//! with its animation frames (`components/App.viewport.ts`), `AppWheel.handle`
//! (`components/App.wheel.ts`) event by event, and the zoom actions of
//! `actions/actionCanvas.tsx` (perform and keyTest). Every case is
//! reproduced exactly (same doubles).
//!
//! The tests after the replay port the assertions of upstream's
//! `tests/wheel.test.tsx`, `tests/scrollConstraints.test.tsx` (pure
//! suites), `tests/viewport.test.ts` and `tests/fitToContent.test.tsx`
//! one by one, and pin the constants and the wheel formula
//! (`site/content/research/rendering.md` section 4).

use excali_core::app_state::AppState;
use excali_core::constants::{MAX_ZOOM, MIN_ZOOM, ZOOM_STEP};
use excali_core::element::Element;
use excali_editor::viewport::{
    center_scroll_on, constrain_scroll_state, ease_out, get_closest_element_bounds,
    get_normalized_zoom, get_scroll_to_content_state,
    get_viewport_for_zoom_with_scroll_constraints, handle_wheel, perform_zoom_action,
    scene_coords_to_viewport_coords, scroll_bounds_into_view, translate,
    viewport_coords_to_scene_coords, wheel_zoom_value, zoom_to_fit_bounds, AppViewport, Fit,
    InputDevice, Offsets, Overscroll, ScrollConstraints, SetViewportOptions, TooLarge,
    TranslateOptions, Viewport, ViewportAnimation, ViewportLock, ViewportState, ViewportUpdate,
    WheelContext, WheelEvent, WheelOutcome, WheelTarget, ZoomAction, ZoomKeyEvent, ZoomToFit,
    DEFAULT_OVERSCROLL,
};
use excali_math::js;
use serde_json::{json, Map, Value};

const FIXTURE: &str = include_str!("fixtures/viewport.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("viewport.json parses")
}

/// A fixture number: a JSON number, or "NaN" / "Infinity" / "-Infinity".
fn num(v: &Value) -> f64 {
    match v {
        Value::Number(n) => n.as_f64().expect("a double"),
        Value::String(s) => match s.as_str() {
            "NaN" => f64::NAN,
            "Infinity" => f64::INFINITY,
            "-Infinity" => f64::NEG_INFINITY,
            other => panic!("not a number: {other}"),
        },
        other => panic!("not a number: {other}"),
    }
}

fn opt_num(v: &Value, key: &str) -> Option<f64> {
    v.get(key).filter(|x| !x.is_null()).map(num)
}

/// Same double, NaN included; `-0` and `0` are equal (JSON writes both 0).
fn same(a: f64, b: f64) -> bool {
    (a.is_nan() && b.is_nan()) || a == b
}

fn assert_same(actual: f64, expected: f64, what: &str) {
    assert!(
        same(actual, expected),
        "{what}: got {actual:?}, upstream {expected:?}"
    );
}

fn assert_viewport(actual: Viewport, expected: &Value, what: &str) {
    assert_same(
        actual.scroll_x,
        num(&expected["scrollX"]),
        &format!("{what} scrollX"),
    );
    assert_same(
        actual.scroll_y,
        num(&expected["scrollY"]),
        &format!("{what} scrollY"),
    );
    assert_same(actual.zoom, num(&expected["zoom"]), &format!("{what} zoom"));
}

fn offsets(v: Option<&Value>) -> Offsets {
    v.filter(|v| !v.is_null())
        .map(Offsets::from_json)
        .unwrap_or_default()
}

/// A fixture state (`zoom` as a number, the rest as upstream names them).
fn state(v: &Value) -> ViewportState {
    ViewportState {
        scroll_x: opt_num(v, "scrollX").unwrap_or(0.0),
        scroll_y: opt_num(v, "scrollY").unwrap_or(0.0),
        zoom: num(&v["zoom"]),
        width: opt_num(v, "width").unwrap_or(0.0),
        height: opt_num(v, "height").unwrap_or(0.0),
        offset_left: opt_num(v, "offsetLeft").unwrap_or(0.0),
        offset_top: opt_num(v, "offsetTop").unwrap_or(0.0),
        scroll_constraints: v
            .get("scrollConstraints")
            .and_then(ScrollConstraints::from_json),
    }
}

fn bounds(v: &Value) -> [f64; 4] {
    let a = v.as_array().expect("bounds");
    [num(&a[0]), num(&a[1]), num(&a[2]), num(&a[3])]
}

fn elements(f: &Value) -> Vec<Element> {
    f["elements"]
        .as_array()
        .expect("elements")
        .iter()
        .map(|e| {
            Element::from_map(e.as_object().expect("an element").clone())
                .expect("an element upstream built")
        })
        .collect()
}

fn element_set<'a>(f: &Value, all: &'a [Element], set: &str) -> Vec<&'a Element> {
    let ids: Vec<&str> = f["elementSets"][set]
        .as_array()
        .unwrap_or_else(|| panic!("no element set {set}"))
        .iter()
        .map(|id| id.as_str().expect("an id"))
        .collect();
    all.iter()
        .filter(|e| ids.contains(&e.base.id.as_str()))
        .collect()
}

// -- constants and the zoom formula ---------------------------------------------

#[test]
fn zoom_limits_and_step_are_upstreams() {
    // constants.ts:362-364, viewport.ts:41
    assert_eq!(MIN_ZOOM, 0.1);
    assert_eq!(MAX_ZOOM, 30.0);
    assert_eq!(ZOOM_STEP, 0.1);
    assert_eq!(DEFAULT_OVERSCROLL, 150.0);
    let c = &fixture()["constants"];
    assert_eq!(num(&c["MIN_ZOOM"]), MIN_ZOOM);
    assert_eq!(num(&c["MAX_ZOOM"]), MAX_ZOOM);
    assert_eq!(num(&c["ZOOM_STEP"]), ZOOM_STEP);
    assert_eq!(num(&c["DEFAULT_OVERSCROLL"]), DEFAULT_OVERSCROLL);
}

#[test]
fn normalized_zoom_matches_upstream() {
    let f = fixture();
    let cases = f["normalizedZoom"].as_array().expect("cases");
    assert!(cases.len() >= 30);
    for c in cases {
        let input = num(&c["input"]);
        assert_same(
            get_normalized_zoom(input),
            num(&c["output"]),
            &format!("getNormalizedZoom({input:?})"),
        );
    }
}

#[test]
fn normalized_zoom_rounds_to_six_places_then_clamps() {
    // clamp(round(zoom, 6), MIN_ZOOM, MAX_ZOOM)
    assert_eq!(get_normalized_zoom(1.23456749), 1.234567);
    assert_eq!(get_normalized_zoom(1.2345675), 1.234568);
    assert_eq!(get_normalized_zoom(0.05), MIN_ZOOM);
    assert_eq!(get_normalized_zoom(-1.0), MIN_ZOOM);
    assert_eq!(get_normalized_zoom(31.0), MAX_ZOOM);
    assert_eq!(get_normalized_zoom(f64::INFINITY), MAX_ZOOM);
    assert_eq!(get_normalized_zoom(f64::NEG_INFINITY), MIN_ZOOM);
    assert!(get_normalized_zoom(f64::NAN).is_nan());
}

#[test]
fn wheel_formula() {
    // App.wheel.ts zoomBy: newZoom = z - delta/100
    //   + log10(max(1, z)) * -sign(Δ) * min(1, |Δ|/20), delta capped at
    //   ZOOM_STEP * 100, then getNormalizedZoom(max(newZoom, minZoom))
    let step = |z: f64, d: f64| wheel_zoom_value(z, d, MIN_ZOOM);
    // below 100% only the linear term: one notch of 100 is capped at 10
    assert_eq!(step(1.0, -100.0), 1.1);
    assert_eq!(step(0.5, 100.0), 0.4);
    assert_eq!(step(0.5, -4.0), 0.54);
    // above 100% the steps grow by log10(z), scaled by min(1, |Δ|/20)
    let expected = get_normalized_zoom(1.1 - 0.1 - js::log10(1.1));
    assert_eq!(step(1.1, 100.0), expected);
    assert_eq!(step(1.1, 100.0), 0.958607);
    let z = 5.0;
    let expected = get_normalized_zoom(z + 0.05 + js::log10(5.0) * (5.0 / 20.0));
    assert_eq!(step(z, -5.0), expected);
    // the limits
    assert_eq!(step(0.1, 100.0), MIN_ZOOM);
    assert_eq!(step(30.0, -100.0), MAX_ZOOM);
    // a zoom lock floors the zoom-out
    assert_eq!(wheel_zoom_value(0.6, 100.0, 0.5), 0.5);
}

// -- coordinate transforms ------------------------------------------------------

#[test]
fn coordinate_transforms_match_upstream() {
    let f = fixture();
    for c in f["coords"].as_array().expect("coords") {
        let s = state(&c["state"]);
        let [x, y] = [num(&c["point"][0]), num(&c["point"][1])];
        let (sx, sy) = viewport_coords_to_scene_coords(x, y, &s);
        assert_same(sx, num(&c["toScene"]["x"]), "toScene x");
        assert_same(sy, num(&c["toScene"]["y"]), "toScene y");
        let (vx, vy) = scene_coords_to_viewport_coords(x, y, &s);
        assert_same(vx, num(&c["toViewport"]["x"]), "toViewport x");
        assert_same(vy, num(&c["toViewport"]["y"]), "toViewport y");
    }
}

#[test]
fn coordinate_transforms_invert_each_other() {
    let s = ViewportState {
        scroll_x: 12.5,
        scroll_y: -7.25,
        zoom: 2.0,
        width: 1000.0,
        height: 800.0,
        offset_left: 10.0,
        offset_top: 20.0,
        scroll_constraints: None,
    };
    let (sx, sy) = viewport_coords_to_scene_coords(110.0, 220.0, &s);
    // (110 - 10) / 2 - 12.5, (220 - 20) / 2 + 7.25
    assert_eq!((sx, sy), (37.5, 107.25));
    assert_eq!(scene_coords_to_viewport_coords(sx, sy, &s), (110.0, 220.0));
}

// -- scroll constraints -------------------------------------------------------------

#[test]
fn constrain_scroll_state_matches_upstream() {
    let f = fixture();
    for c in f["constrain"].as_array().expect("constrain") {
        let name = c["name"].as_str().unwrap();
        let overscroll = opt_num(c, "overscroll").unwrap_or(0.0);
        assert_viewport(
            constrain_scroll_state(&state(&c["state"]), overscroll),
            &c["result"],
            name,
        );
    }
}

fn locked(x: f64, y: f64, w: f64, h: f64) -> ScrollConstraints {
    ScrollConstraints {
        x,
        y,
        width: w,
        height: h,
        lock_scroll: false,
        lock_zoom: false,
        zoom: 1.0,
        overscroll: 0.0,
        offsets: Offsets::default(),
    }
}

fn view_200x100(
    scroll_x: f64,
    scroll_y: f64,
    zoom: f64,
    lock: Option<ScrollConstraints>,
) -> ViewportState {
    ViewportState {
        scroll_x,
        scroll_y,
        zoom,
        width: 200.0,
        height: 100.0,
        offset_left: 0.0,
        offset_top: 0.0,
        scroll_constraints: lock,
    }
}

#[test]
fn upstream_scroll_lock_suites() {
    // scrollConstraints.test.tsx "constrainScrollState (pure)"
    let no_lock = constrain_scroll_state(&view_200x100(123.0, -45.0, 0.5, None), 0.0);
    assert_eq!(
        no_lock,
        Viewport {
            scroll_x: 123.0,
            scroll_y: -45.0,
            zoom: 0.5
        }
    );

    let zoom_only = ScrollConstraints {
        lock_zoom: true,
        zoom: 0.2,
        ..locked(0.0, 0.0, 1000.0, 1000.0)
    };
    let r = constrain_scroll_state(&view_200x100(9999.0, 9999.0, 1.0, Some(zoom_only)), 0.0);
    assert_eq!((r.scroll_x, r.scroll_y), (9999.0, 9999.0));

    let scroll_lock = ScrollConstraints {
        lock_scroll: true,
        ..locked(0.0, 0.0, 1000.0, 1000.0)
    };
    let r = constrain_scroll_state(
        &view_200x100(0.0, 0.0, 0.15, Some(scroll_lock.clone())),
        0.0,
    );
    assert!((r.zoom - 0.15).abs() < 1e-9);
    let corner = constrain_scroll_state(
        &view_200x100(100.0, 100.0, 1.0, Some(scroll_lock.clone())),
        0.0,
    );
    assert_eq!((corner.scroll_x, corner.scroll_y), (0.0, 0.0));
    let far = constrain_scroll_state(
        &view_200x100(-5000.0, -5000.0, 1.0, Some(scroll_lock.clone())),
        0.0,
    );
    assert_eq!((far.scroll_x, far.scroll_y), (-800.0, -900.0));
    let inside = constrain_scroll_state(
        &view_200x100(-100.0, -100.0, 1.0, Some(scroll_lock.clone())),
        0.0,
    );
    assert_eq!(
        inside,
        Viewport {
            scroll_x: -100.0,
            scroll_y: -100.0,
            zoom: 1.0
        }
    );
    let centred = constrain_scroll_state(
        &view_200x100(999.0, 0.0, 0.1, Some(scroll_lock.clone())),
        0.0,
    );
    assert!((centred.scroll_x - (200.0 / 0.1 - 1000.0) / 2.0).abs() < 1e-9);

    // "zoom lock (pure)"
    let zoom_lock = ScrollConstraints {
        lock_zoom: true,
        zoom: 0.5,
        ..locked(0.0, 0.0, 1000.0, 1000.0)
    };
    assert_eq!(
        constrain_scroll_state(&view_200x100(0.0, 0.0, 0.1, Some(zoom_lock.clone())), 0.0).zoom,
        0.5
    );
    assert_eq!(
        constrain_scroll_state(
            &view_200x100(0.0, 0.0, MAX_ZOOM, Some(zoom_lock.clone())),
            0.0
        )
        .zoom,
        MAX_ZOOM
    );
    assert_eq!(
        constrain_scroll_state(&view_200x100(0.0, 0.0, 1.5, Some(zoom_lock)), 0.0).zoom,
        1.5
    );

    // "offsets (pure)"
    let with_offsets = ScrollConstraints {
        offsets: Offsets {
            top: 10.0,
            right: 20.0,
            bottom: 30.0,
            left: 40.0,
        },
        ..scroll_lock.clone()
    };
    let r = constrain_scroll_state(
        &view_200x100(999.0, 999.0, 1.0, Some(with_offsets.clone())),
        0.0,
    );
    assert_eq!((r.scroll_x, r.scroll_y), (40.0, 10.0));
    let r = constrain_scroll_state(
        &view_200x100(-5000.0, -5000.0, 1.0, Some(with_offsets)),
        0.0,
    );
    assert_eq!((r.scroll_x, r.scroll_y), (-820.0, -930.0));
    let top_40 = ScrollConstraints {
        offsets: Offsets {
            top: 40.0,
            ..Offsets::default()
        },
        ..scroll_lock.clone()
    };
    assert_eq!(
        constrain_scroll_state(&view_200x100(0.0, 999.0, 2.0, Some(top_40)), 0.0).scroll_y,
        20.0
    );
    let left_40 = ScrollConstraints {
        overscroll: 30.0,
        offsets: Offsets {
            left: 40.0,
            ..Offsets::default()
        },
        ..scroll_lock.clone()
    };
    assert_eq!(
        constrain_scroll_state(&view_200x100(999.0, 0.0, 1.0, Some(left_40)), 30.0).scroll_x,
        70.0
    );

    // "rubberband overscroll (pure)"
    let give = ScrollConstraints {
        overscroll: 30.0,
        ..scroll_lock.clone()
    };
    assert_eq!(
        constrain_scroll_state(&view_200x100(999.0, 0.0, 1.0, Some(give.clone())), 30.0).scroll_x,
        30.0
    );
    assert_eq!(
        constrain_scroll_state(&view_200x100(999.0, 0.0, 2.0, Some(give.clone())), 30.0).scroll_x,
        15.0
    );
    assert_eq!(
        constrain_scroll_state(&view_200x100(999.0, 0.0, 1.0, Some(scroll_lock)), 0.0).scroll_x,
        0.0
    );
    let small = view_200x100(9999.0, 0.0, 0.1, Some(give));
    assert!((constrain_scroll_state(&small, 30.0).scroll_x - 800.0).abs() < 1e-9);
    assert!((constrain_scroll_state(&small, 0.0).scroll_x - 500.0).abs() < 1e-9);
}

fn set_viewport_options(v: &Value) -> SetViewportOptions {
    SetViewportOptions {
        target: v["target"].as_array().map(|_| bounds(&v["target"])),
        fit: match v.get("fit").and_then(Value::as_str) {
            Some("contain") => Fit::Contain,
            Some("none") => Fit::None,
            _ => Fit::ScaleDown,
        },
        offsets: v.get("offsets").map(Offsets::from_json),
        lock: v.get("lock").map(|l| ViewportLock {
            scroll: l["scroll"].as_bool().unwrap_or(false),
            zoom: l["zoom"].as_bool().unwrap_or(false),
            overscroll: match l.get("overscroll") {
                None | Some(Value::Bool(true)) => Overscroll::Default,
                Some(Value::Bool(false)) => Overscroll::Off,
                Some(n) => Overscroll::Give(num(n)),
            },
        }),
        animation: match v.get("animation") {
            None | Some(Value::Bool(true)) => ViewportAnimation::Default,
            Some(Value::Bool(false)) => ViewportAnimation::Off,
            Some(o) => o.get("duration").map_or(ViewportAnimation::Default, |d| {
                ViewportAnimation::Duration(num(d))
            }),
        },
    }
}

#[test]
fn set_viewport_matches_upstream() {
    let f = fixture();
    let cases = f["setViewport"].as_array().expect("setViewport");
    assert!(cases.len() >= 20);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let mut s = state(&case["state"]);
        let mut cache = case["state"]["shouldCacheIgnoreZoom"].as_bool().unwrap();
        let mut nav = AppViewport::default();
        for (i, step) in case["steps"].as_array().unwrap().iter().enumerate() {
            let what = format!("{name} step {i} {}", step["step"]);
            let kind = step["step"][0].as_str().unwrap();
            let t = num(&step["step"][1]);
            let arg = &step["step"][2];
            let mut calls: Vec<&str> = Vec::new();
            match kind {
                "set" => {
                    if let Some(patch) = nav.set_viewport(&s, &set_viewport_options(arg)) {
                        calls = vec!["requestUnfollow", "cancelSnapBack"];
                        patch.apply(&mut s, &mut cache);
                    }
                }
                "frame" => {
                    if let Some(patch) = nav.frame(t) {
                        patch.apply(&mut s, &mut cache);
                    }
                }
                "translate" => {
                    let update = ViewportUpdate {
                        scroll_x: opt_num(arg, "scrollX"),
                        scroll_y: opt_num(arg, "scrollY"),
                        zoom: opt_num(arg, "zoom"),
                    };
                    let out = nav.translate(&s, Some(update), TranslateOptions::default());
                    assert_eq!(out.is_some(), step["returned"].as_bool().unwrap(), "{what}");
                    if let Some(out) = out {
                        if out.reset_should_cache_ignore_zoom {
                            cache = false;
                        }
                        if out.translation.cancel_snap_back {
                            calls.push("cancelSnapBack");
                        }
                        calls.push("requestUnfollow");
                        s = s.with_viewport(out.translation.viewport);
                    }
                }
                other => panic!("{what}: unknown step {other}"),
            }
            assert_eq!(calls, strings(&step["calls"]), "{what} calls");
            assert_eq!(
                nav.is_locked_transition_pending(),
                step["lockedTransitionPending"].as_bool().unwrap(),
                "{what} lockedTransitionPending"
            );
            assert_eq!(
                nav.is_animating(),
                step["animating"].as_bool().unwrap(),
                "{what} animating"
            );
            let expected = &step["state"];
            assert_viewport(s.viewport(), expected, &what);
            assert_eq!(
                s.scroll_constraints,
                ScrollConstraints::from_json(&expected["scrollConstraints"]),
                "{what} scrollConstraints"
            );
            assert_eq!(
                cache,
                expected["shouldCacheIgnoreZoom"].as_bool().unwrap(),
                "{what} shouldCacheIgnoreZoom"
            );
        }
    }
}

#[test]
fn set_viewport_eases_out_over_the_duration() {
    // easeOut (packages/common/src/utils.ts:232-234): 1 - (1 - k)^4
    assert_eq!(ease_out(0.0), 0.0);
    assert_eq!(ease_out(0.5), 0.9375);
    assert_eq!(ease_out(1.0), 1.0);
    // the search menu's navigation: 300 ms, settled on the last frame
    let s = ViewportState {
        width: 1000.0,
        height: 800.0,
        ..state(&json!({ "zoom": 1 }))
    };
    let mut nav = AppViewport::default();
    let opts = SetViewportOptions {
        animation: ViewportAnimation::Duration(300.0),
        ..SetViewportOptions::new([2000.0, 1500.0, 2100.0, 1540.0])
    };
    let first = nav.set_viewport(&s, &opts).expect("resolved");
    assert_eq!(first.should_cache_ignore_zoom, Some(true));
    assert!(nav.is_animating());
    assert!(nav.frame(10.0).is_some());
    let mid = nav.frame(160.0).expect("a frame");
    assert_eq!(mid.should_cache_ignore_zoom, Some(true));
    assert!(nav.is_animating());
    let last = nav.frame(310.0).expect("the last frame");
    assert_eq!(last.should_cache_ignore_zoom, Some(false));
    assert_eq!(last.scroll_constraints, Some(None));
    assert!(!nav.is_animating());
    assert_eq!(nav.frame(400.0), None);
}

#[test]
fn zoom_at_a_point_matches_upstream() {
    let f = fixture();
    for c in f["zoomAt"].as_array().expect("zoomAt") {
        let name = c["name"].as_str().unwrap();
        let r = get_viewport_for_zoom_with_scroll_constraints(
            num(&c["viewportX"]),
            num(&c["viewportY"]),
            num(&c["nextZoom"]),
            &state(&c["state"]),
        );
        assert_viewport(r, &c["result"], name);
    }
}

#[test]
fn zooming_keeps_the_screen_space_overscroll() {
    // scrollConstraints.test.tsx "preserves the screen-space overscroll
    // distance while zooming"
    let lock = ScrollConstraints {
        lock_scroll: true,
        overscroll: 50.0,
        ..locked(0.0, 0.0, 1000.0, 1000.0)
    };
    let s = view_200x100(0.0, 50.0, 1.0, Some(lock));
    let v = get_viewport_for_zoom_with_scroll_constraints(0.0, 0.0, get_normalized_zoom(2.0), &s);
    let resting = constrain_scroll_state(&s.with_viewport(v), 0.0);
    assert_eq!(v.zoom, 2.0);
    assert!(((v.scroll_y - resting.scroll_y) * v.zoom - 50.0).abs() < 1e-9);
}

fn translate_opts(v: Option<&Value>) -> TranslateOptions {
    let flag = |k: &str| {
        v.and_then(|o| o.get(k))
            .and_then(Value::as_bool)
            .unwrap_or(false)
    };
    TranslateOptions {
        zoom_pre_constrained: flag("zoomPreConstrained"),
        preserve_scroll_constraints_snap_back: flag("preserveScrollConstraintsSnapBack"),
    }
}

fn translation_calls(t: &excali_editor::viewport::Translation) -> Vec<&'static str> {
    // AppViewport.translate: cancel the snap-back animation (unless
    // preserved), request unfollow, then the state update, which may
    // schedule the snap-back
    let mut calls = Vec::new();
    if t.cancel_snap_back {
        calls.push("cancelSnapBack");
    }
    calls.push("requestUnfollow");
    if t.schedule_snap_back {
        calls.push("scheduleSnapBack");
    }
    calls
}

fn strings(v: &Value) -> Vec<&str> {
    v.as_array()
        .expect("strings")
        .iter()
        .map(|s| s.as_str().expect("a string"))
        .collect()
}

#[test]
fn translate_matches_upstream() {
    let f = fixture();
    for c in f["translate"].as_array().expect("translate") {
        let name = c["name"].as_str().unwrap();
        let update = (!c["update"].is_null()).then(|| ViewportUpdate {
            scroll_x: opt_num(&c["update"], "scrollX"),
            scroll_y: opt_num(&c["update"], "scrollY"),
            zoom: opt_num(&c["update"], "zoom"),
        });
        let t = translate(&state(&c["state"]), update, translate_opts(c.get("opts")));
        assert_eq!(translation_calls(&t), strings(&c["calls"]), "{name} calls");
        assert_viewport(t.viewport, &c["result"], name);
    }
}

// -- zoom to fit, scrolling to bounds ------------------------------------------------

fn fit_options(bounds: [f64; 4], offsets: Offsets, o: &Value) -> ZoomToFit {
    ZoomToFit {
        bounds,
        canvas_offsets: offsets,
        fit: match o.get("fit").and_then(Value::as_str) {
            None | Some("scale-down") => Fit::ScaleDown,
            Some("contain") => Fit::Contain,
            Some("none") => Fit::None,
            Some(other) => panic!("fit {other}"),
        },
        min_zoom: opt_num(o, "minZoom").unwrap_or(f64::NEG_INFINITY),
        max_zoom: opt_num(o, "maxZoom").unwrap_or(f64::INFINITY),
        stepped_zoom: o
            .get("steppedZoom")
            .and_then(Value::as_bool)
            .unwrap_or(false),
    }
}

#[test]
fn zoom_to_fit_bounds_matches_upstream() {
    let f = fixture();
    let cases = f["zoomToFitBounds"].as_array().expect("cases");
    assert!(cases.len() >= 900);
    for (i, c) in cases.iter().enumerate() {
        let opts = fit_options(
            bounds(&c["bounds"]),
            offsets(c.get("offsets")),
            &c["options"],
        );
        let r = zoom_to_fit_bounds(&opts, &state(&c["state"]));
        assert_viewport(r, &c["result"], &format!("zoomToFitBounds #{i} {c}"));
    }
}

#[test]
fn zoom_to_fit_upstream_cases() {
    let s = |w: f64, h: f64, zoom: f64| ViewportState {
        scroll_x: 0.0,
        scroll_y: 0.0,
        zoom,
        width: w,
        height: h,
        offset_left: 0.0,
        offset_top: 0.0,
        scroll_constraints: None,
    };
    // fitToContent.test.tsx "scale-down": a 50 x 100 element in a 10 x 10 view
    let r = zoom_to_fit_bounds(
        &ZoomToFit::new([50.0, 100.0, 100.0, 200.0]),
        &s(10.0, 10.0, 1.0),
    );
    assert!(r.zoom <= 0.1);
    // two 20 x 20 elements spanning 100 x 100
    let r = zoom_to_fit_bounds(
        &ZoomToFit::new([0.0, 0.0, 100.0, 100.0]),
        &s(10.0, 10.0, 1.0),
    );
    assert!(r.zoom <= 0.1);
    // "contain" scrolls to the element
    let contain = ZoomToFit {
        fit: Fit::Contain,
        ..ZoomToFit::new([100.0, 100.0, 200.0, 200.0])
    };
    let r = zoom_to_fit_bounds(&contain, &s(10.0, 10.0, 1.0));
    assert_eq!(r.zoom, 0.1);
    assert!(r.scroll_x != 0.0 && r.scroll_y != 0.0);
    // "none" keeps the zoom and centres the target
    let none = ZoomToFit {
        fit: Fit::None,
        ..ZoomToFit::new([1000.0, 1000.0, 1050.0, 1050.0])
    };
    let r = zoom_to_fit_bounds(&none, &s(100.0, 100.0, 0.5));
    assert_eq!(r.zoom, 0.5);
    assert!((r.scroll_x - (100.0 / 2.0 / 0.5 - 1025.0)).abs() < 1e-9);
    assert!((r.scroll_y - (100.0 / 2.0 / 0.5 - 1025.0)).abs() < 1e-9);
    // scale-down never zooms past 100%
    let r = zoom_to_fit_bounds(
        &ZoomToFit::new([0.0, 0.0, 10.0, 10.0]),
        &s(1000.0, 800.0, 0.5),
    );
    assert_eq!(r.zoom, 1.0);
}

#[test]
fn center_scroll_on_matches_upstream() {
    let f = fixture();
    for c in f["centerScrollOn"].as_array().expect("cases") {
        let (x, y) = center_scroll_on(
            (num(&c["scenePoint"]["x"]), num(&c["scenePoint"]["y"])),
            num(&c["viewportDimensions"]["width"]),
            num(&c["viewportDimensions"]["height"]),
            num(&c["zoom"]),
            &offsets(c.get("offsets")),
        );
        assert_same(
            x,
            num(&c["result"]["scrollX"]),
            &format!("centerScrollOn {c}"),
        );
        assert_same(
            y,
            num(&c["result"]["scrollY"]),
            &format!("centerScrollOn {c}"),
        );
    }
}

#[test]
fn scroll_bounds_into_view_matches_upstream() {
    let f = fixture();
    for c in f["scrollBoundsIntoView"].as_array().expect("cases") {
        let name = c["name"].as_str().unwrap();
        let too_large = match c.get("tooLarge").and_then(Value::as_str) {
            None | Some("alignStart") => TooLarge::AlignStart,
            Some("leave") => TooLarge::Leave,
            Some(other) => panic!("tooLarge {other}"),
        };
        let r = scroll_bounds_into_view(
            bounds(&c["bounds"]),
            &state(&c["state"]),
            &offsets(c.get("offsets")),
            too_large,
        );
        match (&c["result"], r) {
            (Value::Null, None) => {}
            (Value::Null, Some(r)) => panic!("{name}: got {r:?}, upstream null"),
            (_, None) => panic!("{name}: got null, upstream {}", c["result"]),
            (want, Some((x, y))) => {
                assert_same(x, num(&want["scrollX"]), name);
                assert_same(y, num(&want["scrollY"]), name);
            }
        }
    }
}

#[test]
fn scroll_bounds_into_view_upstream_cases() {
    // tests/viewport.test.ts
    let s = |zoom: f64| ViewportState {
        scroll_x: 0.0,
        scroll_y: 0.0,
        zoom,
        width: 1000.0,
        height: 800.0,
        offset_left: 0.0,
        offset_top: 0.0,
        scroll_constraints: None,
    };
    let none = Offsets::default();
    let right = |r: f64| Offsets {
        right: r,
        ..Offsets::default()
    };
    let go = |b: [f64; 4], st: &ViewportState, o: &Offsets, t: TooLarge| {
        scroll_bounds_into_view(b, st, o, t)
    };
    assert_eq!(
        go(
            [100.0, 100.0, 200.0, 200.0],
            &s(1.0),
            &none,
            TooLarge::AlignStart
        ),
        None
    );
    assert_eq!(
        go(
            [900.0, -30.0, 1050.0, 100.0],
            &s(1.0),
            &none,
            TooLarge::AlignStart
        ),
        Some((-50.0, 30.0))
    );
    assert_eq!(
        go(
            [900.0, 100.0, 1000.0, 200.0],
            &s(1.0),
            &right(320.0),
            TooLarge::AlignStart
        ),
        Some((-320.0, 0.0))
    );
    assert_eq!(
        go(
            [450.0, 100.0, 550.0, 150.0],
            &s(2.0),
            &none,
            TooLarge::AlignStart
        ),
        Some((-50.0, 0.0))
    );
    assert_eq!(
        go(
            [100.0, 500.0, 200.0, 2000.0],
            &s(1.0),
            &none,
            TooLarge::AlignStart
        ),
        Some((0.0, -500.0))
    );
    assert_eq!(
        go(
            [100.0, 500.0, 200.0, 2000.0],
            &s(1.0),
            &none,
            TooLarge::Leave
        ),
        None
    );
    let both = Offsets {
        left: 600.0,
        right: 600.0,
        ..Offsets::default()
    };
    assert_eq!(
        go(
            [900.0, 0.0, 1100.0, 10.0],
            &s(1.0),
            &both,
            TooLarge::AlignStart
        ),
        None
    );
}

#[test]
fn closest_element_bounds_match_upstream() {
    let f = fixture();
    let all = elements(&f);
    for c in f["closestElementBounds"].as_array().expect("cases") {
        let set = element_set(&f, &all, c["set"].as_str().unwrap());
        let r = get_closest_element_bounds(&set, (num(&c["from"]["x"]), num(&c["from"]["y"])));
        let want = bounds(&c["result"]);
        for i in 0..4 {
            assert_same(r[i], want[i], &format!("getClosestElementBounds {c}"));
        }
    }
}

#[test]
fn scroll_to_content_matches_upstream() {
    let f = fixture();
    let all = elements(&f);
    for c in f["scrollToContent"].as_array().expect("cases") {
        let set = element_set(&f, &all, c["set"].as_str().unwrap());
        let (x, y) = get_scroll_to_content_state(&set, &state(&c["state"]));
        assert_same(
            x,
            num(&c["result"]["scrollX"]),
            &format!("getScrollToContentState {c}"),
        );
        assert_same(
            y,
            num(&c["result"]["scrollY"]),
            &format!("getScrollToContentState {c}"),
        );
    }
}

// -- the wheel ---------------------------------------------------------------------------

fn wheel_event(e: &Value) -> WheelEvent {
    let flag = |k: &str| e.get(k).and_then(Value::as_bool).unwrap_or(false);
    WheelEvent {
        delta_x: opt_num(e, "deltaX").unwrap_or(0.0),
        delta_y: opt_num(e, "deltaY").unwrap_or(0.0),
        ctrl_key: flag("ctrlKey"),
        meta_key: flag("metaKey"),
        shift_key: flag("shiftKey"),
        buttons: e.get("buttons").and_then(Value::as_u64).unwrap_or(0) as u16,
        target: match e.get("target").and_then(Value::as_str).unwrap_or("canvas") {
            "canvas" => WheelTarget::Canvas,
            "textarea" => WheelTarget::TextArea,
            "iframe" => WheelTarget::IFrame,
            "frameName" => WheelTarget::FrameName,
            "other" => WheelTarget::Other,
            other => panic!("target {other}"),
        },
    }
}

fn outcome_calls(o: &WheelOutcome) -> Vec<&'static str> {
    let mut calls = Vec::new();
    if o.flush_pan_move {
        calls.push("flushMove");
    }
    if let Some(t) = &o.translation {
        calls.extend(translation_calls(t));
    }
    if o.reset_should_cache_ignore_zoom {
        calls.push("resetShouldCacheIgnoreZoom");
    }
    calls
}

#[test]
fn wheel_matches_upstream_event_by_event() {
    let f = fixture();
    let wheel = &f["wheel"];
    // the fixture ran with navigator.platform "" (not a Mac): CTRL_OR_CMD
    // is ctrlKey
    let is_darwin = wheel["ctrlOrCmd"] == "metaKey";
    let sequences = wheel["sequences"].as_array().expect("sequences");
    assert!(sequences.len() >= 200);
    for seq in sequences {
        let name = seq["name"].as_str().unwrap();
        let mut s = state(&seq["state"]);
        let mut should_cache_ignore_zoom = false;
        let ctx = WheelContext {
            navigation_enabled: seq["navigation"].as_bool().unwrap(),
            pan_active: seq["panActive"].as_bool().unwrap(),
            input_device: InputDevice::from_name(seq["state"]["inputDevice"].as_str().unwrap())
                .unwrap(),
            last_position: (
                num(&seq["lastPosition"]["x"]),
                num(&seq["lastPosition"]["y"]),
            ),
            is_darwin,
        };
        for (i, step) in seq["steps"].as_array().unwrap().iter().enumerate() {
            let what = format!("{name} step {i} {}", step["event"]);
            let o = handle_wheel(&s, &ctx, &wheel_event(&step["event"]));
            assert_eq!(
                o.prevent_default,
                step["prevented"].as_bool().unwrap(),
                "{what} prevented"
            );
            assert_eq!(outcome_calls(&o), strings(&step["calls"]), "{what} calls");
            if let Some(t) = &o.translation {
                s = s.with_viewport(t.viewport);
            }
            should_cache_ignore_zoom |= o.should_cache_ignore_zoom;
            assert_viewport(s.viewport(), &step["state"], &what);
            assert_eq!(
                should_cache_ignore_zoom,
                step["state"]["shouldCacheIgnoreZoom"].as_bool().unwrap(),
                "{what}"
            );
        }
    }
}

fn editor(zoom: f64, input_device: InputDevice) -> (ViewportState, WheelContext) {
    (
        ViewportState {
            scroll_x: 0.0,
            scroll_y: 0.0,
            zoom,
            width: 1000.0,
            height: 800.0,
            offset_left: 0.0,
            offset_top: 0.0,
            scroll_constraints: None,
        },
        WheelContext {
            navigation_enabled: true,
            pan_active: false,
            input_device,
            last_position: (100.0, 100.0),
            is_darwin: false,
        },
    )
}

fn ev(delta_x: f64, delta_y: f64) -> WheelEvent {
    WheelEvent {
        delta_x,
        delta_y,
        ..WheelEvent::default()
    }
}

fn apply(s: &ViewportState, o: &WheelOutcome) -> ViewportState {
    o.translation
        .as_ref()
        .map_or_else(|| s.clone(), |t| s.with_viewport(t.viewport))
}

#[test]
fn upstream_wheel_suite() {
    // wheel.test.tsx "pans on plain wheel, horizontally with shift, and
    // zooms on ctrl/cmd+wheel"
    let (s, ctx) = editor(1.0, InputDevice::Auto);
    let s = apply(&s, &handle_wheel(&s, &ctx, &ev(30.0, 40.0)));
    assert_eq!(
        s.viewport(),
        Viewport {
            scroll_x: -30.0,
            scroll_y: -40.0,
            zoom: 1.0
        }
    );
    let s = apply(
        &s,
        &handle_wheel(
            &s,
            &ctx,
            &WheelEvent {
                shift_key: true,
                ..ev(0.0, 40.0)
            },
        ),
    );
    assert_eq!(
        s.viewport(),
        Viewport {
            scroll_x: -70.0,
            scroll_y: -40.0,
            zoom: 1.0
        }
    );
    let zoomed = apply(
        &s,
        &handle_wheel(
            &s,
            &ctx,
            &WheelEvent {
                ctrl_key: true,
                ..ev(0.0, -100.0)
            },
        ),
    );
    assert!(zoomed.zoom > 1.0);
    let out = apply(
        &zoomed,
        &handle_wheel(
            &zoomed,
            &ctx,
            &WheelEvent {
                meta_key: true,
                ..ev(0.0, 100.0)
            },
        ),
    );
    assert!(out.zoom < zoomed.zoom);

    // "does nothing on a zoom tick at the zoom limit"
    let (s, ctx) = editor(MIN_ZOOM, InputDevice::Auto);
    let o = handle_wheel(
        &s,
        &ctx,
        &WheelEvent {
            ctrl_key: true,
            ..ev(0.0, 100.0)
        },
    );
    assert_eq!(apply(&s, &o).viewport(), s.viewport());
    assert!(!o.should_cache_ignore_zoom);

    // "wheel button held down: zooms instead of panning, whatever the modifiers"
    let (s, ctx) = editor(1.0, InputDevice::Auto);
    let held = |dy: f64, shift: bool| WheelEvent {
        buttons: 4,
        shift_key: shift,
        ..ev(0.0, dy)
    };
    let a = apply(&s, &handle_wheel(&s, &ctx, &held(-100.0, false)));
    assert!(a.zoom > 1.0);
    let b = apply(&a, &handle_wheel(&a, &ctx, &held(100.0, false)));
    assert!(b.zoom < a.zoom);
    let c = apply(&b, &handle_wheel(&b, &ctx, &held(-100.0, true)));
    assert!(c.zoom > b.zoom);

    // "zooms during the wheel-button drag-pan the button started"
    let (s, mut ctx) = editor(1.0, InputDevice::Auto);
    ctx.pan_active = true;
    let o = handle_wheel(&s, &ctx, &ev(0.0, 40.0));
    assert!(o.translation.is_none() && !o.flush_pan_move);
    let o = handle_wheel(&s, &ctx, &held(-100.0, false));
    assert!(o.flush_pan_move);
    assert!(apply(&s, &o).zoom > 1.0);
    ctx.pan_active = false;
    let released = apply(&s, &o);
    let after = apply(&released, &handle_wheel(&released, &ctx, &ev(0.0, 40.0)));
    assert!((after.scroll_y - (released.scroll_y - 40.0 / released.zoom)).abs() < 1e-9);
}

#[test]
fn upstream_input_device_suite() {
    // "defaults to auto, which resolves to trackpad until detection exists"
    let app_state = AppState::default();
    assert_eq!(InputDevice::from_app_state(&app_state), InputDevice::Auto);
    assert_eq!(InputDevice::Auto.resolve(), InputDevice::Trackpad);

    // "shift+wheel with %s input": pans only the named axis
    for device in [InputDevice::Auto, InputDevice::Mouse, InputDevice::Trackpad] {
        for (ctrl, meta, vertical) in [
            (false, false, false),
            (true, false, true),
            (false, true, true),
        ] {
            let (mut s, ctx) = editor(2.0, device);
            s.scroll_x = 12.0;
            s.scroll_y = 34.0;
            let e = WheelEvent {
                shift_key: true,
                ctrl_key: ctrl,
                meta_key: meta,
                ..ev(10.0, 40.0)
            };
            let moved = apply(&s, &handle_wheel(&s, &ctx, &e));
            let want = if vertical { (12.0, 14.0) } else { (-8.0, 34.0) };
            assert_eq!(
                (moved.scroll_x, moved.scroll_y, moved.zoom),
                (want.0, want.1, 2.0),
                "{device:?}"
            );
            let e = WheelEvent {
                shift_key: true,
                ctrl_key: ctrl,
                meta_key: meta,
                ..ev(-40.0, 0.0)
            };
            let back = apply(&moved, &handle_wheel(&moved, &ctx, &e));
            assert_eq!(back.viewport(), s.viewport(), "{device:?}");
        }
    }

    // "mouse": zooms around the pointer on plain, ctrl and cmd wheel
    for (ctrl, meta) in [(false, false), (true, false), (false, true)] {
        let (s, ctx) = editor(1.0, InputDevice::Mouse);
        let before = viewport_coords_to_scene_coords(100.0, 100.0, &s);
        let e = |dy: f64| WheelEvent {
            ctrl_key: ctrl,
            meta_key: meta,
            ..ev(0.0, dy)
        };
        let zoomed = apply(&s, &handle_wheel(&s, &ctx, &e(-100.0)));
        assert!(zoomed.zoom > 1.0);
        let p = viewport_coords_to_scene_coords(100.0, 100.0, &zoomed);
        assert!((p.0 - before.0).abs() < 1e-9 && (p.1 - before.1).abs() < 1e-9);
        let out = apply(&zoomed, &handle_wheel(&zoomed, &ctx, &e(100.0)));
        assert!(out.zoom < zoomed.zoom);
        let p = viewport_coords_to_scene_coords(100.0, 100.0, &out);
        assert!((p.0 - before.0).abs() < 1e-9 && (p.1 - before.1).abs() < 1e-9);
    }
    // "keeps zooming with the wheel button held"
    let (s, ctx) = editor(1.0, InputDevice::Mouse);
    let e = WheelEvent {
        buttons: 4,
        ctrl_key: true,
        shift_key: true,
        ..ev(0.0, -100.0)
    };
    assert!(apply(&s, &handle_wheel(&s, &ctx, &e)).zoom > 1.0);
    // "pans sideways on a horizontal-only wheel instead of zooming"
    let o = handle_wheel(&s, &ctx, &ev(30.0, 0.0));
    assert_eq!(
        apply(&s, &o).viewport(),
        Viewport {
            scroll_x: -30.0,
            scroll_y: 0.0,
            zoom: 1.0
        }
    );
    assert!(!o.should_cache_ignore_zoom);
}

#[test]
fn wheel_outside_the_editor_surfaces() {
    let (s, ctx) = editor(1.0, InputDevice::Auto);
    // menus and sidebars keep scrolling; only the browser zoom is prevented
    let o = handle_wheel(
        &s,
        &ctx,
        &WheelEvent {
            target: WheelTarget::Other,
            ..ev(0.0, 40.0)
        },
    );
    assert!(!o.prevent_default && o.translation.is_none());
    let o = handle_wheel(
        &s,
        &ctx,
        &WheelEvent {
            target: WheelTarget::Other,
            ctrl_key: true,
            ..ev(0.0, 40.0)
        },
    );
    assert!(o.prevent_default && o.translation.is_none());
    // CTRL_OR_CMD is metaKey on a Mac
    let mac = WheelContext {
        is_darwin: true,
        ..ctx
    };
    let o = handle_wheel(
        &s,
        &mac,
        &WheelEvent {
            target: WheelTarget::Other,
            meta_key: true,
            ..ev(0.0, 40.0)
        },
    );
    assert!(o.prevent_default && o.translation.is_none());
    let o = handle_wheel(
        &s,
        &mac,
        &WheelEvent {
            target: WheelTarget::Other,
            ctrl_key: true,
            ..ev(0.0, 40.0)
        },
    );
    assert!(!o.prevent_default);
    // frame labels are editor surface: "wheel over a frame label is handled once"
    let o = handle_wheel(
        &s,
        &ctx,
        &WheelEvent {
            target: WheelTarget::FrameName,
            ..ev(0.0, 40.0)
        },
    );
    assert_eq!(apply(&s, &o).scroll_y, -40.0);
    // navigation disabled: nothing at all
    let off = WheelContext {
        navigation_enabled: false,
        ..ctx
    };
    let o = handle_wheel(
        &s,
        &off,
        &WheelEvent {
            ctrl_key: true,
            ..ev(0.0, 40.0)
        },
    );
    assert!(!o.prevent_default && o.translation.is_none());
}

// -- zoom actions --------------------------------------------------------------------

#[test]
fn zoom_actions_match_upstream() {
    let f = fixture();
    let all = elements(&f);
    let a = &f["actions"];
    let states = &a["elementStates"];
    let performed = a["performed"].as_array().expect("performed");
    assert!(performed.len() >= 1000);
    for c in performed {
        let action = ZoomAction::from_name(c["action"].as_str().unwrap()).expect("an action");
        let s = state(&states[c["state"].as_str().unwrap()]);
        let scene = element_set(&f, &all, c["elements"].as_str().unwrap());
        let selected: Map<String, Value> = match c["selection"].as_str().unwrap() {
            "none" => json!({}),
            "rect" => json!({ "rect": true }),
            "rect-and-arrow" => json!({ "rect": true, "arrow": true }),
            "deleted-only" => json!({ "deleted": true }),
            "freedraw-and-text" => json!({ "freedraw": true, "text": true }),
            other => panic!("selection {other}"),
        }
        .as_object()
        .cloned()
        .unwrap_or_default();
        let offsets = match c["offsets"].as_str().unwrap() {
            "none" => Offsets::default(),
            "ui" => Offsets {
                left: 216.0,
                top: 60.0,
                right: 302.0,
                bottom: 50.0,
            },
            other => panic!("offsets {other}"),
        };
        assert_eq!(strings(&c["calls"]), ["requestUnfollow"]);
        let r = perform_zoom_action(action, &s, &scene, &selected, &offsets);
        assert_viewport(r, &c["result"], &format!("{c}"));
    }
}

#[test]
fn zoom_action_keys_match_upstream() {
    let f = fixture();
    for c in f["actions"]["keys"].as_array().expect("keys") {
        let e = ZoomKeyEvent {
            code: c["code"].as_str().unwrap(),
            shift_key: c["shiftKey"].as_bool().unwrap(),
            alt_key: c["altKey"].as_bool().unwrap(),
            ctrl_or_cmd: c["ctrlOrCmd"].as_bool().unwrap(),
        };
        let matches: Vec<&str> = ZoomAction::ALL
            .iter()
            .filter(|a| a.key_test(&e))
            .map(|a| a.name())
            .collect();
        assert_eq!(matches, strings(&c["matches"]), "{c}");
    }
}

#[test]
fn zoom_actions_step_by_zoom_step_around_the_centre() {
    let s = ViewportState {
        scroll_x: 0.0,
        scroll_y: 0.0,
        zoom: 1.0,
        width: 1000.0,
        height: 800.0,
        offset_left: 0.0,
        offset_top: 0.0,
        scroll_constraints: None,
    };
    let none = Offsets::default();
    let zin = perform_zoom_action(ZoomAction::ZoomIn, &s, &[], &Map::new(), &none);
    assert_eq!(zin.zoom, 1.1);
    // the viewport centre stays put
    let c0 = viewport_coords_to_scene_coords(500.0, 400.0, &s);
    let c1 = viewport_coords_to_scene_coords(500.0, 400.0, &s.with_viewport(zin));
    assert!((c0.0 - c1.0).abs() < 1e-9 && (c0.1 - c1.1).abs() < 1e-9);
    assert_eq!(
        perform_zoom_action(ZoomAction::ZoomOut, &s, &[], &Map::new(), &none).zoom,
        0.9
    );
    let max = ViewportState {
        zoom: MAX_ZOOM,
        ..s.clone()
    };
    assert_eq!(
        perform_zoom_action(ZoomAction::ZoomIn, &max, &[], &Map::new(), &none).zoom,
        MAX_ZOOM
    );
    let min = ViewportState {
        zoom: MIN_ZOOM,
        ..s.clone()
    };
    assert_eq!(
        perform_zoom_action(ZoomAction::ZoomOut, &min, &[], &Map::new(), &none).zoom,
        MIN_ZOOM
    );
    let far = ViewportState {
        zoom: 7.5,
        ..s.clone()
    };
    assert_eq!(
        perform_zoom_action(ZoomAction::ResetZoom, &far, &[], &Map::new(), &none).zoom,
        1.0
    );
    // scrollConstraints.test.tsx "resets zoom to the locked minimum zoom"
    let lock = ScrollConstraints {
        lock_zoom: true,
        zoom: 0.5,
        ..locked(0.0, 0.0, 4000.0, 3000.0)
    };
    let locked_state = ViewportState {
        zoom: 2.0,
        scroll_constraints: Some(lock),
        ..s
    };
    assert_eq!(
        perform_zoom_action(
            ZoomAction::ResetZoom,
            &locked_state,
            &[],
            &Map::new(),
            &none
        )
        .zoom,
        0.5
    );
}

// -- app state --------------------------------------------------------------------------

#[test]
fn viewport_state_reads_and_writes_the_app_state() {
    let mut app_state = AppState::default();
    let s = ViewportState::from_app_state(&app_state);
    assert_eq!(
        s.viewport(),
        Viewport {
            scroll_x: 0.0,
            scroll_y: 0.0,
            zoom: 1.0
        }
    );
    assert_eq!(s.scroll_constraints, None);
    app_state.insert("width", json!(1024));
    app_state.insert("height", json!(768));
    app_state.insert("offsetLeft", json!(8));
    app_state.insert("offsetTop", json!(16));
    app_state.insert(
        "scrollConstraints",
        json!({"x": 1, "y": 2, "width": 3, "height": 4, "lockScroll": true, "lockZoom": false, "zoom": 0.5, "overscroll": 150, "offsets": {"left": 10}}),
    );
    let s = ViewportState::from_app_state(&app_state);
    assert_eq!(
        (s.width, s.height, s.offset_left, s.offset_top),
        (1024.0, 768.0, 8.0, 16.0)
    );
    let lock = s.scroll_constraints.clone().expect("a lock");
    assert!(lock.lock_scroll && !lock.lock_zoom);
    assert_eq!(
        lock.offsets,
        Offsets {
            left: 10.0,
            ..Offsets::default()
        }
    );
    assert_eq!(ScrollConstraints::from_json(&lock.to_json()), Some(lock));
    Viewport {
        scroll_x: -3.5,
        scroll_y: 7.25,
        zoom: 2.0,
    }
    .write_to(&mut app_state);
    assert_eq!(app_state.get("scrollX"), Some(&json!(-3.5)));
    assert_eq!(app_state.get("scrollY"), Some(&json!(7.25)));
    assert_eq!(app_state.zoom(), Some(2.0));
}
