//! The phone layout: `MobileMenu` (`components/MobileMenu.tsx`), the top
//! bar and the bottom bar LayerUI renders on a phone instead of the
//! desktop's top menu (`LayerUI.tsx:612-629`), and its `MobileToolbar`
//! (`components/MobileToolbar.tsx`) with the tool popovers of
//! `components/ToolPopover.tsx` and `Tools.tsx` (`SelectionToolPopover`,
//! `FreedrawToolPopover`).
//!
//! A phone is an editor at most 599 px wide, or less than 500 px high and
//! 1000 px wide ([`crate::editor_interface::is_mobile_breakpoint`]); it
//! starts with the lasso as its selection tool ([`init_selection_tool`]).
//! Research `ui-design-system.md` §3.7, mockup 06:
//!
//! - the top bar: the host's main menu (and top-left UI) on the left; pen
//!   mode (once a pen is detected) and the library trigger, or the exit
//!   view mode button, on the right;
//! - the bottom bar, at most 450 px wide and centred: the styles row
//!   ([`crate::styles_panel::mobile_shape_actions`]) above the toolbar;
//! - the toolbar's 36 px buttons: hand, selection/lasso, freedraw/draw to
//!   shape, eraser, rectangle/diamond/ellipse, arrow/line, then text,
//!   image and frame while the toolbar is wide enough ([`tools_outside`]),
//!   then "…" with the other tools and "Generate".
//!
//! [`mobile_toolbar`] and [`mobile_menu`] build the DOM upstream leaves
//! (`tests/mobile_menu.rs` holds every case of
//! `tests/fixtures/mobile-menu.json` to it). The toolbar's listeners
//! report [`ToolbarEvent`]s, which the host applies with
//! [`apply_toolbar_event`] to its [`MobileToolbarState`] (the popovers,
//! the remembered options and the measured width upstream keeps in React
//! state) and its tool state, then re-renders; a press on the canvas
//! closes the popovers ([`MobileToolbarState::close_popovers`], upstream's
//! `onPointerDownEmitter`). The menu's own buttons report
//! [`MobileMenuEvent`]s. The styles are upstream's `MobileToolbar.scss`,
//! `ToolPopover.scss`, `FixedSideContainer.scss` and the phone layout's
//! rules of `styles.scss`, compiled ([`MOBILE_MENU_CSS`]).
//!
//! Not ported here: the viewport status badge (`props.viewportStatusFrame`,
//! a host feature the port has no counterpart of yet).

use std::rc::Rc;

use excali_editor::tools::{
    tool_config, SelectionTool, Tool, ToolRefusal, ToolState, ToolSwitch, ToolType,
};

use crate::dom::{class_names, Element, Node};
use crate::editor_interface::FormFactor;
use crate::primitives::{
    icon_button, island, stack_col, IconButtonKind, IconButtonProps, IslandProps, Rect, StackProps,
};
use crate::toolbar::{
    activate_extra_tool, activate_tool_button, capitalize, emit, extra_tools_trigger, icon_node,
    menu_item, radix_menu_content_aligned, set_tool, tool_button_for, tool_icon, toolbar_text,
    DropdownAlign, DropdownPlacement, DropdownSide, MenuItem, OnToolbarEvent, ShortcutDisplay,
    ToolbarEvent, DROPDOWN_MENU_EVENT_WRAPPER,
};

/// Upstream's `MobileToolbar.scss`, `ToolPopover.scss`,
/// `FixedSideContainer.scss` and the phone layout's rules of `styles.scss`,
/// compiled (generated by `tools/goldens/mobile-menu.mjs`).
pub const MOBILE_MENU_CSS: &str = include_str!("mobile_menu.css");

/// The `data-excali-ui` value of the `<style>` holding [`MOBILE_MENU_CSS`].
const STYLESHEET_ID: &str = "mobile-menu";

/// Adds [`MOBILE_MENU_CSS`] to `document`'s head once, after the
/// toolbar's stylesheet ([`crate::toolbar::install_stylesheet`], which it
/// installs first).
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::toolbar::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(MOBILE_MENU_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let toolbar = document.query_selector("style[data-excali-ui=\"toolbar\"]")?;
    let next = toolbar.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings of the phone layout (`locales/en.json`); the key
/// itself for any other.
pub fn mobile_text(key: &str) -> &str {
    match key {
        "buttons.scrollBackToContent" => "Scroll back to content",
        other => toolbar_text(other),
    }
}

// -- widths -------------------------------------------------------------------

/// A toolbar button's size (`WIDTH`, `MobileToolbar.tsx:104`).
pub const TOOL_SIZE: f64 = 36.0;

/// The gap between the toolbar's buttons (`GAP`, `MobileToolbar.tsx:105`).
pub const TOOL_GAP: f64 = 4.0;

/// The buttons always shown: hand, selection, freedraw, eraser,
/// rectangle, arrow and "…" (`MIN_TOOLS`, `MobileToolbar.tsx:108`).
pub const MIN_TOOLS: f64 = 7.0;

/// Their width with their gaps (`MIN_WIDTH`, `MobileToolbar.tsx:109`).
pub const MIN_WIDTH: f64 = MIN_TOOLS * TOOL_SIZE + (MIN_TOOLS - 1.0) * TOOL_GAP;

/// What each further button needs (`ADDITIONAL_WIDTH`,
/// `MobileToolbar.tsx:110`).
pub const ADDITIONAL_WIDTH: f64 = TOOL_SIZE + TOOL_GAP;

/// `.App-bottom-bar`'s `max-width` (`styles.scss:322-346`).
pub const BOTTOM_BAR_MAX_WIDTH: f64 = 450.0;

/// What `.App-bottom-bar` leaves of the editor's width (`calc(100% -
/// 28px)`).
pub const BOTTOM_BAR_INSET: f64 = 28.0;

/// The padding of the bottom bar's islands (`.App-bottom-bar > .Island`).
pub const BOTTOM_BAR_PADDING: f64 = 4.0;

/// `SCROLLBAR_WIDTH` and `SCROLLBAR_MARGIN` (`scene/scrollbars.ts`): the
/// bottom bar's margin below.
pub const SCROLLBAR_WIDTH: f64 = 6.0;
pub const SCROLLBAR_MARGIN: f64 = 4.0;

/// The toolbar's width in the bottom bar of an editor `editor_width` wide,
/// as the compiled CSS lays it out: what upstream's toolbar measures.
pub fn toolbar_width(editor_width: f64) -> f64 {
    ((editor_width - BOTTOM_BAR_INSET).min(BOTTOM_BAR_MAX_WIDTH) - 2.0 * BOTTOM_BAR_PADDING)
        .max(0.0)
}

/// Which of text, image and frame the toolbar shows as buttons rather
/// than in "…".
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ToolsOutside {
    pub text: bool,
    pub image: bool,
    pub frame: bool,
}

/// `showTextToolOutside`, `showImageToolOutside` and
/// `showFrameToolOutside` for a toolbar `width` wide
/// (`MobileToolbar.tsx:112-114`).
pub fn tools_outside(width: f64) -> ToolsOutside {
    ToolsOutside {
        text: width >= MIN_WIDTH + ADDITIONAL_WIDTH,
        image: width >= MIN_WIDTH + 2.0 * ADDITIONAL_WIDTH,
        frame: width >= MIN_WIDTH + 3.0 * ADDITIONAL_WIDTH,
    }
}

// -- state --------------------------------------------------------------------

/// The toolbar's popovers (`ToolPopover`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ToolPopover {
    /// Selection and lasso (`SelectionToolPopover`, `Tools.tsx:373-420`).
    Selection,
    /// Freedraw and draw to shape (`FreedrawToolPopover`, `Tools.tsx:426-476`).
    Freedraw,
    /// Rectangle, diamond and ellipse (`MobileToolbar.tsx:184-205`).
    Shapes,
    /// Arrow and line (`MobileToolbar.tsx:208-230`).
    Linear,
}

impl ToolPopover {
    pub const ALL: [ToolPopover; 4] = [
        ToolPopover::Selection,
        ToolPopover::Freedraw,
        ToolPopover::Shapes,
        ToolPopover::Linear,
    ];

    /// The popover's options, in order.
    pub fn options(self) -> &'static [ToolType] {
        match self {
            ToolPopover::Selection => &[ToolType::Selection, ToolType::Lasso],
            ToolPopover::Freedraw => &[ToolType::Freedraw, ToolType::Autoshape],
            ToolPopover::Shapes => &[ToolType::Rectangle, ToolType::Diamond, ToolType::Ellipse],
            ToolPopover::Linear => &[ToolType::Arrow, ToolType::Line],
        }
    }

    /// The trigger's `data-testid`.
    pub fn test_id(self) -> &'static str {
        match self {
            ToolPopover::Selection => "toolbar-selection",
            ToolPopover::Freedraw => "toolbar-freedraw",
            ToolPopover::Shapes => "toolbar-rectangle",
            ToolPopover::Linear => "toolbar-arrow",
        }
    }

    fn id(self) -> &'static str {
        match self {
            ToolPopover::Selection => "selection",
            ToolPopover::Freedraw => "freedraw",
            ToolPopover::Shapes => "shapes",
            ToolPopover::Linear => "linear",
        }
    }
}

/// What the toolbar keeps between renders (React state upstream).
#[derive(Clone, Debug, PartialEq)]
pub struct MobileToolbarState {
    /// Its measured width (`toolbarWidth`; 0 until measured).
    pub width: f64,
    /// "…" is open (`isOtherShapesMenuOpen`).
    pub extra_tools_open: bool,
    /// The open popover (each `ToolPopover`'s `isPopupOpen`).
    pub open_popover: Option<ToolPopover>,
    /// The shapes popover's remembered option (`lastActiveGenericShape`).
    pub last_shape: ToolType,
    /// The arrow/line popover's (`lastActiveLinearElement`).
    pub last_linear: ToolType,
    /// The freedraw popover's (`lastDrawingTool`).
    pub last_drawing: ToolType,
}

impl MobileToolbarState {
    /// The state after the first render with `tools`.
    pub fn new(tools: &ToolState) -> MobileToolbarState {
        let mut state = MobileToolbarState {
            width: 0.0,
            extra_tools_open: false,
            open_popover: None,
            last_shape: ToolType::Rectangle,
            last_linear: ToolType::Arrow,
            last_drawing: ToolType::Freedraw,
        };
        state.sync(tools);
        state
    }

    /// Follows the active tool, however it changed: each popover
    /// remembers it when it is one of its options (the toolbar's and
    /// `FreedrawToolPopover`'s effects), and an open popover whose options
    /// do not hold it closes (`ToolPopover.tsx:52-55`).
    pub fn sync(&mut self, tools: &ToolState) {
        let Some(active) = tools.active_tool.tool.builtin() else {
            self.open_popover = None;
            return;
        };
        match active {
            ToolType::Rectangle | ToolType::Diamond | ToolType::Ellipse => self.last_shape = active,
            ToolType::Arrow | ToolType::Line => self.last_linear = active,
            ToolType::Freedraw | ToolType::Autoshape => self.last_drawing = active,
            _ => {}
        }
        if let Some(open) = self.open_popover {
            if !open.options().contains(&active) {
                self.open_popover = None;
            }
        }
    }

    /// Closes the popovers (a press on the canvas).
    pub fn close_popovers(&mut self) {
        self.open_popover = None;
    }

    /// The option a popover's trigger shows and activates.
    pub fn displayed(&self, popover: ToolPopover, tools: &ToolState) -> ToolType {
        match popover {
            ToolPopover::Selection => tools.preferred_selection_tool.tool.tool_type(),
            ToolPopover::Freedraw => self.last_drawing,
            ToolPopover::Shapes => self.last_shape,
            ToolPopover::Linear => self.last_linear,
        }
    }
}

/// A popover's `onToolChange(type)`: the selection popover makes its
/// option the preferred selection tool (`Tools.tsx:406-414`); the others
/// remember it (`MobileToolbar.tsx:192-201, 216-224`, `Tools.tsx:465-470`);
/// all activate it.
fn tool_change(
    state: &mut MobileToolbarState,
    tools: &mut ToolState,
    popover: ToolPopover,
    ty: ToolType,
) -> Result<ToolSwitch, ToolRefusal> {
    match popover {
        ToolPopover::Selection => {
            let result = set_tool(tools, ty);
            tools.preferred_selection_tool.tool = if ty == ToolType::Lasso {
                SelectionTool::Lasso
            } else {
                SelectionTool::Selection
            };
            tools.preferred_selection_tool.initialized = true;
            result
        }
        ToolPopover::Freedraw => {
            state.last_drawing = ty;
            set_tool(tools, ty)
        }
        ToolPopover::Shapes => {
            state.last_shape = ty;
            set_tool(tools, ty)
        }
        ToolPopover::Linear => {
            state.last_linear = ty;
            set_tool(tools, ty)
        }
    }
}

/// Applies a toolbar event to the toolbar's state and the tool state, as
/// upstream's handlers do, and syncs the state to the tool it leaves
/// active. Returns what `setActiveTool` answered, when it was asked.
/// `ExtraToolsToggle` also asks the host to close its menus and popups
/// (`setAppState({ openMenu: null, openPopup: null })`); `MermaidToExcalidraw`
/// and `MagicFrame` are the host's; `PenMode`, `Lock` and
/// `ToolButtonPointerDown` are not the phone toolbar's.
pub fn apply_toolbar_event(
    state: &mut MobileToolbarState,
    tools: &mut ToolState,
    event: &ToolbarEvent,
) -> Option<Result<ToolSwitch, ToolRefusal>> {
    let result = match event {
        ToolbarEvent::ToolButton { tool, pointer_type } => {
            activate_tool_button(tools, *tool, *pointer_type)
        }
        ToolbarEvent::ExtraToolsToggle => {
            state.extra_tools_open = !state.extra_tools_open;
            None
        }
        ToolbarEvent::ExtraToolsClose => {
            state.extra_tools_open = false;
            None
        }
        ToolbarEvent::ExtraTool(ty) => Some(activate_extra_tool(tools, *ty)),
        ToolbarEvent::ToolPopoverTrigger(popover) => {
            state.open_popover = if state.open_popover == Some(*popover) {
                None
            } else {
                Some(*popover)
            };
            let ty = state.displayed(*popover, tools);
            Some(tool_change(state, tools, *popover, ty))
        }
        ToolbarEvent::ToolPopoverOption(popover, ty) => {
            if tools.active_tool.tool.builtin() == Some(*ty) {
                None
            } else {
                // setActiveTool, then onToolChange (ToolPopover.tsx:94-101)
                let _ = set_tool(tools, *ty);
                Some(tool_change(state, tools, *popover, *ty))
            }
        }
        ToolbarEvent::MobileToolbarWidth(width) => {
            state.width = *width;
            None
        }
        ToolbarEvent::ToolButtonPointerDown { .. }
        | ToolbarEvent::PenMode
        | ToolbarEvent::Lock
        | ToolbarEvent::MermaidToExcalidraw
        | ToolbarEvent::MagicFrame => None,
    };
    state.sync(tools);
    result
}

/// App.tsx:3660-3683 on load: an uninitialized preferred selection tool
/// becomes the lasso on a phone and the selection elsewhere, and a
/// restored selection, lasso or image tool becomes the preferred one.
pub fn init_selection_tool(tools: &mut ToolState, form_factor: FormFactor) {
    let preferred = &mut tools.preferred_selection_tool;
    if !preferred.initialized {
        preferred.tool = if form_factor == FormFactor::Phone {
            SelectionTool::Lasso
        } else {
            SelectionTool::Selection
        };
        preferred.initialized = true;
    }
    let tool = preferred.tool.tool_type();
    if matches!(
        tools.active_tool.tool.builtin(),
        Some(ToolType::Image | ToolType::Lasso | ToolType::Selection)
    ) {
        tools.active_tool.tool = Tool::Builtin(tool);
    }
}

// -- the toolbar ----------------------------------------------------------------

/// The toolbar's props.
#[derive(Clone)]
pub struct MobileToolbarProps<'a> {
    /// The active tool, the preferred selection tool and the host's forced
    /// tool (`props.activeTool`).
    pub tools: &'a ToolState,
    pub state: &'a MobileToolbarState,
    /// `props.aiEnabled !== false`.
    pub ai_enabled: bool,
    /// A `diagramToCode` plugin is registered (the magic frame entry).
    pub diagram_to_code: bool,
    /// Prefix of the ids tying the triggers and their content together.
    pub id_prefix: String,
    /// The text-to-diagram trigger (`TTDDialogTriggerTunnel.Out`), under
    /// "Generate" while AI is enabled.
    pub ttd_trigger: Option<Node>,
    pub on_event: Option<OnToolbarEvent>,
}

/// A popover option's label: the trigger's is the tool's
/// (`capitalizeString(t("toolBar.<type>"))`), an option's its type
/// (`capitalizeString(type)`, `ToolPopover.tsx:90-91`).
fn trigger_title(ty: ToolType) -> String {
    capitalize(toolbar_text(&format!("toolBar.{}", ty.as_str())))
}

fn fillable(ty: ToolType) -> &'static str {
    if tool_config(ty).is_some_and(|c| c.is_fillable()) {
        "fillable"
    } else {
        ""
    }
}

/// `ToolPopover` (`ToolPopover.tsx:39-113`): the trigger showing the
/// remembered option and, while open, radix's popper wrapper around the
/// options.
fn tool_popover(props: &MobileToolbarProps<'_>, popover: ToolPopover, out: &mut Vec<Node>) {
    let tools = props.tools;
    let active = tools.active_tool.tool.builtin();
    let displayed = props.state.displayed(popover, tools);
    let title = trigger_title(displayed);
    let on_trigger = props.on_event.clone();
    out.push(Node::Element(icon_button(IconButtonProps {
        kind: IconButtonKind::Toggle {
            checked: active == Some(displayed),
        },
        class_name: fillable(displayed).into(),
        icon: Some(tool_icon(displayed)),
        disabled: popover
            .options()
            .iter()
            .all(|o| tools.is_tool_button_disabled(o.as_str())),
        title: Some(title.clone()),
        aria_label: title,
        test_id: Some(popover.test_id().into()),
        on_select: Some(Rc::new(move |_| {
            emit(&on_trigger, ToolbarEvent::ToolPopoverTrigger(popover))
        })),
        ..IconButtonProps::default()
    })));
    if props.state.open_popover != Some(popover) {
        return;
    }
    let options = popover.options().iter().map(|&ty| {
        let label = capitalize(ty.as_str());
        let on_option = props.on_event.clone();
        Node::Element(icon_button(IconButtonProps {
            kind: IconButtonKind::Toggle {
                checked: active == Some(ty),
            },
            class_name: fillable(ty).into(),
            icon: Some(tool_icon(ty)),
            disabled: tools.is_tool_button_disabled(ty.as_str()),
            title: Some(label.clone()),
            aria_label: label,
            test_id: Some(format!("toolbar-{}", ty.as_str())),
            on_select: Some(Rc::new(move |_| {
                emit(&on_option, ToolbarEvent::ToolPopoverOption(popover, ty))
            })),
            ..IconButtonProps::default()
        }))
    });
    let content = Element::new("div")
        .attr("class", "tool-popover-content")
        .attr(
            "id",
            format!("{}-tool-popover-{}", props.id_prefix, popover.id()),
        )
        .attr("role", "dialog")
        .attr("tabindex", "-1")
        .attr("data-state", "open")
        .attr("data-side", "bottom")
        .attr("data-align", "center")
        .style(
            "--radix-popover-content-transform-origin",
            "var(--radix-popper-transform-origin)",
        )
        .style(
            "--radix-popover-content-available-width",
            "var(--radix-popper-available-width)",
        )
        .style(
            "--radix-popover-content-available-height",
            "var(--radix-popper-available-height)",
        )
        .style(
            "--radix-popover-trigger-width",
            "var(--radix-popper-anchor-width)",
        )
        .style(
            "--radix-popover-trigger-height",
            "var(--radix-popper-anchor-height)",
        )
        .children_from(options);
    out.push(Node::Element(
        Element::new("div")
            .attr("data-radix-popper-content-wrapper", "")
            .on_mount(place_tool_popover)
            .child(content),
    ));
}

/// `sideOffset` of the tool popovers (`ToolPopover.tsx:47`).
pub const TOOL_POPOVER_SIDE_OFFSET: f64 = 16.0;

/// A tool popover's placement for its trigger rect and size within the
/// editor container (`boundary`), as radix's Popper places
/// `Popover.Content` (side bottom, align center, `sideOffset={16}`,
/// `collisionBoundary` the container) through floating-ui: below the
/// trigger and centred on it, flipped above when it overflows the
/// container below and less so above (on a phone's bottom bar, always),
/// then shifted horizontally into the container.
pub fn tool_popover_position(
    trigger: Rect,
    content: (f64, f64),
    boundary: Rect,
) -> DropdownPlacement {
    let (width, height) = content;
    let below = trigger.top + trigger.height + TOOL_POPOVER_SIDE_OFFSET;
    let above = trigger.top - TOOL_POPOVER_SIDE_OFFSET - height;
    let bottom = boundary.top + boundary.height;
    let overflow_below = (below + height - bottom).max(0.0);
    let overflow_above = (boundary.top - above).max(0.0);
    let side = if overflow_below > 0.0 && overflow_above < overflow_below {
        DropdownSide::Top
    } else {
        DropdownSide::Bottom
    };
    let y = match side {
        DropdownSide::Bottom => below,
        DropdownSide::Top => above,
    };
    let x = trigger.left + trigger.width / 2.0 - width / 2.0;
    let x = x
        .min(boundary.left + boundary.width - width)
        .max(boundary.left);
    DropdownPlacement { x, y, side }
}

fn rect_of(el: &web_sys::Element) -> Rect {
    let r = el.get_bounding_client_rect();
    Rect {
        left: r.left(),
        top: r.top(),
        width: r.width(),
        height: r.height(),
    }
}

/// Places a mounted popover's wrapper by its trigger (the button before
/// it) within the editor container.
fn place_tool_popover(wrapper: &web_sys::Element) {
    use wasm_bindgen::JsCast;
    let Some(trigger) = wrapper.previous_element_sibling() else {
        return;
    };
    let Some(html) = wrapper.dyn_ref::<web_sys::HtmlElement>() else {
        return;
    };
    let style = html.style();
    let _ = style.set_property("position", "fixed");
    let _ = style.set_property("left", "0px");
    let _ = style.set_property("top", "0px");
    let _ = style.set_property("min-width", "max-content");
    let boundary = wrapper
        .closest(".excalidraw")
        .ok()
        .flatten()
        .map(|c| rect_of(&c))
        .unwrap_or_else(|| {
            let n = |v: Result<wasm_bindgen::JsValue, _>| v.ok().and_then(|v| v.as_f64());
            let (w, h) = web_sys::window()
                .map(|w| {
                    (
                        n(w.inner_width()).unwrap_or(0.0),
                        n(w.inner_height()).unwrap_or(0.0),
                    )
                })
                .unwrap_or((0.0, 0.0));
            Rect {
                left: 0.0,
                top: 0.0,
                width: w,
                height: h,
            }
        });
    let c = wrapper.get_bounding_client_rect();
    let placed = tool_popover_position(rect_of(&trigger), (c.width(), c.height()), boundary);
    let _ = style.set_property(
        "transform",
        &format!("translate({}px, {}px)", placed.x, placed.y),
    );
    if let Some(content) = wrapper.first_element_child() {
        let side = match placed.side {
            DropdownSide::Bottom => "bottom",
            DropdownSide::Top => "top",
        };
        let _ = content.set_attribute("data-side", side);
    }
}

/// The "…" trigger's icon: the active tool's when it is in "…"
/// (`MobileToolbar.tsx:116-159`).
fn extra_icon(active: Option<ToolType>, in_menu: bool) -> &'static str {
    if !in_menu {
        return "DotsIcon";
    }
    match active {
        Some(ToolType::Text) => "TextIcon",
        Some(ToolType::Image) => "ImageIcon",
        Some(ToolType::Frame) => "frameToolIcon",
        Some(ToolType::Stickynote) => "stickyNoteToolIcon",
        Some(ToolType::Embeddable) => "EmbedIcon",
        Some(ToolType::Laser) => "laserPointerToolIcon",
        Some(ToolType::Bucketfill) => "bucketFillIcon",
        Some(ToolType::Magicframe) => "MagicIcon",
        _ => "DotsIcon",
    }
}

/// "…" (`MobileToolbar.tsx:243-373`): the trigger and, while open, the
/// menu of the tools not shown as buttons and "Generate".
fn extra_tools(props: &MobileToolbarProps<'_>, outside: ToolsOutside) -> Element {
    let tools = props.tools;
    let active = tools.active_tool.tool.builtin();
    let in_menu = active.is_some_and(|a| {
        matches!(
            a,
            ToolType::Stickynote
                | ToolType::Embeddable
                | ToolType::Laser
                | ToolType::Bucketfill
                | ToolType::Magicframe
        ) || (a == ToolType::Text && !outside.text)
            || (a == ToolType::Frame && !outside.frame)
    });
    let open = props.state.extra_tools_open;
    let trigger_id = format!("{}-extra-tools-trigger", props.id_prefix);
    let content_id = format!("{}-extra-tools-content", props.id_prefix);
    let class = class_names([
        ("dropdown-menu-button", true),
        ("App-toolbar__extra-tools-trigger", true),
        ("App-toolbar__extra-tools-trigger--mobile", true),
        (
            "App-toolbar__extra-tools-trigger--selected",
            in_menu || open,
        ),
        ("zen-mode-transition", true),
        ("dropdown-menu-button--mobile", true),
    ]);
    let size = format!("{TOOL_SIZE}px");
    let trigger = extra_tools_trigger(
        &trigger_id,
        &content_id,
        open,
        class,
        extra_icon(active, in_menu),
        &props.on_event,
    )
    .style("width", size.clone())
    .style("height", size)
    .style("display", "flex")
    .style("align-items", "center")
    .style("justify-content", "center");
    let mut wrapper = Element::new("div")
        .attr("class", DROPDOWN_MENU_EVENT_WRAPPER)
        .style("display", "contents")
        .child(trigger);
    if open {
        wrapper = wrapper.child(extra_tools_menu(props, outside, &trigger_id, &content_id));
    }
    wrapper
}

fn extra_tools_menu(
    props: &MobileToolbarProps<'_>,
    outside: ToolsOutside,
    trigger_id: &str,
    content_id: &str,
) -> Element {
    let tools = props.tools;
    let active = tools.active_tool.tool.builtin();
    // a phone's menu items show no shortcut (DropdownMenuItemContent.tsx:28)
    let item = |ty: ToolType, test_id: &'static str| MenuItem {
        icon: tool_config(ty).map_or("", |c| c.icon),
        label: toolbar_text(&format!("toolBar.{}", ty.as_str())).to_owned(),
        shortcut: None,
        test_id,
        selected: active == Some(ty),
        disabled: tools.is_tool_button_disabled(ty.as_str()),
        badge: None,
        event: ToolbarEvent::ExtraTool(ty),
    };
    let mut items: Vec<MenuItem> = Vec::new();
    if !outside.text {
        items.push(item(ToolType::Text, "toolbar-text"));
    }
    if !outside.image {
        items.push(item(ToolType::Image, "toolbar-image"));
    }
    items.push(item(ToolType::Stickynote, "toolbar-stickynote"));
    if !outside.frame {
        items.push(item(ToolType::Frame, "toolbar-frame"));
    }
    items.push(item(ToolType::Embeddable, "toolbar-embeddable"));
    items.push(item(ToolType::Autoshape, "toolbar-autoshape"));
    items.push(item(ToolType::Laser, "toolbar-laser"));
    items.push(item(ToolType::Bucketfill, "toolbar-bucketfill"));
    let mut children: Vec<Node> = items
        .into_iter()
        .map(|i| menu_item(i, &props.on_event))
        .collect();
    children.push(Node::Element(
        Element::new("div")
            .style("margin", "6px 0px")
            .style("font-size", "14px")
            .style("font-weight", "600")
            .child("Generate"),
    ));
    if props.ai_enabled {
        children.extend(props.ttd_trigger.clone());
    }
    children.push(menu_item(
        MenuItem {
            icon: "mermaidLogoIcon",
            label: toolbar_text("toolBar.mermaidToExcalidraw").to_owned(),
            shortcut: None,
            // upstream's test id for this entry (MobileToolbar.tsx:352-358)
            test_id: "toolbar-embeddable",
            selected: false,
            disabled: false,
            badge: None,
            event: ToolbarEvent::MermaidToExcalidraw,
        },
        &props.on_event,
    ));
    if props.ai_enabled && props.diagram_to_code {
        children.push(menu_item(
            MenuItem {
                icon: "MagicIcon",
                label: toolbar_text("toolBar.magicframe").to_owned(),
                shortcut: None,
                test_id: "toolbar-magicframe",
                selected: false,
                disabled: tools.is_tool_button_disabled("magicframe"),
                badge: Some("AI"),
                event: ToolbarEvent::MagicFrame,
            },
            &props.on_event,
        ));
    }
    // a phone's DropdownMenuContent is a column, not an island
    let container = stack_col(
        StackProps {
            class_name: Some("dropdown-menu-container".into()),
            ..StackProps::default()
        },
        children,
    );
    let on_close = props.on_event.clone();
    radix_menu_content_aligned(
        "dropdown-menu App-toolbar__extra-tools-dropdown dropdown-menu--mobile",
        DropdownAlign::Start,
        trigger_id,
        content_id,
        container,
        Rc::new(move || emit(&on_close, ToolbarEvent::ExtraToolsClose)),
    )
}

/// `MobileToolbar` (`MobileToolbar.tsx:50-376`) at the state's measured
/// width; once mounted it reports its width when that differs
/// ([`ToolbarEvent::MobileToolbarWidth`]).
pub fn mobile_toolbar(props: MobileToolbarProps<'_>) -> Element {
    let tools = props.tools;
    let on_event = &props.on_event;
    let outside = tools_outside(props.state.width);
    let mut row: Vec<Node> = Vec::new();
    row.push(tool_button_for(
        tools,
        on_event,
        ToolType::Hand,
        ToolType::Hand,
        ShortcutDisplay::NoKeyBinding,
    ));
    tool_popover(&props, ToolPopover::Selection, &mut row);
    tool_popover(&props, ToolPopover::Freedraw, &mut row);
    row.push(tool_button_for(
        tools,
        on_event,
        ToolType::Eraser,
        ToolType::Eraser,
        ShortcutDisplay::Hidden,
    ));
    tool_popover(&props, ToolPopover::Shapes, &mut row);
    tool_popover(&props, ToolPopover::Linear, &mut row);
    for (shown, ty) in [
        (outside.text, ToolType::Text),
        (outside.image, ToolType::Image),
        (outside.frame, ToolType::Frame),
    ] {
        if shown {
            row.push(tool_button_for(
                tools,
                on_event,
                ty,
                ty,
                ShortcutDisplay::Hidden,
            ));
        }
    }
    row.push(Node::Element(extra_tools(&props, outside)));
    let measured = props.state.width;
    let on_width = props.on_event.clone();
    Element::new("div")
        .attr("class", "mobile-toolbar")
        .on_mount(move |el| {
            let width = el.get_bounding_client_rect().width();
            if width != measured {
                emit(&on_width, ToolbarEvent::MobileToolbarWidth(width));
            }
        })
        .children_from(row)
}

// -- the menu -------------------------------------------------------------------

/// What the phone layout's own buttons report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MobileMenuEvent {
    /// The pen mode button (`onPenModeToggle(null)`).
    PenMode,
    /// The exit view mode button (`actionToggleViewMode`).
    ExitViewMode,
    /// "Scroll back to content" (`getScrollToContentState`).
    ScrollBackToContent,
}

/// Receives the menu's [`MobileMenuEvent`]s.
pub type OnMobileMenuEvent = Rc<dyn Fn(MobileMenuEvent)>;

/// `MobileMenu`'s props: the app state it reads, the host's settings and
/// its slots.
#[derive(Clone, Default)]
pub struct MobileMenuProps {
    /// `appState.viewModeEnabled`.
    pub view_mode: bool,
    /// `appState.penMode`.
    pub pen_mode: bool,
    /// `appState.penDetected`.
    pub pen_detected: bool,
    /// `appState.scrolledOutside`.
    pub scrolled_outside: bool,
    /// `appState.openMenu` is set.
    pub menu_open: bool,
    /// `appState.openSidebar` is set.
    pub sidebar_open: bool,
    /// `appState.openDialog` is the element link selector.
    pub element_link_selector: bool,
    /// `app.isInteractionEnabled()`.
    pub interaction_enabled: bool,
    /// LayerUI's `defaultUIEnabled`.
    pub default_ui: bool,
    /// LayerUI's `scrollBackToContentUIEnabled`.
    pub scroll_back_ui: bool,
    /// LayerUI's `renderWelcomeScreen`.
    pub render_welcome_screen: bool,
    /// `renderSidebars()`.
    pub sidebars: Option<Node>,
    /// `WelcomeScreenCenterTunnel.Out`.
    pub welcome_screen: Option<Node>,
    /// `MainMenuTunnel.Out`.
    pub main_menu: Option<Node>,
    /// `DefaultSidebarTriggerTunnel.Out`.
    pub sidebar_trigger: Option<Node>,
    /// `renderTopLeftUI(true, appState)`.
    pub top_left_ui: Option<Node>,
    /// `renderTopRightUI(true, appState)`: replaces pen mode and the
    /// sidebar trigger when given.
    pub top_right_ui: Option<Node>,
    /// The styles row ([`crate::styles_panel::mobile_shape_actions`]).
    pub shape_actions: Option<Node>,
    /// The toolbar ([`mobile_toolbar`]).
    pub toolbar: Option<Node>,
    pub on_event: Option<OnMobileMenuEvent>,
}

fn menu_emit(on_event: &Option<OnMobileMenuEvent>, event: MobileMenuEvent) {
    if let Some(f) = on_event {
        f(event);
    }
}

/// `MobileMenu` (`MobileMenu.tsx:47-204`): the sidebars, the welcome
/// screen, the bottom bar (the styles row and the toolbar island, unless
/// in view mode) and the top bar, in that order (the top bar last, so on
/// top).
pub fn mobile_menu(props: MobileMenuProps) -> Vec<Node> {
    let mut out: Vec<Node> = Vec::new();
    out.extend(props.sidebars.clone());
    let mut welcome = Element::new("div").attr("class", "App-welcome-screen");
    if props.render_welcome_screen {
        welcome = welcome.children_from(props.welcome_screen.clone());
    }
    out.push(Node::Element(welcome));

    let scroll_back =
        (props.scroll_back_ui && props.scrolled_outside && !props.menu_open && !props.sidebar_open)
            .then(|| {
                let on_event = props.on_event.clone();
                Node::Element(
                    Element::new("button")
                        .attr("type", "button")
                        .attr("class", "scroll-back-to-content")
                        .on("click", move |_| {
                            menu_emit(&on_event, MobileMenuEvent::ScrollBackToContent)
                        })
                        .child(mobile_text("buttons.scrollBackToContent")),
                )
            });
    let status_stack = |button: Node| {
        Node::Element(
            Element::new("div")
                .attr("class", "floating-status-stack")
                .child(button),
        )
    };
    let bottom_bar = props.default_ui && !props.view_mode;
    if bottom_bar {
        let mut children: Vec<Node> = Vec::new();
        children.extend(scroll_back.clone().map(status_stack));
        children.extend(props.shape_actions.clone());
        let toolbar = if props.element_link_selector {
            Vec::new()
        } else {
            props.toolbar.clone().into_iter().collect()
        };
        children.push(Node::Element(island(
            IslandProps {
                class_name: Some("App-toolbar".into()),
                ..IslandProps::default()
            },
            toolbar,
        )));
        out.push(Node::Element(
            Element::new("div")
                .attr("class", "App-bottom-bar")
                .attr("data-viewport-ui", "bottom")
                .style(
                    "margin-bottom",
                    format!("{}px", SCROLLBAR_WIDTH + SCROLLBAR_MARGIN),
                )
                .children_from(children),
        ));
    } else if let Some(button) = scroll_back {
        out.push(status_stack(button));
    }

    let mut top = Element::new("div").attr(
        "class",
        "FixedSideContainer FixedSideContainer_side_top App-top-bar",
    );
    if !props.element_link_selector {
        top = top.child(top_bar(&props));
    }
    out.push(Node::Element(top));
    out
}

/// `renderAppTopBar` (`MobileMenu.tsx:66-116`).
fn top_bar(props: &MobileMenuProps) -> Element {
    let mut right: Vec<Node> = Vec::new();
    match &props.top_right_ui {
        Some(ui) => right.push(ui.clone()),
        None if !props.view_mode => {
            if props.default_ui && props.pen_detected {
                let title = toolbar_text("toolBar.penMode");
                let on_event = props.on_event.clone();
                right.push(Node::Element(icon_button(IconButtonProps {
                    kind: IconButtonKind::Toggle {
                        checked: props.pen_mode,
                    },
                    class_name: "ToolIcon__penMode is-mobile".into(),
                    icon: Some(icon_node("PenModeIcon")),
                    title: Some(title.into()),
                    aria_label: title.into(),
                    on_select: Some(Rc::new(move |_| {
                        menu_emit(&on_event, MobileMenuEvent::PenMode)
                    })),
                    ..IconButtonProps::default()
                })));
            }
            right.extend(props.sidebar_trigger.clone());
        }
        None => {}
    }
    if props.default_ui && props.view_mode && props.interaction_enabled {
        let on_event = props.on_event.clone();
        right.push(Node::Element(
            Element::new("button")
                .attr("type", "button")
                .attr("class", "disable-view-mode")
                .on("click", move |_| {
                    menu_emit(&on_event, MobileMenuEvent::ExitViewMode)
                })
                .child(icon_node("pencilIcon")),
        ));
    }
    let mut left: Vec<Node> = Vec::new();
    left.extend(props.top_left_ui.clone());
    left.extend(props.main_menu.clone());
    Element::new("div")
        .attr("class", "App-toolbar-content")
        .style("display", "flex")
        .style("flex-direction", "row")
        .style("justify-content", "space-between")
        .child(
            Element::new("div")
                .attr("class", "excalidraw-ui-top-left")
                .children_from(left),
        )
        .child(
            Element::new("div")
                .attr("class", "excalidraw-ui-top-right")
                .children_from(right),
        )
}
