//! The shapes toolbar: the desktop `Toolbar` island and its
//! `ExtraToolsDropdown` (`components/Toolbar.tsx`), with the tool buttons
//! of `components/Tools.tsx` (`createToolButton`, `LockButton.tsx`,
//! `PenModeButton.tsx`) and the dropdown menu they open
//! (`components/dropdownMenu/*` over radix-ui's `DropdownMenu`).
//!
//! Order and grouping (`Toolbar.tsx:262-323`, research
//! `ui-design-system.md` §3.1): pen mode (once a pen is detected), lock,
//! divider, hand, selection (or lasso when preferred), rectangle, diamond,
//! ellipse, arrow, line, freedraw, text, sticky note, eraser, divider, the
//! "More tools" dropdown: image, frame, embeddable, autoshape, laser,
//! bucket fill, lasso, then "Generate" (the host's text-to-diagram
//! trigger, Mermaid to Excalidraw, Wireframe to code). Tooltips read
//! "Label — R or 2" (`getToolShortcut`).
//!
//! [`toolbar`] builds the DOM upstream leaves (`tests/toolbar.rs` holds
//! every case of `tests/fixtures/toolbar.json` to it), radix's attributes
//! included; its listeners report [`ToolbarEvent`]s, which the host applies
//! with [`activate_tool_button`], [`activate_extra_tool`] and the tool
//! state's `toggle_lock` / `toggle_pen_mode`, re-rendering with
//! [`ToolbarProps::extra_tools_open`] as the dropdown's state. The styles
//! are upstream's `Toolbar.scss` and `DropdownMenu.scss` compiled
//! ([`TOOLBAR_CSS`]).
//!
//! Not ported here: the compact (tablet) toolbar's selection and freedraw
//! popovers (`ToolPopover`), the HintViewer (ex-528) and the
//! text-to-diagram trigger, which the host passes in as slots, and the
//! collaboration laser island (`LayerUI.tsx:374-393`). Of radix's menu
//! behaviour the port keeps the trigger's press handling, focus on open,
//! arrow-key focus among the items and its placement ([`dropdown_position`]).

use std::cell::RefCell;
use std::rc::Rc;

use excali_editor::tools::{
    get_tool_letter, get_tool_shortcut, tool_config, PointerType, SelectionTool,
    SetActiveToolOptions, ShortcutLabels, Tool, ToolRefusal, ToolRequest, ToolState, ToolSwitch,
    ToolType,
};
use excali_scene::shape::Theme;
use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;
use web_sys::{Event, KeyboardEvent, MouseEvent};

use crate::dom::{class_names, Element, Node};
use crate::icons;
use crate::primitives::{
    icon_button, island, stack_row, IconButtonKind, IconButtonProps, IslandProps, Rect, StackProps,
};

/// Upstream's `Toolbar.scss` and `dropdownMenu/DropdownMenu.scss`,
/// compiled (generated by `tools/goldens/toolbar.mjs`).
pub const TOOLBAR_CSS: &str = include_str!("toolbar.css");

/// The `data-excali-ui` value of the `<style>` holding [`TOOLBAR_CSS`].
const STYLESHEET_ID: &str = "toolbar";

/// Adds [`TOOLBAR_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(TOOLBAR_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// `CLASSES.DROPDOWN_MENU_EVENT_WRAPPER` (`common/src/constants.ts:119`).
pub const DROPDOWN_MENU_EVENT_WRAPPER: &str = "dropdown-menu-event-wrapper";

/// `sideOffset` of `DropdownMenuContent` (`DropdownMenuContent.tsx:101`).
pub const DROPDOWN_SIDE_OFFSET: f64 = 8.0;

/// The English strings of the toolbar (`locales/en.json`); the key itself
/// for any other.
pub fn toolbar_text(key: &str) -> &str {
    match key {
        "toolBar.hand" => "Hand (panning tool)",
        "toolBar.selection" => "Selection",
        "toolBar.lasso" => "Lasso selection",
        "toolBar.rectangle" => "Rectangle",
        "toolBar.diamond" => "Diamond",
        "toolBar.ellipse" => "Ellipse",
        "toolBar.arrow" => "Arrow",
        "toolBar.line" => "Line",
        "toolBar.freedraw" => "Draw",
        "toolBar.text" => "Text",
        "toolBar.stickynote" => "Sticky note",
        "toolBar.image" => "Insert image",
        "toolBar.eraser" => "Eraser",
        "toolBar.frame" => "Frame tool",
        "toolBar.embeddable" => "Web Embed",
        "toolBar.autoshape" => "Draw to shape",
        "toolBar.laser" => "Laser pointer",
        "toolBar.bucketfill" => "Bucket fill",
        "toolBar.magicframe" => "Wireframe to code",
        "toolBar.lock" => "Keep selected tool active after drawing",
        "toolBar.penMode" => "Pen mode - prevent touch",
        "toolBar.extraTools" => "More tools",
        "toolBar.mermaidToExcalidraw" => "Mermaid to Excalidraw",
        "helpDialog.or" => ShortcutLabels::EN.or,
        "keys.shift" => ShortcutLabels::EN.shift,
        other => other,
    }
}

fn tool_label(ty: ToolType) -> String {
    capitalize(toolbar_text(&format!("toolBar.{}", ty.as_str())))
}

/// JS `capitalizeString`.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// What the toolbar's controls report.
#[derive(Debug, Clone, PartialEq)]
pub enum ToolbarEvent {
    /// A tool button's activation, with the pointer type of the press
    /// (`None` from the keyboard or assistive technology): apply with
    /// [`activate_tool_button`].
    ToolButton {
        tool: ToolType,
        pointer_type: Option<PointerType>,
    },
    /// A press on a tool button, which may become a drag onto the canvas
    /// (`app.toolDrag.handleButtonPointerDown`).
    ToolButtonPointerDown { tool: ToolType, event: Event },
    /// The pen mode button (`onPenModeToggle(null)`).
    PenMode,
    /// The lock button (`onLockToggle`).
    Lock,
    /// The "More tools" trigger: flip the dropdown and close other menus
    /// and popups (`setAppState({ openMenu: null, openPopup: null })`).
    ExtraToolsToggle,
    /// A press outside the open dropdown, Escape, or a selected item.
    ExtraToolsClose,
    /// A dropdown tool item: apply with [`activate_extra_tool`].
    ExtraTool(ToolType),
    /// "Mermaid to Excalidraw": `setOpenDialog({ name: "ttd", tab: "mermaid" })`.
    MermaidToExcalidraw,
    /// "Wireframe to code": `onMagicframeToolSelect()`.
    MagicFrame,
}

/// Receives the toolbar's [`ToolbarEvent`]s.
pub type OnToolbarEvent = Rc<dyn Fn(ToolbarEvent)>;

/// The toolbar's props: the tool state it shows and the host's settings.
#[derive(Clone)]
pub struct ToolbarProps<'a> {
    /// The active tool and its lock, pen mode and detection, the preferred
    /// selection tool, and the host's forced tool (`props.activeTool`) and
    /// image tool (`UIOptions.tools.image`).
    pub tools: &'a ToolState,
    /// `appState.zenModeEnabled`.
    pub zen_mode: bool,
    /// `props.isCollaborating`: the laser has its own island then, so the
    /// trigger does not show it.
    pub collaborating: bool,
    /// `props.aiEnabled !== false`.
    pub ai_enabled: bool,
    /// A `diagramToCode` plugin is registered (the magic frame entry).
    pub diagram_to_code: bool,
    /// The dropdown is open.
    pub extra_tools_open: bool,
    /// Prefix of the ids tying the trigger and the menu together.
    pub id_prefix: String,
    /// The HintViewer, first in the island.
    pub hint_viewer: Option<Node>,
    /// The text-to-diagram trigger (`TTDDialogTriggerTunnel.Out`), under
    /// "Generate" while AI is enabled.
    pub ttd_trigger: Option<Node>,
    pub on_event: Option<OnToolbarEvent>,
}

fn emit(on_event: &Option<OnToolbarEvent>, event: ToolbarEvent) {
    if let Some(f) = on_event {
        f(event);
    }
}

fn pointer_type(name: Option<String>) -> Option<PointerType> {
    match name.as_deref() {
        Some("mouse") => Some(PointerType::Mouse),
        Some("pen") => Some(PointerType::Pen),
        Some("touch") => Some(PointerType::Touch),
        _ => None,
    }
}

fn icon_node(name: &str) -> Node {
    let icon = icons::icon(name).unwrap_or_else(|| panic!("icons.tsx has no {name}"));
    Node::Element(
        icon.element(Theme::Light)
            .unwrap_or_else(|| panic!("{name} is a path list")),
    )
}

fn tool_icon(ty: ToolType) -> Node {
    icon_node(tool_config(ty).map_or("", |c| c.icon))
}

fn active_type(tools: &ToolState) -> Option<ToolType> {
    tools.active_tool.tool.builtin()
}

/// A tool button (`createToolButton`, `Tools.tsx:266-326`): `shortcut` is
/// the tool whose shortcut it shows (the lasso button shows selection's).
fn tool_button(
    props: &ToolbarProps<'_>,
    ty: ToolType,
    shortcut: ToolType,
    hide_key_binding: bool,
) -> Node {
    let labels = ShortcutLabels::EN;
    let label = tool_label(ty);
    let hint = get_tool_shortcut(shortcut, &labels);
    let key_binding = (!hide_key_binding).then(|| {
        get_tool_letter(shortcut, &labels)
            .or_else(|| tool_config(shortcut).and_then(|c| c.numeric_key.map(str::to_owned)))
            .unwrap_or_default()
    });
    let fillable = tool_config(ty).is_some_and(|c| c.is_fillable());
    let on_select = props.on_event.clone();
    let on_down = props.on_event.clone();
    Node::Element(icon_button(IconButtonProps {
        kind: IconButtonKind::Toggle {
            checked: active_type(props.tools) == Some(ty),
        },
        class_name: if fillable {
            "fillable".into()
        } else {
            String::new()
        },
        icon: Some(tool_icon(ty)),
        disabled: props.tools.is_tool_button_disabled(ty.as_str()),
        title: Some(format!("{label} — {hint}")),
        key_binding_label: key_binding,
        aria_label: label,
        aria_keyshortcuts: Some(hint),
        test_id: Some(format!("toolbar-{}", ty.as_str())),
        on_pointer_down: Some(Rc::new(move |e: &Event| {
            emit(
                &on_down,
                ToolbarEvent::ToolButtonPointerDown {
                    tool: ty,
                    event: e.clone(),
                },
            )
        })),
        on_select: Some(Rc::new(move |pointer: Option<String>| {
            emit(
                &on_select,
                ToolbarEvent::ToolButton {
                    tool: ty,
                    pointer_type: pointer_type(pointer),
                },
            )
        })),
        ..IconButtonProps::default()
    }))
}

/// `LockButton` (`LockButton.tsx`).
fn lock_button(props: &ToolbarProps<'_>) -> Node {
    let locked = props.tools.active_tool.locked;
    let title = toolbar_text("toolBar.lock");
    let on_event = props.on_event.clone();
    Node::Element(icon_button(IconButtonProps {
        kind: IconButtonKind::Toggle { checked: locked },
        class_name: "ToolIcon__lock".into(),
        icon: Some(icon_node(if locked {
            "LockedIcon"
        } else {
            "UnlockedIcon"
        })),
        disabled: props.tools.options.forced_tool.is_some(),
        title: Some(format!("{title} — Q")),
        aria_label: title.into(),
        test_id: Some("toolbar-lock".into()),
        on_select: Some(Rc::new(move |_| emit(&on_event, ToolbarEvent::Lock))),
        ..IconButtonProps::default()
    }))
}

/// `PenModeButton` (`PenModeButton.tsx`): nothing until a pen is detected.
fn pen_mode_button(props: &ToolbarProps<'_>) -> Option<Node> {
    if !props.tools.pen_detected {
        return None;
    }
    let title = toolbar_text("toolBar.penMode");
    let on_event = props.on_event.clone();
    Some(Node::Element(icon_button(IconButtonProps {
        kind: IconButtonKind::Toggle {
            checked: props.tools.pen_mode,
        },
        class_name: "ToolIcon__penMode".into(),
        icon: Some(icon_node("PenModeIcon")),
        title: Some(title.into()),
        aria_label: title.into(),
        on_select: Some(Rc::new(move |_| emit(&on_event, ToolbarEvent::PenMode))),
        ..IconButtonProps::default()
    })))
}

fn divider(side: &str) -> Node {
    Node::Element(
        Element::new("div")
            .attr("class", "App-toolbar__divider")
            .style(side, "0.25rem"),
    )
}

/// The desktop toolbar island (`Toolbar`, `Toolbar.tsx:226-326`) in full
/// styles-panel mode.
pub fn toolbar(props: ToolbarProps<'_>) -> Element {
    let tools = props.tools;
    let forced = tools.options.forced_tool.is_some();
    let mut row: Vec<Node> = Vec::new();
    row.extend(pen_mode_button(&props));
    if !forced {
        row.push(lock_button(&props));
        row.push(divider("margin-right"));
    }
    row.push(tool_button(&props, ToolType::Hand, ToolType::Hand, true));
    if tools.preferred_selection_tool.tool == SelectionTool::Lasso {
        row.push(tool_button(
            &props,
            ToolType::Lasso,
            ToolType::Selection,
            false,
        ));
    } else {
        row.push(tool_button(
            &props,
            ToolType::Selection,
            ToolType::Selection,
            false,
        ));
    }
    for ty in [
        ToolType::Rectangle,
        ToolType::Diamond,
        ToolType::Ellipse,
        ToolType::Arrow,
        ToolType::Line,
        ToolType::Freedraw,
        ToolType::Text,
        ToolType::Stickynote,
        ToolType::Eraser,
    ] {
        row.push(tool_button(&props, ty, ty, false));
    }
    row.push(divider("margin-left"));
    row.push(Node::Element(extra_tools_dropdown(&props)));
    let mut children: Vec<Node> = Vec::new();
    children.extend(props.hint_viewer.clone());
    children.push(Node::Element(stack_row(
        StackProps {
            gap: Some(1.0),
            ..StackProps::default()
        },
        row,
    )));
    island(
        IslandProps {
            padding: Some(1.0),
            class_name: Some(class_names([
                ("App-toolbar", true),
                ("zen-mode", props.zen_mode),
            ])),
            viewport_ui: Some("top".into()),
            ..IslandProps::default()
        },
        children,
    )
}

// -- extra tools --------------------------------------------------------------

/// A dropdown entry.
struct MenuItem {
    icon: &'static str,
    label: String,
    shortcut: Option<String>,
    test_id: &'static str,
    selected: bool,
    disabled: bool,
    badge: Option<&'static str>,
    event: ToolbarEvent,
}

/// `ExtraToolsDropdown` (`Toolbar.tsx:54-222`).
fn extra_tools_dropdown(props: &ToolbarProps<'_>) -> Element {
    let tools = props.tools;
    let active = active_type(tools);
    let is = |ty| active == Some(ty);
    let image = is(ToolType::Image);
    let frame = is(ToolType::Frame);
    let autoshape = is(ToolType::Autoshape);
    let laser = is(ToolType::Laser);
    let bucketfill = is(ToolType::Bucketfill);
    let lasso = is(ToolType::Lasso) && tools.preferred_selection_tool.tool != SelectionTool::Lasso;
    let embeddable = is(ToolType::Embeddable);
    let laser_shown = laser && !props.collaborating;
    let selected = image || frame || embeddable || autoshape || lasso || bucketfill || laser_shown;
    let trigger_icon = if image {
        "ImageIcon"
    } else if frame {
        "frameToolIcon"
    } else if embeddable {
        "EmbedIcon"
    } else if autoshape {
        "drawShapeToolIcon"
    } else if laser_shown {
        "laserPointerToolIcon"
    } else if lasso {
        "LassoIcon"
    } else if bucketfill {
        "bucketFillIcon"
    } else {
        "DotsIcon"
    };
    let labels = ShortcutLabels::EN;
    let disabled = |ty: &str| tools.is_tool_button_disabled(ty);
    let tool_item = |ty: ToolType, shortcut: Option<String>, selected: bool| MenuItem {
        icon: tool_config(ty).map_or("", |c| c.icon),
        label: toolbar_text(&format!("toolBar.{}", ty.as_str())).to_owned(),
        shortcut,
        test_id: match ty {
            ToolType::Image => "toolbar-image",
            ToolType::Frame => "toolbar-frame",
            ToolType::Embeddable => "toolbar-embeddable",
            ToolType::Autoshape => "toolbar-autoshape",
            ToolType::Laser => "toolbar-laser",
            ToolType::Bucketfill => "toolbar-bucketfill",
            _ => "toolbar-lasso",
        },
        selected,
        disabled: disabled(ty.as_str()),
        badge: None,
        event: ToolbarEvent::ExtraTool(ty),
    };
    let mut items: Vec<Option<MenuItem>> = Vec::new();
    if tools.options.image_tool {
        items.push(Some(tool_item(ToolType::Image, Some("9".into()), image)));
    }
    items.push(Some(tool_item(ToolType::Frame, Some("F".into()), frame)));
    items.push(Some(tool_item(ToolType::Embeddable, None, embeddable)));
    items.push(Some(tool_item(
        ToolType::Autoshape,
        Some(get_tool_shortcut(ToolType::Autoshape, &labels)),
        autoshape,
    )));
    items.push(Some(tool_item(ToolType::Laser, Some("K".into()), laser)));
    items.push(Some(tool_item(
        ToolType::Bucketfill,
        Some("B".into()),
        bucketfill,
    )));
    items.push(Some(tool_item(ToolType::Lasso, None, lasso)));
    // None: the "Generate" heading and the text-to-diagram slot
    items.push(None);
    items.push(Some(MenuItem {
        icon: "mermaidLogoIcon",
        label: toolbar_text("toolBar.mermaidToExcalidraw").to_owned(),
        shortcut: None,
        // upstream's test id for this entry (Toolbar.tsx:196-202)
        test_id: "toolbar-embeddable",
        selected: false,
        disabled: false,
        badge: None,
        event: ToolbarEvent::MermaidToExcalidraw,
    }));
    if props.ai_enabled && props.diagram_to_code {
        items.push(Some(MenuItem {
            icon: "MagicIcon",
            label: toolbar_text("toolBar.magicframe").to_owned(),
            shortcut: None,
            test_id: "toolbar-magicframe",
            selected: false,
            disabled: disabled("magicframe"),
            badge: Some("AI"),
            event: ToolbarEvent::MagicFrame,
        }));
    }

    let open = props.extra_tools_open;
    let trigger_id = format!("{}-extra-tools-trigger", props.id_prefix);
    let content_id = format!("{}-extra-tools-content", props.id_prefix);
    let trigger_class = class_names([
        ("App-toolbar__extra-tools-trigger", true),
        ("App-toolbar__extra-tools-trigger--selected", selected),
    ]);
    let on_toggle = props.on_event.clone();
    let trigger = Element::new("button")
        .attr("type", "button")
        .attr("id", trigger_id.clone())
        .attr("aria-haspopup", "menu")
        .attr("aria-expanded", open.to_string())
        .attr_opt("aria-controls", open.then(|| content_id.clone()))
        .attr("data-state", if open { "open" } else { "closed" })
        .attr(
            "class",
            format!("dropdown-menu-button {trigger_class} zen-mode-transition"),
        )
        .attr("data-testid", "dropdown-menu-button")
        .attr("title", toolbar_text("toolBar.extraTools"))
        // radix's trigger (react-dropdown-menu 2.1.16): a primary press
        // toggles its (here controlled) state and, while closed, keeps
        // focus off the trigger
        .on("pointerdown", move |e| {
            let Some(m) = e.dyn_ref::<MouseEvent>() else {
                return;
            };
            if m.button() == 0 && !m.ctrl_key() && !open {
                e.prevent_default();
            }
        })
        .on("keydown", |e| {
            if let Some(k) = e.dyn_ref::<KeyboardEvent>() {
                if matches!(k.key().as_str(), "Enter" | " " | "ArrowDown") {
                    e.prevent_default();
                }
            }
        })
        .on("click", move |_| {
            emit(&on_toggle, ToolbarEvent::ExtraToolsToggle)
        })
        .child(icon_node(trigger_icon));
    let mut wrapper = Element::new("div")
        .attr("class", DROPDOWN_MENU_EVENT_WRAPPER)
        .style("display", "contents")
        .child(trigger);
    if open {
        wrapper = wrapper.child(menu(props, items, &trigger_id, &content_id));
    }
    wrapper
}

/// `DropdownMenuItem` (`DropdownMenuItem.tsx`) in radix's `Menu.Item`.
fn menu_item(item: MenuItem, on_event: &Option<OnToolbarEvent>) -> Node {
    let class = format!(
        "dropdown-menu-item dropdown-menu-item-base  {}",
        if item.selected {
            "dropdown-menu-item--selected"
        } else {
            ""
        }
    );
    let class = format!("radix-menu-item {}", class.trim());
    let on_event = on_event.clone();
    let event = item.event;
    let mut el = Element::new("button")
        .attr("class", class)
        .attr("role", "menuitem")
        .attr("tabindex", "-1")
        .attr("data-orientation", "vertical")
        .attr("data-radix-collection-item", "")
        .attr("data-testid", item.test_id)
        .flag("disabled", item.disabled)
        .child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__icon")
                .child(icon_node(item.icon)),
        )
        .child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__text")
                .child(
                    // Ellipsify (Ellipsify.tsx)
                    Element::new("span")
                        .style("text-overflow", "ellipsis")
                        .style("overflow", "hidden")
                        .style("white-space", "nowrap")
                        .child(item.label),
                ),
        );
    if let Some(badge) = item.badge {
        el = el.child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__badge")
                .child(ai_badge(badge)),
        );
    }
    if let Some(shortcut) = item.shortcut {
        el = el.child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__shortcut")
                .child(shortcut),
        );
    }
    // radix's item selects on click; the content's onSelect then closes
    Node::Element(el.on("click", move |_| {
        emit(&on_event, event.clone());
        emit(&on_event, ToolbarEvent::ExtraToolsClose);
    }))
}

/// `DropDownMenuItemBadge` of the default (blue) type in the light theme
/// (`DropdownMenuItem.tsx:71-110`).
fn ai_badge(text: &str) -> Element {
    Element::new("div")
        .attr("class", "DropDownMenuItemBadge")
        .style("display", "inline-flex")
        .style("margin-left", "auto")
        .style("padding", "2px 4px")
        .style("border-radius", "6px")
        .style("font-size", "9px")
        .style("font-family", "Cascadia, monospace")
        .style("border", "1.5px solid white")
        .style("background", "var(--color-promo)")
        .style("color", "var(--color-surface-lowest)")
        .child(text.to_owned())
}

/// The open menu: radix's popper wrapper and `Menu.Content` around
/// `DropdownMenuContent`'s island (`DropdownMenuContent.tsx:92-118`).
fn menu(
    props: &ToolbarProps<'_>,
    items: Vec<Option<MenuItem>>,
    trigger_id: &str,
    content_id: &str,
) -> Element {
    let mut children: Vec<Node> = Vec::new();
    for item in items {
        match item {
            Some(item) => children.push(menu_item(item, &props.on_event)),
            None => {
                children.push(Node::Element(
                    Element::new("div")
                        .style("margin", "6px 0px")
                        .style("font-size", "14px")
                        .style("font-weight", "600")
                        .child("Generate"),
                ));
                if props.ai_enabled {
                    children.extend(props.ttd_trigger.clone());
                }
            }
        }
    }
    let container = island(
        IslandProps {
            padding: Some(2.0),
            class_name: Some("dropdown-menu-container".into()),
            ..IslandProps::default()
        },
        children,
    );
    let on_event = props.on_event.clone();
    radix_menu_content(
        "dropdown-menu App-toolbar__extra-tools-dropdown",
        trigger_id,
        content_id,
        container,
        Rc::new(move || emit(&on_event, ToolbarEvent::ExtraToolsClose)),
    )
}

/// radix's popper wrapper and `Menu.Content` (react-dropdown-menu 2.1.16)
/// around a `DropdownMenuContent`'s `container`, of class `class`: placed
/// by its trigger and focused once mounted; Escape and a press outside the
/// dropdown's wrapper ask `close`.
pub(crate) fn radix_menu_content(
    class: &str,
    trigger_id: &str,
    content_id: &str,
    container: Element,
    close: Rc<dyn Fn()>,
) -> Element {
    let on_key = close.clone();
    let trigger = trigger_id.to_owned();
    let content = Element::new("div")
        .attr("id", content_id)
        .attr("aria-labelledby", trigger_id)
        .attr("role", "menu")
        .attr("aria-orientation", "vertical")
        .attr("data-state", "open")
        .attr("data-radix-menu-content", "")
        .attr("dir", "ltr")
        .attr("data-side", "bottom")
        .attr("data-align", "end")
        .attr("class", class)
        .attr("data-testid", "dropdown-menu")
        .attr("tabindex", "-1")
        .attr("data-orientation", "vertical")
        .style("outline", "none")
        .style(
            "--radix-dropdown-menu-content-transform-origin",
            "var(--radix-popper-transform-origin)",
        )
        .style(
            "--radix-dropdown-menu-content-available-width",
            "var(--radix-popper-available-width)",
        )
        .style(
            "--radix-dropdown-menu-content-available-height",
            "var(--radix-popper-available-height)",
        )
        .style(
            "--radix-dropdown-menu-trigger-width",
            "var(--radix-popper-anchor-width)",
        )
        .style(
            "--radix-dropdown-menu-trigger-height",
            "var(--radix-popper-anchor-height)",
        )
        .on("keydown", move |e| {
            if let Some(k) = e.dyn_ref::<KeyboardEvent>() {
                menu_keydown(k, &*on_key);
            }
        })
        .child(container);
    Element::new("div")
        .attr("data-radix-popper-content-wrapper", "")
        .attr("dir", "ltr")
        .on_mount(move |wrapper| {
            place(wrapper, &trigger);
            close_on_outside_press(wrapper, close.clone());
        })
        .child(content)
}

/// The items of the open menu, in order.
fn menu_items(content: &web_sys::Element) -> Vec<web_sys::HtmlElement> {
    let Ok(list) = content.query_selector_all("[role=menuitem]:not([disabled])") else {
        return Vec::new();
    };
    (0..list.length())
        .filter_map(|i| list.item(i))
        .filter_map(|n| n.dyn_into::<web_sys::HtmlElement>().ok())
        .collect()
}

/// Keys in the menu: Escape closes (`DropdownMenuContent.tsx:63-83`), Tab
/// stays, the arrows, Home and End move focus among the items (radix's
/// `Menu.Content` and roving focus group).
fn menu_keydown(e: &KeyboardEvent, close: &dyn Fn()) {
    let key = e.key();
    if key == "Escape" {
        e.prevent_default();
        e.stop_immediate_propagation();
        close();
        return;
    }
    if key == "Tab" {
        e.prevent_default();
        return;
    }
    let Some(content) = e
        .current_target()
        .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
    else {
        return;
    };
    let items = menu_items(&content);
    if items.is_empty() {
        return;
    }
    let focused = content
        .owner_document()
        .and_then(|d| d.active_element())
        .and_then(|a| {
            items
                .iter()
                .position(|i| AsRef::<web_sys::Element>::as_ref(i) == &a)
        });
    let last = items.len() - 1;
    let next = match (key.as_str(), focused) {
        ("ArrowDown", Some(i)) => (i + 1).min(last),
        ("ArrowDown", None) | ("Home", _) | ("PageUp", _) => 0,
        ("ArrowUp", Some(i)) => i.saturating_sub(1),
        ("ArrowUp", None) | ("End", _) | ("PageDown", _) => last,
        _ => return,
    };
    e.prevent_default();
    let _ = items[next].focus();
}

/// Places the popper wrapper by its trigger and focuses the menu (radix
/// focuses the content when it opens).
fn place(wrapper: &web_sys::Element, trigger_id: &str) {
    let Some(document) = wrapper.owner_document() else {
        return;
    };
    let Some(trigger) = document.get_element_by_id(trigger_id) else {
        return;
    };
    let Some(html) = wrapper.dyn_ref::<web_sys::HtmlElement>() else {
        return;
    };
    let style = html.style();
    let _ = style.set_property("position", "fixed");
    let _ = style.set_property("left", "0px");
    let _ = style.set_property("top", "0px");
    let _ = style.set_property("min-width", "max-content");
    let content = wrapper.first_element_child();
    if let Some(z) = content
        .as_ref()
        .and_then(|c| web_sys::window()?.get_computed_style(c).ok().flatten())
        .and_then(|s| s.get_property_value("z-index").ok())
    {
        let _ = style.set_property("z-index", &z);
    }
    let t = trigger.get_bounding_client_rect();
    let c = wrapper.get_bounding_client_rect();
    let (vw, vh) = web_sys::window()
        .map(|w| {
            let n = |v: Result<wasm_bindgen::JsValue, _>| v.ok().and_then(|v| v.as_f64());
            (
                n(w.inner_width()).unwrap_or(0.0),
                n(w.inner_height()).unwrap_or(0.0),
            )
        })
        .unwrap_or((0.0, 0.0));
    let placed = dropdown_position(
        Rect {
            left: t.left(),
            top: t.top(),
            width: t.width(),
            height: t.height(),
        },
        (c.width(), c.height()),
        (vw, vh),
    );
    let _ = style.set_property(
        "transform",
        &format!("translate({}px, {}px)", placed.x, placed.y),
    );
    if let Some(content) = content {
        let side = match placed.side {
            DropdownSide::Bottom => "bottom",
            DropdownSide::Top => "top",
        };
        let _ = content.set_attribute("data-side", side);
        if let Some(c) = content.dyn_ref::<web_sys::HtmlElement>() {
            let opts = web_sys::FocusOptions::new();
            opts.set_prevent_scroll(true);
            let _ = c.focus_with_options(&opts);
        }
    }
}

/// Asks to close on a press outside the dropdown's wrapper (the trigger
/// toggles itself) while the menu is in the document (`useOutsideClick`,
/// `DropdownMenuContent.tsx:48-61`).
fn close_on_outside_press(wrapper: &web_sys::Element, close: Rc<dyn Fn()>) {
    let Some(document) = wrapper.owner_document() else {
        return;
    };
    let slot: Rc<RefCell<Option<js_sys::Function>>> = Rc::default();
    let own = slot.clone();
    let menu = wrapper.clone();
    let target = document.clone();
    let closure = Closure::<dyn FnMut(Event)>::new(move |e: Event| {
        if !menu.is_connected() {
            if let Some(f) = own.borrow_mut().take() {
                let _ = target.remove_event_listener_with_callback("pointerdown", &f);
                let _ = target.remove_event_listener_with_callback("touchstart", &f);
            }
            return;
        }
        let node = e.target().and_then(|t| t.dyn_into::<web_sys::Node>().ok());
        let Some(node) = node else {
            return;
        };
        if menu.contains(Some(&node))
            || !target
                .document_element()
                .is_some_and(|d| d.contains(Some(&node)))
        {
            return;
        }
        let in_wrapper = menu
            .closest(&format!(".{DROPDOWN_MENU_EVENT_WRAPPER}"))
            .ok()
            .flatten()
            .is_some_and(|w| w.contains(Some(&node)));
        if !in_wrapper {
            close();
        }
    });
    let f: js_sys::Function = closure.into_js_value().unchecked_into();
    let _ = document.add_event_listener_with_callback("pointerdown", &f);
    let _ = document.add_event_listener_with_callback("touchstart", &f);
    *slot.borrow_mut() = Some(f);
}

// -- placement ----------------------------------------------------------------

/// The side of the trigger the menu opened on.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DropdownSide {
    Bottom,
    Top,
}

/// Where the menu goes: its top-left corner in the viewport and its side.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DropdownPlacement {
    pub x: f64,
    pub y: f64,
    pub side: DropdownSide,
}

/// The menu's placement for a trigger rect, the menu's size and the
/// viewport, as radix's Popper places `DropdownMenuContent` (side bottom,
/// `align="end"`, `sideOffset={8}`, collisions avoided with no padding)
/// through floating-ui: below the trigger with the right edges aligned,
/// flipped above when it overflows below and fits there (else on the side
/// that overflows less, below on a tie), then shifted horizontally into
/// the viewport.
pub fn dropdown_position(
    trigger: Rect,
    content: (f64, f64),
    viewport: (f64, f64),
) -> DropdownPlacement {
    let (width, height) = content;
    let below = trigger.top + trigger.height + DROPDOWN_SIDE_OFFSET;
    let above = trigger.top - DROPDOWN_SIDE_OFFSET - height;
    let overflow_below = (below + height - viewport.1).max(0.0);
    let overflow_above = (-above).max(0.0);
    let side = if overflow_below > 0.0 && overflow_above < overflow_below {
        DropdownSide::Top
    } else {
        DropdownSide::Bottom
    };
    let y = match side {
        DropdownSide::Bottom => below,
        DropdownSide::Top => above,
    };
    let x = trigger.left + trigger.width - width;
    let x = x.min(viewport.0 - width).max(0.0);
    DropdownPlacement { x, y, side }
}

// -- activation ---------------------------------------------------------------

fn set_tool(tools: &mut ToolState, ty: ToolType) -> Result<ToolSwitch, ToolRefusal> {
    tools.set_active_tool(
        ToolRequest::new(Tool::Builtin(ty)),
        SetActiveToolOptions::default(),
    )
}

/// A tool button's `onSelect` (`Tools.tsx:300-316`, the selection button's
/// :340-352): the first pen press turns pen mode on; pointer-clicking the
/// active selection tool switches to the lasso; any other button activates
/// its tool unless it is already active (`None` when nothing is asked of
/// `setActiveTool`).
pub fn activate_tool_button(
    tools: &mut ToolState,
    ty: ToolType,
    pointer: Option<PointerType>,
) -> Option<Result<ToolSwitch, ToolRefusal>> {
    if !tools.pen_detected && pointer == Some(PointerType::Pen) {
        tools.toggle_pen_mode(Some(true));
    }
    let active = active_type(tools);
    if ty == ToolType::Selection && active == Some(ToolType::Selection) && pointer.is_some() {
        return Some(set_tool(tools, ToolType::Lasso));
    }
    if active == Some(ty) {
        return None;
    }
    Some(set_tool(tools, ty))
}

/// A dropdown tool item's `onSelect` (`Toolbar.tsx:124-189`): activates its
/// tool.
pub fn activate_extra_tool(tools: &mut ToolState, ty: ToolType) -> Result<ToolSwitch, ToolRefusal> {
    set_tool(tools, ty)
}
