//! The help dialog (`components/HelpDialog.tsx`, `HelpDialog.scss`): a
//! [`dialog`] titled "Help" with the header links (documentation, blog,
//! GitHub issues, YouTube) and, under "Keyboard shortcuts", the Tools,
//! View and Editor islands (research `ui-design-system.md` §3.5).
//!
//! [`shortcut_islands`] is the dialog's content as data, per [`Platform`]
//! (`isDarwin` picks Cmd and Option, `isWindows` adds Ctrl+Y to redo,
//! `isFirefox` drops the second command palette shortcut, and copy as PNG
//! needs `probablySupportsClipboardBlob` or Firefox) and whether the host
//! enables the theme action (`UIOptions.canvasActions.toggleTheme`,
//! `actionToggleTheme.predicate`); [`help_dialog`] builds the DOM upstream
//! leaves from it (`tests/help_dialog.rs` holds every case of
//! `tests/fixtures/help-dialog.json` to it), and
//! [`shortcuts_page_section`] the section of the shortcuts page
//! (`site/content/design-system/shortcuts.md`) that lists it.
//!
//! The host opens the dialog while `appState.openDialog.name` is `"help"`
//! (`LayerUI.tsx:577-583`, [`crate::footer::toggle_shortcuts`]) and on
//! close applies [`close_help_dialog`].

use std::rc::Rc;

use excali_core::app_state::AppState;
use excali_editor::actions::{get_shortcut_from_shortcut_name, get_shortcut_key, KeyLabels};
use excali_scene::shape::Theme;
use serde_json::Value;

use crate::dom::{Element, Node};
use crate::icons;
use crate::primitives::{dialog, DialogProps, DialogSize};

/// Upstream's `components/HelpDialog.scss`, compiled (generated by
/// `tools/goldens/help-dialog.mjs`).
pub const HELP_DIALOG_CSS: &str = include_str!("help_dialog.css");

/// The `data-excali-ui` value of the `<style>` holding [`HELP_DIALOG_CSS`].
const STYLESHEET_ID: &str = "help-dialog";

/// Adds [`HELP_DIALOG_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(HELP_DIALOG_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings of the help dialog (`locales/en.json`, every
/// `t(...)` key of `HelpDialog.tsx`); the key itself for any other.
pub fn help_text(key: &str) -> &str {
    match key {
        "helpDialog.documentation" => "Documentation",
        "helpDialog.blog" => "Read our blog",
        "helpDialog.github" => "Found an issue? Submit",
        "helpDialog.or" => "or",
        "helpDialog.title" => "Help",
        "helpDialog.shortcuts" => "Keyboard shortcuts",
        "helpDialog.tools" => "Tools",
        "helpDialog.view" => "View",
        "helpDialog.editor" => "Editor",
        "helpDialog.editLineArrowPoints" => "Edit line/arrow points",
        "helpDialog.editText" => "Edit text / add label",
        "helpDialog.textNewLine" => "Add new line (text editor)",
        "helpDialog.textFinish" => "Finish editing (text editor)",
        "helpDialog.curvedArrow" => "Curved arrow",
        "helpDialog.curvedLine" => "Curved line",
        "helpDialog.click" => "click",
        "helpDialog.doubleClick" => "double-click",
        "helpDialog.drag" => "drag",
        "helpDialog.cropStart" => "Crop image",
        "helpDialog.cropFinish" => "Finish image cropping",
        "helpDialog.preventBinding" => "Prevent arrow binding",
        "helpDialog.zoomToFit" => "Zoom to fit all elements",
        "helpDialog.zoomToSelection" => "Zoom to selection",
        "helpDialog.movePageUpDown" => "Move page up/down",
        "helpDialog.movePageLeftRight" => "Move page left/right",
        "helpDialog.createFlowchart" => "Create a flowchart from a generic element",
        "helpDialog.navigateFlowchart" => "Navigate a flowchart",
        "helpDialog.deepSelect" => "Deep select",
        "helpDialog.deepBoxSelect" => "Deep select within box, and prevent dragging",
        "helpDialog.toggleElementLock" => "Lock/unlock selection",
        "toolBar.hand" => "Hand (panning tool)",
        "toolBar.selection" => "Selection",
        "toolBar.rectangle" => "Rectangle",
        "toolBar.diamond" => "Diamond",
        "toolBar.ellipse" => "Ellipse",
        "toolBar.arrow" => "Arrow",
        "toolBar.line" => "Line",
        "toolBar.freedraw" => "Draw",
        "toolBar.text" => "Text",
        "toolBar.stickynote" => "Sticky note",
        "toolBar.image" => "Insert image",
        "toolBar.eraser" => "Eraser",
        "toolBar.frame" => "Frame tool",
        "toolBar.laser" => "Laser pointer",
        "toolBar.bucketfill" => "Bucket fill",
        "toolBar.lock" => "Keep selected tool active after drawing",
        "toolBar.link" => "Add / Update link for a selected shape",
        "toolBar.convertElementType" => "Toggle shape type",
        "buttons.zoomIn" => "Zoom in",
        "buttons.zoomOut" => "Zoom out",
        "buttons.resetZoom" => "Reset zoom",
        "buttons.zenMode" => "Zen mode",
        "buttons.objectsSnapMode" => "Snap to objects",
        "buttons.clearReset" => "Reset the canvas",
        "buttons.undo" => "Undo",
        "buttons.redo" => "Redo",
        "labels.eyeDropper" => "Pick color from canvas",
        "labels.toggleGrid" => "Toggle grid",
        "labels.viewMode" => "View mode",
        "labels.toggleTheme" => "Toggle light/dark theme",
        "labels.moveCanvas" => "Move canvas",
        "labels.delete" => "Delete",
        "labels.cut" => "Cut",
        "labels.copy" => "Copy",
        "labels.paste" => "Paste",
        "labels.pasteAsPlaintext" => "Paste as plaintext",
        "labels.selectAll" => "Select all",
        "labels.multiSelect" => "Add element to selection",
        "labels.copyAsPng" => "Copy to clipboard as PNG",
        "labels.copyStyles" => "Copy styles",
        "labels.pasteStyles" => "Paste styles",
        "labels.sendToBack" => "Send to back",
        "labels.bringToFront" => "Bring to front",
        "labels.sendBackward" => "Send backward",
        "labels.bringForward" => "Bring forward",
        "labels.alignTop" => "Align top",
        "labels.alignBottom" => "Align bottom",
        "labels.alignLeft" => "Align left",
        "labels.alignRight" => "Align right",
        "labels.duplicateSelection" => "Duplicate",
        "labels.group" => "Group selection",
        "labels.ungroup" => "Ungroup selection",
        "labels.flipHorizontal" => "Flip horizontal",
        "labels.flipVertical" => "Flip vertical",
        "labels.showStroke" => "Show stroke color picker",
        "labels.showBackground" => "Show background color picker",
        "labels.showFonts" => "Show font picker",
        "labels.decreaseFontSize" => "Decrease font size",
        "labels.increaseFontSize" => "Increase font size",
        "stats.fullTitle" => "Canvas & Shape properties",
        "search.title" => "Find on canvas",
        "commandPalette.title" => "Command palette",
        other => other,
    }
}

/// The browser facts the dialog reads when upstream's modules load
/// (`common/src/editorInterface.ts:37-43`, `clipboard.ts:68-72`).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Platform {
    /// `isDarwin`: Cmd for CtrlOrCmd, Option for Alt.
    pub darwin: bool,
    /// `isWindows`: redo also reads Ctrl+Y.
    pub windows: bool,
    /// `isFirefox`: one command palette shortcut; copy as PNG always shown.
    pub firefox: bool,
    /// `probablySupportsClipboardBlob`.
    pub clipboard_blob: bool,
}

/// One `Shortcut` row: its label and shortcuts, each a `+`-joined string
/// as upstream passes it (split by [`shortcut_keys`]).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShortcutRow {
    pub label: String,
    pub shortcuts: Vec<String>,
    /// `isOr`: "or" between the shortcuts; otherwise they are one sequence.
    pub is_or: bool,
}

/// One `ShortcutIsland`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShortcutIsland {
    /// `HelpDialog__island--tools`, `--view` or `--editor`.
    pub class_name: &'static str,
    pub caption: String,
    pub rows: Vec<ShortcutRow>,
}

/// `upperCaseSingleChars` (`HelpDialog.tsx:91-93`): the first lone
/// lowercase ASCII letter (`/\b[a-z]\b/`, not global) upper-cased.
fn upper_case_single_chars(key: &str) -> String {
    let word = |c: Option<char>| c.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_');
    let chars: Vec<char> = key.chars().collect();
    for i in 0..chars.len() {
        let before = i.checked_sub(1).map(|j| chars[j]);
        if chars[i].is_ascii_lowercase() && !word(before) && !word(chars.get(i + 1).copied()) {
            let mut out = chars.clone();
            out[i] = chars[i].to_ascii_uppercase();
            return out.into_iter().collect();
        }
    }
    key.to_owned()
}

/// The keys of one shortcut as `Shortcut` shows them
/// (`HelpDialog.tsx:104-111`): split on `+`, a trailing `++` ending in the
/// `+` key, each key through `upperCaseSingleChars`.
pub fn shortcut_keys(shortcut: &str) -> Vec<String> {
    let keys: Vec<&str> = match shortcut.strip_suffix("++") {
        Some(head) => head.split('+').chain(["+"]).collect(),
        None => shortcut.split('+').collect(),
    };
    keys.into_iter().map(upper_case_single_chars).collect()
}

/// The three islands for `platform` (`HelpDialog.tsx:145-516`);
/// `toggle_theme` is `actionManager.isActionEnabled(actionToggleTheme)`.
pub fn shortcut_islands(platform: Platform, toggle_theme: bool) -> Vec<ShortcutIsland> {
    let labels = KeyLabels::EN;
    let key = |s: &str| get_shortcut_key(s, platform.darwin, &labels);
    let named = |name: &str, idx: usize| {
        get_shortcut_from_shortcut_name(name, idx, platform.darwin, &labels)
    };
    let click = help_text("helpDialog.click");
    let drag = help_text("helpDialog.drag");
    let row = |label: &str, shortcuts: Vec<String>| ShortcutRow {
        label: help_text(label).to_owned(),
        shortcuts,
        is_or: true,
    };
    let sequence = |label: &str, shortcuts: Vec<String>| ShortcutRow {
        is_or: false,
        ..row(label, shortcuts)
    };
    let raw = |keys: &[&str]| keys.iter().map(|k| (*k).to_owned()).collect::<Vec<_>>();

    let tools = vec![
        row("toolBar.hand", raw(&["h"])),
        row("toolBar.selection", raw(&["v", "1"])),
        row("toolBar.rectangle", raw(&["r", "2"])),
        row("toolBar.diamond", raw(&["d", "3"])),
        row("toolBar.ellipse", raw(&["o", "4"])),
        row("toolBar.arrow", raw(&["a", "5"])),
        row("toolBar.line", raw(&["l", "6"])),
        row("toolBar.freedraw", raw(&["p", "7"])),
        row("toolBar.text", raw(&["t", "8"])),
        row("toolBar.stickynote", raw(&["n"])),
        row("toolBar.image", raw(&["9"])),
        row("toolBar.eraser", raw(&["e", "0"])),
        row("toolBar.frame", raw(&["f"])),
        row("toolBar.laser", raw(&["k"])),
        row("toolBar.bucketfill", raw(&["b"])),
        row("labels.eyeDropper", raw(&["i", "Shift+S", "Shift+G"])),
        row(
            "helpDialog.editLineArrowPoints",
            vec![key("CtrlOrCmd+Enter")],
        ),
        row("helpDialog.editText", vec![key("Enter")]),
        row(
            "helpDialog.textNewLine",
            vec![key("Enter"), key("Shift+Enter")],
        ),
        row(
            "helpDialog.textFinish",
            vec![key("Esc"), key("CtrlOrCmd+Enter")],
        ),
        sequence("helpDialog.curvedArrow", raw(&["A", click, click, click])),
        sequence("helpDialog.curvedLine", raw(&["L", click, click, click])),
        row(
            "helpDialog.cropStart",
            vec![help_text("helpDialog.doubleClick").to_owned(), key("Enter")],
        ),
        row("helpDialog.cropFinish", vec![key("Enter"), key("Escape")]),
        row("toolBar.lock", raw(&["q"])),
        row("helpDialog.preventBinding", vec![key("CtrlOrCmd")]),
        row("toolBar.link", vec![key("CtrlOrCmd+K")]),
        row("toolBar.convertElementType", raw(&["Tab", "Shift+Tab"])),
    ];

    let mut view = vec![
        row("buttons.zoomIn", vec![key("CtrlOrCmd++")]),
        row("buttons.zoomOut", vec![key("CtrlOrCmd+-")]),
        row("buttons.resetZoom", vec![key("CtrlOrCmd+0")]),
        row("helpDialog.zoomToFit", raw(&["Shift+1"])),
        row("helpDialog.zoomToSelection", raw(&["Shift+2"])),
        row("helpDialog.movePageUpDown", raw(&["PgUp/PgDn"])),
        row("helpDialog.movePageLeftRight", raw(&["Shift+PgUp/PgDn"])),
        row("buttons.zenMode", vec![key("Alt+Z")]),
        row("buttons.objectsSnapMode", vec![key("Alt+S")]),
        row("labels.toggleGrid", vec![key("CtrlOrCmd+'")]),
        row("labels.viewMode", vec![key("Alt+R")]),
    ];
    if toggle_theme {
        view.push(row("labels.toggleTheme", vec![key("Alt+Shift+D")]));
    }
    view.push(row("stats.fullTitle", vec![key("Alt+/")]));
    view.push(row("search.title", vec![named("searchMenu", 0)]));
    view.push(row(
        "commandPalette.title",
        if platform.firefox {
            vec![named("commandPalette", 0)]
        } else {
            vec![named("commandPalette", 0), named("commandPalette", 1)]
        },
    ));

    let mut editor = vec![
        row(
            "helpDialog.createFlowchart",
            vec![key("CtrlOrCmd+Arrow Key")],
        ),
        row("helpDialog.navigateFlowchart", vec![key("Alt+Arrow Key")]),
        row(
            "labels.moveCanvas",
            vec![key(&format!("Space+{drag}")), key(&format!("Wheel+{drag}"))],
        ),
        row("buttons.clearReset", vec![key("CtrlOrCmd+Delete")]),
        row("labels.delete", vec![key("Delete")]),
        row("labels.cut", vec![key("CtrlOrCmd+X")]),
        row("labels.copy", vec![key("CtrlOrCmd+C")]),
        row("labels.paste", vec![key("CtrlOrCmd+V")]),
        row("labels.pasteAsPlaintext", vec![key("CtrlOrCmd+Shift+V")]),
        row("labels.selectAll", vec![key("CtrlOrCmd+A")]),
        row("labels.multiSelect", vec![key(&format!("Shift+{click}"))]),
        row(
            "helpDialog.deepSelect",
            vec![key(&format!("CtrlOrCmd+{click}"))],
        ),
        row(
            "helpDialog.deepBoxSelect",
            vec![key(&format!("CtrlOrCmd+{drag}"))],
        ),
    ];
    if platform.clipboard_blob || platform.firefox {
        editor.push(row("labels.copyAsPng", vec![key("Shift+Alt+C")]));
    }
    let (to_back, to_front) = if platform.darwin {
        ("CtrlOrCmd+Alt+[", "CtrlOrCmd+Alt+]")
    } else {
        ("CtrlOrCmd+Shift+[", "CtrlOrCmd+Shift+]")
    };
    editor.extend([
        row("labels.copyStyles", vec![key("CtrlOrCmd+Alt+C")]),
        row("labels.pasteStyles", vec![key("CtrlOrCmd+Alt+V")]),
        row("labels.sendToBack", vec![key(to_back)]),
        row("labels.bringToFront", vec![key(to_front)]),
        row("labels.sendBackward", vec![key("CtrlOrCmd+[")]),
        row("labels.bringForward", vec![key("CtrlOrCmd+]")]),
        row("labels.alignTop", vec![key("CtrlOrCmd+Shift+Up")]),
        row("labels.alignBottom", vec![key("CtrlOrCmd+Shift+Down")]),
        row("labels.alignLeft", vec![key("CtrlOrCmd+Shift+Left")]),
        row("labels.alignRight", vec![key("CtrlOrCmd+Shift+Right")]),
        row(
            "labels.duplicateSelection",
            vec![key("CtrlOrCmd+D"), key(&format!("Alt+{drag}"))],
        ),
        row(
            "helpDialog.toggleElementLock",
            vec![key("CtrlOrCmd+Shift+L")],
        ),
        row("buttons.undo", vec![key("CtrlOrCmd+Z")]),
        row(
            "buttons.redo",
            if platform.windows {
                vec![key("CtrlOrCmd+Y"), key("CtrlOrCmd+Shift+Z")]
            } else {
                vec![key("CtrlOrCmd+Shift+Z")]
            },
        ),
        row("labels.group", vec![key("CtrlOrCmd+G")]),
        row("labels.ungroup", vec![key("CtrlOrCmd+Shift+G")]),
        row("labels.flipHorizontal", vec![key("Shift+H")]),
        row("labels.flipVertical", vec![key("Shift+V")]),
        row("labels.showStroke", vec![key("S")]),
        row("labels.showBackground", vec![key("G")]),
        row("labels.showFonts", vec![key("Shift+F")]),
        row("labels.decreaseFontSize", vec![key("CtrlOrCmd+Shift+<")]),
        row("labels.increaseFontSize", vec![key("CtrlOrCmd+Shift+>")]),
    ]);

    vec![
        ShortcutIsland {
            class_name: "HelpDialog__island--tools",
            caption: help_text("helpDialog.tools").to_owned(),
            rows: tools,
        },
        ShortcutIsland {
            class_name: "HelpDialog__island--view",
            caption: help_text("helpDialog.view").to_owned(),
            rows: view,
        },
        ShortcutIsland {
            class_name: "HelpDialog__island--editor",
            caption: help_text("helpDialog.editor").to_owned(),
            rows: editor,
        },
    ]
}

/// The help dialog's props.
#[derive(Clone, Default)]
pub struct HelpDialogProps {
    pub platform: Platform,
    /// `actionManager.isActionEnabled(actionToggleTheme)`.
    pub toggle_theme_enabled: bool,
    /// The editor container's id: the title's id is `{id}-dialog-title`.
    pub container_id: String,
    pub theme: Theme,
    /// The phone form factor: full screen, with a close button.
    pub phone: bool,
    /// `onClose`: the host applies [`close_help_dialog`].
    pub on_close: Option<Rc<dyn Fn()>>,
}

fn icon_node(name: &str) -> Node {
    let icon = icons::icon(name).unwrap_or_else(|| panic!("icons.tsx has no {name}"));
    Node::Element(
        icon.element(Theme::Light)
            .unwrap_or_else(|| panic!("{name} is a path list")),
    )
}

/// `Header` (`HelpDialog.tsx:21-60`).
fn header() -> Element {
    let link = |href: &str, rel: &str, icon: &str, label: &str| {
        Element::new("a")
            .attr("class", "HelpDialog__btn")
            .attr("href", href)
            .attr("target", "_blank")
            .attr("rel", rel)
            .child(
                Element::new("div")
                    .attr("class", "HelpDialog__link-icon")
                    .child(icon_node(icon)),
            )
            .child(label)
    };
    Element::new("div")
        .attr("class", "HelpDialog__header")
        .child(link(
            "https://docs.excalidraw.com",
            "noopener",
            "ExternalLinkIcon",
            help_text("helpDialog.documentation"),
        ))
        .child(link(
            "https://plus.excalidraw.com/blog",
            "noopener",
            "ExternalLinkIcon",
            help_text("helpDialog.blog"),
        ))
        .child(link(
            "https://github.com/excalidraw/excalidraw/issues",
            "noopener noreferrer",
            "GithubIcon",
            help_text("helpDialog.github"),
        ))
        .child(link(
            "https://youtube.com/@excalidraw",
            "noopener noreferrer",
            "youtubeIcon",
            "YouTube",
        ))
}

/// `Shortcut` (`HelpDialog.tsx:95-122`): the label, then each shortcut's
/// keys as `kbd`s, with "or" between shortcuts when `is_or`.
fn shortcut(row: &ShortcutRow) -> Element {
    let mut keys = Element::new("div").attr("class", "HelpDialog__key-container");
    for (i, s) in row.shortcuts.iter().enumerate() {
        if i > 0 && row.is_or {
            keys = keys.child(help_text("helpDialog.or"));
        }
        for key in shortcut_keys(s) {
            keys = keys.child(
                Element::new("kbd")
                    .attr("class", "HelpDialog__key")
                    .child(key),
            );
        }
    }
    Element::new("div")
        .attr("class", "HelpDialog__shortcut")
        .child(Element::new("div").child(row.label.clone()))
        .child(keys)
}

/// `ShortcutIsland` (`HelpDialog.tsx:69-78`).
fn island(island: &ShortcutIsland) -> Element {
    Element::new("div")
        .attr("class", format!("HelpDialog__island {}", island.class_name))
        .child(
            Element::new("h4")
                .attr("class", "HelpDialog__island-title")
                .child(island.caption.clone()),
        )
        .child(
            Element::new("div")
                .attr("class", "HelpDialog__island-content")
                .children_from(island.rows.iter().map(|r| Node::Element(shortcut(r)))),
        )
}

/// `HelpDialog` (`HelpDialog.tsx:128-521`): the modal container the
/// dialog portals to the body ([`crate::primitives::open_modal`] mounts
/// it there).
pub fn help_dialog(props: HelpDialogProps) -> Element {
    let islands = shortcut_islands(props.platform, props.toggle_theme_enabled);
    let section = [
        Node::Element(Element::new("h3").child(help_text("helpDialog.shortcuts"))),
        Node::Element(
            Element::new("div")
                .attr("class", "HelpDialog__islands-container")
                .children_from(islands.iter().map(|i| Node::Element(island(i)))),
        ),
    ];
    dialog(
        DialogProps {
            class_name: Some("HelpDialog".into()),
            size: DialogSize::Default,
            title: Some(Node::text(help_text("helpDialog.title"))),
            container_id: props.container_id,
            theme: props.theme,
            phone: props.phone,
            on_close_request: props.on_close,
            ..DialogProps::default()
        },
        std::iter::once(Node::Element(header()))
            .chain(section)
            .collect(),
    )
}

/// Closing the dialog: `Dialog`'s `setAppState({openMenu: null})`
/// (`Dialog.tsx:94-99`), then LayerUI's `onClose`,
/// `setAppState({openDialog: null})` (`LayerUI.tsx:577-583`).
pub fn close_help_dialog(app_state: &mut AppState) {
    app_state.insert("openMenu", Value::Null);
    app_state.insert("openDialog", Value::Null);
}

/// The "Help dialog" section of the shortcuts page
/// (`site/content/design-system/shortcuts.md`): the three islands as the
/// dialog shows them on Linux with the async clipboard and the theme
/// action, one table each, every key in a code span, "or" between
/// alternatives; then what the other platforms change.
pub fn shortcuts_page_section() -> String {
    let platform = Platform {
        clipboard_blob: true,
        ..Platform::default()
    };
    let mut out = String::from(
        "## Help dialog\n\n\
         What the Help dialog (`?`) shows, row for row, as upstream renders it on \
         Linux with the async clipboard and the theme action enabled \
         (`HelpDialog.tsx:145-516`). `tests/help_dialog.rs` fails when this section \
         and the port's dialog differ.\n",
    );
    for island in shortcut_islands(platform, true) {
        out.push_str(&format!(
            "\n### {}\n\n| Action | Keys |\n|---|---|\n",
            island.caption
        ));
        for row in &island.rows {
            let group = |s: &String| {
                shortcut_keys(s)
                    .iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join(" ")
            };
            let separator = if row.is_or {
                format!(" {} ", help_text("helpDialog.or"))
            } else {
                " ".to_owned()
            };
            let keys = row
                .shortcuts
                .iter()
                .map(group)
                .collect::<Vec<_>>()
                .join(&separator);
            out.push_str(&format!("| {} | {keys} |\n", row.label));
        }
    }
    out.push_str(
        "\nOn a Mac every `Ctrl` reads `Cmd` and every `Alt` reads `Option`, and send to \
         back and bring to front are `Cmd` `Option` `[` and `Cmd` `Option` `]`. Windows \
         adds `Ctrl` `Y` before redo's `Ctrl` `Shift` `Z`. Firefox lists only `Ctrl` `/` \
         for the command palette. Copy to clipboard as PNG is shown only with the async \
         clipboard or in Firefox, and toggle theme only when the host enables the theme \
         action.\n",
    );
    out
}
