//! The command palette (`components/CommandPalette/CommandPalette.tsx`,
//! `CommandPalette.scss`): a [`dialog`] 720 px wide with a search field,
//! the key hints and the commands by category (research
//! `ui-design-system.md` §3.14).
//!
//! [`palette_commands`] is the palette's `allCommands` as data: the
//! commands built from actions ([`commands_from_actions`]), the additional
//! ones (library, search, shape switch, the colour pickers, each tool, the
//! tool lock, text to diagram and Mermaid) and the host's own
//! (`customCommandPaletteItems`; [`hosted_app_links`] are the hosted app's
//! Links), each with the availability `isCommandAvailable` gives it;
//! [`library_commands`] are the named library items. [`palette_view`]
//! filters, searches (upstream's `fuzzy` 0.1.3, [`fuzzy_match`]) and groups
//! them by category in `getCategoryOrder`'s order (App, Export, Editor,
//! Tools, Elements, Links, then Library), [`palette_key_down`] is the
//! palette's window key handler and [`command_palette`] builds the DOM
//! upstream renders. `tests/command_palette.rs` holds all of them to
//! `tests/fixtures/command-palette.json`.
//!
//! The host opens the palette while `appState.openDialog.name` is
//! `"commandPalette"` (Ctrl/Cmd+/ or Ctrl/Cmd+Shift+P:
//! [`excali_editor::keyboard::command_palette_key_down`]) and, to run a
//! command, closes it and applies [`perform_command`]'s effects.

use std::rc::Rc;

use excali_core::app_state::AppState;
use excali_core::library::LibraryItem;
use excali_editor::actions::{
    commands_from_actions, get_shortcut_key, palette_change_background_available,
    palette_change_stroke_available, palette_command_available, ActionContext, ActionName,
    ActionSource, KeyLabels, PaletteCategory, PaletteCommandSource,
};
use excali_editor::tools::{get_tool_letter, ShortcutLabels, ToolType, TOOLS};
use excali_scene::shape::Theme;
use serde_json::{json, Map, Value};

use crate::dom::{Element, Node};
use crate::icons;
use crate::library_sidebar::deburr;
use crate::primitives::{
    dialog, text_field, DialogProps, DialogSize, TextFieldProps, TextFieldValue,
};

/// Upstream's `components/CommandPalette/CommandPalette.scss`, compiled
/// (generated by `tools/goldens/command-palette.mjs`).
pub const COMMAND_PALETTE_CSS: &str = include_str!("command_palette.css");

/// The `data-excali-ui` value of the `<style>` holding
/// [`COMMAND_PALETTE_CSS`].
const STYLESHEET_ID: &str = "command-palette";

/// Adds [`COMMAND_PALETTE_CSS`] to `document`'s head once, right after the
/// primitives' stylesheet ([`crate::primitives::install_stylesheet`], which
/// it installs first), so the host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::primitives::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(COMMAND_PALETTE_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let primitives = document.query_selector("style[data-excali-ui=\"primitives\"]")?;
    let next = primitives.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings of the palette (`locales/en.json`): the `t(...)`
/// keys of `CommandPalette.tsx`, each tool's `toolBar.<tool>`, the palette
/// actions' labels and the hosted app's Links; the key itself for any
/// other.
pub fn palette_text(key: &str) -> &str {
    match key {
        "buttons.darkMode" => "Dark mode",
        "buttons.exportImage" => "Export image...",
        "buttons.lightMode" => "Light mode",
        "buttons.objectsSnapMode" => "Snap to objects",
        "buttons.redo" => "Redo",
        "buttons.resetZoom" => "Reset zoom",
        "buttons.save" => "Save to current file",
        "buttons.undo" => "Undo",
        "buttons.zenMode" => "Zen mode",
        "buttons.zoomIn" => "Zoom in",
        "buttons.zoomOut" => "Zoom out",
        "commandPalette.itemNotAvailable" => "Command is not available...",
        "commandPalette.recents" => "Recently used",
        "commandPalette.search.noMatch" => "No matching commands...",
        "commandPalette.search.placeholder" => "Search menus, commands, and discover hidden gems",
        "commandPalette.shortcuts.close" => "Close",
        "commandPalette.shortcuts.confirm" => "Confirm",
        "commandPalette.shortcuts.select" => "Select",
        "exportDialog.disk_title" => "Save to disk",
        "helpDialog.cropStart" => "Crop image",
        "helpDialog.zoomToFit" => "Zoom to fit all elements",
        "helpDialog.zoomToSelection" => "Zoom to selection",
        "labels.alignBottom" => "Align bottom",
        "labels.alignLeft" => "Align left",
        "labels.alignRight" => "Align right",
        "labels.alignTop" => "Align top",
        "labels.bringForward" => "Bring forward",
        "labels.bringToFront" => "Bring to front",
        "labels.canvasBackground" => "Canvas background",
        "labels.centerHorizontally" => "Center horizontally",
        "labels.centerVertically" => "Center vertically",
        "labels.changeBackground" => "Change background color",
        "labels.changeStroke" => "Change stroke color",
        "labels.clearCanvas" => "Clear canvas",
        "labels.copy" => "Copy",
        "labels.copyAsPng" => "Copy to clipboard as PNG",
        "labels.copyAsSvg" => "Copy to clipboard as SVG",
        "labels.copyElementLink" => "Copy link to object",
        "labels.copyStyles" => "Copy styles",
        "labels.cut" => "Cut",
        "labels.decreaseFontSize" => "Decrease font size",
        "labels.delete" => "Delete",
        "labels.discordChat" => "Discord chat",
        "labels.duplicateSelection" => "Duplicate",
        "labels.elementLock.lock" => "Lock",
        "labels.elementLock.unlock" => "Unlock",
        "labels.elementLock.unlockAll" => "Unlock all",
        "labels.flipHorizontal" => "Flip horizontal",
        "labels.flipVertical" => "Flip vertical",
        "labels.followUs" => "Follow us",
        "labels.group" => "Group selection",
        "labels.increaseFontSize" => "Increase font size",
        "labels.lineEditor.edit" => "Edit line",
        "labels.lineEditor.editArrow" => "Edit arrow",
        "labels.link.create" => "Add link",
        "labels.link.createEmbed" => "",
        "labels.link.edit" => "Edit link",
        "labels.link.editEmbed" => "Edit embeddable link",
        "labels.linkToElement" => "Link to object",
        "labels.pasteStyles" => "Paste styles",
        "labels.polygon.breakPolygon" => "Break polygon",
        "labels.polygon.convertToPolygon" => "Convert to polygon",
        "labels.selectAll" => "Select all",
        "labels.sendBackward" => "Send backward",
        "labels.sendToBack" => "Send to back",
        "labels.shapeSwitch" => "Switch shape",
        "labels.textToDiagram" => "Text to diagram",
        "labels.toggleGrid" => "Toggle grid",
        "labels.ungroup" => "Ungroup selection",
        "labels.viewMode" => "View mode",
        "labels.wrapSelectionInFrame" => "Wrap selection in frame",
        "labels.zoomToFitViewport" => "Zoom to fit in viewport",
        "search.title" => "Find on canvas",
        "stats.fullTitle" => "Canvas & Shape properties",
        "toolBar.arrow" => "Arrow",
        "toolBar.autoshape" => "Draw to shape",
        "toolBar.bucketfill" => "Bucket fill",
        "toolBar.diamond" => "Diamond",
        "toolBar.ellipse" => "Ellipse",
        "toolBar.embeddable" => "Web Embed",
        "toolBar.eraser" => "Eraser",
        "toolBar.frame" => "Frame tool",
        "toolBar.freedraw" => "Draw",
        "toolBar.hand" => "Hand (panning tool)",
        "toolBar.image" => "Insert image",
        "toolBar.laser" => "Laser pointer",
        "toolBar.lasso" => "Lasso selection",
        "toolBar.library" => "Library",
        "toolBar.line" => "Line",
        "toolBar.lock" => "Keep selected tool active after drawing",
        "toolBar.magicframe" => "Wireframe to code",
        "toolBar.mermaidToExcalidraw" => "Mermaid to Excalidraw",
        "toolBar.rectangle" => "Rectangle",
        "toolBar.selection" => "Selection",
        "toolBar.stickynote" => "Sticky note",
        "toolBar.text" => "Text",
        "welcomeScreen.defaults.helpHint" => "Shortcuts & help",
        other => other,
    }
}

/// What the palette reads from the editor besides the actions' context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PaletteEnv {
    /// `isDarwin`: Cmd and Option in the shortcuts.
    pub is_darwin: bool,
    /// The phone form factor: full screen, no key hints or shortcuts.
    pub phone: bool,
    /// `props.aiEnabled` (`index.tsx` passes `aiEnabled !== false`): the
    /// text-to-diagram and Mermaid commands.
    pub ai_enabled: bool,
    /// `UIOptions.tools.image !== false`: the image tool's command.
    pub image_tool: bool,
}

impl Default for PaletteEnv {
    fn default() -> PaletteEnv {
        PaletteEnv {
            is_darwin: false,
            phone: false,
            ai_enabled: true,
            image_tool: true,
        }
    }
}

/// What running a command does, after the palette closes
/// (`setAppState({openDialog: null})`, `CommandPalette.tsx:645-671`).
#[derive(Debug, Clone, PartialEq)]
pub enum PaletteEffect {
    /// `actionManager.executeAction(action, source)`.
    ExecuteAction(ActionName, ActionSource),
    /// `setAppState(patch)`.
    SetAppState(Map<String, Value>),
    /// `editorJotaiStore.set(activeConfirmDialogAtom, name)`.
    ConfirmDialog(&'static str),
    /// `app.setActiveTool({type}, {toggle: false})`.
    SetActiveTool(ToolType),
    /// `app.toggleLock()`.
    ToggleLock,
    /// `app.onInsertElements(distributeLibraryItemsOnSquareGrid([item]))`,
    /// the library item's id.
    InsertLibraryItem(String),
    /// `window.open(url, "_blank", "noopener noreferrer")`.
    OpenUrl(&'static str),
}

/// What a command runs.
#[derive(Debug, Clone, PartialEq)]
pub enum PalettePerform {
    /// The effect as built.
    Effect(PaletteEffect),
    /// The library command: close the sidebar when one is open, else open
    /// the default sidebar on its library tab (`CommandPalette.tsx:424-446`).
    ToggleLibrary,
    /// The canvas background command: toggle the main menu and open the
    /// canvas background picker (`CommandPalette.tsx:503-514`).
    CanvasBackground,
}

/// A command (`CommandPaletteItem` after `allCommands`' map,
/// `CommandPalette.tsx:595-607`).
#[derive(Debug, Clone, PartialEq)]
pub struct PaletteCommand {
    pub label: String,
    pub category: PaletteCategory,
    /// `getCategoryOrder(category)`.
    pub order: u32,
    /// The shortcut hint, when there is one.
    pub shortcut: Option<String>,
    pub keywords: Vec<&'static str>,
    /// What the search matches: the deburred, lower-cased label and the
    /// keywords (a library item's deburred name).
    pub haystack: String,
    /// The `icons.tsx` export; `None` for a library item, whose icon is its
    /// preview.
    pub icon: Option<&'static str>,
    /// The library item's id, for a library command.
    pub library_item: Option<String>,
    /// `isCommandAvailable(command)` in the state the list was built in.
    pub available: bool,
    pub perform: PalettePerform,
}

impl PaletteCommand {
    fn new(
        label: String,
        category: PaletteCategory,
        icon: Option<&'static str>,
        keywords: &[&'static str],
        perform: PalettePerform,
    ) -> PaletteCommand {
        let haystack = format!("{} {}", deburr(&label.to_lowercase()), keywords.join(" "));
        PaletteCommand {
            label,
            category,
            order: category.order(),
            shortcut: None,
            keywords: keywords.to_vec(),
            haystack,
            // `icon: command.icon || boltIcon`
            icon: Some(icon.unwrap_or("boltIcon")),
            library_item: None,
            available: true,
            perform,
        }
    }

    fn shortcut(mut self, shortcut: Option<String>) -> PaletteCommand {
        self.shortcut = shortcut.filter(|s| !s.is_empty());
        self
    }
}

fn set_app_state(patch: Value) -> PalettePerform {
    let Value::Object(patch) = patch else {
        unreachable!("a patch is an object");
    };
    PalettePerform::Effect(PaletteEffect::SetAppState(patch))
}

fn truthy(v: Option<&Value>) -> bool {
    match v {
        None | Some(Value::Null) => false,
        Some(Value::Bool(b)) => *b,
        Some(Value::Number(n)) => n.as_f64().is_some_and(|n| n != 0.0 && !n.is_nan()),
        Some(Value::String(s)) => !s.is_empty(),
        Some(_) => true,
    }
}

/// `command.viewMode === false && uiAppState.viewModeEnabled`.
fn hidden_in_view_mode(ctx: &ActionContext<'_>, view_mode: Option<bool>) -> bool {
    view_mode == Some(false) && truthy(ctx.app_state.get("viewModeEnabled"))
}

/// The palette's `allCommands` (`CommandPalette.tsx:250-615`): the commands
/// built from actions, the additional commands, then the host's `custom`
/// ones, each with its availability in `ctx` (whose elements should be the
/// non-deleted ones).
pub fn palette_commands(
    ctx: &ActionContext<'_>,
    env: &PaletteEnv,
    custom: Vec<PaletteCommand>,
) -> Vec<PaletteCommand> {
    let labels = KeyLabels::EN;
    let mut out: Vec<PaletteCommand> = commands_from_actions()
        .iter()
        .map(|c| {
            let icon = match c.source {
                PaletteCommandSource::Action(a) => a.spec().icon_name(ctx),
                PaletteCommandSource::ClearCanvas => ActionName::ClearCanvas.spec().icon_name(ctx),
                PaletteCommandSource::ImageExport => Some("ExportImageIcon"),
            };
            let perform = match c.source {
                PaletteCommandSource::Action(a) => PalettePerform::Effect(
                    PaletteEffect::ExecuteAction(a, ActionSource::CommandPalette),
                ),
                PaletteCommandSource::ClearCanvas => {
                    PalettePerform::Effect(PaletteEffect::ConfirmDialog("clearCanvas"))
                }
                PaletteCommandSource::ImageExport => {
                    set_app_state(json!({ "openDialog": { "name": "imageExport" } }))
                }
            };
            let mut command = PaletteCommand::new(
                palette_text(c.label_key(ctx)).to_owned(),
                c.category,
                icon,
                c.keywords(),
                perform,
            )
            .shortcut(Some(c.shortcut(env.is_darwin, &labels)));
            command.available = palette_command_available(c, ctx);
            command
        })
        .collect();

    // additionalCommands after the theme toggle (CommandPalette.tsx:426-592)
    let view_mode_aware = |mut c: PaletteCommand, view_mode: Option<bool>, predicate: bool| {
        c.available = !hidden_in_view_mode(ctx, view_mode) && predicate;
        c
    };
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("toolBar.library").to_owned(),
            PaletteCategory::App,
            Some("LibraryIcon"),
            &[],
            PalettePerform::ToggleLibrary,
        ),
        Some(false),
        true,
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("search.title").to_owned(),
            PaletteCategory::App,
            Some("searchIcon"),
            &[],
            PalettePerform::Effect(PaletteEffect::ExecuteAction(
                ActionName::SearchMenu,
                ActionSource::Api,
            )),
        ),
        Some(true),
        true,
    ));
    out.push(PaletteCommand::new(
        palette_text("labels.shapeSwitch").to_owned(),
        PaletteCategory::Elements,
        Some("boltIcon"),
        &[],
        PalettePerform::Effect(PaletteEffect::ExecuteAction(
            ActionName::ToggleShapeSwitch,
            ActionSource::Api,
        )),
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("labels.changeStroke").to_owned(),
            PaletteCategory::Elements,
            Some("bucketFillIcon"),
            &["color", "outline"],
            set_app_state(json!({ "openPopup": "elementStroke" })),
        ),
        Some(false),
        palette_change_stroke_available(ctx),
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("labels.changeBackground").to_owned(),
            PaletteCategory::Elements,
            Some("bucketFillIcon"),
            &["color", "fill"],
            set_app_state(json!({ "openPopup": "elementBackground" })),
        ),
        Some(false),
        palette_change_background_available(ctx),
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("labels.canvasBackground").to_owned(),
            PaletteCategory::Editor,
            Some("bucketFillIcon"),
            &["color"],
            PalettePerform::CanvasBackground,
        ),
        Some(false),
        true,
    ));
    for (ty, config) in TOOLS.iter() {
        if *ty == ToolType::Image && !env.image_tool {
            continue;
        }
        // getToolLetter(value) || config.numericKey
        let shortcut = get_tool_letter(*ty, &ShortcutLabels::EN)
            .map(|l| get_shortcut_key(&l, env.is_darwin, &labels))
            .or_else(|| config.numeric_key.map(str::to_owned));
        let command = PaletteCommand::new(
            palette_text(&format!("toolBar.{}", ty.as_str())).to_owned(),
            PaletteCategory::Tools,
            Some(config.icon),
            &["toolbar"],
            PalettePerform::Effect(PaletteEffect::SetActiveTool(*ty)),
        )
        .shortcut(shortcut);
        out.push(view_mode_aware(command, Some(false), true));
    }
    let locked = ctx
        .app_state
        .get("activeTool")
        .and_then(|t| t.get("locked"))
        .is_some_and(|l| truthy(Some(l)));
    out.push(view_mode_aware(
        PaletteCommand::new(
            palette_text("toolBar.lock").to_owned(),
            PaletteCategory::Tools,
            Some(if locked { "LockedIcon" } else { "UnlockedIcon" }),
            &[],
            PalettePerform::Effect(PaletteEffect::ToggleLock),
        )
        .shortcut(Some("Q".into())),
        Some(false),
        true,
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            format!("{}...", palette_text("labels.textToDiagram")),
            PaletteCategory::Tools,
            Some("brainIconThin"),
            &[],
            set_app_state(json!({ "openDialog": { "name": "ttd", "tab": "text-to-diagram" } })),
        ),
        Some(false),
        env.ai_enabled,
    ));
    out.push(view_mode_aware(
        PaletteCommand::new(
            format!("{}...", palette_text("toolBar.mermaidToExcalidraw")),
            PaletteCategory::Tools,
            Some("mermaidLogoIcon"),
            &[],
            set_app_state(json!({ "openDialog": { "name": "ttd", "tab": "mermaid" } })),
        ),
        Some(false),
        env.ai_enabled,
    ));
    out.extend(custom);
    out
}

/// The hosted app's Links commands (`excalidraw-app/App.tsx:1176-1245`):
/// GitHub, X, Discord and YouTube, always available.
pub fn hosted_app_links() -> Vec<PaletteCommand> {
    let link = |label: &str, icon, keywords: &[&'static str], url| {
        PaletteCommand::new(
            label.to_owned(),
            PaletteCategory::Links,
            Some(icon),
            keywords,
            PalettePerform::Effect(PaletteEffect::OpenUrl(url)),
        )
    };
    vec![
        link(
            "GitHub",
            "GithubIcon",
            &[
                "issues",
                "bugs",
                "requests",
                "report",
                "features",
                "social",
                "community",
            ],
            "https://github.com/excalidraw/excalidraw",
        ),
        link(
            palette_text("labels.followUs"),
            "XBrandIcon",
            &["twitter", "contact", "social", "community"],
            "https://x.com/excalidraw",
        ),
        link(
            palette_text("labels.discordChat"),
            "DiscordIcon",
            &[
                "chat",
                "talk",
                "contact",
                "bugs",
                "requests",
                "report",
                "feedback",
                "suggestions",
                "social",
                "community",
            ],
            "https://discord.gg/UexuTaE",
        ),
        link(
            "YouTube",
            "youtubeIcon",
            &["features", "tutorials", "howto", "help", "community"],
            "https://youtube.com/@excalidraw",
        ),
    ]
}

/// `libraryCommands` (`CommandPalette.tsx:223-248`): each named library
/// item, inserted on the canvas when run.
pub fn library_commands(items: &[LibraryItem]) -> Vec<PaletteCommand> {
    items
        .iter()
        .filter_map(|item| {
            let name = item.name.as_ref().filter(|n| !n.is_empty())?;
            Some(PaletteCommand {
                label: name.clone(),
                category: PaletteCategory::Library,
                order: PaletteCategory::Library.order(),
                shortcut: None,
                keywords: Vec::new(),
                haystack: deburr(name),
                icon: None,
                library_item: Some(item.id.clone()),
                available: true,
                perform: PalettePerform::Effect(PaletteEffect::InsertLibraryItem(item.id.clone())),
            })
        })
        .collect()
}

/// What running `command` does once the palette is closed, in `app_state`
/// (the state it was opened in): the close, `setAppState({openDialog:
/// null})`, then `command.perform`.
pub fn perform_command(command: &PaletteCommand, app_state: &AppState) -> Vec<PaletteEffect> {
    let close = set_app_state_effect(json!({ "openDialog": null }));
    let effect = match &command.perform {
        PalettePerform::Effect(e) => e.clone(),
        PalettePerform::ToggleLibrary => {
            if truthy(app_state.get("openSidebar")) {
                set_app_state_effect(json!({ "openSidebar": null }))
            } else {
                set_app_state_effect(
                    json!({ "openSidebar": { "name": "default", "tab": "library" } }),
                )
            }
        }
        PalettePerform::CanvasBackground => {
            let open = app_state.get("openMenu").and_then(Value::as_str) == Some("canvas");
            set_app_state_effect(json!({
                "openMenu": if open { Value::Null } else { json!("canvas") },
                "openPopup": "canvasBackground",
            }))
        }
    };
    vec![close, effect]
}

fn set_app_state_effect(patch: Value) -> PaletteEffect {
    match set_app_state(patch) {
        PalettePerform::Effect(e) => e,
        _ => unreachable!(),
    }
}

// -- search -------------------------------------------------------------------

/// `fuzzy.match(pattern, str)` of fuzzy 0.1.3: the characters of `pattern`
/// in order in `s`, ignoring case, scored by runs of consecutive matches;
/// infinite when the two are equal ignoring case. Both are read as UTF-16
/// code units, as JavaScript indexes them.
pub fn fuzzy_match(pattern: &str, s: &str) -> Option<f64> {
    let original: Vec<u16> = s.encode_utf16().collect();
    let compare: Vec<u16> = s.to_lowercase().encode_utf16().collect();
    let pattern: Vec<u16> = pattern.to_lowercase().encode_utf16().collect();
    let mut pattern_idx = 0;
    let mut total = 0.0;
    let mut current = 0.0;
    for idx in 0..original.len() {
        if pattern_idx < pattern.len() && compare.get(idx) == Some(&pattern[pattern_idx]) {
            pattern_idx += 1;
            // `currScore += 1 + currScore`
            current = 2.0 * current + 1.0;
        } else {
            current = 0.0;
        }
        total += current;
    }
    (pattern_idx == pattern.len()).then(|| {
        if compare == pattern {
            f64::INFINITY
        } else {
            total
        }
    })
}

/// `fuzzy.filter(pattern, commands, {extract: haystack})`, then upstream's
/// sort by score: the matches, best first, ties in list order.
fn fuzzy_filter(pattern: &str, commands: Vec<PaletteCommand>) -> Vec<PaletteCommand> {
    let mut scored: Vec<(f64, PaletteCommand)> = commands
        .into_iter()
        .filter_map(|c| fuzzy_match(pattern, &c.haystack).map(|score| (score, c)))
        .collect();
    // stable: equal scores (including two infinite ones) keep their order
    scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
    scored.into_iter().map(|(_, c)| c).collect()
}

/// The last used command, as the palette shows it under "Recently used".
#[derive(Debug, Clone, PartialEq)]
pub struct PaletteRecent {
    pub command: PaletteCommand,
    /// `isCommandAvailable(lastUsed)`: shown disabled when not.
    pub available: bool,
}

/// What the palette shows (`CommandPalette.tsx:858-909`).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PaletteView {
    /// The last used command, shown while the search is empty.
    pub recents: Option<PaletteRecent>,
    /// `commandsByCategory`: each category in first-appearance order.
    pub categories: Vec<(String, Vec<PaletteCommand>)>,
    /// `currentCommand`'s label.
    pub current: Option<String>,
}

impl PaletteView {
    /// `Object.values(commandsByCategory).flat()`.
    fn matching(&self) -> impl Iterator<Item = &PaletteCommand> {
        self.categories.iter().flat_map(|(_, items)| items)
    }

    /// The command labelled `label`, among the shown ones.
    pub fn command(&self, label: &str) -> Option<&PaletteCommand> {
        self.recents
            .iter()
            .map(|r| &r.command)
            .chain(self.matching())
            .find(|c| c.label == label)
    }

    /// Whether the last used command takes part in the arrow keys.
    fn considers_last_used(&self) -> Option<&PaletteCommand> {
        self.recents
            .as_ref()
            .filter(|r| r.available)
            .map(|r| &r.command)
    }
}

fn by_category(commands: Vec<PaletteCommand>) -> Vec<(String, Vec<PaletteCommand>)> {
    let mut out: Vec<(String, Vec<PaletteCommand>)> = Vec::new();
    for command in commands {
        let title = command.category.as_str();
        match out.iter_mut().find(|(t, _)| t == title) {
            Some((_, items)) => items.push(command),
            None => out.push((title.to_owned(), vec![command])),
        }
    }
    out
}

/// The palette's list for `search` (`CommandPalette.tsx:771-834`): the
/// available commands by category order, the library items too once the
/// search has two characters, fuzzy-matched and best first while
/// searching; with an empty search the last used command (`last_used`,
/// found by label among `commands` and `library`) under "Recently used"
/// and selected when available, else the first command.
pub fn palette_view(
    commands: &[PaletteCommand],
    library: &[PaletteCommand],
    search: &str,
    last_used: Option<&str>,
) -> PaletteView {
    let last_used = last_used.and_then(|label| {
        commands
            .iter()
            .chain(library)
            .find(|c| c.label == label)
            .cloned()
    });
    let mut matching: Vec<PaletteCommand> =
        commands.iter().filter(|c| c.available).cloned().collect();
    matching.sort_by_key(|c| c.order);
    if search.encode_utf16().count() > 1 {
        matching.extend(library.iter().cloned());
    }
    if search.is_empty() {
        let recents = last_used.map(|command| PaletteRecent {
            available: command.available,
            command,
        });
        let shown = recents.as_ref().filter(|r| r.available);
        if let Some(shown) = shown {
            matching.retain(|c| c.label != shown.command.label);
        }
        let current = shown
            .map(|r| r.command.label.clone())
            .or_else(|| matching.first().map(|c| c.label.clone()));
        return PaletteView {
            recents,
            categories: by_category(matching),
            current,
        };
    }
    let query: String = search
        .to_lowercase()
        .chars()
        .filter(|c| !matches!(c, '<' | '>' | '_' | '|' | ' ' | '-'))
        .collect();
    let matching = fuzzy_filter(&deburr(&query), matching);
    let current = matching.first().map(|c| c.label.clone());
    PaletteView {
        recents: None,
        categories: by_category(matching),
        current,
    }
}

// -- keys -----------------------------------------------------------------------

/// What the palette's window keydown handler did.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PaletteKeyOutcome {
    /// The command to select, when the selection moves.
    pub current: Option<String>,
    /// Run the selected command (Enter; upstream defers it with
    /// `setTimeout`).
    pub execute: bool,
    pub prevent_default: bool,
    pub stop_propagation: bool,
    /// Focus the search input (a letter or digit typed outside it).
    pub focus_input: bool,
}

/// `handleKeyDown` (`CommandPalette.tsx:691-799`), the palette's window
/// keydown listener (capture phase): the arrows move the selection through
/// the shown commands (wrapping, through the last used one when shown and
/// available), Enter runs it, a letter or digit outside the input focuses
/// the input, and every other key outside the input is kept from the
/// editor. `writable_target` is `isWritableElement(event.target)`,
/// `toggle_shortcut` [`excali_editor::keyboard::is_command_palette_toggle_shortcut`].
pub fn palette_key_down(
    view: &PaletteView,
    key: &str,
    writable_target: bool,
    toggle_shortcut: bool,
) -> PaletteKeyOutcome {
    let mut out = PaletteKeyOutcome::default();
    let ignore_alphanumerics = writable_target || toggle_shortcut || key == "Escape";
    if ignore_alphanumerics && !matches!(key, "ArrowUp" | "ArrowDown" | "Enter") {
        return out;
    }
    let matching: Vec<&PaletteCommand> = view.matching().collect();
    let current = view.current.as_deref();
    let index = matching
        .iter()
        .position(|c| Some(c.label.as_str()) == current);
    let last_used = view.considers_last_used();
    let is_last_used = last_used.is_some_and(|l| Some(l.label.as_str()) == current);
    let label = |c: &PaletteCommand| Some(c.label.clone());
    match key {
        "ArrowUp" => {
            out.prevent_default = true;
            if let Some(last_used) = last_used {
                if index == Some(0) {
                    out.current = label(last_used);
                    return out;
                }
                if is_last_used {
                    out.current = matching.last().and_then(|c| label(c));
                    return out;
                }
            }
            let next = match index {
                None | Some(0) => matching.len().checked_sub(1),
                Some(i) => Some(i - 1),
            };
            out.current = next.and_then(|i| matching.get(i)).and_then(|c| label(c));
            return out;
        }
        "ArrowDown" => {
            out.prevent_default = true;
            if let Some(last_used) = last_used {
                if current.is_none() || index == matching.len().checked_sub(1) {
                    out.current = label(last_used);
                    return out;
                }
                if is_last_used {
                    out.current = matching.first().and_then(|c| label(c));
                    return out;
                }
            }
            let next = match index {
                None => 0,
                Some(i) => i + 1,
            };
            out.current = (!matching.is_empty())
                .then(|| matching[next % matching.len()])
                .and_then(label);
            return out;
        }
        "Enter" => out.execute = current.is_some(),
        _ => {}
    }
    if ignore_alphanumerics {
        return out;
    }
    out.stop_propagation = true;
    let mut chars = key.chars();
    if let (Some(c), None) = (chars.next(), chars.next()) {
        if c.is_ascii_alphanumeric() {
            out.focus_input = true;
            return out;
        }
    }
    out.prevent_default = true;
    out
}

// -- DOM ------------------------------------------------------------------------

/// `shortcut.replace("++", "+$").split("+")` (`CommandShortcutHint`,
/// `CommandPalette.tsx:116-139`): the keys of a shortcut hint.
pub fn shortcut_keys(shortcut: &str) -> Vec<String> {
    shortcut
        .replacen("++", "+$", 1)
        .split('+')
        .map(|k| {
            if k == "$" {
                "+".to_owned()
            } else {
                k.to_owned()
            }
        })
        .collect()
}

/// `CommandShortcutHint`: each key in a wrapper, then the description.
fn shortcut_hint(shortcut: &str, desc: Option<&str>) -> Element {
    Element::new("div")
        .attr("class", "shortcut")
        .children_from(shortcut_keys(shortcut).into_iter().map(|key| {
            Node::Element(
                Element::new("div")
                    .attr("class", "shortcut-wrapper")
                    .child(Element::new("div").attr("class", "shortcut-key").child(key)),
            )
        }))
        .child(
            Element::new("div")
                .attr("class", "shortcut-desc")
                .children_from(desc.map(Node::text)),
        )
}

fn icon_node(name: &str, theme: Theme) -> Node {
    let icon = icons::icon(name).unwrap_or_else(|| panic!("icons.tsx has no {name}"));
    Node::Element(
        icon.element(theme)
            .unwrap_or_else(|| panic!("{name} is a path list")),
    )
}

/// `InlineIcon` (`components/InlineIcon.tsx`) with `className="icon"` and
/// `size="var(--icon-size, 1rem)"`.
fn inline_icon(icon: Node) -> Element {
    Element::new("span")
        .attr("class", "icon")
        .style("width", "var(--icon-size, 1rem)")
        .style("height", "100%")
        // React's `margin: "0 0.5ex 0 0.5ex"`, as the DOM serializes it
        .style("margin", "0px 0.5ex 0px 0.5ex")
        .style("display", "inline-flex")
        .style("line-height", "0")
        .style("vertical-align", "middle")
        .style("flex", "0 0 auto")
        .child(icon)
}

/// `Ellipsify` (`components/Ellipsify.tsx`).
fn ellipsify(text: &str) -> Element {
    Element::new("span")
        .style("text-overflow", "ellipsis")
        .style("overflow", "hidden")
        .style("white-space", "nowrap")
        .child(text)
}

/// A library item's preview by id.
pub type LibraryPreview = Rc<dyn Fn(&str) -> Option<Node>>;

/// The palette's props.
#[derive(Clone, Default)]
pub struct CommandPaletteProps {
    pub view: PaletteView,
    /// The search field's value.
    pub search: String,
    pub is_darwin: bool,
    /// The phone form factor: full screen, no key hints or shortcuts.
    pub phone: bool,
    pub theme: Theme,
    /// The editor container's id.
    pub container_id: String,
    /// The search field changed.
    pub on_search: Option<Rc<dyn Fn(String)>>,
    /// A command was clicked, by label.
    pub on_execute: Option<Rc<dyn Fn(String)>>,
    /// The pointer moved over a command, by label: it becomes the current
    /// one.
    pub on_hover: Option<Rc<dyn Fn(String)>>,
    /// `onCloseRequest`: the host sets `openDialog` to null.
    pub on_close: Option<Rc<dyn Fn()>>,
    /// A library item's preview, by id, for its icon.
    pub library_preview: Option<LibraryPreview>,
}

/// `CommandItem` (`CommandPalette.tsx:985-1043`).
fn command_item(
    props: &CommandPaletteProps,
    command: &PaletteCommand,
    disabled: bool,
    large: bool,
) -> Element {
    let selected = props.view.current.as_deref() == Some(command.label.as_str());
    let mut class = String::from("command-item");
    if selected {
        class.push_str(" item-selected");
    }
    if disabled {
        class.push_str(" item-disabled");
    }
    if large {
        class.push_str(" command-item-large");
    }
    let icon = match (&command.library_item, command.icon) {
        (Some(id), _) => Some(Node::Element(
            Element::new("div")
                .attr("class", "library-item-icon")
                .children_from(props.library_preview.as_ref().and_then(|p| p(id))),
        )),
        (None, Some(name)) => Some(icon_node(name, props.theme)),
        (None, None) => None,
    };
    let mut item = Element::new("div")
        .attr("class", class)
        .attr(
            "title",
            if disabled {
                palette_text("commandPalette.itemNotAvailable")
            } else {
                ""
            },
        )
        .child(
            Element::new("div")
                .attr("class", "name")
                .children_from(icon.map(|i| Node::Element(inline_icon(i))))
                .child(ellipsify(&command.label)),
        )
        .children_from(
            command
                .shortcut
                .as_deref()
                .filter(|_| !props.phone)
                .map(|s| Node::Element(shortcut_hint(s, None))),
        );
    if selected && !disabled {
        item = item.on_mount(|el| {
            let options = web_sys::ScrollIntoViewOptions::new();
            options.set_block(web_sys::ScrollLogicalPosition::Nearest);
            el.scroll_into_view_with_scroll_into_view_options(&options);
        });
    }
    if !disabled {
        if let Some(on_execute) = props.on_execute.clone() {
            let label = command.label.clone();
            item = item.on("click", move |e| {
                e.stop_propagation();
                e.prevent_default();
                on_execute(label.clone());
            });
        }
        if let Some(on_hover) = props.on_hover.clone() {
            let label = command.label.clone();
            item = item.on("mousemove", move |_| on_hover(label.clone()));
        }
    }
    item
}

/// The palette's `div.commands`: the last used command under "Recently
/// used", then each category, or "No matching commands..." when nothing
/// matches (`CommandPalette.tsx:884-929`).
pub fn command_list(props: &CommandPaletteProps) -> Element {
    let recents = props.view.recents.as_ref().map(|recent| {
        Node::Element(
            Element::new("div")
                .attr("class", "command-category")
                .child(
                    Element::new("div")
                        .attr("class", "command-category-title")
                        .child(palette_text("commandPalette.recents"))
                        .child(
                            Element::new("div")
                                .attr("class", "icon")
                                .style("margin-left", "6px")
                                .child(icon_node("historyCommandIcon", props.theme)),
                        ),
                )
                .child(command_item(
                    props,
                    &recent.command,
                    !recent.available,
                    false,
                )),
        )
    });
    let body: Vec<Node> = if props.view.categories.is_empty() {
        vec![Node::Element(
            Element::new("div")
                .attr("class", "no-match")
                .child(
                    Element::new("div")
                        .attr("class", "icon")
                        .child(icon_node("searchIcon", props.theme)),
                )
                .child(" ")
                .child(palette_text("commandPalette.search.noMatch")),
        )]
    } else {
        props
            .view
            .categories
            .iter()
            .map(|(title, items)| {
                let large = title == PaletteCategory::Library.as_str();
                Node::Element(
                    Element::new("div")
                        .attr("class", "command-category")
                        .child(
                            Element::new("div")
                                .attr("class", "command-category-title")
                                .child(title.clone()),
                        )
                        .children_from(
                            items
                                .iter()
                                .map(|c| Node::Element(command_item(props, c, false, large))),
                        ),
                )
            })
            .collect()
    };
    Element::new("div")
        .attr("class", "commands")
        .children_from(recents)
        .children_from(body)
}

/// `CommandPaletteInner`'s dialog (`CommandPalette.tsx:858-931`): the modal
/// container the dialog portals to the body
/// ([`crate::primitives::open_modal`] mounts it there).
pub fn command_palette(props: CommandPaletteProps) -> Element {
    let field = text_field(TextFieldProps {
        value: TextFieldValue::Controlled(props.search.clone()),
        placeholder: Some(palette_text("commandPalette.search.placeholder").to_owned()),
        on_change: props.on_search.clone(),
        select_on_render: true,
        ..TextFieldProps::default()
    });
    let hints = (!props.phone).then(|| {
        let esc = get_shortcut_key("Esc", props.is_darwin, &KeyLabels::EN);
        Node::Element(
            Element::new("div")
                .attr("class", "shortcuts-wrapper")
                .child(shortcut_hint(
                    "↑↓",
                    Some(palette_text("commandPalette.shortcuts.select")),
                ))
                .child(shortcut_hint(
                    "↵",
                    Some(palette_text("commandPalette.shortcuts.confirm")),
                ))
                .child(shortcut_hint(
                    &esc,
                    Some(palette_text("commandPalette.shortcuts.close")),
                )),
        )
    });
    let list = command_list(&props);
    dialog(
        DialogProps {
            class_name: Some("command-palette-dialog".into()),
            size: DialogSize::Px(720.0),
            title: None,
            autofocus: true,
            close_on_click_outside: true,
            container_id: props.container_id,
            theme: props.theme,
            phone: props.phone,
            on_close_request: props.on_close,
            ..DialogProps::default()
        },
        std::iter::once(Node::Element(field))
            .chain(hints)
            .chain(std::iter::once(Node::Element(list)))
            .collect(),
    )
}
