//! `deburr` (`packages/excalidraw/deburr.ts`, from lodash): Latin-1 and
//! Latin Extended-A letters to one basic Latin letter each, combining
//! marks removed. The table is upstream's `deburredLetters`.

/// The basic letter upstream's `deburredLetters` maps `c` to, if any.
fn deburred_letter(c: char) -> Option<char> {
    Some(match c {
        '\u{c0}' => 'A',
        '\u{c1}' => 'A',
        '\u{c2}' => 'A',
        '\u{c3}' => 'A',
        '\u{c4}' => 'A',
        '\u{c5}' => 'A',
        '\u{e0}' => 'a',
        '\u{e1}' => 'a',
        '\u{e2}' => 'a',
        '\u{e3}' => 'a',
        '\u{e4}' => 'a',
        '\u{e5}' => 'a',
        '\u{c7}' => 'C',
        '\u{e7}' => 'c',
        '\u{d0}' => 'D',
        '\u{f0}' => 'd',
        '\u{c8}' => 'E',
        '\u{c9}' => 'E',
        '\u{ca}' => 'E',
        '\u{cb}' => 'E',
        '\u{e8}' => 'e',
        '\u{e9}' => 'e',
        '\u{ea}' => 'e',
        '\u{eb}' => 'e',
        '\u{cc}' => 'I',
        '\u{cd}' => 'I',
        '\u{ce}' => 'I',
        '\u{cf}' => 'I',
        '\u{ec}' => 'i',
        '\u{ed}' => 'i',
        '\u{ee}' => 'i',
        '\u{ef}' => 'i',
        '\u{d1}' => 'N',
        '\u{f1}' => 'n',
        '\u{d2}' => 'O',
        '\u{d3}' => 'O',
        '\u{d4}' => 'O',
        '\u{d5}' => 'O',
        '\u{d6}' => 'O',
        '\u{d8}' => 'O',
        '\u{f2}' => 'o',
        '\u{f3}' => 'o',
        '\u{f4}' => 'o',
        '\u{f5}' => 'o',
        '\u{f6}' => 'o',
        '\u{f8}' => 'o',
        '\u{d9}' => 'U',
        '\u{da}' => 'U',
        '\u{db}' => 'U',
        '\u{dc}' => 'U',
        '\u{f9}' => 'u',
        '\u{fa}' => 'u',
        '\u{fb}' => 'u',
        '\u{fc}' => 'u',
        '\u{dd}' => 'Y',
        '\u{fd}' => 'y',
        '\u{ff}' => 'y',
        '\u{c6}' => 'E',
        '\u{e6}' => 'e',
        '\u{de}' => 'T',
        '\u{fe}' => 't',
        '\u{df}' => 's',
        '\u{100}' => 'A',
        '\u{102}' => 'A',
        '\u{104}' => 'A',
        '\u{101}' => 'a',
        '\u{103}' => 'a',
        '\u{105}' => 'a',
        '\u{106}' => 'C',
        '\u{108}' => 'C',
        '\u{10a}' => 'C',
        '\u{10c}' => 'C',
        '\u{107}' => 'c',
        '\u{109}' => 'c',
        '\u{10b}' => 'c',
        '\u{10d}' => 'c',
        '\u{10e}' => 'D',
        '\u{110}' => 'D',
        '\u{10f}' => 'd',
        '\u{111}' => 'd',
        '\u{112}' => 'E',
        '\u{114}' => 'E',
        '\u{116}' => 'E',
        '\u{118}' => 'E',
        '\u{11a}' => 'E',
        '\u{113}' => 'e',
        '\u{115}' => 'e',
        '\u{117}' => 'e',
        '\u{119}' => 'e',
        '\u{11b}' => 'e',
        '\u{11c}' => 'G',
        '\u{11e}' => 'G',
        '\u{120}' => 'G',
        '\u{122}' => 'G',
        '\u{11d}' => 'g',
        '\u{11f}' => 'g',
        '\u{121}' => 'g',
        '\u{123}' => 'g',
        '\u{124}' => 'H',
        '\u{126}' => 'H',
        '\u{125}' => 'h',
        '\u{127}' => 'h',
        '\u{128}' => 'I',
        '\u{12a}' => 'I',
        '\u{12c}' => 'I',
        '\u{12e}' => 'I',
        '\u{130}' => 'I',
        '\u{129}' => 'i',
        '\u{12b}' => 'i',
        '\u{12d}' => 'i',
        '\u{12f}' => 'i',
        '\u{131}' => 'i',
        '\u{134}' => 'J',
        '\u{135}' => 'j',
        '\u{136}' => 'K',
        '\u{137}' => 'k',
        '\u{138}' => 'k',
        '\u{139}' => 'L',
        '\u{13b}' => 'L',
        '\u{13d}' => 'L',
        '\u{13f}' => 'L',
        '\u{141}' => 'L',
        '\u{13a}' => 'l',
        '\u{13c}' => 'l',
        '\u{13e}' => 'l',
        '\u{140}' => 'l',
        '\u{142}' => 'l',
        '\u{143}' => 'N',
        '\u{145}' => 'N',
        '\u{147}' => 'N',
        '\u{14a}' => 'N',
        '\u{144}' => 'n',
        '\u{146}' => 'n',
        '\u{148}' => 'n',
        '\u{14b}' => 'n',
        '\u{14c}' => 'O',
        '\u{14e}' => 'O',
        '\u{150}' => 'O',
        '\u{14d}' => 'o',
        '\u{14f}' => 'o',
        '\u{151}' => 'o',
        '\u{154}' => 'R',
        '\u{156}' => 'R',
        '\u{158}' => 'R',
        '\u{155}' => 'r',
        '\u{157}' => 'r',
        '\u{159}' => 'r',
        '\u{15a}' => 'S',
        '\u{15c}' => 'S',
        '\u{15e}' => 'S',
        '\u{160}' => 'S',
        '\u{15b}' => 's',
        '\u{15d}' => 's',
        '\u{15f}' => 's',
        '\u{161}' => 's',
        '\u{162}' => 'T',
        '\u{164}' => 'T',
        '\u{166}' => 'T',
        '\u{163}' => 't',
        '\u{165}' => 't',
        '\u{167}' => 't',
        '\u{168}' => 'U',
        '\u{16a}' => 'U',
        '\u{16c}' => 'U',
        '\u{16e}' => 'U',
        '\u{170}' => 'U',
        '\u{172}' => 'U',
        '\u{169}' => 'u',
        '\u{16b}' => 'u',
        '\u{16d}' => 'u',
        '\u{16f}' => 'u',
        '\u{171}' => 'u',
        '\u{173}' => 'u',
        '\u{174}' => 'W',
        '\u{175}' => 'w',
        '\u{176}' => 'Y',
        '\u{177}' => 'y',
        '\u{178}' => 'Y',
        '\u{179}' => 'Z',
        '\u{17b}' => 'Z',
        '\u{17d}' => 'Z',
        '\u{17a}' => 'z',
        '\u{17c}' => 'z',
        '\u{17e}' => 'z',
        '\u{132}' => 'I',
        '\u{133}' => 'i',
        '\u{152}' => 'E',
        '\u{153}' => 'e',
        '\u{149}' => 'n',
        '\u{17f}' => 's',
        _ => return None,
    })
}

/// `reLatin`: `[\xc0-\xd6\xd8-\xf6\xf8-\xff\u0100-\u017f]`.
fn is_latin(c: char) -> bool {
    matches!(c, '\u{c0}'..='\u{d6}' | '\u{d8}'..='\u{f6}' | '\u{f8}'..='\u{ff}' | '\u{100}'..='\u{17f}')
}

/// `rsCombo`: combining marks, half marks and marks for symbols.
fn is_combo_mark(c: char) -> bool {
    matches!(c, '\u{300}'..='\u{36f}' | '\u{fe20}'..='\u{fe2f}' | '\u{20d0}'..='\u{20ff}')
}

/// `deburr(str)`: each Latin letter replaced by its basic letter (kept when
/// the table has none), then the combining marks removed.
pub fn deburr(s: &str) -> String {
    s.chars()
        .map(|c| {
            if is_latin(c) {
                deburred_letter(c).unwrap_or(c)
            } else {
                c
            }
        })
        .filter(|c| !is_combo_mark(*c))
        .collect()
}
