//! The library sidebar: upstream's `DefaultSidebar`
//! (`components/DefaultSidebar.tsx`) as LayerUI renders it, over the
//! Sidebar parts (`components/Sidebar/*`: the island, the header with the
//! Search and Library tab triggers and the dock and close buttons, the
//! tabs), with the `LibraryMenu` in its library tab (`LibraryMenu.tsx`,
//! `LibraryMenuItems.tsx`, `LibraryMenuSection.tsx`, `LibraryUnit.tsx`,
//! `LibraryMenuHeaderContent.tsx`, `LibraryMenuControlButtons.tsx`,
//! `LibraryMenuBrowseButton.tsx`), and LayerUI's library trigger
//! (`DefaultSidebar.Trigger`, `LayerUI.tsx:481-499`).
//!
//! Layout (research `ui-design-system.md` §3.6): the header's tab triggers
//! (Search, Library), then the dock button (while the sidebar fits and the
//! search tab does not force docking) and close; in the library tab the
//! search field and the header menu (Load, Export, Publish, Reset or
//! Remove), the "Personal Library" section (the selection waiting to be
//! added, then the unpublished items), the "Excalidraw Library" section
//! (published items), or the matches of a search, and the "Browse
//! libraries" link. The sidebar is `RIGHT_SIDEBAR_WIDTH` (302 px) less the
//! island's outer margin wide ([`LIBRARY_SIDEBAR_CSS`]).
//!
//! [`default_sidebar`] builds the DOM for the host's state
//! ([`LibrarySidebarProps`]: the app state keys it reads in a
//! [`LibraryContext`], the library, the previews the host renders and the
//! menu's own [`LibraryMenuState`]); what the user does comes back as
//! [`LibrarySidebarEvent`]s, which the host runs through [`update`]: it
//! updates the menu state and returns the [`LibraryEffect`]s upstream's
//! handlers have (app state patches, items to insert with
//! `excali_editor::edit_actions::insert_library_items`, the library to
//! store, files to load or save), then the host renders again. Dragging an
//! item puts [`drag_data`] on the drag (`MIME_TYPE_EXCALIDRAWLIB_IDS`),
//! which the canvas's drop reads back.
//!
//! The dialogs the header menu opens (the Reset and Remove confirmation,
//! the publish dialog and its success dialog) are [`library_dialogs`]
//! (`dialogs.rs`); the host mounts them with `primitives::open_modal`, and
//! does the files, storage and network their effects ask for
//! ([`LibraryEffect::LoadLibrary`], [`LibraryEffect::ExportLibrary`],
//! [`LibraryEffect::LoadPublishData`], [`LibraryEffect::SavePublishData`],
//! [`LibraryEffect::SubmitLibrary`]).
//!
//! Not here: the search tab's content (`SearchMenu`, ex-708; the host's
//! [`LibrarySidebarProps::search_menu`]), host sidebars and tab
//! triggers (`Sidebar` with another name, `DefaultSidebar.TabTriggers`),
//! radix's arrow-key roving focus among the tab triggers, and the
//! batched rendering of long sections (`LibraryMenuSection` renders 17 or
//! 64 units per transition; every unit is built here).

mod deburr;
mod dialogs;

pub use dialogs::{
    dialog_action_button, library_dialogs, publish_form_fields, ActionType, LibraryDialog,
    LibraryDialogsProps, PublishField, PublishLibraryData, PublishState, PublishSuccess,
    PUBLISH_LIBRARY_STORAGE_KEY,
};

use std::rc::Rc;

use excali_core::color::js_trim;
use excali_core::element::{Element as SceneElement, ElementKind};
use excali_core::library::{LibraryItem, LibraryItemStatus, MIME_TYPE_EXCALIDRAWLIB_IDS};
use excali_core::restore::RestoreEnv;
use excali_scene::shape::Theme;
use serde_json::{json, Map, Value};
use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;
use web_sys::{Event, KeyboardEvent, MouseEvent};

use crate::dom::{class_names, Element, Node};
use crate::icons::{self, Icon};
use crate::primitives::{
    button, island, stack_col, text_field, tooltip, Align, ButtonProps, IslandProps, StackProps,
    TextFieldProps, TextFieldType, TextFieldValue, TooltipProps,
};
use crate::toolbar::radix_menu_content;

pub use deburr::deburr;

/// CheckboxItem.scss, LibraryUnit.scss, Spinner.scss, LibraryMenuItems.scss,
/// LibraryMenu.scss, SidebarTrigger.scss and Sidebar.scss in upstream's
/// import order, compiled (generated by `tools/goldens/library-sidebar.mjs`).
pub const LIBRARY_SIDEBAR_CSS: &str = include_str!("library_sidebar.css");

/// The `data-excali-ui` value of the `<style>` holding
/// [`LIBRARY_SIDEBAR_CSS`].
const STYLESHEET_ID: &str = "library-sidebar";

/// `DEFAULT_SIDEBAR.name` (`common/src/constants.ts:537-540`).
pub const DEFAULT_SIDEBAR_NAME: &str = "default";
/// `LIBRARY_SIDEBAR_TAB`, `DEFAULT_SIDEBAR.defaultTab`.
pub const LIBRARY_SIDEBAR_TAB: &str = "library";
/// `CANVAS_SEARCH_TAB`: the tab that forces docking.
pub const CANVAS_SEARCH_TAB: &str = "search";

/// `import.meta.env.VITE_APP_LIBRARY_URL` (`.env.production`): the public
/// library repository the "Browse libraries" link opens.
pub const LIBRARY_URL: &str = "https://libraries.excalidraw.com";

/// `VERSIONS.excalidrawLibrary` (`common/src/constants.ts:418`).
const LIBRARY_VERSION: u32 = 2;

/// Adds [`LIBRARY_SIDEBAR_CSS`] to `document`'s head once, after the
/// toolbar's stylesheet (which holds `DropdownMenu.scss`, the header
/// menu's, and which it installs first, the primitives' before it), so the
/// host's own rules still come later and win.
pub fn install_stylesheet(document: &web_sys::Document) -> Result<(), wasm_bindgen::JsValue> {
    crate::toolbar::install_stylesheet(document)?;
    let selector = format!("style[data-excali-ui=\"{STYLESHEET_ID}\"]");
    if document.query_selector(&selector)?.is_some() {
        return Ok(());
    }
    let style = document.create_element("style")?;
    style.set_attribute("data-excali-ui", STYLESHEET_ID)?;
    style.set_text_content(Some(LIBRARY_SIDEBAR_CSS));
    let head = document
        .head()
        .ok_or_else(|| wasm_bindgen::JsValue::from_str("the document has no head"))?;
    let toolbar = document.query_selector("style[data-excali-ui=\"toolbar\"]")?;
    let next = toolbar.and_then(|p| p.next_sibling());
    head.insert_before(&style, next.as_ref())?;
    Ok(())
}

/// The English strings of the sidebar (`locales/en.json`); the key itself
/// for any other.
pub fn library_text(key: &str) -> &str {
    match key {
        "toolBar.library" => "Library",
        "labels.more_options" => "More options",
        "labels.sidebarLock" => "Keep sidebar open",
        "buttons.close" => "Close",
        "labels.personalLib" => "Personal Library",
        "labels.excalidrawLib" => "Excalidraw Library",
        "labels.libraries" => "Browse libraries",
        "labels.libraryLoadingMessage" => "Loading library…",
        "library.noItems" => "No items added yet...",
        "library.hint_emptyLibrary" => "Select an item on canvas to add it here, or install a library from the public repository, below.",
        "library.hint_emptyPrivateLibrary" => "Select an item on canvas to add it here.",
        "library.search.inputPlaceholder" => "Search library",
        "library.search.heading" => "Library matches",
        "library.search.noResults" => "No matching items found...",
        "library.search.clearSearch" => "Clear search",
        "buttons.load" => "Open",
        "buttons.export" => "Save to...",
        "buttons.publishLibrary" => "Rename or publish",
        "buttons.remove" => "Remove",
        "buttons.resetLibrary" => "Reset library",
        "errors.libraryElementTypeError.embeddable" => {
            "Embeddable elements cannot be added to the library."
        }
        "errors.libraryElementTypeError.iframe" => "IFrame elements cannot be added to the library.",
        "errors.libraryElementTypeError.image" => {
            "Support for adding images to the library coming soon!"
        }
        "errors.importLibraryError" => "Couldn't load library",
        "alerts.errorAddingToLibrary" => "Couldn't add item to the library",
        "alerts.errorRemovingFromLibrary" => "Couldn't remove item from the library",
        "alerts.resetLibrary" => "This will clear your library. Are you sure?",
        "confirmDialog.resetLibrary" => "Reset library",
        "confirmDialog.removeItemsFromLib" => "Remove selected items from library",
        "alerts.removeItemsFromsLibrary" => "Delete {{count}} item(s) from library?",
        "buttons.confirm" => "Confirm",
        "buttons.cancel" => "Cancel",
        "buttons.saveLibNames" => "Save name(s) and exit",
        "buttons.submit" => "Submit",
        "labels.statusPublished" => "Published",
        "publishDialog.title" => "Publish library",
        "publishDialog.itemName" => "Item name",
        "publishDialog.authorName" => "Author name",
        "publishDialog.githubUsername" => "GitHub username",
        "publishDialog.twitterUsername" => "Twitter username",
        "publishDialog.libraryName" => "Library name",
        "publishDialog.libraryDesc" => "Library description",
        "publishDialog.website" => "Website",
        "publishDialog.placeholder.authorName" => "Your name or username",
        "publishDialog.placeholder.libraryName" => "Name of your library",
        "publishDialog.placeholder.libraryDesc" => {
            "Description of your library to help people understand its usage"
        }
        "publishDialog.placeholder.githubHandle" => {
            "GitHub handle (optional), so you can edit the library once submitted for review"
        }
        "publishDialog.placeholder.twitterHandle" => {
            "Twitter username (optional), so we know who to credit when promoting over Twitter"
        }
        "publishDialog.placeholder.website" => {
            "Link to your personal website or elsewhere (optional)"
        }
        "publishDialog.errors.required" => "Required",
        "publishDialog.errors.website" => "Enter a valid URL",
        "publishDialog.noteDescription" => "Submit your library to be included in the <link>public library repository</link> for other people to use in their drawings.",
        "publishDialog.noteGuidelines" => "The library needs to be manually approved first. Please read the <link>guidelines</link> before submitting. You will need a GitHub account to communicate and make changes if requested, but it is not strictly required.",
        "publishDialog.noteLicense" => "By submitting, you agree the library will be published under the <link>MIT License</link>, which in short means anyone can use them without restrictions.",
        "publishDialog.noteItems" => "Each library item must have its own name so it's filterable. The following library items will be included:",
        "publishDialog.atleastOneLibItem" => {
            "Please select at least one library item to get started"
        }
        "publishDialog.republishWarning" => "Note: some of the selected items are marked as already published/submitted. You should only resubmit items when updating an existing library or submission.",
        "publishSuccessDialog.title" => "Library submitted",
        "publishSuccessDialog.content" => "Thank you {{authorName}}. Your library has been submitted for review. You can track the status <link>here</link>",
        other => other,
    }
}

// ---------------------------------------------------------------------------
// state
// ---------------------------------------------------------------------------

/// `appState.openSidebar`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OpenSidebar {
    pub name: String,
    pub tab: Option<String>,
}

/// `libraryItemsAtom`'s status: loaded, or loading (`isInitialized` once
/// the library has loaded before).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LibraryStatus {
    Loaded,
    Loading { initialized: bool },
}

impl LibraryStatus {
    fn is_loading(self) -> bool {
        matches!(self, LibraryStatus::Loading { .. })
    }
}

/// What the sidebar reads of the editor: the app state keys, the editor
/// interface, the library and the elements waiting to be added.
#[derive(Clone, Debug)]
pub struct LibraryContext<'a> {
    /// `appState.openSidebar`.
    pub open_sidebar: Option<OpenSidebar>,
    /// `appState.defaultSidebarDockedPreference`.
    pub docked_preference: bool,
    /// `editorInterface.canFitSidebar`.
    pub can_fit_sidebar: bool,
    /// `editorInterface.formFactor === "phone"`.
    pub phone: bool,
    pub status: LibraryStatus,
    /// The library's items, in order.
    pub items: &'a [LibraryItem],
    /// The pending elements ([`pending_elements`]): the selection the
    /// library offers to add.
    pub pending: &'a [SceneElement],
}

impl LibraryContext<'_> {
    fn open_tab(&self) -> Option<&str> {
        self.open_sidebar.as_ref().and_then(|o| o.tab.as_deref())
    }

    /// The default sidebar is the open one.
    fn is_open(&self) -> bool {
        self.open_sidebar
            .as_ref()
            .is_some_and(|o| o.name == DEFAULT_SIDEBAR_NAME)
    }

    /// `isForceDocked`: the search tab docks the sidebar.
    fn force_docked(&self) -> bool {
        self.open_tab() == Some(CANVAS_SEARCH_TAB)
    }

    /// DefaultSidebar's `docked`.
    fn docked(&self) -> bool {
        self.force_docked() || self.docked_preference
    }

    /// The dock button shows: the sidebar fits and LayerUI's `onDock`
    /// is not dropped for the search tab (`SidebarHeader.tsx:22-24`).
    fn can_dock(&self) -> bool {
        self.can_fit_sidebar && !self.force_docked()
    }

    /// The library tab's content is mounted.
    fn library_mounted(&self) -> bool {
        self.is_open() && self.open_tab() == Some(LIBRARY_SIDEBAR_TAB)
    }

    fn unpublished(&self) -> Vec<&LibraryItem> {
        self.items
            .iter()
            .filter(|i| i.status != LibraryItemStatus::Published)
            .collect()
    }

    fn published(&self) -> Vec<&LibraryItem> {
        self.items
            .iter()
            .filter(|i| i.status == LibraryItemStatus::Published)
            .collect()
    }

    fn is_library_empty(&self) -> bool {
        self.items.is_empty() && self.pending.is_empty()
    }
}

/// `isSidebarDockedAtom` as the default sidebar leaves it: rendered and
/// docked.
pub fn is_sidebar_docked(cx: &LibraryContext<'_>) -> bool {
    cx.is_open() && cx.docked()
}

/// LayerUI's `isSidebarDockedAndFits` (`LayerUI.tsx:462-466`): the UI gives
/// the sidebar `--right-sidebar-width` (`layer-ui__wrapper`'s width) and
/// hides the library trigger.
pub fn is_sidebar_docked_and_fits(cx: &LibraryContext<'_>) -> bool {
    cx.open_sidebar.is_some() && is_sidebar_docked(cx) && cx.can_fit_sidebar
}

/// A library unit: an item by id, or the pending selection.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum UnitKey {
    Item(String),
    Pending,
}

impl UnitKey {
    fn id(&self) -> Option<&str> {
        match self {
            UnitKey::Item(id) => Some(id),
            UnitKey::Pending => None,
        }
    }
}

/// The library menu's own state (LibraryMenu's and LibraryMenuItems'
/// `useState`s, and `isLibraryMenuOpenAtom`).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct LibraryMenuState {
    /// `selectedItems`, in the order they were selected.
    pub selected_items: Vec<String>,
    /// `lastSelectedItem`: where a Shift range starts.
    pub last_selected_item: Option<String>,
    /// `searchInputValue`.
    pub search: String,
    /// The unit under the mouse (`isHovered`).
    pub hovered: Option<UnitKey>,
    /// `isLibraryMenuOpenAtom`: the header menu is open.
    pub menu_open: bool,
    /// The tab trigger radix's roving focus group made the tab stop (the
    /// last one pressed or focused; `tabindex="0"`), until the sidebar
    /// closes.
    pub tab_stop: Option<String>,
    /// The sidebar rendered again since it opened (the app state changed
    /// while it was open; [`update`] notes its own patches, the host any
    /// other). Until then the tab panel active at mount keeps radix's
    /// `animation-duration: 0s`, which stops its mount animation.
    pub rerendered: bool,
    /// `showRemoveLibAlert`: the Reset or Remove confirmation is open.
    pub confirm_open: bool,
    /// `showPublishLibraryDialog`, with the dialog's own state.
    pub publish: Option<PublishState>,
    /// `publishLibSuccess`: the success dialog is open.
    pub publish_success: Option<PublishSuccess>,
}

impl LibraryMenuState {
    /// The library tab's content unmounts (another tab, or the sidebar
    /// closes): LibraryMenu's and LibraryMenuItems' own state goes with it
    /// (the header menu's atom stays).
    fn unmount_library(&mut self) {
        self.selected_items.clear();
        self.last_selected_item = None;
        self.search.clear();
        self.hovered = None;
        // the header menu's dialogs are LibraryDropdownMenuButton's state
        self.confirm_open = false;
        self.publish = None;
        self.publish_success = None;
    }

    /// The sidebar closes.
    fn close(&mut self) {
        self.unmount_library();
        self.tab_stop = None;
        self.rerendered = false;
    }
}

/// The previews the host renders for the units (upstream's
/// `useLibraryItemSvg`: `exportToSvg` of the item's elements with no
/// background, on white); a unit without one is a skeleton.
#[derive(Clone, Debug, Default)]
pub struct Previews {
    pub items: std::collections::HashMap<String, Node>,
    pub pending: Option<Node>,
}

impl Previews {
    fn get(&self, unit: &UnitKey) -> Option<&Node> {
        match unit {
            UnitKey::Item(id) => self.items.get(id),
            UnitKey::Pending => self.pending.as_ref(),
        }
    }
}

/// The "Browse libraries" link's inputs: the app's id (the token the
/// library site returns with), the host's `libraryReturnUrl`, the page's
/// `location.origin + location.pathname`, and `window.name`.
#[derive(Clone, Debug, Default)]
pub struct BrowseLink {
    pub app_id: String,
    pub library_return_url: Option<String>,
    pub location: String,
    pub window_name: String,
}

/// The header menu's entries (`LibraryMenuHeaderContent.tsx:206-238`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LibraryMenuAction {
    Load,
    Export,
    Publish,
    Reset,
    Remove,
}

/// What the user did.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LibrarySidebarEvent {
    /// A tab trigger pressed (radix selects on a primary mousedown, Enter,
    /// Space or focus).
    SelectTab(String),
    /// The close button.
    Close,
    /// The dock button: dock (`true`) or undock.
    Dock(bool),
    /// LayerUI's library trigger.
    ToggleTrigger,
    /// A click on a unit.
    UnitClick { unit: UnitKey, shift: bool },
    /// A click on a unit's checkbox.
    CheckboxToggle { id: String, shift: bool },
    /// The mouse entered or left a unit (a drag start leaves it).
    UnitHover { unit: UnitKey, hovered: bool },
    /// The search field's value.
    SearchInput(String),
    /// "Clear search", or the "esc to clear" hint.
    ClearSearch,
    /// A key down in the document (the sidebar listens on the document).
    KeyDown {
        key: String,
        target: KeyTarget,
        /// A `.Dialog` is open.
        dialog_open: bool,
    },
    /// A press outside the sidebar.
    OutsideClick {
        /// On a `.sidebar-trigger` (the trigger toggles itself).
        on_trigger: bool,
        dialog_open: bool,
    },
    /// The header menu's trigger.
    MenuToggle,
    /// A press outside the open header menu, or Escape in it.
    MenuClose,
    /// A header menu entry.
    MenuSelect(LibraryMenuAction),
    /// The confirmation's Cancel button.
    ConfirmCancel,
    /// The confirmation's Confirm button: reset the library, or remove the
    /// selected items.
    ConfirmAccept,
    /// A dialog's close request (Escape, a click on the backdrop, the
    /// phone's close button: `Dialog.onClose`).
    DialogClose(LibraryDialog),
    /// A publish dialog field's value.
    PublishInput { field: PublishField, value: String },
    /// A publish dialog item's name.
    PublishItemName { id: String, value: String },
    /// A publish dialog item's remove button.
    PublishRemoveItem(String),
    /// The publish form submitted (the browser has checked its required
    /// fields and the website's pattern).
    PublishSubmit,
    /// "Save name(s) and exit".
    PublishSaveNames,
    /// What the host read for [`LibraryEffect::LoadPublishData`].
    PublishDataLoaded(Option<PublishLibraryData>),
    /// The library backend took the submission: its tracking url.
    PublishSucceeded { url: String },
    /// The submission failed: `String(error)`.
    PublishFailed(String),
    /// The success dialog's Close button.
    PublishSuccessClose,
}

/// Where a key went down.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum KeyTarget {
    /// The library's search field, with its value.
    SearchInput { value: String },
    /// Elsewhere in the sidebar; `empty_input` for an empty writable input.
    InSidebar { empty_input: bool },
    /// Outside the sidebar; `cursor_over_sidebar` when the pointer is over
    /// it.
    Outside { cursor_over_sidebar: bool },
}

/// What the host does for an event.
#[derive(Clone, Debug)]
pub enum LibraryEffect {
    /// `setAppState(patch)`.
    SetAppState(Map<String, Value>),
    /// `trackEvent(category, action, label)`.
    TrackEvent(String, String, String),
    /// `app.focusContainer()`.
    FocusContainer,
    /// Insert these items (by id, in library order) at the viewport's
    /// centre (`onInsertElements`), with
    /// `excali_editor::edit_actions::insert_library_items`.
    Insert(Vec<String>),
    /// `library.setLibrary(items)`: store the library.
    SetLibrary(Vec<LibraryItem>),
    /// `library.resetLibrary()`, and clear the previews.
    ResetLibrary,
    /// `library.updateLibrary({ libraryItems: fileOpen(...), merge: true,
    /// openLibraryMenu: true })`: open a library file and merge it in
    /// (`errors.importLibraryError` on failure).
    LoadLibrary,
    /// `saveLibraryAsJSON(items)`: save these items (by id) to a file.
    ExportLibrary(Vec<String>),
    /// Drop these items' previews.
    DeletePreviews(Vec<String>),
    /// `EditorLocalStorage.get(PUBLISH_LIBRARY)` as the publish dialog
    /// mounts: the host answers with
    /// [`LibrarySidebarEvent::PublishDataLoaded`].
    LoadPublishData,
    /// `EditorLocalStorage.set(PUBLISH_LIBRARY, data)`, or `.delete` for
    /// `None` ([`PUBLISH_LIBRARY_STORAGE_KEY`]).
    SavePublishData(Option<PublishLibraryData>),
    /// Submit these items, as a `.excalidrawlib`, with the form's fields
    /// to the library backend (`PublishLibrary.onSubmit`); the host answers
    /// with [`LibrarySidebarEvent::PublishSucceeded`] or
    /// [`LibrarySidebarEvent::PublishFailed`].
    SubmitLibrary {
        items: Vec<LibraryItem>,
        data: PublishLibraryData,
    },
    /// `window.alert(message)`.
    Alert(String),
}

/// What [`update`] returns: the effects, and whether the DOM event's
/// default is prevented and its propagation stopped.
#[derive(Clone, Debug, Default)]
pub struct Update {
    pub effects: Vec<LibraryEffect>,
    pub prevent_default: bool,
    pub stop_propagation: bool,
}

fn patch<const N: usize>(entries: [(&str, Value); N]) -> Map<String, Value> {
    entries
        .into_iter()
        .map(|(k, v)| (k.to_owned(), v))
        .collect()
}

fn close_sidebar(state: &mut LibraryMenuState) -> LibraryEffect {
    state.close();
    LibraryEffect::SetAppState(patch([("openSidebar", Value::Null)]))
}

fn form_factor(cx: &LibraryContext<'_>) -> &'static str {
    if cx.phone {
        "mobile"
    } else {
        "desktop"
    }
}

/// `onItemSelectToggle(id, event)` (`LibraryMenuItems.tsx:129-178`): select
/// (a Shift click after a selection extends it over the range between, in
/// the order unpublished then published), or deselect.
fn toggle_item(state: &mut LibraryMenuState, cx: &LibraryContext<'_>, id: &str, shift: bool) {
    let should_select = !state.selected_items.iter().any(|s| s == id);
    if should_select {
        let ordered: Vec<&str> = cx
            .unpublished()
            .into_iter()
            .chain(cx.published())
            .map(|i| i.id.as_str())
            .collect();
        match state.last_selected_item.as_deref().filter(|_| shift) {
            Some(last) => {
                let start = ordered.iter().position(|i| *i == last);
                let end = ordered.iter().position(|i| *i == id);
                match (start, end) {
                    (Some(start), Some(end)) => {
                        let (min, max) = (start.min(end), start.max(end));
                        let next = ordered
                            .iter()
                            .enumerate()
                            .filter(|(i, item)| {
                                (*i >= min && *i <= max)
                                    || state.selected_items.iter().any(|s| s == *item)
                            })
                            .map(|(_, item)| (*item).to_owned())
                            .collect();
                        state.selected_items = next;
                    }
                    _ => {
                        state.selected_items.push(id.to_owned());
                        return;
                    }
                }
            }
            None => state.selected_items.push(id.to_owned()),
        }
        state.last_selected_item = Some(id.to_owned());
    } else {
        state.last_selected_item = None;
        state.selected_items.retain(|s| s != id);
    }
}

fn set_selected(state: &mut LibraryMenuState, selected: Vec<String>) {
    state.selected_items = selected;
    // an emptied selection forgets where a range starts
    if state.selected_items.is_empty() {
        state.last_selected_item = None;
    }
}

/// `LIBRARY_DISABLED_TYPES` (`common/src/constants.ts:542-546`), in order.
fn disabled_type(elements: &[SceneElement]) -> Option<&'static str> {
    let has = |f: fn(&ElementKind) -> bool| elements.iter().any(|e| f(&e.kind));
    if has(|k| matches!(k, ElementKind::Iframe)) {
        Some("iframe")
    } else if has(|k| matches!(k, ElementKind::Embeddable)) {
        Some("embeddable")
    } else if has(|k| matches!(k, ElementKind::Image(_))) {
        Some("image")
    } else {
        None
    }
}

/// The ids of `ids`' items, in library order.
fn in_library_order(items: &[LibraryItem], ids: &[String]) -> Vec<String> {
    items
        .iter()
        .filter(|i| ids.contains(&i.id))
        .map(|i| i.id.clone())
        .collect()
}

/// Runs an event through upstream's handlers: updates `state` and returns
/// what else they do. `env` draws a new item's id and creation time
/// (`randomId()`, `Date.now()`).
pub fn update(
    state: &mut LibraryMenuState,
    event: LibrarySidebarEvent,
    cx: &LibraryContext<'_>,
    env: &mut dyn RestoreEnv,
) -> Update {
    let mut out = Update::default();
    let was_open = cx.is_open();
    let effects = &mut out.effects;
    match event {
        LibrarySidebarEvent::SelectTab(tab) => {
            // radix's controlled value changes only to another tab
            if let Some(open) = &cx.open_sidebar {
                state.tab_stop = Some(tab.clone());
                if open.tab.as_deref() != Some(tab.as_str()) {
                    if tab != LIBRARY_SIDEBAR_TAB {
                        state.unmount_library();
                    }
                    effects.push(LibraryEffect::SetAppState(patch([(
                        "openSidebar",
                        json!({"name": open.name, "tab": tab}),
                    )])));
                }
            }
        }
        LibrarySidebarEvent::Close => effects.push(close_sidebar(state)),
        LibrarySidebarEvent::Dock(docked) => {
            // LayerUI's onDock, then DefaultSidebar's
            effects.push(LibraryEffect::TrackEvent(
                "sidebar".into(),
                format!("toggleDock ({})", if docked { "dock" } else { "undock" }),
                format!("({})", form_factor(cx)),
            ));
            effects.push(LibraryEffect::SetAppState(patch([(
                "defaultSidebarDockedPreference",
                json!(docked),
            )])));
        }
        LibrarySidebarEvent::ToggleTrigger => {
            let next_open = !cx.is_open();
            if !next_open {
                state.close();
            }
            effects.push(LibraryEffect::SetAppState(patch([
                (
                    "openSidebar",
                    if next_open {
                        json!({"name": DEFAULT_SIDEBAR_NAME, "tab": LIBRARY_SIDEBAR_TAB})
                    } else {
                        Value::Null
                    },
                ),
                ("openMenu", Value::Null),
                ("openPopup", Value::Null),
            ])));
            if next_open {
                effects.push(LibraryEffect::TrackEvent(
                    "sidebar".into(),
                    format!("{DEFAULT_SIDEBAR_NAME} (open)"),
                    format!("button ({})", form_factor(cx)),
                ));
            }
        }
        LibrarySidebarEvent::UnitClick { unit, shift } => match unit {
            UnitKey::Item(id) if shift => toggle_item(state, cx, &id, shift),
            UnitKey::Item(id) => {
                let ids = if state.selected_items.contains(&id) {
                    in_library_order(cx.items, &state.selected_items)
                } else {
                    in_library_order(cx.items, std::slice::from_ref(&id))
                };
                effects.push(LibraryEffect::Insert(ids));
                effects.push(LibraryEffect::FocusContainer);
            }
            UnitKey::Pending => add_to_library(cx, effects, env),
        },
        LibrarySidebarEvent::CheckboxToggle { id, shift } => toggle_item(state, cx, &id, shift),
        LibrarySidebarEvent::UnitHover { unit, hovered } => {
            if hovered {
                state.hovered = Some(unit);
            } else if state.hovered.as_ref() == Some(&unit) {
                state.hovered = None;
            }
        }
        LibrarySidebarEvent::SearchInput(value) => state.search = value,
        LibrarySidebarEvent::ClearSearch => state.search.clear(),
        LibrarySidebarEvent::KeyDown {
            key,
            target,
            dialog_open,
        } => {
            if key != "Escape" || !cx.is_open() {
                return out;
            }
            let outcome = escape_outcome(
                cx.library_mounted(),
                !state.selected_items.is_empty(),
                state.menu_open,
                &target,
            );
            out.prevent_default = outcome.prevent_default();
            out.stop_propagation = outcome != EscapeOutcome::PassOn;
            match outcome {
                EscapeOutcome::ClearSelection { close_menu } => {
                    set_selected(state, Vec::new());
                    state.menu_open &= !close_menu;
                }
                EscapeOutcome::CloseAndFocus { close_menu } => {
                    state.menu_open &= !close_menu;
                    out.effects.push(close_sidebar(state));
                    out.effects.push(LibraryEffect::FocusContainer);
                }
                EscapeOutcome::CloseMenu => state.menu_open = false,
                EscapeOutcome::ClearSearch => state.search.clear(),
                // Sidebar's listener: an undocked (or unfitting) sidebar
                // closes
                EscapeOutcome::PassOn => {
                    if (!cx.docked() || !cx.can_fit_sidebar) && !dialog_open {
                        out.effects.push(close_sidebar(state));
                    }
                }
            }
        }
        LibrarySidebarEvent::OutsideClick {
            on_trigger,
            dialog_open,
        } => {
            if !on_trigger && (!cx.docked() || !cx.can_fit_sidebar) && !dialog_open {
                effects.push(close_sidebar(state));
            }
        }
        LibrarySidebarEvent::MenuToggle => state.menu_open = !state.menu_open,
        LibrarySidebarEvent::MenuClose => state.menu_open = false,
        LibrarySidebarEvent::MenuSelect(action) => {
            state.menu_open = false;
            let selected = in_library_order(cx.items, &state.selected_items);
            match action {
                LibraryMenuAction::Load => effects.push(LibraryEffect::LoadLibrary),
                LibraryMenuAction::Export => {
                    let ids = if state.selected_items.is_empty() {
                        cx.items.iter().map(|i| i.id.clone()).collect()
                    } else {
                        selected
                    };
                    effects.push(LibraryEffect::ExportLibrary(ids));
                }
                LibraryMenuAction::Publish => {
                    state.publish = Some(PublishState::default());
                    effects.push(LibraryEffect::LoadPublishData);
                }
                LibraryMenuAction::Reset | LibraryMenuAction::Remove => state.confirm_open = true,
            }
        }
        LibrarySidebarEvent::ConfirmCancel => {
            confirm_button(state, effects);
            state.confirm_open = false;
            effects.push(LibraryEffect::FocusContainer);
        }
        LibrarySidebarEvent::ConfirmAccept => {
            confirm_button(state, effects);
            if state.selected_items.is_empty() {
                effects.push(LibraryEffect::ResetLibrary);
            } else {
                // LibraryDropdownMenu's removeFromLibrary
                let next = cx
                    .items
                    .iter()
                    .filter(|i| !state.selected_items.contains(&i.id))
                    .cloned()
                    .collect();
                effects.push(LibraryEffect::SetLibrary(next));
                effects.push(LibraryEffect::DeletePreviews(state.selected_items.clone()));
                set_selected(state, Vec::new());
            }
            state.confirm_open = false;
            effects.push(LibraryEffect::FocusContainer);
        }
        LibrarySidebarEvent::DialogClose(which) => {
            // Dialog's onClose, then the dialog's onCloseRequest
            effects.push(LibraryEffect::SetAppState(patch([(
                "openMenu",
                Value::Null,
            )])));
            state.menu_open = false;
            match which {
                LibraryDialog::Confirm => state.confirm_open = false,
                LibraryDialog::Publish => close_publish(state, cx, effects),
                LibraryDialog::PublishSuccess => state.publish_success = None,
            }
        }
        LibrarySidebarEvent::PublishSaveNames => close_publish(state, cx, effects),
        LibrarySidebarEvent::PublishDataLoaded(data) => {
            if let (Some(publish), Some(data)) = (state.publish.as_mut(), data) {
                publish.data = data;
            }
        }
        LibrarySidebarEvent::PublishInput { field, value } => {
            if let Some(publish) = state.publish.as_mut() {
                publish.data.set(field, value);
            }
        }
        LibrarySidebarEvent::PublishItemName { id, value } => {
            if let Some(publish) = state.publish.as_mut() {
                // the dialog's items are the library's own until a submit
                // fails validation
                if !publish.detached {
                    publish.library_names.insert(id.clone(), value.clone());
                }
                publish.dialog_names.insert(id, value);
            }
        }
        LibrarySidebarEvent::PublishRemoveItem(id) => {
            let next = state
                .selected_items
                .iter()
                .filter(|s| **s != id)
                .cloned()
                .collect();
            set_selected(state, next);
            // the items change: clonedLibItems are the library's again
            if let Some(publish) = state.publish.as_mut() {
                publish.dialog_names = publish.library_names.clone();
                publish.detached = false;
                publish.errors.clear();
            }
        }
        LibrarySidebarEvent::PublishSubmit => {
            if let Some(publish) = state.publish.as_ref() {
                let items = dialogs::publish_items(cx, state, publish);
                let errors: std::collections::HashMap<String, String> = items
                    .iter()
                    .map(|i| {
                        let error = if i.name.as_deref().unwrap_or("").is_empty() {
                            library_text("publishDialog.errors.required")
                        } else {
                            ""
                        };
                        (i.id.clone(), error.to_owned())
                    })
                    .collect();
                let publish = state.publish.as_mut().expect("the publish dialog is open");
                if errors.values().any(|e| !e.is_empty()) {
                    publish.errors = errors;
                    publish.detached = true;
                    publish.submitting = false;
                } else {
                    publish.submitting = true;
                    effects.push(LibraryEffect::SubmitLibrary {
                        items,
                        data: publish.data.clone(),
                    });
                }
            }
        }
        LibrarySidebarEvent::PublishSucceeded { url } => {
            if let Some(publish) = state.publish.take() {
                effects.push(LibraryEffect::SavePublishData(None));
                // onPublishLibSuccess: the library, its selected items
                // published
                let next = cx
                    .items
                    .iter()
                    .map(|i| {
                        let mut item = dialogs::named(i, &publish.library_names);
                        if state.selected_items.contains(&item.id) {
                            item.status = LibraryItemStatus::Published;
                        }
                        item
                    })
                    .collect();
                state.publish_success = Some(PublishSuccess {
                    url,
                    author_name: publish.data.author_name,
                });
                effects.push(LibraryEffect::SetLibrary(next));
            }
        }
        LibrarySidebarEvent::PublishFailed(message) => {
            if let Some(publish) = state.publish.as_mut() {
                effects.push(LibraryEffect::Alert(message));
                publish.submitting = false;
            }
        }
        LibrarySidebarEvent::PublishSuccessClose => state.publish_success = None,
    }
    // an app state change renders an open sidebar again (one that closes
    // has been reset, one that opens mounts)
    let patched = out
        .effects
        .iter()
        .any(|e| matches!(e, LibraryEffect::SetAppState(_)));
    let closes = out.effects.iter().any(|e| match e {
        LibraryEffect::SetAppState(p) => p.get("openSidebar") == Some(&Value::Null),
        _ => false,
    });
    if patched && was_open && !closes {
        state.rerendered = true;
    }
    out
}

/// A confirmation button's `setAppState({ openMenu: null })` and
/// `setIsLibraryMenuOpen(false)` (`ConfirmDialog.tsx:44-73`); the button
/// then focuses the container.
fn confirm_button(state: &mut LibraryMenuState, effects: &mut Vec<LibraryEffect>) {
    effects.push(LibraryEffect::SetAppState(patch([(
        "openMenu",
        Value::Null,
    )])));
    state.menu_open = false;
}

/// PublishLibrary's `onDialogClose`: the library stored with the names
/// typed (`updateItemsInStorage`, which stores the library's items), the
/// fields saved, the dialog closed.
fn close_publish(
    state: &mut LibraryMenuState,
    cx: &LibraryContext<'_>,
    effects: &mut Vec<LibraryEffect>,
) {
    let Some(publish) = state.publish.take() else {
        return;
    };
    effects.push(LibraryEffect::SetLibrary(
        cx.items
            .iter()
            .map(|i| dialogs::named(i, &publish.library_names))
            .collect(),
    ));
    effects.push(LibraryEffect::SavePublishData(Some(publish.data)));
}

/// What Escape does in the library before Sidebar's own listener sees it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum EscapeOutcome {
    /// LibraryMenu's capture listener clears the selection (stopped); an
    /// open header menu closes too.
    ClearSelection { close_menu: bool },
    /// It closes the sidebar from an empty input and focuses the canvas
    /// (stopped); an open header menu closes too.
    CloseAndFocus { close_menu: bool },
    /// The open header menu's capture listener closes it (prevented,
    /// stopped immediately).
    CloseMenu,
    /// The search field's handler clears it (prevented and stopped).
    ClearSearch,
    /// Nothing handles it: on to Sidebar's listener.
    PassOn,
}

impl EscapeOutcome {
    fn prevent_default(self) -> bool {
        matches!(
            self,
            EscapeOutcome::CloseMenu
                | EscapeOutcome::ClearSearch
                | EscapeOutcome::ClearSelection { close_menu: true }
                | EscapeOutcome::CloseAndFocus { close_menu: true }
        )
    }
}

/// LibraryMenu's capture listener on the document (`LibraryMenu.tsx:
/// 252-293`, while the library tab is mounted), then the open header
/// menu's (`DropdownMenuContent.tsx:62-85`, bound later, which stops the
/// event from going further), then the search field's handler
/// (`LibraryMenuItems.tsx:388-396`).
fn escape_outcome(
    library_mounted: bool,
    has_selection: bool,
    menu_open: bool,
    target: &KeyTarget,
) -> EscapeOutcome {
    if !library_mounted {
        return EscapeOutcome::PassOn;
    }
    let close_menu = menu_open;
    match target {
        KeyTarget::SearchInput { .. } | KeyTarget::InSidebar { .. } => {
            let empty_input = match target {
                KeyTarget::SearchInput { value } => value.is_empty(),
                KeyTarget::InSidebar { empty_input } => *empty_input,
                KeyTarget::Outside { .. } => false,
            };
            if has_selection {
                return EscapeOutcome::ClearSelection { close_menu };
            }
            if empty_input {
                return EscapeOutcome::CloseAndFocus { close_menu };
            }
        }
        KeyTarget::Outside {
            cursor_over_sidebar,
        } => {
            if has_selection && *cursor_over_sidebar {
                return EscapeOutcome::ClearSelection { close_menu };
            }
        }
    }
    if menu_open {
        return EscapeOutcome::CloseMenu;
    }
    match target {
        KeyTarget::SearchInput { value } if !value.is_empty() => EscapeOutcome::ClearSearch,
        _ => EscapeOutcome::PassOn,
    }
}

/// A click on the pending unit: `LibraryMenuContent._onAddToLibrary`
/// (`LibraryMenu.tsx:72-103`) and `LibraryMenu.deselectItems`.
fn add_to_library(
    cx: &LibraryContext<'_>,
    effects: &mut Vec<LibraryEffect>,
    env: &mut dyn RestoreEnv,
) {
    effects.push(LibraryEffect::TrackEvent(
        "element".into(),
        "addToLibrary".into(),
        "ui".into(),
    ));
    if let Some(ty) = disabled_type(cx.pending) {
        effects.push(LibraryEffect::SetAppState(patch([(
            "errorMessage",
            json!(library_text(&format!(
                "errors.libraryElementTypeError.{ty}"
            ))),
        )])));
        return;
    }
    let item = LibraryItem::new(
        env.random_id(),
        LibraryItemStatus::Unpublished,
        cx.pending.to_vec(),
        env.now(),
    );
    effects.push(LibraryEffect::SetAppState(patch([
        ("selectedElementIds", json!({})),
        ("selectedGroupIds", json!({})),
        ("activeEmbeddable", Value::Null),
    ])));
    let mut next = vec![item];
    next.extend(cx.items.iter().cloned());
    effects.push(LibraryEffect::SetLibrary(next));
}

/// What a drag of a unit puts on the drag (`LibraryMenuItems.onItemDrag`,
/// `LibraryUnit.tsx:78-85`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DragStart {
    /// The pending unit is not dragged: the default is prevented.
    Prevent,
    /// `dataTransfer.setData(mime, data)`: the ids of the dragged items,
    /// `{"itemIds": [...]}` (the selection when the item is in it).
    Data { mime: String, data: String },
}

/// The drag data for a unit, given the selected items.
pub fn drag_data(unit: &UnitKey, selected: &[String]) -> DragStart {
    match unit {
        UnitKey::Pending => DragStart::Prevent,
        UnitKey::Item(id) => {
            let ids: Vec<&str> = if selected.contains(id) {
                selected.iter().map(String::as_str).collect()
            } else {
                vec![id]
            };
            DragStart::Data {
                mime: MIME_TYPE_EXCALIDRAWLIB_IDS.into(),
                data: json!({ "itemIds": ids }).to_string(),
            }
        }
    }
}

/// The item ids a drop's `MIME_TYPE_EXCALIDRAWLIB_IDS` data names
/// (`App.tsx:13206-13213`); `None` for data that is not such JSON.
pub fn dropped_item_ids(data: &str) -> Option<Vec<String>> {
    let value: Value = serde_json::from_str(data).ok()?;
    value["itemIds"]
        .as_array()?
        .iter()
        .map(|v| v.as_str().map(str::to_owned))
        .collect()
}

/// `getPendingElements` (`LibraryMenu.tsx:162-177`): the selected elements
/// with their bound text and frames' children, which the library offers to
/// add. (Upstream refreshes them once the pointer is up with the selection
/// tool active; the host calls this then.)
pub fn pending_elements(
    elements: &[SceneElement],
    selected_element_ids: &Map<String, Value>,
) -> Vec<SceneElement> {
    excali_editor::edit_actions::selected_elements(elements, selected_element_ids, true, true)
}

/// The search's matches (`LibraryMenuItems.tsx:86-98`): the items whose
/// trimmed name is not empty and whose deburred, lower-cased name holds the
/// deburred, lower-cased, trimmed query; none for a blank query.
pub fn filter_library_items<'a>(items: &'a [LibraryItem], query: &str) -> Vec<&'a LibraryItem> {
    let query = deburr(&js_trim(query).to_lowercase());
    if query.is_empty() {
        return Vec::new();
    }
    items
        .iter()
        .filter(|item| {
            let name = item.name.as_deref().unwrap_or("");
            !js_trim(name).is_empty() && deburr(&name.to_lowercase()).contains(&query)
        })
        .collect()
}

/// The header menu's entries for `selected` selected items of `items`
/// items in the library (`LibraryMenuHeaderContent.tsx:206-238`): the
/// items it acts on are the selected ones when any, else all.
pub fn library_menu_actions(selected: usize, items: usize) -> Vec<LibraryMenuAction> {
    let items_selected = selected > 0;
    let count = if items_selected { selected } else { items };
    let mut out = Vec::new();
    if !items_selected {
        out.push(LibraryMenuAction::Load);
    }
    if count > 0 {
        out.push(LibraryMenuAction::Export);
    }
    if items_selected {
        out.push(LibraryMenuAction::Publish);
    }
    if count > 0 {
        out.push(if items_selected {
            LibraryMenuAction::Remove
        } else {
            LibraryMenuAction::Reset
        });
    }
    out
}

// ---------------------------------------------------------------------------
// DOM
// ---------------------------------------------------------------------------

/// Receives the sidebar's events.
pub type OnLibrarySidebarEvent = Rc<dyn Fn(LibrarySidebarEvent)>;

fn emit(on_event: &Option<OnLibrarySidebarEvent>, event: LibrarySidebarEvent) {
    if let Some(f) = on_event {
        f(event);
    }
}

fn icon_node(icon: &Icon, theme: Theme) -> Node {
    icon.element(theme)
        .expect("a sidebar icon is markup")
        .into()
}

/// The sidebar's props.
#[derive(Clone)]
pub struct LibrarySidebarProps<'a> {
    pub context: LibraryContext<'a>,
    /// The icons' theme, and the library site's (`&theme=`).
    pub theme: Theme,
    pub previews: &'a Previews,
    pub state: &'a LibraryMenuState,
    pub browse: BrowseLink,
    /// The tabs' radix id (`radix-N`): the triggers are
    /// `{id_prefix}-trigger-{tab}`, the panels `{id_prefix}-content-{tab}`.
    pub id_prefix: String,
    /// The header menu's trigger and content ids.
    pub menu_ids: (String, String),
    /// The search tab's content (`SearchMenu`).
    pub search_menu: Option<Node>,
    pub on_event: Option<OnLibrarySidebarEvent>,
}

/// LayerUI's library trigger's props.
#[derive(Clone)]
pub struct SidebarTriggerProps {
    /// The default sidebar is open (`aria-pressed`).
    pub open: bool,
    pub theme: Theme,
    pub on_event: Option<OnLibrarySidebarEvent>,
}

/// `DefaultSidebar.Trigger` as LayerUI renders it (`SidebarTrigger.tsx`
/// with `sidebarRightIcon` and the title "Library").
pub fn default_sidebar_trigger(props: SidebarTriggerProps) -> Element {
    let title = library_text("toolBar.library");
    let on_event = props.on_event;
    Element::new("button")
        .attr("type", "button")
        .attr("title", title)
        .attr("class", "sidebar-trigger__label-element")
        .attr("aria-label", title)
        .attr("aria-keyshortcuts", "0")
        .attr("aria-pressed", props.open.to_string())
        .on("click", move |e| {
            // the layer UI's first-render animation stops
            if let Some(wrapper) = event_document(e)
                .and_then(|d| d.query_selector(".layer-ui__wrapper").ok().flatten())
            {
                let _ = wrapper.class_list().remove_1("animate");
            }
            emit(&on_event, LibrarySidebarEvent::ToggleTrigger);
        })
        .child(
            Element::new("div")
                .attr("class", "sidebar-trigger default-sidebar-trigger")
                .child(Element::new("div").child(icon_node(&icons::sidebarRightIcon, props.theme))),
        )
}

fn event_document(e: &Event) -> Option<web_sys::Document> {
    e.target()
        .and_then(|t| t.dyn_into::<web_sys::Node>().ok())
        .and_then(|n| n.owner_document())
}

/// The default sidebar (`DefaultSidebar.tsx`), or `None` while it is not
/// the open sidebar.
pub fn default_sidebar(props: LibrarySidebarProps<'_>) -> Option<Element> {
    let cx = &props.context;
    if !cx.is_open() {
        return None;
    }
    let docked = cx.docked();
    let header = sidebar_header(&props);
    let library = tab_panel(
        &props,
        LIBRARY_SIDEBAR_TAB,
        vec![Node::Element(library_menu(&props))],
    );
    let search = tab_panel(
        &props,
        CANVAS_SEARCH_TAB,
        props.search_menu.clone().into_iter().collect(),
    );
    let tabs = Element::new("div")
        .attr("dir", "ltr")
        .attr("data-orientation", "horizontal")
        .attr("class", "sidebar-tabs-root")
        .child(header)
        .child(library)
        .child(search);
    let viewport_ui = (!cx.phone).then_some(());
    let sidebar = island(
        IslandProps {
            class_name: Some(class_names([
                ("sidebar", true),
                ("sidebar--docked", docked),
                ("default-sidebar", true),
            ])),
            viewport_ui: viewport_ui.map(|_| "side".into()),
            viewport_ui_name: viewport_ui.map(|_| "sidebar".into()),
            ..IslandProps::default()
        },
        vec![tabs.into()],
    );
    let on_key = props.on_event.clone();
    let on_outside = props.on_event.clone();
    let library_mounted = cx.library_mounted();
    let has_selection = !props.state.selected_items.is_empty();
    let menu_open = props.state.menu_open && library_mounted;
    Some(sidebar.on_mount(move |el| {
        listen_on_document(
            el,
            "keydown",
            true,
            keydown_listener(
                el,
                library_mounted,
                has_selection,
                menu_open,
                on_key.clone(),
            ),
        );
        listen_on_document(
            el,
            "pointerdown",
            false,
            outside_listener(el, on_outside.clone()),
        );
    }))
}

/// `SidebarHeader` with the default sidebar's tab triggers.
fn sidebar_header(props: &LibrarySidebarProps<'_>) -> Element {
    let cx = &props.context;
    let tab = cx.open_tab();
    let triggers = Element::new("div")
        .attr("role", "tablist")
        .attr("aria-orientation", "horizontal")
        .attr("class", "sidebar-triggers")
        .attr("tabindex", "0")
        .attr("data-orientation", "horizontal")
        .style("outline", "none")
        .child(tab_trigger(
            props,
            CANVAS_SEARCH_TAB,
            &icons::searchIcon,
            tab,
        ))
        .child(tab_trigger(
            props,
            LIBRARY_SIDEBAR_TAB,
            &icons::LibraryIcon,
            tab,
        ));
    let mut buttons = Element::new("div").attr("class", "sidebar__header__buttons");
    if cx.can_dock() {
        let docked = cx.docked();
        let on_event = props.on_event.clone();
        let dock = button(
            ButtonProps {
                selected: docked,
                class_name: "sidebar__dock".into(),
                on_select: Some(Rc::new(move || {
                    emit(&on_event, LibrarySidebarEvent::Dock(!docked))
                })),
                ..ButtonProps::default()
            },
            vec![icon_node(&icons::PinIcon, props.theme)],
        )
        .attr("data-testid", "sidebar-dock")
        .attr("aria-label", library_text("labels.sidebarLock"));
        buttons = buttons.child_opt(tooltip(
            TooltipProps {
                label: library_text("labels.sidebarLock").into(),
                ..TooltipProps::default()
            },
            vec![dock.into()],
        ));
    }
    let on_event = props.on_event.clone();
    let close = button(
        ButtonProps {
            class_name: "sidebar__close".into(),
            on_select: Some(Rc::new(move || emit(&on_event, LibrarySidebarEvent::Close))),
            ..ButtonProps::default()
        },
        vec![icon_node(&icons::CloseIcon, props.theme)],
    )
    .attr("data-testid", "sidebar-close")
    .attr("aria-label", library_text("buttons.close"));
    Element::new("div")
        .attr("class", "sidebar__header")
        .attr("data-testid", "sidebar-header")
        .child(triggers)
        .child(buttons.child(close))
}

/// `Sidebar.TabTrigger` in radix's `Tabs.Trigger`: selects on a primary
/// mousedown, Enter, Space, or focus (automatic activation).
fn tab_trigger(
    props: &LibrarySidebarProps<'_>,
    tab: &'static str,
    icon: &Icon,
    open_tab: Option<&str>,
) -> Element {
    let active = open_tab == Some(tab);
    let on_down = props.on_event.clone();
    let on_key = props.on_event.clone();
    let on_focus = props.on_event.clone();
    Element::new("button")
        .attr("type", "button")
        .attr("role", "tab")
        .attr("aria-selected", active.to_string())
        .attr(
            "aria-controls",
            format!("{}-content-{tab}", props.id_prefix),
        )
        .attr("data-state", if active { "active" } else { "inactive" })
        .attr("id", format!("{}-trigger-{tab}", props.id_prefix))
        .attr("class", "excalidraw-button sidebar-tab-trigger")
        .attr(
            "tabindex",
            if props.state.tab_stop.as_deref() == Some(tab) {
                "0"
            } else {
                "-1"
            },
        )
        .attr("data-orientation", "horizontal")
        .attr("data-radix-collection-item", "")
        .on("mousedown", move |e| {
            let Some(m) = e.dyn_ref::<MouseEvent>() else {
                return;
            };
            if m.button() == 0 && !m.ctrl_key() {
                emit(&on_down, LibrarySidebarEvent::SelectTab(tab.into()));
            } else {
                // radix keeps focus off the trigger for other presses
                e.prevent_default();
            }
        })
        .on("keydown", move |e| {
            if let Some(k) = e.dyn_ref::<KeyboardEvent>() {
                if matches!(k.key().as_str(), " " | "Enter") {
                    emit(&on_key, LibrarySidebarEvent::SelectTab(tab.into()));
                }
            }
        })
        .on("focus", move |_| {
            if !active {
                emit(&on_focus, LibrarySidebarEvent::SelectTab(tab.into()));
            }
        })
        .child(icon_node(icon, props.theme))
}

/// `Sidebar.Tab` in radix's `Tabs.Content`: empty and hidden while
/// inactive.
fn tab_panel(props: &LibrarySidebarProps<'_>, tab: &str, children: Vec<Node>) -> Element {
    let active = props.context.open_tab() == Some(tab);
    let el = Element::new("div")
        .attr("data-state", if active { "active" } else { "inactive" })
        .attr("data-orientation", "horizontal")
        .attr("role", "tabpanel")
        .attr(
            "aria-labelledby",
            format!("{}-trigger-{tab}", props.id_prefix),
        )
        .flag("hidden", !active)
        .attr("id", format!("{}-content-{tab}", props.id_prefix))
        .attr("tabindex", "0")
        .attr("data-testid", tab);
    if active {
        el.style_opt(
            "animation-duration",
            (!props.state.rerendered).then_some("0s"),
        )
        .children_from(children)
    } else {
        el
    }
}

/// `Spinner` (`Spinner.tsx`) of `size`, not synchronized.
fn spinner(size: &str) -> Element {
    Element::new("div").attr("class", "Spinner ").child(
        Element::svg("svg")
            .attr("viewBox", "0 0 100 100")
            .style("width", size)
            .style("height", size)
            .style("--spinner-delay", "0")
            .child(
                Element::svg("circle")
                    .attr("cx", "50")
                    .attr("cy", "50")
                    .attr("r", "46")
                    .attr("stroke-width", "8")
                    .attr("fill", "none")
                    .attr("stroke-miterlimit", "10"),
            ),
    )
}

/// `LibraryMenu` in `LibraryMenuWrapper` (`LibraryMenu.tsx:105-160`).
fn library_menu(props: &LibrarySidebarProps<'_>) -> Element {
    let cx = &props.context;
    let wrapper = Element::new("div").attr("class", "layer-ui__library");
    if cx.status == (LibraryStatus::Loading { initialized: false }) {
        return wrapper.child(
            Element::new("div")
                .attr("class", "layer-ui__library-message")
                .child(Element::new("div").child(spinner("2em")).child(
                    Element::new("span").child(library_text("labels.libraryLoadingMessage")),
                )),
        );
    }
    let show_button = !cx.items.is_empty() || !cx.pending.is_empty();
    let wrapper = wrapper.child(library_menu_items(props));
    if show_button {
        wrapper.child(control_buttons(
            props,
            "library-menu-control-buttons--at-bottom",
            vec![("padding".into(), "16px 12px 0 12px".into())],
        ))
    } else {
        wrapper
    }
}

/// `LibraryMenuControlButtons` with the "Browse libraries" link
/// (`LibraryMenuBrowseButton.tsx`).
fn control_buttons(
    props: &LibrarySidebarProps<'_>,
    class_name: &str,
    style: Vec<(String, String)>,
) -> Element {
    let b = &props.browse;
    let target = if b.window_name.is_empty() {
        "_blank"
    } else {
        b.window_name.as_str()
    };
    let referrer = b
        .library_return_url
        .as_deref()
        .filter(|u| !u.is_empty())
        .unwrap_or(&b.location);
    let theme = match props.theme {
        Theme::Light => "light",
        Theme::Dark => "dark",
    };
    let href = format!(
        "{LIBRARY_URL}?target={target}&referrer={referrer}&useHash=true&token={}&theme={theme}&version={LIBRARY_VERSION}",
        b.app_id
    );
    Element::new("div")
        .attr(
            "class",
            class_names([("library-menu-control-buttons", true), (class_name, true)]),
        )
        .styles(style)
        .child(
            Element::new("a")
                .attr("class", "library-menu-browse-button")
                .attr("href", href)
                .attr("target", "_excalidraw_libraries")
                .child(library_text("labels.libraries")),
        )
}

/// `LibraryMenuItems` (`LibraryMenuItems.tsx:366-441`).
fn library_menu_items(props: &LibrarySidebarProps<'_>) -> Element {
    let cx = &props.context;
    let state = props.state;
    let empty = cx.is_library_empty();
    let searching = !empty && !js_trim(&state.search).is_empty();
    let unpublished = cx.unpublished();
    let published = cx.published();
    let any = !cx.pending.is_empty() || !unpublished.is_empty() || !published.is_empty();

    let mut header = Element::new("div").attr("class", "library-menu-items-header");
    if !empty {
        header = header.child(search_field(props));
    }
    header = header.child(library_dropdown(props));

    let mut items: Vec<Node> = Vec::new();
    if cx.status.is_loading() {
        items.push(
            Element::new("div")
                .style("position", "absolute")
                .style("top", "var(--container-padding-y)")
                .style("right", "var(--container-padding-x)")
                .style("transform", "translateY(50%)")
                .child(spinner("1em"))
                .into(),
        );
    }
    if searching {
        items.extend(when_searching(props));
    } else {
        items.extend(when_not_searching(props, &unpublished, &published));
    }
    if empty {
        items.push(
            control_buttons(
                props,
                "",
                vec![
                    ("padding".into(), "16px 0".into()),
                    ("width".into(), "100%".into()),
                ],
            )
            .into(),
        );
    }
    let list = stack_col(
        StackProps {
            gap: Some(1.0),
            align: Some(Align::Start),
            class_name: Some("library-menu-items-container__items".into()),
            style: vec![
                (
                    "flex".into(),
                    if published.is_empty() {
                        "0 1 auto"
                    } else {
                        "1"
                    }
                    .into(),
                ),
                ("margin".into(), if empty { "auto" } else { "0" }.into()),
            ],
            ..StackProps::default()
        },
        items,
    );
    let container = Element::new("div").attr("class", "library-menu-items-container");
    let container = if any {
        container.style("justify-content", "flex-start")
    } else {
        container.style("border-bottom", "0")
    };
    container.child(header).child(list)
}

/// The search field (`LibraryMenuItems.tsx:378-397`), focused once
/// mounted.
fn search_field(props: &LibrarySidebarProps<'_>) -> Element {
    let on_change = props.on_event.clone();
    let class = class_names([
        ("library-menu-items-container__search", true),
        ("hideCancelButton", !props.context.phone),
    ]);
    text_field(TextFieldProps {
        value: TextFieldValue::Controlled(props.state.search.clone()),
        on_change: Some(Rc::new(move |value| {
            emit(&on_change, LibrarySidebarEvent::SearchInput(value))
        })),
        class_name: Some(class),
        placeholder: Some(library_text("library.search.inputPlaceholder").into()),
        kind: Some(TextFieldType::Search),
        ..TextFieldProps::default()
    })
    .on_mount(|el| {
        let Ok(Some(input)) = el.query_selector("input") else {
            return;
        };
        let focused = input
            .owner_document()
            .and_then(|d| d.active_element())
            .is_some_and(|a| a.closest("input, textarea").ok().flatten().is_some());
        if !focused {
            if let Some(input) = input.dyn_ref::<web_sys::HtmlInputElement>() {
                let _ = input.focus();
                // a field built again keeps the caret at the end
                let end = input.value().encode_utf16().count() as u32;
                let _ = input.set_selection_range(end, end);
            }
        }
    })
}

/// The sections while not searching (`LibraryMenuItems.tsx:248-315`).
fn when_not_searching(
    props: &LibrarySidebarProps<'_>,
    unpublished: &[&LibraryItem],
    published: &[&LibraryItem],
) -> Vec<Node> {
    let cx = &props.context;
    let mut out: Vec<Node> = Vec::new();
    if !cx.is_library_empty() {
        out.push(section_header(library_text("labels.personalLib"), false).into());
    }
    if cx.pending.is_empty() && unpublished.is_empty() {
        let mut none = Element::new("div").attr("class", "library-menu-items__no-items");
        if published.is_empty() {
            none = none.child(
                Element::new("div")
                    .attr("class", "library-menu-items__no-items__label")
                    .child(library_text("library.noItems")),
            );
        }
        none = none.child(
            Element::new("div")
                .attr("class", "library-menu-items__no-items__hint")
                .child(library_text(if published.is_empty() {
                    "library.hint_emptyLibrary"
                } else {
                    "library.hint_emptyPrivateLibrary"
                })),
        );
        out.push(none.into());
    } else {
        let mut units: Vec<Node> = Vec::new();
        if !cx.pending.is_empty() {
            units.push(library_unit(props, UnitKey::Pending, None, false).into());
        }
        units.extend(unpublished.iter().map(|i| unit_for(props, i, false)));
        out.push(grid(units, false).into());
    }
    if !published.is_empty() {
        out.push(section_header(library_text("labels.excalidrawLib"), true).into());
        out.push(
            grid(
                published
                    .iter()
                    .map(|i| unit_for(props, i, false))
                    .collect(),
                false,
            )
            .into(),
        );
    }
    out
}

/// The matches of a search (`LibraryMenuItems.tsx:317-364`).
fn when_searching(props: &LibrarySidebarProps<'_>) -> Vec<Node> {
    let cx = &props.context;
    let mut heading = Element::new("div")
        .attr("class", "library-menu-items-container__header")
        .child(library_text("library.search.heading"));
    if !cx.status.is_loading() {
        let on_event = props.on_event.clone();
        heading = heading.child(
            Element::new("div")
                .attr("class", "library-menu-items-container__header__hint")
                .style("cursor", "pointer")
                .on("pointerdown", |e| e.prevent_default())
                .on("click", move |_| {
                    emit(&on_event, LibrarySidebarEvent::ClearSearch)
                })
                .child(Element::new("kbd").child("esc"))
                .child(" to clear"),
        );
    }
    let matches = filter_library_items(cx.items, &props.state.search);
    let body = if matches.is_empty() {
        let on_event = props.on_event.clone();
        Element::new("div")
            .attr("class", "library-menu-items__no-items")
            .child(
                Element::new("div")
                    .attr("class", "library-menu-items__no-items__hint")
                    .child(library_text("library.search.noResults")),
            )
            .child(
                button(
                    ButtonProps {
                        style: vec![
                            ("width".into(), "auto".into()),
                            ("margin-top".into(), "1rem".into()),
                        ],
                        on_select: Some(Rc::new(move || {
                            emit(&on_event, LibrarySidebarEvent::ClearSearch)
                        })),
                        ..ButtonProps::default()
                    },
                    vec![library_text("library.search.clearSearch").into()],
                )
                .on("pointerdown", |e| e.prevent_default()),
            )
    } else {
        grid(
            matches.iter().map(|i| unit_for(props, i, true)).collect(),
            true,
        )
    };
    vec![heading.into(), body.into()]
}

fn section_header(text: &str, published: bool) -> Element {
    Element::new("div")
        .attr("class", "library-menu-items-container__header")
        .style_opt("margin-top", published.then_some("0.75rem"))
        .child(text)
}

/// `LibraryMenuSectionGrid`.
fn grid(units: Vec<Node>, show_names: bool) -> Element {
    Element::new("div")
        .attr(
            "class",
            class_names([
                ("library-menu-items-container__grid", true),
                ("library-menu-items-container__grid--named", show_names),
            ]),
        )
        .children_from(units)
}

fn unit_for(props: &LibrarySidebarProps<'_>, item: &LibraryItem, show_name: bool) -> Node {
    library_unit(
        props,
        UnitKey::Item(item.id.clone()),
        item.name.as_deref(),
        show_name,
    )
    .into()
}

/// `LibraryUnit` (`LibraryUnit.tsx`).
fn library_unit(
    props: &LibrarySidebarProps<'_>,
    unit: UnitKey,
    name: Option<&str>,
    show_name: bool,
) -> Element {
    let state = props.state;
    let pending = unit == UnitKey::Pending;
    let selected = unit
        .id()
        .is_some_and(|id| state.selected_items.iter().any(|s| s == id));
    let hovered = state.hovered.as_ref() == Some(&unit);
    let preview = props.previews.get(&unit).cloned();
    let has_name = name.is_some_and(|n| !js_trim(n).is_empty());

    let on_click = props.on_event.clone();
    let click_unit = unit.clone();
    let drag_unit = unit.clone();
    let drag_selected = state.selected_items.clone();
    let on_drag = props.on_event.clone();
    let mut dragger = Element::new("div")
        .attr(
            "class",
            class_names([
                ("library-unit__dragger", true),
                ("library-unit__pulse", pending),
            ]),
        )
        .attr("draggable", "true")
        .on("click", move |e| {
            let shift = e.dyn_ref::<MouseEvent>().is_some_and(MouseEvent::shift_key);
            emit(
                &on_click,
                LibrarySidebarEvent::UnitClick {
                    unit: click_unit.clone(),
                    shift,
                },
            );
        })
        .on("dragstart", move |e| {
            match drag_data(&drag_unit, &drag_selected) {
                DragStart::Prevent => e.prevent_default(),
                DragStart::Data { mime, data } => {
                    emit(
                        &on_drag,
                        LibrarySidebarEvent::UnitHover {
                            unit: drag_unit.clone(),
                            hovered: false,
                        },
                    );
                    if let Some(transfer) = e
                        .dyn_ref::<web_sys::DragEvent>()
                        .and_then(web_sys::DragEvent::data_transfer)
                    {
                        let _ = transfer.set_data(&mime, &data);
                    }
                }
            }
        });
    if show_name {
        dragger = dragger
            .child(
                Element::new("div")
                    .attr("class", "library-unit__preview")
                    .child_opt(preview.clone()),
            )
            .child(
                Element::new("div")
                    .attr("class", "library-unit__name")
                    .child(name.unwrap_or("")),
            );
    } else {
        dragger = dragger.child_opt(preview.clone());
    }

    let on_enter = props.on_event.clone();
    let on_leave = props.on_event.clone();
    let enter_unit = unit.clone();
    let leave_unit = unit.clone();
    let mut el = Element::new("div")
        .attr(
            "class",
            class_names([
                ("library-unit", true),
                ("library-unit__active", true),
                ("library-unit--hover", hovered),
                ("library-unit--selected", selected),
                ("library-unit--skeleton", preview.is_none()),
                ("library-unit--named", show_name),
            ]),
        )
        .on("mouseenter", move |_| {
            emit(
                &on_enter,
                LibrarySidebarEvent::UnitHover {
                    unit: enter_unit.clone(),
                    hovered: true,
                },
            )
        })
        .on("mouseleave", move |_| {
            emit(
                &on_leave,
                LibrarySidebarEvent::UnitHover {
                    unit: leave_unit.clone(),
                    hovered: false,
                },
            )
        });
    if has_name {
        let label = name.unwrap_or("").to_owned();
        el = el
            .on("pointerenter", move |e| {
                let Some(target) = e
                    .current_target()
                    .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
                else {
                    return;
                };
                // a name shown below the item needs no tooltip unless cut
                if show_name {
                    if let Ok(Some(name)) = target.query_selector(".library-unit__name") {
                        if name.scroll_width() <= name.client_width() {
                            return;
                        }
                    }
                }
                crate::primitives::show_tooltip(
                    &target,
                    &label,
                    crate::primitives::TooltipOptions {
                        long: false,
                        delay: true,
                        placement: crate::primitives::TooltipPlacement::Top,
                    },
                );
            })
            .on("pointerleave", hide_tooltip_of)
            .on("pointerdown", hide_tooltip_of);
    }
    el = el.child(dragger);
    if pending {
        el = el.child(
            Element::new("div")
                .attr("class", "library-unit__adder")
                .child(icon_node(&icons::PlusIcon, props.theme)),
        );
    }
    if let Some(id) = unit.id() {
        if hovered || props.context.phone || selected {
            el = el.child(checkbox(props, id, selected));
        }
    }
    el
}

fn hide_tooltip_of(e: &Event) {
    if let Some(document) = event_document(e) {
        crate::primitives::hide_tooltip(&document);
    }
}

/// `CheckboxItem` (`CheckboxItem.tsx`) as the unit's checkbox: a click
/// toggles the item and focuses the box.
fn checkbox(props: &LibrarySidebarProps<'_>, id: &str, checked: bool) -> Element {
    let on_event = props.on_event.clone();
    let id = id.to_owned();
    Element::new("div")
        .attr(
            "class",
            class_names([
                ("Checkbox", true),
                ("library-unit__checkbox", true),
                ("is-checked", checked),
            ]),
        )
        .on("click", move |e| {
            let shift = e.dyn_ref::<MouseEvent>().is_some_and(MouseEvent::shift_key);
            emit(
                &on_event,
                LibrarySidebarEvent::CheckboxToggle {
                    id: id.clone(),
                    shift,
                },
            );
            if let Some(b) = e
                .current_target()
                .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
                .and_then(|t| t.query_selector(".Checkbox-box").ok().flatten())
                .and_then(|b| b.dyn_into::<web_sys::HtmlElement>().ok())
            {
                let _ = b.focus();
            }
        })
        .child(
            Element::new("button")
                .attr("type", "button")
                .attr("class", "Checkbox-box")
                .attr("role", "checkbox")
                .attr("aria-checked", checked.to_string())
                .child(icon_node(&icons::checkIcon, props.theme)),
        )
        .child(Element::new("div").attr("class", "Checkbox-label"))
}

/// `LibraryDropdownMenu` (`LibraryMenuHeaderContent.tsx:195-261`): the
/// header menu and the selection's count.
fn library_dropdown(props: &LibrarySidebarProps<'_>) -> Element {
    let cx = &props.context;
    let state = props.state;
    let open = state.menu_open;
    let (trigger_id, content_id) = &props.menu_ids;
    let on_toggle = props.on_event.clone();
    let trigger = Element::new("button")
        .attr("type", "button")
        .attr("id", trigger_id.clone())
        .attr("aria-haspopup", "menu")
        .attr("aria-expanded", open.to_string())
        .attr_opt("aria-controls", open.then(|| content_id.clone()))
        .attr("data-state", if open { "open" } else { "closed" })
        .attr(
            "class",
            format!(
                "dropdown-menu-button  zen-mode-transition{}",
                if cx.phone {
                    " dropdown-menu-button--mobile"
                } else {
                    ""
                }
            ),
        )
        .attr("data-testid", "dropdown-menu-button")
        // radix's trigger: a primary press keeps focus off it while closed
        .on("pointerdown", move |e| {
            let Some(m) = e.dyn_ref::<MouseEvent>() else {
                return;
            };
            if m.button() == 0 && !m.ctrl_key() && !open {
                e.prevent_default();
            }
        })
        .on("click", move |_| {
            emit(&on_toggle, LibrarySidebarEvent::MenuToggle)
        })
        .child(icon_node(&icons::DotsIcon, props.theme));
    let mut wrapper = Element::new("div")
        .attr("class", crate::main_menu::DROPDOWN_MENU_EVENT_WRAPPER)
        .style("display", "contents")
        .child(trigger);
    if open {
        wrapper = wrapper.child(dropdown_content(props, trigger_id, content_id));
    }
    let mut container = Element::new("div")
        .attr(
            "class",
            "library-menu-dropdown-container library-menu-dropdown-container--in-heading",
        )
        .child(wrapper);
    if !state.selected_items.is_empty() {
        container = container.child(
            Element::new("div")
                .attr("class", "library-actions-counter")
                .child(state.selected_items.len().to_string()),
        );
    }
    container
}

/// The open header menu (`DropdownMenu.Content` with class `library-menu`).
fn dropdown_content(
    props: &LibrarySidebarProps<'_>,
    trigger_id: &str,
    content_id: &str,
) -> Element {
    let cx = &props.context;
    let selected = props.state.selected_items.len();
    let items: Vec<Node> = library_menu_actions(selected, cx.items.len())
        .into_iter()
        .map(|action| menu_item(props, action).into())
        .collect();
    let container = if cx.phone {
        stack_col(
            StackProps {
                class_name: Some("dropdown-menu-container".into()),
                ..StackProps::default()
            },
            items,
        )
    } else {
        island(
            IslandProps {
                padding: Some(2.0),
                class_name: Some("dropdown-menu-container".into()),
                ..IslandProps::default()
            },
            items,
        )
    };
    let on_close = props.on_event.clone();
    let class = if cx.phone {
        "dropdown-menu library-menu dropdown-menu--mobile"
    } else {
        "dropdown-menu library-menu"
    };
    radix_menu_content(
        class,
        trigger_id,
        content_id,
        container,
        Rc::new(move || emit(&on_close, LibrarySidebarEvent::MenuClose)),
    )
}

/// A `DropdownMenu.Item` of the header menu, in radix's `Menu.Item`.
fn menu_item(props: &LibrarySidebarProps<'_>, action: LibraryMenuAction) -> Element {
    let (icon, label, test_id) = match action {
        LibraryMenuAction::Load => (&icons::LoadIcon, "buttons.load", Some("lib-dropdown--load")),
        LibraryMenuAction::Export => (
            &icons::ExportIcon,
            "buttons.export",
            Some("lib-dropdown--export"),
        ),
        // upstream's test id for Publish is "--remove"
        LibraryMenuAction::Publish => (
            &icons::publishIcon,
            "buttons.publishLibrary",
            Some("lib-dropdown--remove"),
        ),
        LibraryMenuAction::Reset => (&icons::TrashIcon, "buttons.resetLibrary", None),
        LibraryMenuAction::Remove => (&icons::TrashIcon, "buttons.remove", None),
    };
    let on_event = props.on_event.clone();
    Element::new("button")
        .attr(
            "class",
            "radix-menu-item dropdown-menu-item dropdown-menu-item-base",
        )
        .attr("role", "menuitem")
        .attr("tabindex", "-1")
        .attr("data-orientation", "vertical")
        .attr("data-radix-collection-item", "")
        .attr_opt("data-testid", test_id)
        .on("click", move |_| {
            emit(&on_event, LibrarySidebarEvent::MenuSelect(action))
        })
        .child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__icon")
                .child(icon_node(icon, props.theme)),
        )
        .child(
            Element::new("div")
                .attr("class", "dropdown-menu-item__text")
                .child(
                    // Ellipsify (Ellipsify.tsx)
                    Element::new("span")
                        .style("text-overflow", "ellipsis")
                        .style("overflow", "hidden")
                        .style("white-space", "nowrap")
                        .child(library_text(label)),
                ),
        )
}

// ---------------------------------------------------------------------------
// the document's listeners
// ---------------------------------------------------------------------------

type Listener = Box<dyn FnMut(Event) -> bool>;

/// Listens for `event` on `el`'s document while `el` is in it: `listener`
/// returns whether to go on listening (and the listener is removed once
/// `el` is gone).
fn listen_on_document(
    el: &web_sys::Element,
    event: &'static str,
    capture: bool,
    mut listener: Listener,
) {
    let Some(document) = el.owner_document() else {
        return;
    };
    let slot: Rc<std::cell::RefCell<Option<js_sys::Function>>> = Rc::default();
    let own = slot.clone();
    let target = document.clone();
    let owner = el.clone();
    let closure = Closure::<dyn FnMut(Event)>::new(move |e: Event| {
        if !owner.is_connected() || !listener(e) {
            if let Some(f) = own.borrow_mut().take() {
                let _ = target.remove_event_listener_with_callback_and_bool(event, &f, capture);
            }
        }
    });
    let f: js_sys::Function = closure.into_js_value().unchecked_into();
    let _ = document.add_event_listener_with_callback_and_bool(event, &f, capture);
    *slot.borrow_mut() = Some(f);
}

fn dialog_open(document: &web_sys::Document) -> bool {
    document.query_selector(".Dialog").ok().flatten().is_some()
}

/// The sidebar's key handling (LibraryMenu's capture listener, the search
/// field's handler and Sidebar's listener) as one capture listener on the
/// document: the event goes to the host, which runs it through [`update`];
/// the DOM event is prevented and stopped as upstream's handlers do
/// ([`escape_outcome`], for the state the sidebar was built from, the open
/// header menu's own document listener included).
fn keydown_listener(
    sidebar: &web_sys::Element,
    library_mounted: bool,
    has_selection: bool,
    menu_open: bool,
    on_event: Option<OnLibrarySidebarEvent>,
) -> Listener {
    let sidebar = sidebar.clone();
    Box::new(move |e: Event| {
        let Some(k) = e.dyn_ref::<KeyboardEvent>() else {
            return true;
        };
        let key = k.key();
        if key != "Escape" {
            return true;
        }
        let target = e
            .target()
            .and_then(|t| t.dyn_into::<web_sys::Element>().ok());
        let inside = target
            .as_ref()
            .is_some_and(|t| sidebar.contains(Some(t.as_ref())));
        let input = target
            .as_ref()
            .and_then(|t| t.dyn_ref::<web_sys::HtmlInputElement>().cloned());
        let target_kind = match (&input, inside) {
            (Some(i), true)
                if i.closest(".library-menu-items-container__search")
                    .ok()
                    .flatten()
                    .is_some() =>
            {
                KeyTarget::SearchInput { value: i.value() }
            }
            (input, true) => KeyTarget::InSidebar {
                empty_input: input
                    .as_ref()
                    .is_some_and(|i| i.value().is_empty() && !i.read_only()),
            },
            (_, false) => KeyTarget::Outside {
                cursor_over_sidebar: sidebar.matches(":hover").unwrap_or(false),
            },
        };
        let outcome = escape_outcome(library_mounted, has_selection, menu_open, &target_kind);
        if outcome.prevent_default() {
            e.prevent_default();
        }
        if outcome != EscapeOutcome::PassOn {
            e.stop_propagation();
        }
        let dialog = sidebar.owner_document().is_some_and(|d| dialog_open(&d));
        emit(
            &on_event,
            LibrarySidebarEvent::KeyDown {
                key,
                target: target_kind,
                dialog_open: dialog,
            },
        );
        true
    })
}

/// `useOutsideClick` on the sidebar's island (`Sidebar.tsx:115-131`).
fn outside_listener(
    sidebar: &web_sys::Element,
    on_event: Option<OnLibrarySidebarEvent>,
) -> Listener {
    let sidebar = sidebar.clone();
    Box::new(move |e: Event| {
        let Some(target) = e
            .target()
            .and_then(|t| t.dyn_into::<web_sys::Element>().ok())
        else {
            return true;
        };
        let in_document = sidebar
            .owner_document()
            .and_then(|d| d.document_element())
            .is_some_and(|d| d.contains(Some(target.as_ref())));
        if sidebar.contains(Some(target.as_ref())) || !in_document {
            return true;
        }
        let on_trigger = target.closest(".sidebar-trigger").ok().flatten().is_some();
        let dialog = sidebar.owner_document().is_some_and(|d| dialog_open(&d));
        emit(
            &on_event,
            LibrarySidebarEvent::OutsideClick {
                on_trigger,
                dialog_open: dialog,
            },
        );
        true
    })
}
