//! Every case of `tests/fixtures/restore-element.json`: upstream's own
//! `restoreElement` output at the pinned commit
//! (generated by `tools/goldens/restore-fixtures.mjs`), compared byte for
//! byte as `JSON.stringify` writes it.
//!
//! Upstream migrates a legacy binding (no `mode`) whose target exists with
//! element geometry (`restore.ts:362-418`), which restore takes from its
//! [`RestoreEnv`]. The fixture records which ends reached that branch; the
//! environment here answers with the binding upstream computed, so the test
//! pins the branch's inputs (which ends, which target) and everything
//! restore does around it.

use serde_json::{Map, Value};

use super::{
    restore_element_encoded, BindingEnd, ElementsMap, LegacyBinding, LegacyBindingRequest,
    RestoreEnv, RestoreOptions, TestEnv,
};
use crate::json;

const FIXTURE: &str = include_str!("../../tests/fixtures/restore-element.json");

fn object(value: &Value, what: &str) -> Map<String, Value> {
    match value {
        Value::Object(m) => m.clone(),
        _ => panic!("{what} is not an object"),
    }
}

fn elements(value: &Value, what: &str) -> Vec<Map<String, Value>> {
    value
        .as_array()
        .unwrap_or_else(|| panic!("{what} is not an array"))
        .iter()
        .map(|e| object(e, what))
        .collect()
}

/// [`TestEnv`] plus the legacy binding migration answered from the fixture.
struct FixtureEnv {
    test: TestEnv,
    expected: Option<Map<String, Value>>,
    calls: Vec<&'static str>,
}

impl RestoreEnv for FixtureEnv {
    fn now(&mut self) -> f64 {
        self.test.now()
    }

    fn random_id(&mut self) -> String {
        self.test.random_id()
    }

    fn random_integer(&mut self) -> f64 {
        self.test.random_integer()
    }

    fn migrate_legacy_binding(
        &mut self,
        request: LegacyBindingRequest<'_>,
    ) -> Option<LegacyBinding> {
        let (end, key) = match request.end {
            BindingEnd::Start => ("start", "startBinding"),
            BindingEnd::End => ("end", "endBinding"),
        };
        self.calls.push(end);
        let binding = self.expected.as_ref()?.get(key)?.as_object()?;
        Some(LegacyBinding {
            mode: binding.get("mode")?.clone(),
            fixed_point: binding.get("fixedPoint")?.clone(),
        })
    }
}

fn restore_case(case: &Map<String, Value>, id: &str) -> Result<(), String> {
    let element = object(&case["element"], "element");
    let targets = match case.get("targets") {
        Some(t) => elements(t, "targets"),
        None => vec![element.clone()],
    };
    let targets = ElementsMap::from_encoded(targets);
    let existing = case
        .get("existing")
        .map(|e| ElementsMap::from_encoded(elements(e, "existing")));
    let opts = RestoreOptions {
        delete_invisible_elements: case
            .get("opts")
            .and_then(|o| o.get("deleteInvisibleElements"))
            .and_then(Value::as_bool)
            .unwrap_or(false),
    };
    let mut env = FixtureEnv {
        test: TestEnv::default(),
        expected: case.get("result").and_then(Value::as_object).cloned(),
        calls: Vec::new(),
    };
    let got = restore_element_encoded(&element, &targets, existing.as_ref(), opts, &mut env);
    let geometry: Vec<&str> = case
        .get("geometry")
        .and_then(Value::as_array)
        .map(|g| g.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    if env.calls != geometry {
        return Err(format!(
            "{id}: legacy binding migration for {:?}, upstream {geometry:?}",
            env.calls
        ));
    }
    match (got, case.get("result"), case.get("error")) {
        (Ok(restored), Some(expected), None) => {
            let got = json::write_parsed(&restored.map_or(Value::Null, Value::Object));
            let want = json::write_parsed(expected);
            if got != want {
                return Err(format!("{id}:\n got {got}\nwant {want}"));
            }
        }
        (Err(err), None, Some(Value::String(message))) => {
            if err.to_string() != *message {
                return Err(format!("{id}: error {err} != {message}"));
            }
        }
        (got, result, error) => {
            return Err(format!("{id}: got {got:?}, want {result:?} / {error:?}"));
        }
    }
    Ok(())
}

#[test]
fn upstream_fixture() {
    let fixture = json::parse(FIXTURE).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    assert!(cases.len() > 350, "{} cases", cases.len());
    let mut failures = Vec::new();
    for case in cases {
        let case = object(case, "case");
        let id = case["id"].as_str().expect("id");
        let outcome = match case["call"].as_str() {
            Some("restoreElement") => restore_case(&case, id),
            other => panic!("{id}: unknown call {other:?}"),
        };
        if let Err(failure) = outcome {
            failures.push(failure);
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

/// The migration is asked about the target upstream resolves: the targets
/// map first, then the existing elements, the last element of an id
/// winning, ids compared as JS `Map` keys (`7` and `"7"` differ). Each case
/// has the right target at x 100 and a decoy at x 1000.
#[test]
fn legacy_binding_targets() {
    let fixture = json::parse(FIXTURE).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    // (case, the target is in the targets map rather than the existing one)
    for (id, in_targets) in [
        ("arrow-binding-legacy-target-map-wins", true),
        ("arrow-binding-legacy-migrated-duplicate-id-last-wins", true),
        ("arrow-binding-legacy-numeric-id", true),
        ("arrow-binding-legacy-migrated-existing", false),
    ] {
        let case = object(
            cases
                .iter()
                .find(|c| c["id"] == id)
                .unwrap_or_else(|| panic!("no case {id}")),
            "case",
        );
        let element = object(&case["element"], "element");
        let targets = ElementsMap::from_encoded(match case.get("targets") {
            Some(t) => elements(t, "targets"),
            None => vec![element.clone()],
        });
        let existing = case
            .get("existing")
            .map(|e| ElementsMap::from_encoded(elements(e, "existing")));
        let mut env = Probe::default();
        restore_element_encoded(
            &element,
            &targets,
            existing.as_ref(),
            RestoreOptions::default(),
            &mut env,
        )
        .expect("restores");
        assert_eq!(env.seen, [(Value::from(100), in_targets)], "{id}");
    }
}

/// Records the `x` of each bound element a migration request names, and
/// whether the request's map is the targets map (the one holding the
/// arrow).
#[derive(Default)]
struct Probe {
    test: TestEnv,
    seen: Vec<(Value, bool)>,
}

impl RestoreEnv for Probe {
    fn now(&mut self) -> f64 {
        self.test.now()
    }

    fn random_id(&mut self) -> String {
        self.test.random_id()
    }

    fn random_integer(&mut self) -> f64 {
        self.test.random_integer()
    }

    fn migrate_legacy_binding(
        &mut self,
        request: LegacyBindingRequest<'_>,
    ) -> Option<LegacyBinding> {
        let x = request
            .bound_element
            .get("x")
            .cloned()
            .unwrap_or(Value::Null);
        let in_targets = request.elements.get(&Value::from("arrow")).is_some();
        self.seen.push((x, in_targets));
        None
    }
}
