//! Every case of `tests/fixtures/restore-elements.json`: upstream's own
//! `restoreElements` and `bumpElementVersions` output at the pinned commit
//! (generated by `tools/goldens/restore-elements-fixtures.mjs`), compared
//! byte for byte as `JSON.stringify` writes it, element order included.
//!
//! Three steps need geometry or text measurement that `excali-core` takes
//! from its [`RestoreEnv`]: the elbow arrow re-route
//! (`updateElbowArrowPoints`), `refreshTextDimensions` and
//! `getStickyNoteLayout`. The fixture records, in call order, what upstream
//! passed to each and what it returned; the environment here checks that
//! restore asks for the same thing (the element as it stands at that point,
//! the other element, the elbow update) and answers with upstream's result.
//! Everything around those calls is the port's own.

use serde_json::{Map, Value};

use super::{
    restore_elements_encoded, ElbowArrowRequest, RestoreElementsOptions, RestoreEnv, SceneCall,
    StickyNoteLayout, StickyNoteLayoutRequest, TestEnv, TextDimensionsRequest,
};
use crate::json;

const FIXTURE: &str = include_str!("../../tests/fixtures/restore-elements.json");

fn object(value: &Value, what: &str) -> Map<String, Value> {
    match value {
        Value::Object(m) => m.clone(),
        _ => panic!("{what} is not an object"),
    }
}

fn objects(value: &Value, what: &str) -> Vec<Map<String, Value>> {
    value
        .as_array()
        .unwrap_or_else(|| panic!("{what} is not an array"))
        .iter()
        .map(|e| object(e, what))
        .collect()
}

/// [`TestEnv`] plus the three recorded hooks, answered in order.
struct FixtureEnv {
    test: TestEnv,
    hooks: Vec<Map<String, Value>>,
    next: usize,
    mismatches: Vec<String>,
}

impl FixtureEnv {
    /// The next recorded call, checked against what restore passes.
    fn expect(
        &mut self,
        hook: &str,
        element: &Map<String, Value>,
        check: impl FnOnce(&Map<String, Value>) -> Option<String>,
    ) -> Option<Value> {
        let Some(recorded) = self.hooks.get(self.next).cloned() else {
            self.mismatches
                .push(format!("unexpected {hook} for {}", id_of(element)));
            return None;
        };
        self.next += 1;
        if recorded["hook"] != hook {
            self.mismatches.push(format!(
                "{hook} for {}, upstream called {}",
                id_of(element),
                recorded["hook"]
            ));
            return None;
        }
        let want = json::write_parsed(&recorded["element"]);
        let got = json::write_parsed(&Value::Object(element.clone()));
        if got != want {
            self.mismatches
                .push(format!("{hook} element:\n got {got}\nwant {want}"));
        }
        if let Some(mismatch) = check(&recorded) {
            self.mismatches.push(format!("{hook}: {mismatch}"));
        }
        Some(recorded["result"].clone())
    }
}

fn id_of(element: &Map<String, Value>) -> String {
    element
        .get("id")
        .map_or("undefined".to_owned(), Value::to_string)
}

/// The id of the second argument as the fixture records it.
fn other_id(other: Option<&Map<String, Value>>) -> Value {
    other
        .and_then(|o| o.get("id"))
        .cloned()
        .unwrap_or(Value::Null)
}

impl RestoreEnv for FixtureEnv {
    fn now(&mut self) -> f64 {
        self.test.now()
    }

    fn random_id(&mut self) -> String {
        self.test.random_id()
    }

    fn random_integer(&mut self) -> f64 {
        self.test.random_integer()
    }

    fn refresh_text_dimensions(
        &mut self,
        request: TextDimensionsRequest<'_>,
    ) -> Option<Map<String, Value>> {
        let container = other_id(request.container);
        let result = self.expect("refreshTextDimensions", request.text, |recorded| {
            (recorded["other"] != container)
                .then(|| format!("container {container}, upstream {}", recorded["other"]))
        })?;
        result.as_object().cloned()
    }

    fn sticky_note_layout(
        &mut self,
        request: StickyNoteLayoutRequest<'_>,
    ) -> Option<StickyNoteLayout> {
        let text = other_id(request.text);
        let result = self.expect("getStickyNoteLayout", request.note, |recorded| {
            (recorded["other"] != text)
                .then(|| format!("label {text}, upstream {}", recorded["other"]))
        })?;
        Some(StickyNoteLayout {
            container: result["container"].as_object()?.clone(),
            text: result["text"].as_object().cloned(),
        })
    }

    fn update_elbow_arrow_points(
        &mut self,
        request: ElbowArrowRequest<'_>,
    ) -> Option<Map<String, Value>> {
        let points = Value::Array(request.points.to_vec());
        let result = self.expect("updateElbowArrowPoints", request.arrow, |recorded| {
            let want = &recorded["updates"]["points"];
            (json::write_parsed(want) != json::write_parsed(&points))
                .then(|| format!("points {points}, upstream {want}"))
        })?;
        result.as_object().cloned()
    }
}

fn options(case: &Map<String, Value>) -> RestoreElementsOptions {
    let flag = |key: &str| {
        case.get("opts")
            .and_then(|o| o.get(key))
            .and_then(Value::as_bool)
            .unwrap_or(false)
    };
    RestoreElementsOptions {
        refresh_dimensions: flag("refreshDimensions"),
        repair_bindings: flag("repairBindings"),
        delete_invisible_elements: flag("deleteInvisibleElements"),
    }
}

fn run_case(case: &Map<String, Value>, id: &str) -> Result<(), String> {
    let elements = case["elements"]
        .as_array()
        .unwrap_or_else(|| panic!("{id}: elements"))
        .clone();
    let existing = case.get("existing").map(|e| objects(e, "existing"));
    let mut env = FixtureEnv {
        test: TestEnv::default(),
        hooks: case
            .get("hooks")
            .map(|h| objects(h, "hooks"))
            .unwrap_or_default(),
        next: 0,
        mismatches: Vec::new(),
    };
    let input = match case["call"].as_str() {
        Some("restoreElements") => SceneCall::Restore(options(case)),
        Some("bumpElementVersions") => SceneCall::BumpVersions,
        other => panic!("{id}: unknown call {other:?}"),
    };
    let got = restore_elements_encoded(&elements, existing.as_deref(), input, &mut env);
    if env.next != env.hooks.len() {
        env.mismatches.push(format!(
            "{} of {} recorded hooks called",
            env.next,
            env.hooks.len()
        ));
    }
    if !env.mismatches.is_empty() {
        return Err(format!("{id}: {}", env.mismatches.join("\n  ")));
    }
    match (got, case.get("result"), case.get("error")) {
        (Ok(restored), Some(expected), None) => {
            let got = json::write_parsed(&Value::Array(
                restored.into_iter().map(Value::Object).collect(),
            ));
            let want = json::write_parsed(expected);
            if got != want {
                return Err(format!("{id}:\n got {got}\nwant {want}"));
            }
        }
        (Err(err), None, Some(Value::String(message))) => {
            if err.to_string() != *message {
                return Err(format!("{id}: error {err} != {message}"));
            }
        }
        (got, result, error) => {
            return Err(format!("{id}: got {got:?}, want {result:?} / {error:?}"));
        }
    }
    Ok(())
}

#[test]
fn upstream_fixture() {
    let fixture = json::parse(FIXTURE).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    assert!(cases.len() >= 100, "{} cases", cases.len());
    let mut failures = Vec::new();
    for case in cases {
        let case = object(case, "case");
        let id = case["id"].as_str().expect("id");
        if let Err(failure) = run_case(&case, id) {
            failures.push(failure);
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

/// The fixture exercises each hook and each thrown error.
#[test]
fn fixture_covers_every_hook() {
    let fixture = json::parse(FIXTURE).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    for hook in [
        "updateElbowArrowPoints",
        "refreshTextDimensions",
        "getStickyNoteLayout",
    ] {
        assert!(
            cases.iter().any(|c| c["hooks"]
                .as_array()
                .is_some_and(|h| h.iter().any(|h| h["hook"] == hook))),
            "no case reaches {hook}"
        );
    }
    assert!(cases.iter().filter(|c| c.get("error").is_some()).count() >= 5);
}
