//! Every case of `tests/fixtures/restore-base.json`: upstream's own
//! `restoreElementWithProperties` and `restoreElement` output at the pinned
//! commit (generated by `tools/goldens/restore-fixtures.mjs`), compared
//! byte for byte as `JSON.stringify` writes it.
//!
//! The fixture is read with the crate's JSON reader so the lone surrogate
//! of `link-entity-lone-surrogate` survives, which is why this runs inside
//! the crate.

use serde_json::{Map, Value};

use super::{restore_encoded, TestEnv};
use crate::json;

const FIXTURE: &str = include_str!("../../tests/fixtures/restore-base.json");

fn object(value: &Value, what: &str) -> Map<String, Value> {
    match value {
        Value::Object(m) => m.clone(),
        _ => panic!("{what} is not an object"),
    }
}

/// `extra` entries `[key, value]`, or `[key]` for a key set to undefined.
fn extra(case: &Map<String, Value>) -> Vec<(String, Option<Value>)> {
    let Some(Value::Array(entries)) = case.get("extra") else {
        return Vec::new();
    };
    entries
        .iter()
        .map(|entry| match entry.as_array().map(Vec::as_slice) {
            Some([Value::String(k)]) => (k.clone(), None),
            Some([Value::String(k), v]) => (k.clone(), Some(v.clone())),
            _ => panic!("bad extra entry {entry}"),
        })
        .collect()
}

#[test]
fn upstream_fixture() {
    let fixture = json::parse(FIXTURE).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    assert!(cases.len() > 300, "{} cases", cases.len());
    let mut failures = Vec::new();
    for case in cases {
        let case = object(case, "case");
        let id = case["id"].as_str().expect("id");
        let element = object(&case["element"], "element");
        let extra = extra(&case);
        let extra: Vec<(&str, Option<Value>)> =
            extra.iter().map(|(k, v)| (k.as_str(), v.clone())).collect();
        // Generic types restore as restoreElementWithProperties(element, {})
        // (restore.ts:726-731); the fixture records restoreElement for them.
        match case["call"].as_str() {
            Some("base") => {}
            Some("restoreElement") => assert!(extra.is_empty(), "{id}"),
            other => panic!("{id}: unknown call {other:?}"),
        }
        let got = restore_encoded(&element, &extra, &mut TestEnv::default());
        match (got, case.get("result"), case.get("error")) {
            (Ok(map), Some(expected), None) => {
                let got = json::write_parsed(&Value::Object(map));
                let want = json::write_parsed(expected);
                if got != want {
                    failures.push(format!("{id}:\n got {got}\nwant {want}"));
                }
            }
            (Err(err), None, Some(Value::String(message))) => {
                if err.to_string() != *message {
                    failures.push(format!("{id}: error {err} != {message}"));
                }
            }
            (got, result, error) => {
                failures.push(format!("{id}: got {got:?}, want {result:?} / {error:?}"));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
